cfg/gtk.cfg, lib/checkleakautovar.cpp, test/cfg/gnu.c, test/cfg/gtk.c, test/cfg/std.c, test/cfg/windows.cpp, test/testleakautovar.cpp
Note that there are still no warnings for c++-style casts
=> Fix #9047 (c-style casts before malloc)

lib/checkclass.cpp, lib/checkclass.h, lib/checkother.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/valueflow.cpp, test/testclass.cpp, test/testsymboldatabase.cpp
I raised this on the  IRC but haven't seen the response so apologies if this contradicts something said there.
See for example the following code
```
struct A
{
virtual char x() { return 'A'; }
};
struct B : A
{
char x() override { return 'B'; }
B() { std::cout << x(); }
};
struct B2 : A
{
virtual char x() override { return 'X'; }
B2() { std::cout << x(); }
};
```
cppcheck 1.87 will correctly warn that "Virtual function 'x' is called from constructor 'B2()' at line 21. Dynamic binding is not used. [virtualCallInConstructor]" however it will not detect the same for struct B which is structurally identical but lacks the virtual keyword.
Note that B::x is already virtual by virtue of A::x being virtual and matching the method signature. The virtual keyword isn't actually doing anything in …
=> Update symbol database such that the override keyword implies that the function is also virtual

lib/checkstring.cpp, test/teststring.cpp
If there is a cast of the argument buffer, cppcheck would print out the
expression including the cast, which looks a bit strange to talk about
Variable (char*)buf is used as...
Instead, only print the variable name without the cast.
Also, handle arbitrary many casts (the previous code only handled one).
Multiple casts of the input arguments is probably an unusual case in
real code, but can perhaps occur if macros are used.
=> Overlapping sprintf, improve handling of casts

lib/symboldatabase.cpp, lib/symboldatabase.h, lib/token.cpp, lib/token.h, test/testautovariables.cpp
This will create a `Function` object for lambdas. A `eLambda` toktype is added so it can be treated as a function but `isName()` will be false.
This helps improve lifetime analysis with nested lambdas. We will now warn for case like this:
```cpp
auto f()
{
auto g = [&](auto x) { return [&] { return x; }};
return g;
}
```
Parsing the lambda as a `Function` allows the parameters to the lambda to be treated as argument variables.
=> Parse lambdas as functions

cfg/cppcheck-cfg.rng, cfg/std.cfg, lib/checkautovariables.cpp, lib/checkclass.cpp, lib/checkleakautovar.cpp, lib/checkleakautovar.h, lib/checkmemoryleak.cpp, lib/library.cpp, lib/library.h, lib/valueflow.cpp, man/manual.docbook, man/reference-cfg-format.md, test/cfg/std.c, test/testleakautovar.cpp, test/testlibrary.cpp, test/testmemleak.cpp, test/testvalueflow.cpp
This PR adds support to configure realloc like functions in cfg files. It also makes use of the library configurations in some of the memleak checkers. It also makes it possible to configure the buffer size for these functions. Finally, configure functions in std.cfg (specifically `realloc`, `reallocarray` and `freopen`).
Possible improvements are:
* Usage of the function in the `memleakOnRealloc` check (I have a somewhat working prototype that needs some polishing)
* Configuration of other libraries than `std.cfg`. At least `gnu.cfg` (`xrealloc()`), `gtk.cfg` (`g_realloc`, `g_try_realloc()`, and more) and probably `windows.cfg` (`HeapRealloc()`, `LocalRealloc()`) can have their memory configuration improved. (I have tested that it works for the gtk functions, but have some other …
=> Fix #6115 (Add support to realloc to cfg files)

test/cfg/std.c
Includes a testcase for trac ticket [#1379](https://trac.cppcheck.net/ticket/1379) which was fixed in
839fcddd8a1bd21960c8cfc42b5ea16aaea6b395.
=> Add tests of std.cfg buffer size

lib/tokenize.cpp, test/testsimplifyusing.cpp
This fixes simplifyUsing which has the same problem as simplifyTypedef.
simplifyUsing was designed to support using namespace but it was never
implemented. The changes are minor to add it.
simplifyTypedef requires much more work to support using namespace.
=> Partial fix for #9191 (simplifyTypedef: Problem when namespace is used)

cfg/posix.cfg, test/cfg/posix.c
Ignoring the return value of pthread_mutex_trylock is always a bug.
There is no other way to check if the mutex is locked or not after the
call.
=> posix.cfg: Add `<use-retval/>` to pthread_mutex_trylock

lib/templatesimplifier.cpp, lib/templatesimplifier.h, lib/tokenize.cpp, test/testsimplifytemplate.cpp
added function findTemplateDeclarationEnd to skip template declarations
to reduce duplicate code
=> Refactor Tokenizer::simplifyUsing to use continue to reduce indentation

tools/donate-cpu.py
Many projects use a local copy of the sqlite3 library and several of
them use local includes.
=> donate-cpu.py: Enable sqlite3 library for local includes.

lib/checkleakautovar.cpp, test/testleakautovar.cpp
This fixes false positives when the pointer passed to free() (or similar
deallocation functions) is cast using a c-style cast.
Related to Trac ticket [#9047](https://trac.cppcheck.net/ticket/9047) but for dealloction instead of allocation..
=> Fix FP with cast pointer to free()

lib/tokenize.cpp, test/testtokenize.cpp
Constructions like **case '1'...'9'** (gcc extension) converted to a list of separate case tokens. When slash \ symbol appears as a part of this list, it is added "as is", but it should be escaped like '\\' to be valid c++ code.
Next code causes internal error,:
**cppcheckError: Internal Error. MathLib::normalizeCharacterLiteral: Unhandled char constant '\'.**
```
switch( x ) {
case ' ' ... '~': // <--- error here
break;
}
```
Here is my solution of this problem. Please review it, taking in account that I'm new to this project and not sure if my solution good enough for Cppcheck architecture. But at least it works for me.
=> Fix adding unescaped slash token when splitting gcc case range.

cfg/gtk.cfg, test/cfg/gtk.c
* Improve configuration of g_try_realloc and g_try_realloc_n
* Mark g_realloc and similar functions as realloc functions
* Remove g_new, g_new0, etc as <alloc> functions, these are defined as
macros and handled as the functions they're expanded to.
* Add tests. TODO tests will be resolved by using the library
configuration in the checker.
=> Update gtk memory functions

cfg/gnu.cfg, test/cfg/gnu.c
Remove `<noreturn>` tag, since the functions do not return unless there
was no error.
=> Configure xrealloc and adjust gnu memory functions

Makefile, tools/dmake.cpp
See https://github.com/danmar/cppcheck/pull/1988
and https://github.com/danmar/cppcheck/pull/1998
=> Makefile/dmake: Increase stack size to 8M for Cygwin builds to avoid segfaults

tools/donate-cpu-server.py
The loop should be exited as soon as the line with the Cppcheck version
information has been found. Not only when the verification failed.
=> donate-cpu-server.py: Fix rare version verification issue

lib/checkleakautovar.cpp, test/testleakautovar.cpp
This was introduced in 8513fb81d261fe62a822755f22ae4c24e112ae25 when
fixing memory leaks for global variables allocated in condition. The
refactored code had an inconsistency where c and c++ code behaved
slightly differently when `var` is NULL. This seemed to not have an
impact as the code was written prior to 8513fb81d261fe62a822755f22ae4c24e112ae25,
but when the same code was used for conditions, FPs were introduced.
The introduced FPs were memleak warnings when there should have been an
information message about missing configurations for code like
void f() {
char *p = malloc(10);
if (set_data(p)) {}
}
Fix this by always returning true if varTok->Variable() is NULL for
both c and c++ code.
=> Fix FP memory leak with unknown function call in condition

test/testconstructors.cpp, test/testsymboldatabase.cpp, test/testuninitvar.cpp, test/testunusedprivfunc.cpp
Since all checks are run on the full token list and not the simplified
one, run the tests on the full token list as well.
Note: There are more tests that run on the simplified token list, but these were
the ones were it was "simple" to remove them (no test failures), so pick the lowest
hanging fruit first.
=> Run more tests on full token list

lib/checkstl.cpp, lib/valueflow.cpp, test/teststl.cpp
This fixes issue when using direct pointer to containers. There should no longer be warning about this:
```cpp
void f(std::vector<int> &v) {
std::vector<int> *v0 = &v;
v.push_back(123);
std::cout << (*v0)[0] << std::endl;
}
```
=> Fix FP when using a pointer to a container

addons/misra.py, addons/test/test-misra.py
See:
https://github.com/danmar/cppcheck/pull/1996#issuecomment-514180830
https://sourceforge.net/p/cppcheck/discussion/development/thread/232af6ee4c/
=> misra.py: Bring back -P argument for backward compatibility

lib/checkleakautovar.cpp, lib/utils.h
ASAN can use 3x more stack memory, so this lowers the limit from 1000 to 300 to avoid stack overflow errors in ASAN.
=> Lower recursion limit when using asan

lib/templatesimplifier.cpp, lib/tokenize.cpp, test/testgarbage.cpp, test/testsimplifytemplate.cpp
This only fixes the crash. Specialization of nested templates is still
broken.
=> Fix #9225 (Crash on valid C++14 code)

gui/codeeditstylecontrols.h, gui/codeeditstyledialog.cpp
Previous commit had updated declarations in Code Editor Style Dialog to use
const QColor& and const QFont::Weight& variables. This change was not totally
complete as const usage was not propagated to Signal/Slot connect statements.
This commit corrects that oversight.
=> Correct Signal/Slot signatures

lib/checkmemoryleak.cpp, test/testmemleak.cpp
One usecase for freopen() is to redirect input and output streams to
files. For that, the return value is not needed.
=> Fix FP leakVarNotUsed with freopen() and stdin

tools/donate-cpu.py
Sometimes there are no relevant source files (.c, .cpp, ...) extracted,
but other files are (.h, ...).
There could be only header files for example. Then Cppcheck returns with
exit code 1 and prints an error message. This is no crash and now no
longer reported as such.
=> donate-cpu.py: Do not report crash if no source file has been found.

lib/lib.pri, tools/dmake.cpp
Since the number of test files is larger than the number of lib files,
this only caused an extra harmless '\' being printed after the last
header file in lib.pri. If the number of test files would have been
smaller than the number of lib files, the generated lib.pri would have
been broken.
=> dmake: Fix check of last header file in lib.pri

cfg/boost.cfg
The macros defined in unit_test_suite.hpp have a variable number of arguments if BOOST_PP_VARIADICS is defined.
See:
https://github.com/boostorg/test/blob/develop/include/boost/test/unit_test_suite.hpp
=> Variable number of arguments for boost test suite macros

readme.md, readme.txt
- The cppcheck.sln file is configured for Visual Studio 2019
See commit: ae86536
- Add information on how to obtain a current version of PCRE for
Visual Studio using vcpkg from https://github.com/microsoft/vcpkg
=> Update readme files concerning Visual Studio

cfg/gnu.cfg, test/cfg/gnu.c
It is hard to find good references, one that describes it a bit can
be found here:
https://manpages.ubuntu.com/manpages/bionic/man3/xmalloc.3pub.html
xfree() can be used instead of free().
A check, to verify that a memory leak is found if the memory allocated
via xmalloc() is not freed, has also been added.
=> gnu.cfg: Add xfree()

lib/token.cpp, lib/tokenize.cpp
This was causing some bugs in rare cases with scope names that were doubled up or went too far when looking ahead.
=> Fix some bugs in new Scope Calculation code

lib/checkmemoryleak.cpp, lib/checkmemoryleak.h
This makes all the checks in CheckMemoryLeakNoVar separate functions to
improve readability.
=> Memleak: Refactor check to separate function

lib/valueflow.cpp, test/teststl.cpp
This wont warn of negative indices for cases like this:
```cpp
int f(int x, const std::vector<int>& a) {
if (!(x < 5)) {
return a[x - 5];
} else {
return a[4 - x];
}
}
```
=> Fix FP with negative index and negated condition

lib/checkmemoryleak.cpp, test/testmemleak.cpp
Use the AST a little bit more to improve the check. In order to do so,
rewrite the check to work from the outer function first and then check
the arguments, instead of the other way around.
It also fixes Trac ticket #9252, no warning is now given for
void* malloc1() {
return(malloc1(1));
}
This FP seems to be common in daca results.
It also makes it possible to improve handling of casts, for example
cppcheck now warns about
void f() {
strcpy(a, (void*) strdup(p));
}
But not for
char* f() {
char* ret = (char*)strcpy(malloc(10), "abc");
return ret;
}
These FP/FN were introduced when the check was switched to use the
simplified token list.
=> leakNoVarFunctionCall: Use AST more (fix #9252)

cfg/qt.cfg, test/cfg/qt.cpp
- Add iterator end patterns
- Add/fix size and access functions
- Remove marking QList and QStringList as std-like strings
- QStringList configuration now inherits from QList like it is actually the case
=> qt.cfg: Fix and enhance Qt container configuration

lib/astutils.cpp, lib/astutils.h, lib/checkuninitvar.cpp, lib/checkuninitvar.h, lib/valueflow.cpp, test/testuninitvar.cpp
This extends valueflow to set the member variables to unitialized.
=> Fix issue 8825: ValueFlow: uninitialized struct member

tools/donate-cpu.py
Gnome includes GTK+, GLib and other libraries, see
https://developer.gnome.org/platform-overview/unstable/tech.html.en
Some projects simply include "<gnome.h>" and use Gtk/GLib functions.
=> donate-cpu.py: Use "gtk" library cfg if "<gnome.h>" is included.

lib/checkmemoryleak.cpp, test/testmemleak.cpp
There seems to be no reason for stopping checking the scope if a call to
free() is seen (or fclose() or realloc()), so just continue checking.
Also, if there are multiple arguments, check all, perhaps there are more
memory leaks to warn about.
=> leakNoReturnVar: Don't break early

cfg/wxwidgets.cfg, test/cfg/wxwidgets.cpp
Reference: https://docs.wxwidgets.org/3.0/classwx_string.html
=> wxwidgets.cfg: Add container configuration for wxString

lib/astutils.cpp, lib/astutils.h, lib/checkother.cpp, lib/checkuninitvar.cpp, lib/valueflow.cpp, test/testastutils.cpp, test/testsimplifytypedef.cpp, test/testuninitvar.cpp
This refactors `isVariableChangedByFunction` to check for changes based on indirections.
=> Fix issue 9305: False positive uninitvar - struct initialized via function

addons/misra.py, addons/test/misra/misra-test.c
I apologize if I'm jumping the gun since I'm evaluating cppcheck but I don't have a copy of the MISRA rules yet. But from I've deduced, cppcheck misra.py raises a false positive when a macro is defined "twice" in a #if/#else, e.g.
```
#ifdef misra_5_4_macro_hides_macro__31x
#define misra_5_4_macro 1 // no warning
#else
#define misra_5_4_macro 2 // no warning
#endif
```
misra.py thinks these are two distinct macros that have the same 31/63-character prefix, which would violate rule 5.4.
=> misra: fix rule 5.4 false positive

lib/checkclass.cpp, test/testclass.cpp
https://sourceforge.net/p/cppcheck/discussion/general/thread/d5b690ef19/
Check that we warn only about using the initializer list when we assign
the object being constructed.
=> Fix false positive in initializationListUsage

lib/checkuninitvar.cpp, test/testuninitvar.cpp
http://cppcheck.osuosl.org:8000/ycmd
```
2019-08-30 23:21
ftp://ftp.se.debian.org/debian/pool/main/y/ycmd/ycmd_0+20181101+git600f54d.orig.tar.gz
cppcheck-options: -j1 --library=posix --library=gnu --library=qt --library=python --library=googletest --library=boost -D__GNUC__ --check-library --inconclusive --enable=style,information --platform=unix64 --template=daca2 -rp=temp temp
platform: Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
python: 2.7.15+
client-version: 1.1.31
cppcheck: head 1.88
count: Crash! 83
elapsed-time: -11.0 61.2
head results:
Checking temp/ycmd-0+20181101+git600f54d/ycmd/tests/clang/testdata/completion_fixit.cc: __GNUC__=1...
Program received signal SIGSEGV, Segmentation fault.
CheckUninitVar::valueFlowUninit (this=this@entry=0x7fffffffb350) at …
```
=> Fix crash in CheckUninitVar

test/CMakeLists.txt
This improves the test run time on my machine from 1 minute down to 20 seconds.
I also added a cmake flag to skip some tests. The `TestIO` is really slow and takes about 18 seconds. I can set cmake to skip this test. This brings down the test run time to 4 seconds.
=> Run test fixtures as seperate tests so they can run in parallel

lib/token.h, lib/tokenlist.cpp
iscpp11init would take a lot of time when parsing huge arrays.
This patch add memoization to keeps track that we are parsing an array,
and allows to propagate the result without re-parsing the array for each
of its members.
=> Fix issue 8897: Huge array initializations

addons/misc.py, externals/simplecpp/simplecpp.cpp, lib/checkother.cpp, lib/symboldatabase.cpp, lib/templatesimplifier.cpp, lib/token.cpp, lib/token.h, lib/tokenize.cpp, lib/tokenlist.cpp, test/testsimplifytemplate.cpp, test/testtokenize.cpp, test/testvarid.cpp
Using cppcheck -E to preprocess code with ellipsis produces output that
can't be compiled because ... is split into 3 tokens.
=> make ellipsis ... a single token

tools/donate-cpu.py
I looked into many packages where the detection failed and they all use
`#include "ruby.h"`. Some of these packages seem to be Ruby modules,
others seem to be "normal" software.
=> donate-cpu.py: Improve detection of Ruby library usage

cfg/posix.cfg, test/cfg/posix.c
Add tests to make sure no false positives are reported.
Found the issue via daca@home
=> posix.cfg: Fix vsyslog() configuration

test/cfg/posix.c
Add test to avoid further FP for valid code.
Tests for true positives are already present.
https://trac.cppcheck.net/ticket/9334
=> Test for issue 9334: FP resourceLeak for dlopen/dlclose with library posix

lib/astutils.cpp, lib/astutils.h, lib/valueflow.cpp, test/testvalueflow.cpp
This wont just assume a function changes the container. If possible, it will inspect the function to see if it changes the container size. If the function body is not available it falls back on `isVariableChangedByFunctionCall`.
=> Add deeper analysis of when a function changes a containers size

addons/misra.py, addons/test/misra/misra_rules_multiple_lines.txt, addons/test/test-misra.py
Version 1.88 changed the parsing of the MISRA rules file adding a
severity setting.  This caused a regression in rule parsing.
In particular the following format used to parse cleanly and produce
rule output that would show the severity as part of the rule text.
Rule 1.2
Advisory
Rule text goes here.
Rule 1.3
Required
More rule text goes here.
As of 1.88 a file structured like above would parse as having no rules.
The problem is the use of blank lines as a rule delimiter.   The
modified rule parser wants to see a rules formatted like below:
Rule 3.1 Required
R3.1 text.
Rule 4.1 Required
R4.1 text.
or:
Rule 1.1
Add this rule and parse to next, skipping empty lines.
Rule 1.2
Rule text.
Any rule text that did not fall into one of the above formats would
result in incomplete rule text …
=> Loosen restrictions on MISRA rules text structure

test/CMakeLists.txt
This adds a dependency on cppcheck so it will be built when calling `make check`.
=> Fix travis cmake error

Makefile, tools/dmake.cpp
Previously, external files were not searched at all, and dependencies
on header files in cli was not taken into account for test files.
To add dependency of headers in externals, we also need to search for
includes with angular brackets.
This is my attempt to fix #2004 which seems to have gone stale.
=> dmake: Improve dependency detection of external and cli includes

lib/valueflow.cpp
I dont have a test case, this is just based on the backtrace. I assume its because the code is incomplete which is why `arg` is null.
=> Try to fix issue 9341: daca crash: isContainerSizeChangedByFunction

Makefile, tools/dmake.cpp
Makes it simpler to check diffs, and prevents updates to Makefile due to
changes in header includes.
=> dmake: Sort header dependencies

cli/cmdlineparser.cpp, lib/checkbufferoverrun.cpp, lib/checkclass.cpp, lib/checkio.cpp, lib/checkstring.cpp, lib/errorlogger.cpp, lib/importproject.cpp, lib/library.cpp, lib/mathlib.cpp, lib/platform.cpp, lib/preprocessor.cpp, lib/settings.h, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/templatesimplifier.cpp, lib/token.cpp, lib/tokenlist.cpp, test/testcppcheck.cpp, test/testpreprocessor.cpp, test/testsuite.cpp, test/testsymboldatabase.cpp
clang-tidy was used to detect these and its quick fixes were applied with the `auto` usage being reverted to the actual type. Adjusted costness in a few cases as well.
=> use range loops / constness

.travis.yml
Python 3 does not search parent directories of the initially executed
script for modules imported by modules in this parent directory by
default. So simply set the PYTHONPATH to the ./addons directory. Thus
all scripts are found. It is similar to running the test-*.py script
from the ./addons directory, but this way all the paths in the test-*.py
scripts do not have to be changed (for example to find the cppcheck
executable.
For more details regarding the parent directory issue see for example:
https://stackoverflow.com/questions/11393492/python-package-import-from-parent-directory
For details about the used PYTHONPATH solution see:
https://stackoverflow.com/questions/4580101/python-add-pythonpath-during-command-line-module-run
=> .travis.yml: Run addon tests also with Python 3

man/manual.md
Hi, I just noticed an invalid XML output example in the manual, so I fixes it.
(Yes, this is just one character fix 😄)
=> Add missing ending tag in XML example

lib/checkleakautovar.cpp
Crashes found by daca@home
http://cppcheck1.osuosl.org:8000/crash.html
For instance
```
2019-09-20 16:27
ftp://ftp.se.debian.org/debian/pool/main/n/nedit/nedit_5.7.orig.tar.gz
cppcheck-options: -j1 --library=posix --library=gnu --library=motif -D__GNUC__ --check-library --inconclusive --enable=style,information --platform=unix64 --template=daca2 -rp=temp temp
platform: Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
python: 2.7.16
client-version: 1.1.37
cppcheck: head 1.89
head-info: 38dec6a9a (2019-09-20 16:46:57 +0200)
count: Crash! 934
elapsed-time: -11.0 9.0
head results:
Checking temp/nedit-5.7/source/shell.c: __GNUC__=1...
Program received signal SIGSEGV, Segmentation fault.
0x000055555564b862 in CheckLeakAutoVar::ret (this=0x7fffffffb8c0, tok=0x5555582ea9e0, varInfo=...) at …
```
=> Fix crashes in checkleakautovar

cli/cppcheckexecutor.cpp, lib/checkleakautovar.cpp, lib/checkunusedfunctions.h, lib/cppcheck.cpp, lib/cppcheck.h, lib/token.h, lib/tokenize.cpp, test/testleakautovar.cpp, test/testsimplifytemplate.cpp
=> do not access static methods through instance

cli/cppcheckexecutor.h, cli/threadexecutor.h, lib/checkassert.h, lib/checkstl.h, lib/checkvaarg.h, lib/cppcheck.h, lib/exprengine.h, test/testcppcheck.cpp, test/testsuite.h, test/testutils.h
=> added missing OVERRIDE usage and removed redundant virtual

lib/check.h, lib/tokenize.h
=> deleted methods should be public

rules/token-matching.xml
The file token-matching.xml contains multiple rules
- Add `<rules></rules>` xml tags
- Fixes the following xmllint error:
`./rules/token-matching.xml:10: parser error :`
`Extra content at the end of the document`
`<rule version="1">`
`^`
=> Fix xml syntax in token-matching.xml

lib/checkleakautovar.cpp, test/testleakautovar.cpp
Fix FPs pointed out by daca@home on the following form:
void* f(void) {
void* x = malloc(1);
return(x);
}
Fix it by only skipping tokens if there is an actual match with a
variable. This allows to remove the special casing of "return;".
=> Fix memleak FP with return  with parenthesis

lib/checkleakautovar.cpp, lib/checkleakautovar.h, test/testleakautovar.cpp
Printout both the locations on double free errors, mismatching
alloc/dealloc and dealloc return error.
=> Fix #7031 (improve error message for memory related warnings)

lib/valueflow.cpp
Using a timeout loop is not very deterministic. ValueFlow can produce different values depending if sanitizers or debugger is used. Instead, this will use a fixed max number of loops.
=> Use fixed number of iterations for valueflow loop

lib/checktype.cpp, test/testtype.cpp
For c++14, shifting a variable with a value larger than or equal to the
number of bits in the variable is undefined. Left-shifting with a value
equal to the number of bits of the variable is implementation defined.
See also trac ticket #9306.
=> Fix severity of c++14 shifts with too many bits

lib/astutils.cpp, lib/astutils.h, lib/valueflow.cpp, test/testvalueflow.cpp
This supports not just variables but expressions in `valueFlowAfterCondition`. Now we can deduce values like `x` here:
```cpp
void f(int* p) {
if (p[0] == 123) {
int x = p[0]; // <- x is 123
}
}
```
This forwards the values of the expression by using the `FwdAnalysis`. It splits the `valueFlowForward` function into two functions: `valueFlowForwardVariable` and `valueFlowForwardExpression`. The `valueFlowForward` will call either function depending if the expression is just a variable or more complex. However, it will try to solve the values of an expression if possible, so an expression may just forward a variable. Like in the case below, `x` will be `124`, because `y+1` is `123`:
```cpp
void f(int y) {
if (y+1 == 123) {
int x = y+2; // <- x is 124
}
}
```
Right now,  it just solves for …
=> Support expression in valueFlowAfterCondition

lib/astutils.cpp
Error C2039 'inserter': is not a member of 'std' cppcheck 
cppcheck\lib\astutils.cpp 1229
=> Fix the following compilation error on VC142 :

addons/misra.py, addons/test/misra/misra-test.c
This commit will fix issues with MISRA rule 4.1 caused by improper escape sequences handling.
References:
1. https://trac.cppcheck.net/ticket/9370
2. https://sourceforge.net/p/cppcheck/discussion/development/thread/7274ed3842/?limit=25#799a
=> misra.py: Fix Rule 4.1

lib/templatesimplifier.cpp, lib/valueflow.cpp
Found by reviewing all emplace_back() usages. Some initial changes had to be reverted since the object are trivially copy-able so std::move() has no effect.
There already exists a ticket about adding a check for this to Cppcheck - https://trac.cppcheck.net/ticket/8945
=> avoid some unnecessary copies in emplace_back() calls

tools/donate-cpu.py
The option "--showtime=top5" is added to the Cppcheck command line.
The timing output is collected and only for HEAD it is shown in the new
category "head-timing-info" in the results output.
The timing output is indented with one white space, so even in the
unlikely case that a function is named "head result:" or "diff:" it does
not break the parser in the server.
=> donate-cpu.py: Add internal timing information of Cppcheck to output

addons/misra.py, addons/test/misra/misra-test.c
Casting a pointer to `(void)` triggered the rule, which shouldn't happen. Looked like a bug?
=> MISRA-C: fix false positive in 11.7

addons/misra.py, addons/test/misra/misra-test.c
MISRA-C 2012 states that `//` is allowed in a `//` comment, as an exception
=> MISRA: add exception to rule 3.1

tools/reduce.py
Allow reducing code that triggers (false positive) error messages.
Print Cppcheck output in case Cppcheck returns unsuccessfully and no
segfault is expected. This helps fixing messed up command lines (for
example issues with the path).
=> reduce.py: Allow reducing error messages, print output in case of error

test/testbufferoverrun.cpp
There are a number of tests and asserts in testbufferoverrun that pass.
Enable them to add test coverage.
Perhaps the ones that are commented out should be converted to TODO_ASSERT_EQUALS instead?
=> TestBufferOverrun: Enable passing tests

lib/astutils.cpp, lib/astutils.h, lib/checkautovariables.cpp, lib/checkautovariables.h, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/valueflow.cpp, test/testautovariables.cpp
This also removes the old `returnTemporary` check.
=> Extend lifetime checking to temporaries

lib/checkother.cpp, lib/token.h, lib/tokenize.cpp, test/testother.cpp, test/testsymboldatabase.cpp
Previously, cppcheck discarded the `extern "C"` specifier.  This patch modifies cppcheck to parse each as a Scope in the symbol database, then uses that scope to avoid false positives when making recommendations about changing a function argument to be a reference (since variable references is a C++ feature, unavailable in C, and thus unavailable in `extern "C"`).
=> Parse `extern "C"`, and use it to avoid FP reference warnings

lib/checkclass.cpp, test/testconstructors.cpp
This change is a fix on #9391.
Cppcheck detects uninitialized member vairables if there is ctor is marked as default
=> fix #9391 uninited member var

lib/exprengine.h
https://stackoverflow.com/questions/16088282/is-there-a-128-bit-integer-in-gcc
suggests to test for `__SIZEOF_INT128__`. This test is added now and
Cppcheck now also compiles for a 32 bit target with the expected
warning that there is no 128-bit integer. "make test" also works.
=> Fix #9399 (Build Failure on x86: error: unknown type name '__int128_t')

cfg/std.cfg
c++20 introduced type char8_t.
From https://en.cppreference.com/w/cpp/language/types:
char8_t - type for UTF-8 character representation, required to be large
enough to represent any UTF-8 code unit (8 bits). It has the same size,
signedness, and alignment as unsigned char (and. therefore, the same size
and alignment as char and signed char), but is a distinct type.
=> std.cfg: Add podtype char8_t

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/container/map/at
=> std.cfg: Add configuration for std::map::at()

lib/checknullpointer.cpp, lib/symboldatabase.cpp, lib/valueflow.cpp
This moves the extra `parseDecl` calls into valuetype where they actually belong.
=> Move necessary code into valuetype

lib/tokenize.cpp, test/testsimplifytypedef.cpp
* Better handle const/noexcept methods
* Fix parsing of some operator
It is still very broken, but at least, it does not fail.
Here is the previous error:
```
TestSimplifyTypedef::simplifyTypedef129
terminate called after throwing an instance of 'InternalError'
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff612a801 in __GI_abort () at abort.c:79
#2  0x00007ffff6b1d957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b23ab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b23af1 in std::terminate() () from …
```
=> Better handle const/noexcept methods

cfg/gnu.cfg, lib/tokenize.cpp, test/testsimplifytypedef.cpp
`__typeof__` is just an alternative keyword for `typeof`, see
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html
Since `typeof` is handled in several checkers it makes sense to define
`__typeof__` as `typeof`.
In Tokenizer::simplifyTypedef() only `__typeof__` was handled.
Handling `typeof` is added there now too.
=> gnu.cfg: Define `__typeof__` as `typeof`, fix simplifyTypedef()

cfg/gnu.cfg, test/cfg/gnu.c
Reference: https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/Alignment.html
=> gnu.cfg: Add configuration for __alignof__()

addons/misra.py, addons/test/misra/misra-test.c
First i thought it should be easy to check for comment starting with "\\\\" and ending either with "\\" or trigraph "??/" which might be resolved to "\\".
NOTE: 
Comment ending with trigraph "??/" is not explicitly mentioned by MISRA-C 2012 Rule 3.2 but it has the same effect if trigraph replacement is active (Verified with Microsoft C/C++ compiler). 
Thus i added it to the check.
However then i faced that "\\" at end of line has been removed from raw token and the comment has been merged with subsequent line if it's not a blank line.
So i decided to split the check.
1. Check for trigraph "??/" at end of comment.
2. Else check if there is a next token to comment token and line numbers are equal.
This is the case if comment line has been merged with subsequent line because last 
character …
=> Add check for MISRA-C 2012 rule 3.2 and test cases.

lib/checkstring.cpp, lib/mathlib.cpp, lib/token.cpp, lib/tokenize.cpp, lib/utils.h, test/testmathlib.cpp, test/testsimplifytokens.cpp, test/teststring.cpp, test/testtoken.cpp, test/testtokenize.cpp
Keeping the prefix in the token allows cppcheck to print the correct
string and char literals in debug and error messages.
To achieve this, move some of the helper functions from token.cpp to
utils.h so that checks that look at string and char literals can reuse
them. This is a large part of this commit.
Note that the only user visible change is that when string and char
literals are printed in error messages, the prefix is now included.
For example:
int f() {
return test.substr( 0 , 4 ) == U"Hello" ? 0 : 1 ;
};
now prints U"Hello" instead of "Hello" in the error message.
=> Keep prefix in string and char literals

cfg/std.cfg
Reference: https://en.cppreference.com/w/c/thread/thrd_exit
=> std.cfg: Add support for C11 functions thrd_*() and mtx_*()

lib/valueflow.cpp, test/testvalueflow.cpp
http://cppcheck1.osuosl.org:8000/crash.html
For instance in http://cppcheck1.osuosl.org:8000/styx
```
==19651==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000001c (pc 0x556f21abc3df bp 0x7ffc140d2720 sp 0x7ffc140d2710 T0)
==19651==The signal is caused by a READ memory access.
==19651==Hint: address points to the zero page.
#0 0x556f21abc3de in Variable::isGlobal() const ../lib/symboldatabase.h:342
#1 0x556f221f801a in valueFlowForwardVariable ../lib/valueflow.cpp:2471
#2 0x556f22208130 in valueFlowForward ../lib/valueflow.cpp:3204
#3 0x556f221e9e14 in valueFlowReverse ../lib/valueflow.cpp:1892
#4 0x556f221f1a43 in valueFlowBeforeCondition ../lib/valueflow.cpp:2200
#5 0x556f2223dbb5 in ValueFlow::setValues(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) …
```
=> Fix crashes in valueflow

tools/donate-cpu-server.py
Refactor `donate-cpu-server.py` slightly, then add the number of crashes per file and line.
I think this could be useful when there are lots of crashes in daca@home (like now for example), to get an overview where the crashes occur, if there are multiple problems, etc. Some input on this would be good (for example, should it be formatted differently? Would it be useful to generate new html-pages for each file/line with links to the packages that crashed?). The changes are easiest to review if you ignore white-space changes, since a fairly large chunk had its indentation changed in `crashReport()`.
Example output:
<h1>Crash report</h1>
<pre>
<b>Package                                  Date        Time   1.89   Head </b>
<a href="ace">ace</a>                                      2019-10-16 …
=> Donate cpu server crash locations

tools/donate-cpu-server.py
Fall back to "~/daca@home" if "/var/daca@home" does not exist.
Print the used work path when the script starts.
This way we do not have to change the server script before uploading
it to the server while being fully backwards compatible.
=> donate-cpu-server.py: Use "/var/daca@home" as work path by default.

lib/checkbufferoverrun.cpp, lib/checkstring.cpp, lib/symboldatabase.cpp, lib/token.cpp, lib/token.h, lib/tokenize.cpp, lib/valueflow.cpp, lib/valueflow.h, test/testbufferoverrun.cpp, test/teststring.cpp, test/testsymboldatabase.cpp, test/testtoken.cpp
Use that string and char literal tokens store the prefix. This makes
it possible to distinghuish between different type of string literals
(i.e., utf8 encoded strings, utf16, wide strings, etc) which have
different type.
When the tokens holding the string and character values have the correct
type, it is possible to improve `Token::getStrSize()` to give the correct
result for all string types. Previously, it would return the number of
characters in the string, i.e., it would give the wrong size unless
the type of the string was char*.
Since strings now can have different size (in number of bytes) and
length (in number of elements), add a new helper function that returns
the number of characters. Checkers have been updated to use the correct
functions.
Having the size makes it possible to …
=> Set correct type and size of string and char literals

cfg/std.cfg
Reference:
https://en.cppreference.com/w/cpp/container/map/equal_range
https://en.cppreference.com/w/cpp/container/map/lower_bound
https://en.cppreference.com/w/cpp/container/map/upper_bound
https://en.cppreference.com/w/cpp/container/map/contains
=> std.cfg: Add some missing std::map::*() function configurations

cli/cmdlineparser.cpp
`--std=posix` is deprecated and will be removed in the future.
=> cmdlineparser.cpp: printHelp(): Replace deprecated option in example

lib/checkio.cpp, test/testio.cpp
The Windows Data Type `SSIZE_T` is declared in `BaseTsd.h`
However, it is written in capital letters
- Fixes e.g. the following false positive:
```console
(portability) %zd in format string (no. 1) requires 'ssize_t' but the
argument type is 'SSIZE_T {aka signed long long}'.
[invalidPrintfArgType_sint]
```
=> Allow SSIZE_T in addition to ssize_t

tools/donate_cpu_lib.py, tools/test-my-pr.py
When I merged (local) branch to master, `merge-base` returned me not valid commit hash.
Also I'd propose to reduce count of packages default value. I bet 1k packages took too much time to execute.
Also it has fix lib file for running scripts from not the tool directory which cause to error on creation workdir
Moreover, it has small tweak to reduce size of result in case of diff is empty
=> test-my-pr.py: several improvements

addons/misra.py, addons/test/misra/misra-test.c
`typetok.astOperand2` could be `None`, if it's a library symbol which wasn't load by cppcheck.
For example, checking codebase with mbedtls:
```c
static const unsigned char bin[] = MBEDTLS_DHM_RFC3526_MODP_2048_P_BIN;
```
Will cause `misra.py` crash with `AttributeError 'NoneType' object has no attribute 'isNumber' `.
=> misra.py: Fix 18.8 crash on checking undefined id

cfg/bsd.cfg, cfg/gnu.cfg, test/cfg/gnu.c
In contrast to POSIX, GNU and BSD allow or even require the argument
"fd" to be set to -1 if MAP_ANONYMOUS or MAP_ANON is specified.
Corresponding Trac ticket: https://trac.cppcheck.net/ticket/9322
=> Fix #9322: bsd.cfg, gnu.cfg: Fix FP for mmap when argument "fd" is -1

htmlreport/cppcheck-htmlreport
This issue and also a fix has been reported by Lionel Gimbert in the forum:
https://sourceforge.net/p/cppcheck/discussion/development/thread/d18fb312ee/
All credit goes to him.
=> cppcheck-htmlreport: Fix premature end of loop in statistics output

.travis.yml
This way we should get a newer version of pygments.
=> .travis.yml: Install pygments via pip instead of apt

tools/triage/.gitignore, tools/triage/mainwindow.cpp, tools/triage/mainwindow.h, tools/triage/mainwindow.ui
Hello
I realized that triage tool doesn't have useful functions to navigate across files and simple search in files by text. This patch should add this functionality.
Drawbacks: I didn't realized how to force widgets inside tabwidget to grew up together w/ window. Also it has 1/3 division ratio which is not beautiful.
I haven't enough experience in qt, will be glad to get advice
Here is a simple example: https://imgur.com/gallery/IlAlYGc
=> Triage tool usability improvement

.travis.yml, htmlreport/check.sh, htmlreport/cppcheck-htmlreport
Add HTML validation with HTML Tidy for the resulting files index.html
and stats.html.
Fix syntax errors found by the validator.
Fix that the links in the footer are not clickable by removing the
"height: 75%;" style for the classes "menu" and "menu_index".
Add some line breaks to the HTML output for better readability and for
easier debugging.
=> htmlreport: Add HTML validation and fix syntax errors

tools/triage/mainwindow.cpp, tools/triage/mainwindow.ui
This patch should improve user interface of triage tool:
* resize for widgets in tabs now working :)
* ui improved by using dockwidget for left/right parts to allow manual resize or moving frame to bottom/top for example
* search in files: removed part of path from root to working dir in output
* added simple filter by file extension: header only, cpp only, both, all files(if both unchecked)
https://imgur.com/gallery/HiMjK0E
=> Triage tool ui improvement

addons/misra.py
Skip execution of globally suppressed checks. It is absolutely necessary when we gradually add MISRA rules checks in the large codebase, because now we have to perform all the checks, even if they disabled with `--suppress-rules`, which leads to a significant loss of time and resources.
@whoopsmith could you please review these changes?
=> misra.py: Skip execution of globally suppressed checks

addons/misra.py
Don't save the whole lxml location when collecting rules suppression's statistics. 
This fixes the problem with large memory usage when some rules are suppressed.
See issue description:
https://sourceforge.net/p/cppcheck/discussion/development/thread/51fc053626/
=> misra.py: Fix large memory usage with suppressions

.travis.yml, htmlreport/cppcheck-htmlreport
The error that pylint does not find HtmlFormatter in pygments.formatters
is known and the common solution is to suppress this error.
See https://github.com/PyCQA/pylint/issues/491
=> htmlreport: Also check "cppcheck-htmlreport" with pylint on Travis

tools/donate-cpu.py
Line 102: Comparison to literal
Line 117: Unnecessary "else" after "break"
=> donate-cpu.py: Fix two pylint warnings

lib/library.cpp
This will still find the correct corresponding cfg files when testing even if there is a previously installed version.
=> Search relative path first before install path

lib/token.cpp, test/testsimplifytokens.cpp, test/testtoken.cpp
Improve handling of adjacent string literals of different types.
Example of adjacent string literals: `"ab" L"cd"`.
In C89, C++98 and C++03, this is undefined. As of C99 and C++11, this is
well defined and the two string literals are concatenated to `L"abcd"`.
C11 and C++11 introduces the utf16, utf32 and (C++ only) utf8 string
types. Concatenating any of these with a regular c-string works exactely
as the wide string example above. The result of having two adjacent
string literals with different prefix is implementation defined, unless
one is an UTF-8 string literal and the other is a wide string literal.
In this case the behaviour is undefined.
Ignore the undefined and ill-formed programs (this behaviour is unchanged)
and make sure that concatenating a plain c string literal with a …
=> Token::ConcatStr(): Handle mixed string literals

addons/misra.py, addons/test/misra/misra-test.c
Fix R16.3 state machine which doesn't report errors in last case/default statement. See added tests for examples.
Issue on a trac: https://trac.cppcheck.net/ticket/8548
=> misra.py: Fix R16.3 FN in last case/default statement

addons/misra.py, addons/test/misra/misra-test.c
Rule 21.1 now doesn't report errors on usage of library functions
started from underscore (e.g. `_exit`) and valid `errno` assignment.
See added tests for examples.
=> misra.py: Fix R21.1 False Positives on standard functions and errno

tools/donate-cpu.py
Add shebang to run the client via Python 3 by default.
Add warning if Python 2 is used.
As discussed in the forum https://sourceforge.net/p/cppcheck/discussion/development/thread/86813a8a53/ switching to Python 3 has some benefits.
=> donate-cpu.py: Add shebang, warn when run under Python 2

test/testvalueflow.cpp
See [#6514](https://trac.cppcheck.net/ticket/6514), which I believe can be closed, but I think it would be good to add a test case to test that valueflow understands these (there are tests of the tokenizer and mathlib, but no test that connects all components).
=> ValueFlow: Add test with hexadecimal floating point literal

test/testleakautovar.cpp
Ticket #9028 was fixed in 5800692fa132a, add a test case where the
class definition is seen.
=> Add regression test for #9028

test/testautovariables.cpp
This was fixed in 5a32d2d017c8a. Add a regression test
with array arguments.
=> Add regression test for #8923

addons/misra.py
Variables from `cppcheckdata.Variable` have no nameToken if they are objects of user-defined classes.
=> misra.py: Fix R21.1 crash on C++ code

addons/misra.py
PyCharm inspection warns for argument `visited=set()` with
"Default argument is mutable".
According to different sources one should nearly never use mutable
default arguments:
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
https://dev.to/florimondmanca/python-mutable-defaults-are-the-source-of-all-evil-6kk
=> misra.py: Fix mutable default argument in "misra_17_2()"

lib/tokenize.cpp, lib/tokenize.h, test/testgarbage.cpp, test/testtokenize.cpp
There are probably a lot more valid code patterns that generates syntax
errors so I added "operator" to the error message to make it easier to
find them.
=> Fix #9472 (Syntax error on valid C++ code)

man/buildman.sh, man/manual.md, man/reference-cfg-format.md
The YAML setting `toc: true` works for PDF creation but for HTML it
simply prints `true` as the table of contents.
It looks like a misconception and the only acceptable solution I have
found is to use `--toc` on the command line instead of the `toc: true`
setting in the YAML header.
It is a known issue, here are more details:
https://github.com/jgm/pandoc/issues/2872
With this fix I get table of contents not only for PDF but for HTML too.
The PDF looks like before for me, the table of contents and the outline
are still present as it was before.
=> manuals: Fix missing/wrong table of contents in HTML files

gui/projectfiledialog.ui
This fixes https://trac.cppcheck.net/ticket/9456 (Tell the user that the
addons require Python) regarding the GUI. Whether it is useful/necessary
to add something similar for the CLI must still be checked.
=> GUI: projectfiledialog.ui: Add note about addons requiring Python

addons/cert.py, addons/findcasts.py, addons/misc.py, addons/misra.py, addons/naming.py, addons/threadsafety.py, addons/y2038.py
Use Python 3 instead of Python 2 if addons are executed directly.
Running cert.py and misra.py against test/cfg/std.c.dump shows that
Python 3 needs only half the time compared to Python 2. I have tested
it repeatedly and the results are always the same. This is no surprise
at all. The memory footprint is very likely also significantly better
but i have not tested it.
=> addons: Change shebang to use Python 3 instead of Python 2

addons/misra.py, addons/test/misra/misra-test.c
Implementation of MISRA-C 2012 Rule 2.7 check: 
There should be no unused parameters in functions (Category: Advisory).
- Add rule check to misra.py
- Add test cases to misra-test.c
NOTE:
Some test patterns for other MISRA rule checks in misra-test.c use functions with unused parameters which will be listed as MISRA-C 2012 Rule 2.7 finding.
Usually compiler reports unused function parameters too (verified by GCC and Microsoft C/C++ compiler).
=> Add check for MISRA-C 2012 Rule 2.7 and test cases.

test/testgarbage.cpp
The invalid code in Trac tickets [#8750](https://trac.cppcheck.net/ticket/8750), [#8753](https://trac.cppcheck.net/ticket/8753), [#8756](https://trac.cppcheck.net/ticket/8756), [#8762](https://trac.cppcheck.net/ticket/8762), [#8764](https://trac.cppcheck.net/ticket/8764)
and [#8765](https://trac.cppcheck.net/ticket/8765) previously crashed cppcheck. Now it throws a syntax error
instead. Add some tests for these tickets.
=> Add regression tests for fixed crashes

addons/naming.py, cli/cmdlineparser.cpp, cli/cppcheckexecutor.cpp, cli/filelister.cpp, gui/checkthread.cpp, lib/checkfunctions.cpp, lib/checkleakautovar.cpp, lib/checkmemoryleak.cpp, lib/checkother.cpp, lib/checkother.h, lib/checkuninitvar.cpp, lib/cppcheck.cpp, lib/errorlogger.h, lib/importproject.cpp, lib/library.cpp, lib/library.h, lib/mathlib.cpp, lib/symboldatabase.cpp, lib/timer.cpp, lib/timer.h, lib/tokenize.cpp, lib/tokenize.h, lib/tokenlist.cpp, naming.json
This fixes that errors in JSON files given via `--addon=*.json` are
silently ignored and maybe only a part of the JSON file is used.
Now the error message which picojson can return is checked and a
corresponding error message is returned again by getAddonInfo().
=> cppcheck.cpp: Check for JSON error when parsing addon .json files

tools/donate-cpu.py
Yesterday, I observed that some client with a wrong jobs setting
(only "-j") requested one package after another and always uploaded
results where it only said that the argument "-j" is invalid for
Cppcheck.
This check should avoid such cases where results are overwritten with
useless data and the server is kept busy for nothing.
=> donate-cpu.py: Verify argument for jobs (-jN)

lib/library.cpp, lib/library.h, test/testbufferoverrun.cpp, test/testnullpointer.cpp
Format-string arguments are now marked to have `in` direction, except
for `scan`-functions (like `scanf`) where these arguments are explicitly
marked to have `out` direction.
=> Fix #9478: Valueflow: printf does not change value

addons/cert.py, addons/test/cert-test.c
There is [following exception](https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177):
> ENV33-C-EX1: It is permissible to call system() with a null pointer argument to determine the presence of a command processor for the system.
This has been reported in [this thread](https://sourceforge.net/p/cppcheck/discussion/development/thread/0ff41d92b7/?limit=25#3240).
=> cert.py: Add ENV33-C-EX1 exception

test/testnullpointer.cpp
This adds a regression test to make sure that directly dereferencing a
returned NULL pointer issues a warning.
This has been asked on Stack Overflow:
https://stackoverflow.com/q/58981369
Cppcheck 1.89 does not warn for such a code, but 1.90 dev does. So it
is a good idea to make sure it is detected in the future too I guess.
=> testnullpointer.cpp: Add test for dereferencing returned NULL pointer

cli/cmdlineparser.cpp
Hi!
*First of all, thanks a lot for this tool!*
I think the cli help could be improved. Here is an attempt to fix:
* The old default format is not indicated. Changing the default format broke my wrapper and it took me a bit of investigation to find out.
* Daca2 format is not indicated in the help but available in the source code
=> Improve cli --help

addons/misra.py, addons/test/misra/misra-test.c
This will close https://trac.cppcheck.net/ticket/9497
=> misra.py: Fix 5.3 FP

gui/cppcheck_de.ts, gui/cppcheck_es.ts, gui/cppcheck_fi.ts, gui/cppcheck_fr.ts, gui/cppcheck_it.ts, gui/cppcheck_ja.ts, gui/cppcheck_ko.ts, gui/cppcheck_nl.ts, gui/cppcheck_ru.ts, gui/cppcheck_sr.ts, gui/cppcheck_sv.ts, gui/cppcheck_zh_CN.ts
The Korean language file was missing the "language" attribute, so it was
no longer updated before.
The Russian language file had the attribute "sourcelanguage" set to
"ru_RU" which does not make sense and led to some wrong/strange entries.
The France and Korean translation files were missing the "location"
entries, so the GUI-preview with the translated text was not shown and
there were no references to the source-code.
All these errors are fixed.
For the German file I translated the new hint about addons requiring
Python being installed.
=> GUI: Fix and update translation files

addons/test/misra/misra-test.c
Adding more tests for rule 14.2 revealed a false negative when the
loop counter is changed inside the loop.
Corresponding line in the example suite:
https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/blob/master/R_14_02.c#L39
Also a false positive has been revealed when the loop counter is
initialized in a function that is called in the first `for` clause.
Corresponding line in the example suite:
https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/blob/master/R_14_02.c#L43
=> misra-test.c: Add more tests for rule 14.2 (including FP and FN)

lib/tokenize.cpp, lib/tokenlist.cpp, test/teststl.cpp, test/testtokenize.cpp
The underling problem is that we simplified `const_cast<a*>(&e)` to `const_cast<a*> e` which causes ast to be wrong. 
I have also made it such that the statements like `if`, `while`, `for`, and `switch` that are missing the ast nodes become a syntax error so we can try to catch more of these cases in the future.
It would be nice if we could add a check such that certain angle brackets are always linked(such as after `template` or a C++ cast), but I didn't add such validation in this PR.
=> Fix crash 9492: Crash in FwdAnalysis::checkRecursive() (condTok is nullptr)

test/testpostfixoperator.cpp
@danmar Could you please evaluate this change?
I looked up the code change history and this test case doesn't quite match the code in the ticket. The code in the ticket is valid and would compile but the code in the test case is invalid (because one cannot randomly increment a pointer outside a function scope) and would not compile with Visual C++. This makes the checker code to not find the increment, so the test doesn't actually test the checker code. The change I propose make the code closer to the ticket code.
Do you have any objections against this change?
=> Valid code for incrementing raw pointer

addons/test/test-y2038.py, addons/test/y2038/y2038-test-5-good-no-time-used.c, addons/y2038.py
At the beginning of `check_y2038_safe()` the variable `y2038safe` should
be initialized with `True` and only be set to `False` if there are any
issues. Otherwise it could never become `True`.
In the unit tests the return value of `check_y2038_safe()` is now
verified. But it does not yet work for the "good" example. The "good"
example also returns `False` since it finds warnings in the include
file. So this verification is marked with a "FIXME" comment.
=> y2038 addon: Fix that check can never return True, add tests

lib/checkmemoryleak.cpp, test/testmemleak.cpp
`checkReallocUsage()` already contains code to suppress the _Common realloc mistake: 'bs' nulled but not freed upon failure [memleakOnRealloc]_ error message when the pointer has been previously copied from another variable (hence there is an additional copy of the original pointer value) within the same function, as so:
```c
char *foo(char *bs0)
{
char *bs = bs0;
bs = realloc(bs, 100);
if (bs == NULL) return bs0;
return bs;
}
```
We were getting false positives in similar code because the initial assignment was of the form
`bs = *bsptr` or `bs = structptr->my_bs` rather than the RHS being a simple identifier. This patch extends the suppression code to recognise those two patterns (and I guess `bs = mystruct.my_bs`) as also meaning that there is an existing variable containing the exact …
=> Avoid some additional memleakOnRealloc false positives

lib/valueflow.cpp, test/testvalueflow.cpp
https://trac.cppcheck.net/ticket/9510
=> Fix #9510: Crash in valueflow.cpp solveExprValues() (division by zero)

addons/cppcheckdata.py, addons/misra.py
**Problem**: Most of python classes have no `__repr__` method defined. While debugging if you do print an object you get something like, as follows:
<cppcheckdata.Suppression object at 0x0000017A3E8D3780>
This does not give much information about the object contents.
Instead the following string representation would be more useful.
Suppression(errorId='misra_21.6', fileName='misra-suppressions1-test.c', lineNumber='7', symbolName=None)
This Pull Request adds `__repr__` to several classes.
=> [python] classes are missing __repr__ methods

externals/simplecpp/simplecpp.cpp, externals/simplecpp/simplecpp.h, lib/cppcheck.cpp, lib/preprocessor.cpp, lib/preprocessor.h
Currently, only errors that are issued during preprocessing are caught.
Related simplecpp issue: danmar/simplecpp#183 simplecpp PR: danmar/simplecpp#184
=> Catch preprocessor errors possibly issued during loading files

addons/test/util.py
Hi,
for reasons that are out of my control I need to run tests in a windows environment.
set PYTHONPATH=addons
python -m pytest addons/test/test-misra.py
This fails because `cppcheck` can't be found, when I compile cppcheck with visual studio. the release binary via `MSBuild cppcheck.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142` it's found under `bin`.
Would this change be ok?
=> [windows] cannot run test-misra (binary not found)

lib/errorlogger.cpp, test/testerrorlogger.cpp
Using "--suppress=unmatchedSuppression" did not suppress the error-id in
all files, one needed to specify `"*"` as file-name. This commit also
allows empty file-names to suppress "unmatchedSuppression", not only "*"
or the exact file-name.
The manual uses the following example for suppressions specified in a
file:
```
// suppress all uninitvar errors in all files
uninitvar
```
This example suggests that no "*" has to be used to get suppression in
all files. I think that the command line parameter should work in the
same way.
=> errorlogger.cpp: Handle empty file-name like "*" (unmatchedSuppression)

tools/donate_cpu_lib.py
Decoding a string is not allowed in python 3 (in python 2 it works).
If fetching the package fails, assign an empty byte string instead to
avoid crashing.
When this happes, previously there was a crash of the running script.
Now it will cause `donate_cpu` do wait 30 seconds before retrying, while
`test-my-pr` will exit cleanly. I saw this when trying to run `test-my-pr`
(more than once), probably due to shaky connection, perhaps `test-my-pr`
should also wait and retry at least a couple of times before exiting?
=> donate_cpu_lib: Fix python 3 crash if fail to get package

tools/test-my-pr.py
Previously, calling test-my-pr with a relative work-path resulted in a
crash when trying to create the result file (due to the change of
current working directory).
=> test-my-pr: Allow work_path to be relative

addons/cppcheckdata.py
This commit fixes `__repr__` methods introduced in d538315268dd84440ddb6dc482672df095e19258. Fields that recursively links to other cppcheckdata objects was removed from `__repr__` to avoid max recursion depth crash on printing.
To reproduce this crash try to print, for example, a single `cppcheckdata.Token` object in any addon file.
=> addons: Fix __repr__ methods

gui/checkthread.cpp, lib/cppcheck.cpp
Hello
We discussed in pr #2153 issue with extra huge .dump files. You proposed to remove it when they have been used. This humble change should add such functionality.
=> Remove .dump file after plugins execution

addons/misra.py, addons/test/misra/misra-test.c
Make rule 12.3 check detect commas in the variables declaration code.
=> misra.py: Fix R12.3 false negative in variables declaration

addons/misra.py, addons/test/misra/misra-test.c
Add feature to detect essential type categories for operators of ternary operation.
This fixes issues with rule 10.1 and closes the following ticket: https://trac.cppcheck.net/ticket/9543
=> misra.py: Handle essential type categories for ternary operations

test/CMakeLists.txt
When tests are built, the minimum required cmake version is 3.4.
The file test/CMakeLists.txt uses `cmake_policy(SET CMP0064 NEW)`,
which requires cmake 3.4 [1].
[1] https://cmake.org/cmake/help/v3.4/policy/CMP0064.html
=> Update cmake_minimum_required VERSION

externals/simplecpp/simplecpp.cpp
From merged PR danmar/simplecpp#187.
=>  bug fix - de-escape double backslashes in file paths of #line directives 

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Please do not merge it yet - the testcase is overcomplicated and can be simplified to expose the same behavior.
The repro in https://trac.cppcheck.net/ticket/7159 exposes the following situation:
1. argCount() yields 1 and initializedArgCount() yields 2 which makes no sense
2. and therefore minArgCount() does unsigned subtraction "1-2" which overflows (defined behavior)
3. result of step 3 is then implicitly converted into signed int which is implementation defined and yields "-1" for many popular implementations
4. "-1" is returned by a function which has "nonneg" annotation
5. minArgCount() yields a value which is negative which makes no sense
So it looks like it should better be addressed. I'm not sure this fix doesn't break anything else.
=> Fixed #7159 (wrong handling of function parameters)

lib/tokenize.cpp, test/testgarbage.cpp
I have run this test-my-pr.py with 978 packages (before getting too bored) and
the only difference is in the package `binkd-1.1a-99`. Both current master and
this change reports a syntax error, but with this change, cppcheck reports that
`!)` is wrong syntax (previously, only the line was reported).
=> Fix #8758 (add syntax error for invalid code)

.travis_suppressions, lib/checkclass.cpp, lib/checkclass.h, test/testclass.cpp
That's kind a weird style when derived class has a private method which is public in parent.
You can't invoke it directly but could cast it to parent and invoke.
=> Check that virtual function non-narrow access modifier in derived class

tools/triage/mainwindow.cpp
Minor tweaks to make `triage` work on log-files generated by `test-my-pr.py`.
=> Make triage work with log-files from test-my-pr.py

lib/astutils.cpp, lib/astutils.h, lib/checkcondition.cpp, lib/checkother.cpp, test/testcondition.cpp
This fixes the FPs in this case:
```cpp
int f(int a, int b) {
static const int x = 10;
return x == 1 ? a : b;
}
```
And in this case:
```cpp
const bool x = false;
void f() {
if (x) {}
}
```
=> Fix false positives in knownConditionTrueFalse when using expressions with const variables

lib/checkother.cpp, test/testother.cpp
This workarounds false positives 'Parameter  can be declared with const [constParameter]'
when said parameter is used in constructor call. It assume the
constructor call might change the parameter (without any checks.
The drawback is that we have false negative, in cases where we could
check the constructor actually takes a const reference, or a copied by
value parameter.
I'll try implementing smarter checks to handle more constructors (right now, only constructor that take only one parameter are considered), and to check if we can have the warning (in cases of const ref/copied by value parameter in the constructor).
However, this looks rather complex. I believe we currently don't have the facility to know which constructor is called; do we ? So fixing this would means find the called …
=> 9356: Prevent false positive when passing non-const reference to member constructor

lib/checkclass.cpp, lib/checkclass.h, lib/checkunusedvar.h, test/testclass.cpp
As you mentioned in initial commit, I improved error message.
Also tracked hits on /diff-hidingInheritedPublic page and doesn't find any suspicious. Yep, some projects has bunch of hits but I didn't find any evidence why.
=> Clarify error msg for hidingInheritedPublic

lib/checkstl.cpp, test/teststl.cpp
Previously, as the check was done on the token and not on the ast,
`i <= v.size()` and `i <= v.size() - 2` would both raise the same
warning.
This patch fixes this, but this mean the check is only done when the
condition if `i <= v.size()`. Any other (more complex) condition is
ignore, and so we have false negative for instance with
`i <= v.size() + 1`.
=> Fix 9546: properly check that the bound is the size

addons/misra.py
improve misra analysis performance:
- misra_5_3
- misra_5_4
- misra_5_5
- misra_12_4
- misra_20_1
- misra_20_2
Hello.
Our group used `cppcheck` and `misra.py` analyzer. But, sometime we handled huge size of dump file.(maximum 13GB..)
It's very critical issue for us. Because, resources are limited and response should be fast.
So, we improved six of misra rules. (we are already used it.)
Core idea is join fewer token list, and get faster value of tokens.
Especially effective at `misra_5_3` and `misra_5_4`.
These two rules sometimes loop in very deeply. So, bring up to slows down analysis performance and consumes a lot of memory.
We've already tested it on several projects, but I hope it's officially released in review here.
=> improve 6 of misra analysis performance

htmlreport/cppcheck-htmlreport
The 1 pixel dotted border that is drawn around every Cppcheck error
message adds 2 extra pixels for every line with an error message.
For more than very few error messages in a file, the discrepancy is
clearly visible and line numbering gets wrong.
This commit removes the dotted border as it is not necessary.
The error message is highlighted with a red background and is still
clearly visible.
Ticket: https://trac.cppcheck.net/ticket/9501
=> Fix #9501: htmlreport: Line number position is shifted

addons/misra.py
After upgrading to latest version of cppcheck, it produced internal errors when using the misra checker (see attached screenshot).
After some investigation, the errors seem to be caused by the misra 12.3 checker function in misra.py.
To me, it looks like there might be a typo: when referencing the end_tokens_map, the linenr of the wrong token seems to be used.
This is fixed by this PR, it removes the internalErrors.
Also, the end_tokens_map is now a defaultdict, to minimize the risk of similar typos in the future and to clean up the code.
=> Fix potential typo: use token.next.linenr instead of token.linenr

.travis.yml
Make more compilation silent, and use `make check` instead of `make test` to avoid printing every single test case.
Also, run tests on osx and Ubuntu Trusty (previously, testrunner was only compiled).
=> Travis: make logs less noisy

.travis.yml, tools/donate-cpu.py, tools/test/run_donate_cpu_client_tests.sh
This makes it possible to implement new features like .tar.xz support
(see https://trac.cppcheck.net/ticket/9508) or aborting endlessly
running analysis via timeout (see
https://sourceforge.net/p/cppcheck/discussion/development/thread/86813a8a53/).
=> daca@home client: Require at least Python 3 from now on

tools/daca2-getpackages.py
There were two issues:
1. The version was not correctly extracted out of the filename. When
extracting a sub-string in Python one has to specify start index and
end index instead of start index and length.
2. The function `semver.cmp()` does nothing useful. Instead the function
`semver.compare()` must be called when two version should be compared.
See https://github.com/python-semver/python-semver/issues/117#issuecomment-479188221
Because `semver.compare()` now really compares the versions it is
possible that an exception is thrown if a version is not in the semver
version format. In such cases the sorting is aborted and the last
filename in the array is returned. This is often but not always already
the latest version from what I have seen.
=> daca2-getpackages.py: Fix semver sorting and getting latest package

lib/valueflow.cpp, test/testvalueflow.cpp
Ensure bifurcate() does not recurse endlessly where a variable is
initialized recursively, or a variable is initialized as `x(0)` or `x{0}`
followed by a recursive assignment (for example `int x(0); x = x / 1;`).
The first case is solved by bailing out if there initialization is done
using `x(0)` or `x{0}`, the second by adding a missing depth argument to a
recursive call.
=> Fix 9577 (endless recursion in Valueflow::bifurcate())

tools/daca2-getpackages.py, tools/donate-cpu.py
Using .tar.xz packages adds about 4500 additional packages that can be
tested and changes many existing packages where a more recent version
can be used now that is only available as .tar.xz file.
Related ticket: https://trac.cppcheck.net/ticket/9508
=> daca2-getpackages.py: Fix #9508: Add support for xz compressed archives

cli/threadexecutor.cpp
The rename to bughuntingReport was incomplete. Found while investigating the failures with https://github.com/danmar/cppcheck/pull/2496
=> Fix AppVeyor issue following reportVerification rename.

cfg/qt.cfg
As far as I can see this is a typo. The actual definition of vsprintf is directly below.
=> Fix typo in cfg file for Qt

cli/cppcheckexecutor.cpp, lib/importproject.cpp, lib/suppressions.cpp, lib/suppressions.h, lib/utils.h, test/testimportproject.cpp, test/testrunner.vcxproj, test/testrunner.vcxproj.filters, test/testsuppressions.cpp, test/testutils.cpp
Ticket 5607: https://trac.cppcheck.net/ticket/5607
Now it is possible to ignore paths with glob:
`cppcheck -i*autogen\*`
Glob pattern matching already been implemented in the Suppression class as a static method. I moved implementation to Utils.
=> Ticket 5607: Allow to exclude folders with glob pattern

tools/donate-cpu-server.py, tools/donate-cpu.py, tools/donate_cpu_lib.py, tools/test-my-pr.py
This adds a timeout of 60 minutes for the Cppcheck analysis.
Timed out results do not count as crash but they are uploaded and
marked with "TO!" in the list of the latest results. No "diff" is
generated for timed out results so they do not add wrong entries to
the "Diff report".
In test-my-pr.py the timed out results are listed separately just like
the crashes.
=> Donate CPU/test-my-pr: Add timeout for the Cppcheck execution

lib/tokenize.cpp, test/testtokenize.cpp
This patch fixes the detection of designated initializers in ``Tokenizer::findGarbageCode``.
=> Ticket #9572: Properly detect designated initializers.

lib/tokenize.cpp, test/testtokenize.cpp
This ticket highlights that we're wrongly substituting type aliases within enum definitions, that should be untouched.
This patch fixes it.
=> Ticket #9569: Do not substitute type aliases within enum definitions.

tools/donate_cpu_lib.py
This limits the backtrace to a maximum of 50 entries.
Trac ticket: https://trac.cppcheck.net/ticket/9584
=> Fix #9584: Limit stack trace depth in daca@home crash page

.travis.yml, addons/cppcheckdata.py, addons/misra.py
Fix false positives with rule 5.4 with C99 standard.
See: [trac 9592](https://trac.cppcheck.net/ticket/9592).
=> misra.py: Fix R5.4 false positives with C99

lib/astutils.cpp, test/testastutils.cpp
Improve isSameExpression() for literals with same value but different
representation, for example  the following different ways of
representing 9 as double: 9.0, 0.9e1 and 0x1.2p3.
With this change, cppcheck can (for example) correctly detect that the
else if statements are always false in the following example:
void f(double x) {
if (x < 9.0) {}
else if (x < 0x1.2p3) {}
else if (x < 0.9e1) {}
}
`test-my-pr` shows no problems with this, except... negative floating point zero, which seems to be optional in the standard (but IEEE floating point standard mandates it, and at least on my computer (linux), gcc (and glibc) treats them slightly different). From my understanding `0.0` and `-0.0` are equal in most aspects, (for example `0.0 == -0.0` is true, `0.0 > -0.0` is false). But! Math …
=> Improve isSameExpression for literals

lib/astutils.cpp, test/testastutils.cpp
It allows (for example) cppcheck to detect that the lhs and the rhs are
the same in the following example:
double g()
{
double a = 1e1
return a & 10.0;
}
=> Improve isSameExpression for same valued literals with followvar

addons/misra.py, addons/test/misra/misra-test.c
Define different sets of reserved keywords for C90 and C99.
This will fix false negative for compliant example, defined in MISRA document, and close [trac 9506](https://trac.cppcheck.net/ticket/9605).
=> misra.py: Fix false negative for rule 20.4

cli/cppcheckexecutor.cpp
Hi,
some time ago I was looking for this feature: https://sourceforge.net/p/cppcheck/discussion/general/thread/08b0400c/
Looks like it is actually almost there. This tiny PR allows filtering (--file-filter) together with project files. 
Thanks for making cppcheck!
=> Allow filtering when using --project

lib/astutils.cpp, lib/astutils.h, lib/checkfunctions.cpp, lib/checkother.cpp, lib/checkunusedvar.cpp, lib/mathlib.cpp, lib/symboldatabase.cpp, test/testastutils.cpp, test/testmathlib.cpp, test/testother.cpp
Technically, it's not really an FP, but I think it's inconsistent that assigning with `0` gives no warning, and `0U` gives a warning.
=> Fix redundant FP assignment with unsigned zero

addons/misra.py, addons/test/misra/misra-test.c
According MISRA standard, rule 21.1 should hanlde `#define`and `#undef` directives only. There are no mentions of other C identifiers in the standard document.
See also: https://github.com/danmar/cppcheck/pull/2524
=> misra.py: Fix rule 21.1 false positives

addons/misra.py, addons/test/misra/misra-test.c
This commit add two additional cases for rule 20.3:
1. Support violations in the following format: `#include file.h`
2. Better multiline include directives and inline comments support.
See added test cases for examples.
=> misra.py: Handle more cases in Rule 20.3 check

addons/misra.py, addons/test/misra/misra-test.c
Add identifiers from C90 and C99 standards which are required to add additional analysis for some MISRA rules.
This commit fix false negatives for rule 21.1 and close [Trac9603](https://trac.cppcheck.net/ticket/9603).
=> misra.py: Add standard library identifiers

lib/checkleakautovar.cpp, test/testleakautovar.cpp
Fix false positive introduced by
https://github.com/danmar/cppcheck/commit/0b7649ca9bb51a2f8b587afc2e085bf1d82d1013
Only return the function token from checkTokenInsideExpression when it
might be one the argument (hence keeping a pointer to one of them).
Otherwise, we can directly skip to the token after the function call.
=> 9575: false positive in fclose

test/testleakautovar.cpp
=> Add regression test for #9187

lib/preprocessor.cpp, lib/suppressions.cpp, lib/suppressions.h, test/testsuppressions.cpp
The old method to declare inline suppress may affect the code readability, especially when I use inline suppresses in big project, It's really a hell. I found the main reason is that every inline suppress need occupy one line, It disorganized the origin code. for example:
Now I give a new method to declare many inline suppress In the same line with the error code. It's format just like: "cppcheck-suppress:errorId@symbol", and you can write many suppress in one line, the  part of "@symbol" can be ignored, also you can use common comment around them arbitrarily. for example:
the suppress comment above has the same effect with old method, but It's more readable.
=> a new method to declare inline suppress which is more readable and more convenient.

tools/donate_cpu_lib.py
Highly inspired by https://stackoverflow.com/a/4791612.
To test, you can run the following command (change `CPPCHECK_TIMEOUT` to 60 or so to avoid waiting for one hour):
```
python donate-cpu.py -j3 --test --package=ftp://ftp.de.debian.org/debian/pool/main/s/skyeye/skyeye_1.2.5.orig.tar.gz
```
When run with `donate-cpu` in the current repo, it does not exit after the timeout has expired.
If someone has a better idea, I'm all for it. This probably needs some testing (according to the python docs, the commands I used are unix only), I've run in on Arch Linux, and it seems to work. Testing on WSL, cygwin, mingw (if donate-cpu runs on these platforms)  would be much appreciated.
=> donate_cpu: Fix timeout if multithreaded

cfg/gtk.cfg, test/cfg/gtk.c
A missing definition for g_assert_cmp*() causes syntax errors if code
like g_assert_cmpint(a, ==, b); is encountered.
The function g_hash_table_iter_replace() does not have to be marked
with leak-ignore since the memory could be freed later if corresponding
functions are present in the GHashTable. Since we can not know if this
is the case we have to assume that the memory is freed to avoid false
positives. The same is true for g_hash_table_insert() and
g_hash_table_replace().
=> gtk.cfg: Fix syntax errors and false positives

cfg/qt.cfg, test/cfg/qt.cpp
chop() and also remove() change the size of a QString, so they have to
be added in the container configuration accordingly to avoid false
positives.
=> qt.cfg: #9650: Fix missing configuration for QString.chop()

addons/misra.py, addons/test/misra/misra-test.c
Add `stdint.h` types to misra.py checks. This will fix false negatives for rules 10.6 and 10.8.
This commit will close [Trac9638](https://trac.cppcheck.net/ticket/9638)
=> misra.py: Handle stdint.h types

tools/donate_cpu_lib.py
Sometimes it could happen that SIGSEGV is thrown when Cppcheck is killed
because of a timeout. Then the execution is wrongly handled as a crash
and debugged with gdb instead of marking it as timed out.
This fixes that issue by checking the time out before checking sig_num.
=> donate_cpu_lib.py: Fix that timed out analyses are handled as crashes

cfg/cppcheck-cfg.rng, cfg/gtk.cfg
This adds/fixes some miscellaneous Gtk/Glib utility functions.
Reference:
https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html
For specifying pointers to pointers as return value types the
cppcheck-cfg.rng has been enhanced to allow this.
=> gtk.cfg/cppcheck-cfg.rng: Add Gtk utility functions, enhance RNG file

cmake/compileroptions.cmake
testrunner fails with SEGFAULT when built with cmake under Cygwin.
This fix adds a compiler option to increase the stack size in the same
way as it is already done in the Makefile.
=> cmake/compileroptions.cmake: Fix missing stack options under Cygwin

lib/symboldatabase.cpp, lib/symboldatabase.h
This is a better implementation of what was discussed in https://github.com/danmar/cppcheck/pull/2384 The code is moved outside header so that users don't need specific warning settings. It can be simplified later if warning settings are changed in the project.
@danmar Daniel, do you like this?
=> Avoid giant C4267 warning in 64-bit Visual C++ build

cmake/compileroptions.cmake
I had this warning disabled locally for quite a while now since it is just too noisy and not helpful at all. The Makefile also doesn't contain this. Has a different author since I came across this while looking at the patches which Debian has applied - see https://packages.debian.org/sid/cppcheck and http://deb.debian.org/debian/pool/main/c/cppcheck/cppcheck_1.90-4.debian.tar.xz
=> Disable warnings causing too much noise

lib/valueflow.cpp, test/testvalueflow.cpp
This should help improve long analysis times when the number of arguments can grow too large.
=> Set a max for the combination of arguments that can be passsed through valueFlowSubFunction

lib/checkstl.cpp, lib/checkstl.h, test/teststl.cpp
This adds a new check `invalidContainerLoop`.
=> Fix issue 9435: False negative: invalidContainer when using range for loop

lib/checkcondition.cpp, test/testcondition.cpp
Now we warn about conditions like these:
```cpp
void f(bool a, bool b) {
if (a || (a && b)) {}
if (a && (a || b)) {}
}
```
=> Find more redundant conditions

lib/checkunusedvar.cpp, test/testunusedvar.cpp
struct A
{
static const int a = 0; //detected as unused member in cppcheck 1.9 release
};
int foo()
{
return A::a; //used here
}
=> avoid false positive unused static const struct member

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml
For Windows PCRE had to be built. On ubuntu and macos the pre-installed library is being used.
=> CI builds now supporting RULES

cli/cmdlineparser.cpp, cli/cmdlineparser.h, lib/importproject.cpp, lib/importproject.h, man/manual.md
In #1795 a command line option was introduced, but the PR was not completed.
Here is the change again, limited to command line access.
Thanks to @fuzzelhjb providing base implementation.
Maybe missing:
=> add command line option to select single project configuration of loaded solution

lib/tokenize.cpp, lib/tokenlist.cpp, test/testtokenize.cpp, test/testvarid.cpp
Hey!
As an exercise to learn how the code works I am attempting to fix a defect reported by myself.
The warning was easy to fix in findGarbage, however there are a couple more places where a change was required. 
I did reuse a couple of test scenarios from previous tickets related to designated initializers to make sure they don't occur with this syntax as well.  If that is excessive, I will remove them.
Will be glad for any feedback.
Currently  these examples all produce different AST's:
{ .x = 3 }; 
{ .x = { 3 } }; 
{ .x { 3 } }; 
I had an idea to use a simplification to change case 3 into case 2, but then read in another pull request that you prefer not to use simplifications.
=> Fixes #9664 - False positive on C++20 designated initialization 

lib/checkother.cpp, lib/checkother.h
This will make the name more consistent with other checks(like `knownConditionTrueFalse`). Checks named with `const` usually are for checking when the `const` keywords can be used(like `constParameter` or `constVariable`). 
This also avoids the confusion between the difference of `Argument` vs `Parameter`.
=> Rename constArgument to knownArgument

gui/mainwindow.cpp
Since knowing the version number is often important, show it in the title bar.
I don't have a fully functional Qt compilation environment, so this is a half-blindly made patch, which is known to compile, but untested otherwise.
=> Show version number in Cppcheck GUI's title bar

lib/checkclass.cpp, test/testclass.cpp
A base class destructor should be either public and virtual, or protected and non-virtual
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-dtor-virtual
Following discussion at: https://sourceforge.net/p/cppcheck/discussion/general/thread/0a321369c3/
=> Enforcing CppCoreGuideline C.35 on virtual class destructor

addons/misra.py
The rules 5.1 and 5.2 did not respect the c standard config value, but had 31 significant number of chars hardcoded.
=> misra.py: Fix 5.1 and 5.2 FP for c99

cfg/posix.cfg
There is another function with name `ttyname`. Also the comment suggests there is a typo.
=> [posix.cfg] Fix ttyname_r typo

cfg/posix.cfg
In `posix.cfg` all parameters that are file descriptors should have a proper range value of [0, Max].
(-1 depicts an invalid fd that is returned in case of error from other file handling functions. 0, 1, 2 can be reused if they had been closed previously.)
=> [posix.cfg] Fix file descriptor params to have proper range value

cfg/gnu.cfg, cfg/posix.cfg
Parameters of the fstat family function that are file descriptors should have a proper range value of [0, Max].
The signature of `fstat` was wrong, it is different from `stat` (probably a copy paste error in the past).
`__fxstatat64` has different signature than `fstatat64`, that is fixed also.
=> [posix.cfg] Fix fstat family

gui/codeeditor.h, gui/filelist.cpp, gui/main.cpp, gui/mainwindow.h, gui/threadhandler.h, gui/xmlreport.h, lib/check.h, lib/exprengine.cpp, lib/forwardanalyzer.h, lib/token.cpp, lib/valueflow.cpp
If we could extract `Severity` from `errorlogger.h` we could get rid of that include in `check.h`. According to `ClangBuildAnalyzer` it is the heaviest include during compilation.
=> cleaned up includes based on include-what-you-use

.travis.yml
I'm not sure how long cppcheck needs to support python 2, but I guess it still does so let's make sure it works with both python 2 and 3.
=> travis: Test matchcompiler with both python2 and python3

test/testtokenize.cpp
In #2646 we agreed that i would be better for testAst to take an enum rather than 2 bools but that it would confuse things to make the change in that pull request. This makes that change. I had assumed that there would be many use cases for the old signature but it turns out there was only one.
=> cleanup after #2646

addons/test/util.py, lib/valueflow.cpp
```
./bin/cppcheck --dump --quiet ../addons/test/misra/misra-test.c
AddressSanitizer:DEADLYSIGNAL
=================================================================
==15993==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x55f6a7e19b53 bp 0x7ffd72146250 sp 0x7ffd72146240 T0)
==15993==The signal is caused by a READ memory access.
==15993==Hint: address points to the zero page.
#0 0x55f6a7e19b52 in Token::isArithmeticalOp() const ../lib/token.h:418
#1 0x55f6a7e19aa5 in Token::isConstOp() const ../lib/token.h:408
#2 0x55f6a860a032 in isDecayedPointer ../lib/valueflow.cpp:3462
#3 0x55f6a860c27e in valueFlowLifetime ../lib/valueflow.cpp:3574
#4 0x55f6a8634aba in ValueFlow::setValues(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) ../lib/valueflow.cpp:6127
#5 …
```
=> Fix crash in addons/test/test-misra.py

addons/misra.py, addons/test/misra/misra-test.c
This will fix crash reported in this thread: https://sourceforge.net/p/cppcheck/discussion/general/thread/0fa96ed286
=> misra.py: Fix R12.4 crash on volatile macro argument

tools/CMakeLists.txt
In tools/, it did not understand that some files are generated by
matchcompiler.py.
```
CMake Error at tools/CMakeLists.txt:7 (add_executable):
Cannot find source file:
</some/path>/cppcheck/build/lib/build/mc_pathmatch.cpp
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
.hpp .hxx .in .txx
CMake Error at tools/CMakeLists.txt:7 (add_executable):
No SOURCES given to target: dmake
```
=> Fix cmake in Release mode

lib/checkclass.cpp, lib/checkother.cpp, lib/checkunusedvar.cpp, lib/symboldatabase.cpp, lib/templatesimplifier.cpp, lib/token.cpp, lib/token.h, lib/tokenize.cpp, lib/valueflow.cpp, test/testastutils.cpp, test/testsimplifytemplate.cpp, test/testsymboldatabase.cpp, test/testvalueflow.cpp
This saves about ~ 0.5% of total instruction count in a run with `mc_exprengine.cpp` - will do some larger tests soon.
=> optimized non-matchcompiled Token::simpleMatch() a bit

lib/checkuninitvar.cpp, test/testuninitvar.cpp
Fix for [#9296](https://trac.cppcheck.net/ticket/9296)
=> fix 9296: false negative uninit variable

cfg/cppcheck-cfg.rng, cfg/opencv2.cfg, test/cfg/opencv2.cpp
cfg/cppcheck-cfg.rng: Fix that functions in classes can not be specified as allocation functions
=> opencv2.cfg: Add types, macros, functions and memory (de)allocation

lib/forwardanalyzer.cpp, test/testbufferoverrun.cpp
In cases like:
```
bool b();
void f()
{
int val[50];
int i, sum=0;
for (i = 1; b() && i < 50; i++)
sum += val[i];
for (; i < 50; i++)
sum -= val[i];
}
```
The forward analysis assumed the second loop was entered, and we ended
up with false positive in it:
`Array 'val[50]' accessed at index 50, which is out of bounds`
=> Fix some false positive in loop forward analysis

lib/tokenize.cpp, test/testsimplifyusing.cpp
The template parameter is confusing simplifyUsing: it does not compute
properly the scope, and we end up replace "type" in "to_string" with
"void", then later "void" is removed and we have an internal error.
=> 9757: skip template parameters when computing scope

AUTHORS, cfg/qt.cfg
https://doc.qt.io/qt-5/qobject.html#Q_FLAG
```
error,unknownMacro,There is an unknown macro here somewhere. Configuration is required. If Q_FLAG is a macro then please configure it.
```
=> Add Q_FLAG macro to qt.cfg

lib/tokenize.cpp, test/testsimplifyusing.cpp, test/testtokenize.cpp
This fixes https://trac.cppcheck.net/ticket/9512 by properly simplifying empty namespaces, handling both anonymous and nested ones.
=> Ticket 9512 - Simplify empty anonymous namespaces.

addons/misra.py, addons/test/test-misra.py, addons/test/util.py
Implemented the option `--severity` for `misra.py` to set a custom severity string for all misra warnings.
The severity string is not limited to `info`, `warning`, `error` etc but it will accept any string, so you could use for example  `misra-warning`.
=> Misra severity

lib/tokenlist.cpp, test/testtokenize.cpp
```
int f(bool x)
{
return x ? 0 : throw 0;
}
```
The `throw` part was not included in the ast, leading to an invalid
ternary operator.
=> 9768: Fix ast with throw in the middle of return

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Cast were not expanded properly: the `<` was not taken into account in
typeindentlevel, so we would then miss a `>`, resulting in syntaxError.
=> Fix handling of c++ casts in template expansion

cfg/boost.cfg, lib/astutils.cpp, test/cfg/boost.cpp
Teaching cppcheck about `BOOST_THROW_EXCEPTION` and
`boost::throw_exception`, and using noreturn information from libraries
in value flow.
This fixes false positive nullPointerRedundantCheck with the following
code:
```
void throwexception(int * buf)
{
if (!buf)
boost::throw_exception(std::bad_alloc());
*buf = 0;
}
```
=> Better handle noreturn or throwing functions in valueflow

lib/valueflow.cpp, test/testvalueflow.cpp
In some cases, the condition of the ternary operator is assigned a known
value after the two possible results, and in such cases, we would not
take the opportunity to assign a value to the ternary operator (and to
the other parents in the ast).
This patch adds this capability.
=> 9769: Improve value flow for ternary operator

win_installer/cppcheck.wxs
The windows installer is currently missing some library files and addons. To make future changes easier, files are ordered alphabetically
=> add missing cfg and addon files to windows installer

cfg/windows.cfg
```
SYSTEM_INFO SystemInfo;
GetSystemInfo(&SystemInfo);
```
causes false positive:
```
error: Uninitialized variable: SystemInfo [uninitvar]
GetSystemInfo(&SystemInfo);
^
```
I'm not sure how exactly cfg files work, but the change included in this PR fixes false positive.
=> cfg/windows.cfg - fixed definition of GetSystemInfo

lib/checkfunctions.cpp, test/cfg/qt.cpp, test/cfg/std.c
This change only report functions that match name in --library but does not match the use defined in --library. Before this change all other function calls not matching a function in --library will be reported as an error.
This fixes trac ticket #9002.
=> not report locally declared functions as missing configuration of --check-library

lib/checkmemoryleak.cpp, lib/symboldatabase.cpp, test/testmemleak.cpp
Skip scopes with lambdas (similar to how `checkleakautovar` does). In
order to fix this when the lambda is inside a for loop, make
`hasInlineOrLambdaFunction()` recursive. This should be what all existing
users want.
=> Fix #9793 (false positive, memleak with lambda)

lib/checkleakautovar.cpp, test/testleakautovar.cpp
When the first argument was `(void *)(1)`, at the start of the second
iteration, arg was pointing to the `1`, which caused problems for
`nextArgument()`, which saw the `)` as the next token and returned
`nullptr`, signalling that there are no more arguments.
Instead, save the first token in the argument, which makes
`nextArgument()` do the right thing.
=> Fix #9652 (fp memleak with function call with cast)

lib/checkleakautovar.cpp, test/testleakautovar.cpp
When checking for comparisons in if-statements, if there are comma
operators in the if-statement, skip until after the last comma.
=> Fix #9635 (FP: Memory leak with comma operator in if-statement)

lib/checkcondition.cpp, test/testcondition.cpp
cppcheck behaved differently if sizeof was to the left or right of the
comparison. In order to fix this, we cannot break the while loop until
all operands have been processed.
I found this when looking for places where visitAstNodes could be used
(as mentioned in #2704) but I figured we could separate the bugfix and
the refactoring.
=> Fix FN with known condition and sizeof

lib/tokenize.cpp, test/testgarbage.cpp, test/testtokenize.cpp
This will fix [#9774](https://trac.cppcheck.net/ticket/9774).
=> Fixed crash on garbage code: comparisson with empty second operand

addons/misra.py
When checking multiple files if the same violation is encountered from
an included file then the violation is both displayed and counted in the
error summary.
Track each violation by location and error number and if the violation
has been previously encountered then do not report it again.
=> misra.py: Squelch duplicate violation messages

lib/checktype.cpp, test/testtype.cpp
The loop only checks astoperand1 and astoperand2. Simplify the condition
to loop over these instead of using a stack. Also, add a testcase for
when astoperand2 is negative.
=> Refactor: Simplify checkSignConversion

lib/astutils.cpp
I was unable to get a reduced test case for this.
=> Fix crash when typeScope is missing

lib/astutils.cpp, lib/astutils.h, lib/checkautovariables.cpp, lib/checkcondition.cpp, lib/ctu.cpp, lib/valueflow.cpp, test/testnullpointer.cpp
This moves aliasing tracking into ValueFlowForwad.
We still check aliases in valueFlowPointerAliasDeref for uninitialized values because some of the aliasing can't be forwarded.
It's also check aliases in valueFlowPointerAliasDeref for container values as well because its not using `valueFlowGenericForward` yet.
=> Fix issue 9807: False positive: ValueFlow in unreachable code, || lhs is true

.gitignore, man/buildman.sh, man/manual-style.tex
The CSS styling only works for HTML files. PDF generation uses LaTeX as an intermediate format, so styling has to be done using latex settings. This now uses the xelatex engine which allows for using any font on your system. I've used Segoe UI and Consolas, fonts but you may need to change those if they aren't supported on your system. I think Consolas is a Windows font, so it may need a more Linux-centric choice.
These are the alternatives which GitHub uses in its own CSS.
BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji
SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace
=> Add GitHub styling to the PDF manual too

addons/misra.py, addons/test/misra/misra-test.c
This will fix [Trac#9633](https://trac.cppcheck.net/ticket/9633)
=> misra.py: Fix false positives in string concatenation for rule 20.7

.gitignore, man/build-html.sh, man/build-pdf.sh, man/buildman.sh
The PDF build command line is getting very long, and it needs another option. Create separate build scripts for HTML and PDF and just pass in the name of the markdown file.
Adds -V subparagraph to fix a LaTeX error.
Adds fallback font selection to the PDF script.
=> Create separate scripts for building HTML and PDF documents

lib/valueflow.cpp, test/testvalueflow.cpp
This fixes issues (at least false positives) in code using them.
For instance:
```
unsigned compute(unsigned long long a) {
unsigned num = 0;
while (a > 0xFFFFFFFF) {
a >>= 32;
num += 32;
}
if (a > 0xFFFF) {
a >>= 16;
num += 16;
}
if (a > 0xFF) {
num += 8;
}
return num;
}
```
would give false positive:
```
cppcheck --enable=style  sl3.cpp
Checking sl3.cpp ...
sl3.cpp:11:11: style: Condition 'a>0xFF' is always false [knownConditionTrueFalse]
if (a > 0xFF) {
^
sl3.cpp:3:14: note: Assuming that condition 'a>0xFFFFFFFF' is not redundant
while (a > 0xFFFFFFFF) {
^
sl3.cpp:11:11: note: Condition 'a>0xFF' is always false
if (a > 0xFF) {
^
```
=> Add missing operators <<= and >>=

lib/suppressions.cpp, test/cli/test-inline-suppress.py
Suppressions::getUnmatchedLocalSuppressions() is called from places where the file name has not been processed by Path::simplifyPath(). This makes the result a miss match with what checks has used as file name. Now we get the same file names.
I do think that 'sprinkling' Path::simplifyPath() around the code is not the best solution. I would like to move this to the user input/config interface. Not the 'backend'. So a future refactor would be to move some of the use of Path::simplifyPath().
=> fix use simplifyPath() to make sure file name is same as in the checks

.gitignore
Keep files generated by clangd and clang tooling project files from git.
=> add temporary clangd and clang project files to .gitignore

lib/checknullpointer.cpp, lib/checkstl.cpp, lib/checkstl.h, lib/token.cpp, lib/valueflow.cpp, lib/valueflow.h, test/teststl.cpp
This adds an initial iterator analysis in valueflow. There is more analysis to be added. For now, I added `checkDereferenceInvalidIterator2` but as valueflow analysis improves, this can hopefully replace `checkDereferenceInvalidIterator`.
=> Fix issue 737: new check: Dereference end iterator

lib/tokenlist.cpp, test/testclass.cpp, test/testtokenize.cpp
https://trac.cppcheck.net/ticket/9839
So this seams to fix the issue, but I'm very confident that this is not done in a good way 😄 
But is shall be more of a starting point, as this is the very first time for me looking into and changing the code in this project.
So I think the problem basically boils down to the issue that the function `` static Token * skipDecl(Token *tok) `` does not skip `` decltype(auto) `` 
so adding my hack 
```cpp
else if (Token::Match(vartok, "decltype ( auto ) ")) {
return vartok->next()->next()->next()->next();
}
```
let still all the test pass.
But...
1)  I'm not really sure this is the real cause of this issue
2)  I don't know if this should be handled in a more generic way?
3) I don't know/understand the bigger picture of cppcheck to dig deeper.
So any …
=> Fix ticket 9839: AST broken; range for loop that uses decltype

lib/symboldatabase.cpp, lib/symboldatabase.h, lib/token.cpp, lib/token.h, test/testvarid.cpp
This adds exprIds to the token. For a variable, the `exprId == varId`. Two tokens only have the same exprId when `isSameExpression` returns true for them. This also doesn't check for variable modifications. We can add value numbering later to track variable modifications but this will most likely be done by ValueFlow analysis. 
We can utilize exprId in both `ExpressionForwardAnalyzer` and `ProgramMemory` in order to evaluate expressions. There maybe other areas where this could be useful.
This also updates the debug print out to show the exprId.
=> Add exprId to tokens

lib/suppressions.cpp, man/manual.md, test/testsuppressions.cpp
We've been adding comments behind our suppressions (in a suppression file) for justifying the suppressions.  This turned out to work okayish until the justification contains a dot.
It turns out that comments after at suppression was not supported at all.
I've added checking for comments as "#" and "//" at the end of suppression lines (and strip whitespace in front), so that this part is ignored when parsing a suppression.  The suppression parsing is kept as before, allthough, the special handling of dots is confusing.
I also added some lines to the manual, and changed one of the examples to use an end-of-line comment.
=> Add support for comments at end of suppression in suppression files

cli/cppcheckexecutor.cpp, lib/exprengine.cpp
Found when building Cppcheck with clang++-12 with `-Wrange-loop-construct`.
=> Prevent copying in range-based for loops

lib/templatesimplifier.cpp, lib/token.cpp, test/testother.cpp, test/testsimplifytemplate.cpp
This code compiles fine but is detected as a syntax error by cppcheck:
```
template <typename T>
constexpr bool is_ratio_v = false;
template <std::intmax_t Num, std::intmax_t Den>
constexpr bool is_ratio_v<std::ratio<Num, Den>> = true;
```
The issue is the >>.
Currently this pull request simply adds a test demonstrating the problem. I would appreciate:
-  if someone with a Trac account would raise a corresponding issue.
- advice on where this test should be located
- currently this test results in an unhanded exception terminating the test runner. How should this be better handled or should I not worry about it since if the test passes it doesn't happen?
- any advice on where to look in the code to fix this.
=> Test for syntax error in nested templates

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
👋 @danmar 
Sorry to bother you again 🙃 
So I have found another issue, and after cutting down my code this fails
```cpp
struct foobar
{
auto operator=(const foobar&) -> foobar&;
};
auto foobar::operator=(const foobar&) -> foobar& = default;
```
with:
```sh
$ cppcheck --enable=all "foobar.cpp"
Checking foobar.cpp ...
foobar.cpp:0:0: error: Internal Error: Invalid syntax [cppcheckError]
^
foobar.cpp:0:0: note: Internal Error: Invalid syntax
^
foobar.cpp:0:0: note: Internal Error: Invalid syntax
^
```
* adding `` { } `` instead of `` default `` works
* adding `` default  `` inside the struct definition works 
* changing it to the classical form ``` foobar& foobar::operator=(const foobar&)  = default; ``` works 
So I added two test cases to reproduce the issue.
cppcheck failes here:
```cpp …
```
=> Add test cases for assign operators with default implementation

lib/valueflow.cpp, test/testcondition.cpp
The code added in test fails because it incorrectly determines that y must be null. It looks like the modified code is there to detect and prevent that case (Related to https://trac.cppcheck.net/ticket/9318 and #2186) however I believe it is failing in this case because the variable in question is defined as auto so astIsPointer returns false (because we don't know if it's a pointer at that stage).
I think in the event that we do know whether the variable is a pointer we should continue to check that because dynamic_casting a reference probably doesn't change what we know about the value (though I suppose it could in the case of non-virtual properties). In the interest of keeping the behavior as similar as possible I've added a check for whether valueType() is null and if it is I skip …
=> False positive dynamic_cast auto variable which has been checked against null

addons/misra.py
When we include the header file with variables definitions, Cppcheck will write `variables` entries with line numbers from the header to the dump file.
If the line number in the header file and the source file are equal, misra.py performs an additional check [here](https://github.com/danmar/cppcheck/blob/e52c4f9aa776cf9b9d60c9e6fa062bd520a2b995/addons/misra.py#L1710-L1726), what leads to false positives.
Minimal example that demonstrates the problem:
`misra_fp.c`:
```c
#include "misra_fp.h"
void test_12_3_fp(void)
{
//Initialize the events queue
QEQueue_init(&me->deferred_event_queue, me->deferred_events_queue_buf, Q_DIM(me->deferred_events_queue_buf));
}
```
`misra_fp.h`:
```c
static const uint32_t timer_max_blocking_call_us;
```
This commit closes [ticket …
=> misra.py: Fix 12.3 FP for variables defined in headers

cfg/std.cfg
Reported in the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/5331c5df2c/
=> std.cfg: Fix memcpy return type

lib/importproject.cpp, lib/importproject.h, test/testimportproject.cpp
@danmar sorry I planned top update this PR more and also do better research where and when this is the issue.
So in my test-example I generate a ` compile_commands.json` via CMake  ` set(CMAKE_EXPORT_COMPILE_COMMANDS ON) ` that looks like this:
```json
[
{
"directory": "C:/Users/dan/git/build-test-cppcheck-Desktop_Qt_5_15_0_MSVC2019_64bit-Debug",
"command": "C:\\PROGRA~2\\MICROS~1\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\HostX64\\x64\\cl.exe  /nologo /TP -IC:\\Users\\dan\\git\\test-cppcheck\\mylib\\src /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd -std:c++17 /Fomylib\\CMakeFiles\\mylib.dir\\src\\foobar\\mylib.cpp.obj /FdTARGET_COMPILE_PDB /FS -c C:\\Users\\dan\\git\\test-cppcheck\\mylib\\src\\foobar\\mylib.cpp",
"file": …
```
=> Fix false skipping of folder-seperator

lib/valueflow.cpp, test/testvalueflow.cpp
The value of something in the middle of a condition with mixed || and &&
gives no information on which branch will be taken.
For instance with:
```
int f(int a, int b, bool x) {\n"
if (a == 1 && (!(b == 2 && x))) {
} else {
if (x) {
}
}
return 0;
}
```
We can enter the if part whether x is true or false, and similarly,
enter the else part whether x is true or false. Same thing with the
value of b.
This fixes the following false positive with above code:
```
:4:13: style: Condition 'x' is always true [knownConditionTrueFalse]
if (x) {
^
:2:33: note: Assuming that condition 'x' is not redundant
if (a == 6 && (!(b == 21 && x))) {
^
```
=> Fix false positives with condition with || and &&

gui/settings.ui, gui/settingsdialog.cpp, gui/settingsdialog.h
This commit adds to cppcheck-gui validation for the path to the Python interpreter entered by the user.
This will reduce the number of user errors like those described at this thread: https://sourceforge.net/p/cppcheck/discussion/general/thread/ccbe9e89/?limit=25&page=4.
=> gui: Add validation for Python path

.gitignore, gui/gui.pro, gui/precompiled_qmake.h
Before
```
Compilation (245 times):
Parsing (frontend):          521.3 s
Codegen & opts (backend):     62.3 s
```
After
```
Compilation (247 times):
Parsing (frontend):          353.5 s
Codegen & opts (backend):     63.0 s
```
Tested with a default build on WSL 2 Kali with Clang 10.
There should be probably a `precompiled_gui.h` include which will be used by `precompiled_qmake.h`, but I will address that when I actually tackled a build needing it.
=> qmake improvements

lib/checkmemoryleak.cpp, test/testmemleak.cpp
Two improvements are made. First, check if the pointer is NULL and do not issue a warning if that is the case. This fixes a few TODO test cases where we know the pointer that is being reallocated is NULL.
Second, fix FN in [#9228](https://trac.cppcheck.net/ticket/9228), that is
```c
void f() {
void *a = NULL;
a = malloc(10);
a = realloc(a, 20); // No warning here due to a = NULL above
}
```
This is done by checking if we assign to a, we avoid assignments with NULL. This change felt a little kludgy but I didn't find a better way to do it.
=> Improve memleakOnRealloc with assignment to NULL

lib/checkunusedvar.cpp, lib/tokenlist.cpp, test/testtokenize.cpp
upgrading from cppcheck 1.90 to 2.1 I observe a new parsing error in code of the form
``` void f(std::function<void()> x = [](){});``` complaining that it cannot parse the lambda.
```cppcheckError: Analysis failed (lambda not recognized). If the code is valid then please report this failure.```
See build results for the first commit for an example of the test failing.
The problem is actually the ```<```. When generating the ast for this expression we end up with ```:: std function``` and miss the rest of the type and the variable name from the term. As such I believe this occurs for any function with a lambda default parameter either of a template type or preceded by a template type.
I asked around and @danmar informs me that we don't really care what the ast for function parameters looks …
=> Improve ast generation for templated function parameters

gui/erroritem.cpp, gui/mainwindow.cpp, gui/projectfiledialog.cpp, gui/resultstree.cpp, gui/threadhandler.cpp, lib/checkinternal.cpp, lib/checkio.cpp, lib/checkother.cpp, lib/checkunusedvar.cpp, lib/cppcheck.cpp, lib/pathmatch.cpp, lib/preprocessor.cpp, lib/symboldatabase.cpp, lib/tokenize.cpp, lib/valueflow.cpp, test/testexprengine.cpp
I did not convert the loops with `const_iterator` since the range loops do not ensure the constness. That's also the reason I didn't enable the warning yet.
=> fixed some modernize-loop-convert clang-tidy warnings

addons/misra.py, addons/test/misra/misra-test.c
C89 standard defines enum members as enumeration contants at ch. 6.4.4.3, and they are always known at compile time.
This commit fix false positives for rule 18.8 (and possible other rules that check "constentness") with enumeration members.
Fix [Trac#9913](https://trac.cppcheck.net/ticket/9913).
Reported on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/fbf8cb7d38/.
=> misra.py: Treat enum constants as constant known at compile time

lib/checkother.cpp, test/testother.cpp
This is a partial fix. Its makes the warning in issue 9916 inconclusive. We could look into removing the inconclusive warning in a future PR, but I think we should add another flag to enable more aggressive copy-paste detection.
=> Fix issue 9916: False positive: duplicateAssignExpression when it's checked if variables have initial value later

lib/templatesimplifier.cpp
Don't count deleted instantiations in the recursive count.
I can't reduce the daca code because creduce requires a preprocessed
file to reduce and the problem doesn't show up when the file is
preprocessed with cppcheck.
There is no test because I couldn't reduce the problem files.
=> fix daca insighttoolkit crash in template simplifier

cfg/wxwidgets.cfg
This creates false positives when calling SetClientData with a nullptr which is completely valid.
=> Remove not-null from wxCommandEvent::SetClientData

Makefile, lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Fix return value types of library functions returning unsigned.
Previously, the valueType of `auto x = f()` would be signed even if `f()`
was specified to return an unsigned type.
This fixes [#9941](https://trac.cppcheck.net/ticket/9941), which is a regression in cppcheck 2.2 compared to 2.1.
The regression was introduced in 32df807b2287.
=> Fix #9941: Return value type of library functions returning unsigned

appveyor.yml, gui/gui.pro
- gui.pro: Update the path of the output file, so that it is also built
inside the `help` sub-directory (add `$$PWD/help/` to the path):
`-o $$PWD/help/online-help.qhc`
- Use **`qcollectiongenerator`** in case of Qt version < 5.12, otherwise
**`qhelpgenerator`**
- appveyor.yml: Add `%QTDIR%\bin` to `PATH`. This allows **`qhelpgenerator`**
or **`qcollectiongenerator`** to be found
=> Enable building of Qt online-help in gui.pro

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Previously, if an enum value was set to a value unknown to cppcheck, the
next enum value would erroneously be set to the last set value plus one
(or zero, if no enum value had been set before). This partially fixes
Trac ticket [#9647](https://trac.cppcheck.net/ticket/9647), in the sense that it no longer sets wrong values for
these enum values. Further improvements to this would be to set the
correct values instead. It also fixes the false positive mentioned in the
comments in the ticket.
I believe to set the correct enum values, we would need to add an extra pass to
valueflow, right?
=> Symboldatabase: Don't set unknown enum values

cli/filelister.cpp
On some platforms, the `d_name` field of `struct dirent` is not a static fixed-sized array but a "flexarray" (i.e. a single character); in this situation, `d_name` points to a buffer allocated somewhere, usually at the end of the buffer used for dirent (which is then allocated in a bigger memory). Because of this, creating a `struct dirent` on stack as buffer for `readdir_r` is not enough to store all the memory needed for a dirent on those platforms.
As result, create an helper union with all the needed space, calculated statically at build time. `NAME_MAX` is still not a perfect option, but it will do the job in the vast majority of cases.
This fixes FileLister on GNU/Hurd: GNU libc there has `struct dirent` with `char d_name[1]`.
=> FileLister: ensure enough space for resulting dirent

lib/symboldatabase.cpp, lib/tokenize.cpp, lib/valueflow.cpp, test/testsymboldatabase.cpp, test/testvarid.cpp
C++ allows enum values to be set using constexprs, which cppcheck did
not handle before. To solve this, add a new pass to `valueflow` to update
enum values after global consts have been processed. In order to do so,
I moved all settings of enum values to valueflow. After setting the enum
values, we need another call to `valueFlowNumber()` to actually set users
of the enums.
There is still room for improvements, since each pass of
`valueFlowGlobalConstVar()` and `valueFlowEnumValue()` only sets variables
that are possible to set directly, and not if setting the value of a
variable allows us to set the value of another. For example
```c++
constexpr int a = 5;
constexpr int b = a + 5;
enum E { X = a };
constexpr E e = X;
```
Here both `b` and `e` will not have their values set, even though …
=> Fix #9647: Set correct enum value

.github/workflows/CI-unixish.yml, addons/test/threadsafety/local_static.cpp, addons/test/threadsafety/local_static_const.cpp, addons/threadsafety.py
C++11 guarantees static initialization to be thread-safe: 6.7  Declaration statement
Do addons have information about the  language standard being configured?
=> threadsafety shall not warn about const vars (in C++11)

cfg/qt.cfg
A QVariant can be constructed with a bool, so there is no reason to
forbid this.
=> qt.cfg: allow bool as second argument of setProperty()

gui/help/online-help.qhp
- Fixes the following errors, when opening **`online-help.qhc`** using Qt
assistant:
```console
QTextBrowser: No document for qthelp://cppcheck.sourceforge.net/doc/./preferences.html
```
etc.
- Furthermore, ./ is not used anymore in Qt documentation:
https://doc.qt.io/qt-5/qtassistant-simpletextviewer-example.html
It was used previously:
https://doc.qt.io/archives/qt-4.8/qt-help-simpletextviewer-example.html
Example:
`<section title="Find File" ref="./findfile.html">`
->
`<section title="Find File" ref="findfile.html">`
=> Remove ./ from relative paths in online-help.qhp

addons/misra.py, addons/test/misra/misra-test.c
Using the bits info for tokens to find bitfields. Then checking if the token's length and type.
=> MISRA Rule 6.1/6.2 Bit field check

lib/checkleakautovar.cpp, test/cfg/posix.c, test/testleakautovar.cpp
Also fix a broken test case related to checking the return value -1
where socket was not defined in the library used in the tests.
This was tested running `test-my-pr` with 500 packages. The difference was
six fewer FPs. Log is attached.
[my_check_diff.log](https://github.com/danmar/cppcheck/files/5455213/my_check_diff.log)
=> Fix #8327 (Memleak with mmap return value check)

lib/checkclass.cpp, lib/symboldatabase.cpp, test/testclass.cpp
* Include detecting variadic template functions by matching against endTok instead of startTok.
* Add argument count check for variadic (template) member functions.
=> Fix #9806 (False positive: template function can be static)

.github/workflows/release-windows.yml
The filename of the daily built installer still contains 2.0 e.g.:
cppcheck-2.0.182-x64-Setup.msi
- Read the `ProductVersion` from productInfo.wxi and use it in the
file name of the cppcheck setup file.
- Add possibility to manually trigger this GitHub action using
`workflow_dispatch:`
- Fix indentation, yamllint error:
`10:5 error wrong indentation: expected 6 but found 4 (indentation)`
=> release-windows: Use current ProductVersion

gui/projectfile.cpp
- getAddonFilePath is used with getDataDir, this works fine
for a local build cppcheck, but not for a system installed one.
As getDataDir reports the location relative to the executable (/usr/bin/)
and the addons are localed in FILESDIR (/usr/share/cppcheck).
Extend the search path by FILESDIR/addons to also make it work for
the installed cppcheck version.
=> Fix addons for installed cppcheck

.github/workflows/release-windows.yml
The step "Create online-help" is not needed anymore since fa84b30.
The online-help files are generated now automatically during
`qmake HAVE_QCHART=yes`
=> release-windows.yml: Remove redundant online-help

cfg/cppunit.cfg, test/cfg/cppunit.cpp, test/cfg/runtests.sh
Very much inspired by #2876, there were missing parenthesis around macro arguments which could cause FPs.
=> cfg: cppunit: Fix FP with compareBoolExpressionWithInt within CPPUNIT_ASSERT_EQUAL

lib/tokenize.cpp, test/testsimplifytypedef.cpp
code:
```c++
namespace foo {
typedef long long int64;
}
typedef int int32;
namespace foo {
int64 i;
}
int32 j;
```
result:
```
1:
|
6:
7: namespace foo {
8: long long i@1 ;
9: }
10:
11: int32 j@2 ;  # should be: int j;
```
=> fix an error in Tokenizer::simplifyTypedef()

addons/misra.py, addons/test/misra/misra-test.c
For all string tokens: check that the variable being assigned is of type const.
For all function calls, check that if a parameter is a string then the argument definition needs to be const.
=> MISRA Rule 7.4 Check if variables assigned as string literals are const

.travis.yml, htmlreport/check.sh, htmlreport/test_htmlreport.py
Somewhat inspired by #2858, make sure htmlreport works in both python2 and python3 by running the tests travis with both python versions. This obviously doubles the time it takes to tests htmlreport, but since it only takes 5 seconds to run, that's ok.
=> travis: Test htmlreport with python2 and python3

addons/misra.py, addons/test/misra/misra-test.c
Fix false positives for the function calls with "const pointer to const value" arguments: https://trac.cppcheck.net/ticket/9967.
The variable.valueType.constness have the same encoding as `ValueType::constness` in Cppcheck.
See also: the same fix for cert.py: 8f21ba91e3abd5c59e19c6022d33288c41be0d4a.
=> misra.py: Fix 7.4 false positive

lib/checkfunctions.cpp, lib/checkfunctions.h, lib/library.cpp, lib/library.h, test/testfunctions.cpp
Added an optional "type" attribute to "use-retval" nodes in the library configuration. When the return type of a function configured with `<use-retval type="error-code"\>` node does not used, the new style error "ignoredReturnErrorCode" will be generated.
See: https://github.com/danmar/cppcheck/pull/2875#issuecomment-720975477
=> library: Add new warning: ignoredReturnErrorCode

addons/misra.py, addons/test/misra/misra-test.c
MISRA rule 7.2 Require 'u' prefix when using large unsigned integer constants
=> MISRA rule 7.2 Require 'u' prefix when using large unsigned integer constants

.github/workflows/codeql-analysis.yml
Adjust build to avoid matchcompiler but also use Z3 and PCRE
The former was suggested  here: https://github.com/danmar/cppcheck/commit/308b150351a278b4f22c52e036ed5c8b934a4390#commitcomment-43916193
=> Adjust Codeql2 build

gui/helpdialog.cpp
- Setting `_q_readonly` disables the timestamp check of the registered
**`online-help.qch`** file
- This enables displaying of Contents and Index of the online help,
even if the timestamp of **`online-help.qch`** is slightly different.
Differences in the timestamp can result from packing **`online-help.qch`**
in a cab file, when building the installer (1 or 2 seconds) or from
installing the file under a different timezone under Linux etc.
- Remark: Qt 5.14 or newer is required to display Contents or Index,
when the help files are readonly [[1]](https://codereview.qt-project.org/c/qt/qttools/+/282190)
[1] https://codereview.qt-project.org/c/qt/qttools/+/282190
Further info concerning this topic can be found here:
https://github.com/danmar/cppcheck/commit/9693940dadfd54bb0bac2549e1b2d6804be9 …
=> Set _q_readonly property for online-help

.github/workflows/release-windows.yml
So far, Qt version 5.12.9 has been used, which is the current default
of jurplel/install-qt-action@v2
- The update of Qt to version 5.15.1 enables displaying of
Contents and Index of the online help, if it is installed in a
readonly location, typically: C:\Program Files\Cppcheck\
- Qt 5.14 or newer is required to display Contents or Index,
when the help files are readonly and the timestamp of online-help.qch
is not correct to the second.
- This is a follow-up to commit 4a057c1
Remark: Qt 5.15.1 has been released on 2020-09-10 and is the first patch release of Qt 5.15 LTS:
https://www.qt.io/blog/qt-5.15.1-released
=> Update Qt version for release-windows to 5.15.1

lib/astutils.cpp, test/testleakautovar.cpp
```
int *f() {
int *p = static_cast<int *>(realloc(nullptr, 10));
if (!!(!p)) {
return nullptr;
}
return p;
}
```
would give
```
memleak2.cpp:4:5: error: Memory leak: p [memleak]
return nullptr;
^
```
Because of the additional `!!̀ .
=> Fix false positive memoryleak

lib/checkother.cpp
Previously it was being handled only if the standard was *exactly* C++11.
=> Handle static_assert if standard is at least C++11

cmake/compilerDefinitions.cmake
Moved -DFILESDIR out of Linux only block so FILESDIR is defined for Windows too
=> Updated cmake script so cppcheck.exe works in place during development

lib/checkcondition.cpp, test/testcondition.cpp
Sometimes, using `sizeof` is involved in if-statements, cppcheck warns that the condition is always true or false. In some cases, while it is technically correct, the code is perfectly fine as is. For example:
```c
void f(int x) {
if (x == sizeof(int)) {}
else if (x == sizeof(long)) {}
}
```
If the size of int and long is the same, cppcheck will warn that the second condition is always false. In my opinion, this code is perfectly fine and cppcheck should not warn about it. Since it's difficult to diagnose when we should warn for `sizeof` or not, disable the condition always true/false checks for now.
In 500 packages tested with `test-my-pr`, there were four fewer warnings, and I believe they are all cases where cppcheck shouldn't warn, or where it at least is debatable. …
=> TestCondition: Don't warn when sizeof is involved

addons/misra.py, addons/test/misra/misra-test.c
Rule 10.2: Expressions of essentially character type shall not be used inappropriately in addition and subtraction operations
=> MISRA rule 10.2 Expressions of essentially character type in additions and subtraction

lib/tokenlist.cpp, test/testtokenize.cpp
```
throw (std::string)"Error: " + strerror(errnum);
```
would result in a broken ast:
```
throw
`-::
|-std
`-string
```
instead of
```
throw
`-+ 'signed char *'
|-( 'container(std :: string|wstring|u16string|u32string)'
| `-"Error: " 'const char *'
`-( 'signed char *'
|-strerror
`-errnum 'signed int'
```
=> 9955: Fix ast when throwing a cast

.github/workflows/release-windows.yml
- Fixes:
The `add-path` command is deprecated and will be disabled on
November 16th. Please upgrade to using Environment Files.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- This is a follow-up commit to: a6a5cbe6
=> Update setup-msbuild also in release-windows

addons/misra.py, addons/test/misra/misra-test.c
I believe we can skip further checking if we encounter an astOperand2 where isName is True.
This will remove the 9.2 issue on line 1250, which probably also should be considered a false positive.
=> Fixed #9988 (false positive: misra-c2012-9.2)

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Currently template type deduction for functions only works for single
template argument single function argument functions with a literal
argument.
This patch starts to add support for single template argument multiple
function argument functions.  It correctly handles functions with
multiple arguments of the same type. It also handles a mix of template
and non-template arguments.
It does not add support for overloading non-template arguments.
It does not add support for multiple parameter template functions.
It does not add support for type deduction from variable arguments.
=> fix #9983 (TemplateSimplifier: template not simplified : f(0,0);)

addons/misra.py, addons/test/misra/misra-test.c
I now use the value of `valueType.pointer` and compare it to the size of the dimensions for the array `len(dimensions)` to determine if a string is an array initializer or a value initializer for a char pointer.
My assumption (after some investigation) is that this value will be at least one higher than the dimensions of the array (Eg. two dimensional array to char pointers will have valueType.pointer = 3).
Points of interest are lines 1591 and 1609
I deliberately don't check the type of the pointer, since I don't believe that to be within the scope of 9.2
=> Fixed #9993 (false positive: misra-c2012-9.2)

cli/cmdlineparser.cpp, platforms/elbrus-e1cp.xml, win_installer/cppcheck.wxs
Added a configuration file for our [Elbrus](https://en.wikipedia.org/wiki/Elbrus_(computer)) e1c+ machines.
A more detailed description of these processors is available [here](http://www.mcst.ru/elbrus-1c-plus) (in Russian).
=> Added Elbrus E1C+ platform file

win_installer/cppcheck.wxs
Fixes the following errors during the `Build Installer` step of
**`release-windows`** GitHub Action:
```console
cppcheck.wxs(135): error CNDL0014: The File/@Id attribute's value,
'elbrus-e1cp.xml', is not a legal identifier. Identifiers may contain
ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).
cppcheck.wxs(137): error CNDL0014: The File/@Id attribute's value,
'pic8-enhanced.xml', is not a legal identifier.
```
Successful GitHub Action test run of **`release-windows`**:
https://github.com/c72578/cppcheck/actions/runs/375485795
=> cppcheck.wxs: Use underscore instead of dash

.github/workflows/release-windows.yml
Qt 5.15.2 has been released on 2020-11-20 [1]. This is the currently newest
patch release of the 5.15 LTS series.
- The update of Qt to version 5.15.2 fixes an issue with the index of
Qt help files as reported upstream:
https://bugreports.qt.io/browse/QTBUG-88342
[1] https://www.qt.io/blog/qt-5.15.2-released
GitHub Actions test-build against Qt 5.15.2:
https://github.com/c72578/cppcheck/actions/runs/375809396
=> Update Qt version for release-windows to 5.15.2

lib/valueflow.cpp
==28830== Conditional jump or move depends on uninitialised value(s)
==28830==    at 0x10252E4: valueFlowLifetime(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*)::{lambda(Token const*, Lambda::Capture, std::function<bool (Token const*)>)#2}::operator()(Token const*, Lambda::Capture, std::function<bool (Token const*)>) const (valueflow.cpp:3656)
==28830==    by 0x1025A03: valueFlowLifetime(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) (valueflow.cpp:3685)
==28830==    by 0x1038E94: ValueFlow::setValues(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) (valueflow.cpp:6569)
==28830==    by 0xF8D155: Tokenizer::simplifyTokens1(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (tokenize.cpp:2384)
==28830==    by …
=> fix a large number of valgrind warnings in testrunner

lib/checkunusedvar.cpp, lib/checkunusedvar.h, lib/token.h, test/testunusedvar.cpp
Analyzing function side effects to better detect classes without side effects. See [this](https://github.com/danmar/cppcheck/pull/2836#issuecomment-718806054) comment and PR for details.
To be done in further PRs:
* side-effect variables in function arguments
* return statements with length > 1 token
* lambdas
* class member functions and static variables
* escape functions
Pointing to any other missed test cases will be appreciated.
=> feat: analyze function side effects

lib/CMakeLists.txt
Include **`externals/tinyxml2`** in **`lib/CMakeLists.txt`** only if
`USE_BUNDLED_TINYXML2` is `ON`, which is the default.
This is a follow-up commit to 8ac55a8
=> lib: Add condition for include externals/tinyxml2

cli/threadexecutor.cpp, cli/threadexecutor.h
This fixes the excessive spawning of processes since the pipes are done earlier than the actual process. I think this might explain some out-of-memory issues with bigger projects.
We also now wait for all child processes to be finished (handling was also bound to the pipes) which should get rid of zombie processes - at least in the `testrunner` as during normal scanning those would have been gone with the parent process after scanning. You will still see zombie processes during run-time as the processes are not being explicitly waited for so up to n processes might already done but not yet handled.
There still seem to be issues since LSAN still reports
```
TestSuppressions::suppressionsSettings
==6089==Running thread 6067 was not suspended. False leaks are possible.
```
=> fixed excessive spawning of child processes / fixed potential zombie processes

test/testclangimport.cpp
Reported by Clang UBSAN
```
TestClangImport::classTemplateDecl1
test/testclangimport.cpp:130:36: runtime error: member call on null pointer of type 'Token'
#0 0x92f5cf in TestClangImport::parse[abi:cxx11](char const*) /home/runner/work/cppcheck/cppcheck/test/testclangimport.cpp:130:36
#1 0x923c25 in TestClangImport::classTemplateDecl1() /home/runner/work/cppcheck/cppcheck/test/testclangimport.cpp:220:9
#2 0x91c833 in TestClangImport::run() /home/runner/work/cppcheck/cppcheck/test/testclangimport.cpp:38:9
#3 0xde6c2c in TestFixture::runTests(options const&) /home/runner/work/cppcheck/cppcheck/test/testsuite.cpp:332:23
#4 0xcbdde4 in main /home/runner/work/cppcheck/cppcheck/test/testrunner.cpp:44:46
#5 0x7efea62fdbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
#6 0x8570b9 …
```
=> testclangimport.cpp: fixed potential nullptr dereference in parse()

cli/threadexecutor.cpp
The blocking of `select()` should probably be reduced since waiting for second for data to appear might slow down execution time of projects with lots of very small files. With projects where each file takes at least a second to analyze it doesn't matter. Not blocking at all will increase the `sys` time and thus consume more CPU for no improvement in analysis time.
=> perform all tasks in each loop execution in ThreadExecutor::check()

.github/workflows/valgrind.yml, valgrind/testrunner.supp
Add valgrind CI action.
Inspired by https://github.com/danmar/cppcheck/pull/2920
=> Add Valgrind CI action

.github/workflows/CI-unixish.yml
That is part of the preparations for the upcoming change in "ubuntu.latest" platform (see https://github.com/actions/virtual-environments/issues/1816)
Probably we shouldn't use `.latest` at all.
=> Github CI: AddUbuntu 20.04 and MacOS 11.0

cli/cmdlineparser.cpp
`cppcheck --help` printed:
--project-configuration=<config>
If used together with a Visual Studio Solution (*.sln)
or Visual Studio Project (*.vcxproj) you can limit
the configuration cppcheck should check.
For example: --project-configuration=Release|Win32    --max-configs=<limit>
Maximum number of configurations to check in a file
before skipping it. Default is '12'. If used together
with '--force', the last option is the one that is
effective.
A `\n` was missing before option `--max-configs`, and the double-quotes did nothing.
=> Add missing \n in help

lib/exprengine.cpp, test/testexprengine.cpp
This is related to false negative in CVE-2020-12654 discussed [on the forum](https://sourceforge.net/p/cppcheck/discussion/development/thread/834110f0e7/?page=1&limit=25#195f).
I managed to reduce the CVE source code to this snippet (see commentary):
```c
#include <string.h>
struct some_struct {
int disabled;
int field[32];
};
int mwifiex_ret_wmm_get_status(struct some_struct *sin)
{
char buf[32] = {0};
memcpy(sin->field, &buf, 32);
while (1) {
switch (1) {
case 1:
sin->disabled = 1; // Comment this to "fix" false negative
memcpy(sin->field, &buf, 32); // False negative
break;
}
}
return 0;
}
```
[expr-printer.py](https://github.com/jubnzv/cppcheck-nvd-checker) can now print exceptions from Cppcheck, so this helps in investigation.
=> ExprEngine: Handle pointer to struct passed as an argument to the function

lib/exprengine.cpp
This helps to quickly determine the location of the exception.
=> ExprEngine: Better debug output for exceptions

lib/checkunusedvar.cpp, test/testunusedvar.cpp
Before this PR, any global variable found in function body marked this function as side-effect one. Analyzing global variables more precisely from now.
Any help with missed test cases will be highly appreciated.
=> feat(unused_var): analyze global variables inside function body

lib/programmemory.cpp, test/testsymboldatabase.cpp
- Include required header file `<limits>`
- Fixes the following errors when compiling with GCC 11:
```console
lib/programmemory.cpp:477:44: error: 'numeric_limits' is not a member of 'std'
test/testsymboldatabase.cpp:5978:18: error: 'numeric_limits' is not a member of 'std'
```
See also:
https://en.cppreference.com/w/cpp/types/numeric_limits
=> Fix gcc11 build errors

lib/checktype.cpp
fixes implicit conversion from 'unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
This warning is emitted by clang-10 when compiling cppcheck via
```
CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MATCHCOMPILER=ON
```
=> fix compile-time rounding error

lib/symboldatabase.cpp, test/test64bit.cpp, test/testsymboldatabase.cpp
Due to a issue while parsing the function declaration (we ended up with
the type of the first argument instead of the return type).
```
c.cpp:6:11: portability: Assigning an integer to a pointer is not portable. [AssignmentIntegerToAddress]
Array a = f(i);
^
```
typedef std::array<int, 2> Array;
Array f(int i);
int g(int i) {
Array a = f(i);
return 2;
}
```
=> Fix false positive AssignmentIntegerToAddress

cmake/compilerDefinitions.cmake
Passing `-DFILESDIR=S:\GitHub\cppcheck-fw` resulted in these compiler warnings (and none of the library files being found) since the backslashes were not escaped:
```
S:\GitHub\cppcheck-fw\cli\cppcheckexecutor.cpp(874): warning C4129: 'G': unrecognized character escape sequence
S:\GitHub\cppcheck-fw\cli\cppcheckexecutor.cpp(874): warning C4129: 'c': unrecognized character escape sequence
S:\GitHub\cppcheck-fw\cli\cppcheckexecutor.cpp(875): warning C4129: 'G': unrecognized character escape sequence
S:\GitHub\cppcheck-fw\cli\cppcheckexecutor.cpp(875): warning C4129: 'c': unrecognized character escape sequence
```
We should probably add some validation for the path on start-up as well.
=> fixed FILESDIR in CMake with Windows file separators

lib/reverseanalyzer.cpp, test/testnullpointer.cpp
reverseanalyzer has a special process for assignments, and would not see
a stop condition on a rhs of an assignment.
=> 10062: Fix FP due to assignment in reverseanalyzer

lib/valueflow.cpp, test/testautovariables.cpp
When storing the address of a local variable in a class field cppcheck will issue a warning even if that local variable is a reference whose value was returned from a function. Unless more is known about the function it is a reasonable assumption that the reference it returns will outlive the function call. It appears that when cppcheck encounters an unknown function it makes the opposite assumption.
=> Test for return address of reference

lib/checksizeof.cpp, lib/templatesimplifier.cpp, lib/templatesimplifier.h, lib/tokenize.cpp, test/testsimplifytemplate.cpp, test/testtokenize.cpp
The template simplifier works well enough now so cleanupAfterSimplify is
no longer necessary.  In fact cleanupAfterSimplify was introducing a bug
which improperly simplified C++ style casts.
Bugs should be exposed and fixed properly rather than just hiding them.
=> remove cleanupAfterSimplify from the template simplifier

lib/checkclass.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h
I filed tickets for warnings which happen with the Cppcheck source - see https://trac.cppcheck.net/ticket/10065 and https://trac.cppcheck.net/ticket/9384. If these are fixed we probably can also enable this in the self-checks.
=> split "varid0" from more generic "debug" messages

tools/matchcompiler.py, tools/test_matchcompiler.py
Previously, Matchcompiler stopped processing the line in case it found a match it could not process, which meant other matches on the same line were not processed, even though they might be simplified (also, due to the implementation, all 
`Token::Match` on the line were processed first, so if the line contained one Match that could not be simplified, no simpleMatches would be simplified).  Fix this by not bailing out and check all matches. Due to indentation changes (I put the relevant lines of code in a for loop), the diff look larger than it really is (compare without whitespace changes and you'll see).
Also, while at it, fix some whitespace formatting in the generated code, and neaten some error messages slightly (I actually looked at the code and error messages when debugging, and …
=> Matchcompiler parse all Match|simpleMatch on the same line

lib/astutils.cpp, lib/checkunusedvar.cpp, test/testunusedvar.cpp
Previously `isVariableChanged()` under astutils.cpp returned `false` for changing array element using pointer arithmetic.
Now this case is handled in `isVariableChanged()` function to avoid false-negatives in unused variables check.
=> checkunusedvar: handle array element change using pointer arithmetic

test/cfg/runtests.sh
This avoids warnings when checking syntax of qt.cpp.
=> runtests: Add -Wno-deprecated-declarations to CXX flags

cfg/std.cfg
Technically, these are locale dependent, but since for example `islower()` and `isupper()` were configured as if it is the "C" locale, I figured these probably can be configured like this too?
=> Add return value config for tolower()/toupper()

addons/cppcheckdata.py
Since class attributes are mutable (list), when you append to them, they don't promote to instance variable which means when you call `parsedump()` multiple times data just gets appended to them.
Found by samed on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/c6e1210ec2/
=> cppcheckdata: Use instance attributes in CppcheckData class

cfg/cppunit.cfg
Addresses issue described here: https://github.com/danmar/cppcheck/commit/fe4657f2185f9bb3fb169aa17534947d48427758#r43715649
specifically the code
```
if (checkA)
CPPUNIT_ASSERT(a);
else
CPPUNIT_ASSERT(b);
```
will expand to
```
if (checkA)
{
if (!(condition))
throw false;
else if (!(condition))
throw false;
}
```
which doesn't match the behavior of the actual cppunit macros or, presumably the authors intent. Fix surrounds the whole expression in braces to make it look like a single statement as far as the if statement is concerned.
Not sure how to test this other than making sure nothing weird happens on my own code. I've had a very similar fix locally for a while but it's not identical.
=> improve cppunit macros

addons/cppcheckdata.py
Extend `CppcheckData` API to make the list of source files public. This can be used by custom addons.
Suggested on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/c6e1210ec2/#91d2
=> cppcheckdata: Make the source files for the current configuration public

.github/workflows/CI-unixish.yml, .travis_suppressions, cli/cmdlineparser.cpp, cli/cppcheckexecutor.cpp, cli/threadexecutor.h, lib/checkbufferoverrun.cpp, lib/checkbufferoverrun.h, lib/checkclass.cpp, lib/checknullpointer.cpp, lib/checkuninitvar.cpp, lib/checkunusedvar.cpp, lib/ctu.cpp, lib/ctu.h, lib/exprengine.cpp, lib/tokenize.cpp, lib/tokenize.h, lib/tokenlist.cpp, lib/tokenlist.h, test/testother.cpp, test/testtoken.cpp
I added `--template=selfcheck` so we see the actual severity and if it is inconclusive. It would also allow us to add additional stuff (like the daca checks) for self-check in the future.
If we add any suppressions in the future I would like to have a comment which describes why and if it is a false positive it should also contain a ticket number.
I would also like to get rid of `-D__CPPCHECK__` and specify a proper configuration like `-D__GNUC__ -D__cplusplus=201103L` instead.
=> some self-check suppression cleanups

gui/cppchecklibrarydata.cpp
Member function `atEnd()` of class `QXmlStreamReader` returns `true` if an error occured and this breaks the XML reader loop.
But this error will not be visible to the user and leaves `CppcheckLibraryData` instance in incomplete state.
=> Check if XML reader stopped because of an error.

gui/cppchecklibrarydata.cpp
Call handler which throws an exception to make it visible to user that attribute is missing.
=> Check for mandatory "name" attribute in "podtype".

cli/threadexecutor.cpp
This change will now fail the self-check step because a forked process crashed.
=> improved error handling in ThreadExecutor

gui/mainwindow.cpp, gui/resultsview.cpp
This PR updates translations of
- Placeholder text of toolbar filter (fix for Trac issue 8879)
- Main window title if project file has been opened
- `ResultsView` auto generated user interface class.
=> Fix update of some translations after application language switch.

lib/checkio.cpp, lib/checkmemoryleak.cpp, lib/library.cpp, lib/library.h, lib/symboldatabase.cpp, lib/token.cpp, lib/tokenize.cpp, lib/tokenlist.h
Most of these were found during profiling - I changed a few other ones on the way. I verified them and the lookup time is basically half with the `std::unordered_*` containers - in case of a map it might be even less.
It reduces the total Ir for scanning the addons folder from 572,268,979 to 556,311,768.
I will refactor the multiple occurrences of the keywords into a sperate class with another PR.
I also added tickets about detecting this with Cppcheck https://trac.cppcheck.net/ticket/10114 and https://trac.cppcheck.net/ticket/10115.
=> Use std::unordered_* containers for faster lookups

lib/checkio.cpp, lib/errorlogger.cpp, lib/mathlib.cpp, lib/symboldatabase.cpp, lib/token.cpp, lib/token.h
The overhead of `std::ostringstream` is just catastrophic and there's no real need for it (beside readability) if you are not relying on custom `operator<<` implementations.
Just replacing the stream with simply appending to an existing string greatly reduces the Ir count for running a scan on the `addons` folder which produces some (but not a lot) of warnings:
1,631,343,719 - old
1,009,194,749 - new
The root of this is `calculateWarningHash()` in the error reporting. Even after this change it is still the function which consumes the most.
I am also evaluating the `fmt` library to restore readability and maybe even better performance. In version 4.x it doesn't even require C++11 and can be used as header-only - see https://fmt.dev/latest/index.html#portability
=> refs issue #9089: avoid usage of expensive std::stringstream

lib/checkstl.cpp, test/teststl.cpp
Considering new use case added to issue 9938 (https://trac.cppcheck.net/ticket/9938) enhanced earlier fix to consider increment number in comparison check
=> Made missing comparison in loop check more generic

.gitignore
While using visual studio code for development one need to create .vscode at root of workspace. This change adds to .gitignore so its not accidently pushed to origin
=> Added .vscode to gitignore

.github/workflows/CI-unixish.yml, gui/cppchecklibrarydata.cpp, gui/cppchecklibrarydata.h, gui/test/cppchecklibrarydata/cppchecklibrarydata.pro, gui/test/cppchecklibrarydata/files/mandatory_attribute_missing.cfg, gui/test/cppchecklibrarydata/files/podtype_valid.cfg, gui/test/cppchecklibrarydata/files/smartptr_valid.cfg, gui/test/cppchecklibrarydata/files/typechecks_valid.cfg, gui/test/cppchecklibrarydata/files/unhandled_element.cfg, gui/test/cppchecklibrarydata/files/xml_reader_error.cfg, gui/test/cppchecklibrarydata/resources.qrc, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/cppchecklibrarydata/testcppchecklibrarydata.h
Avoid configuration load failure due to unhandled element.
Smart pointers configuration is used by boost.cfg, opencv2.cfg and wxwidgets.cfg .
Type Checks configuration is used by std.cfg .
@danmar I created a `QTest` project for `CppcheckLibraryData` with some basic test patterns. Will a new test project automatically be built and executed after providing it by pull request ?
=> Add missing support for "type-checks" and "smart-pointer" configuration.

philosophy.md
Inspired by https://github.com/danmar/cppcheck/pull/2839 inconclusive messages are added to this document.
=> philosophy.md : Describe inconclusive messages

gui/cppcheck_de.ts, gui/mainwindow.cpp, gui/scratchpad.cpp, gui/scratchpad.h
Scratchpad UI translation function won't be called again if object already exists.
Therefore i added `translate()` member function and call it on language change.
Added/Fixed some German translations.
=> Fix scratchpad translation on language change.

lib/tokenize.cpp, test/teststl.cpp
This fixes an infinite recursion in ``CheckStl::checkMutexes`` by handling auto variables in ``Tokenizer::initVar``.
=> Ticket #10028: Properly simplify auto variables' initialization.

lib/astutils.cpp, lib/astutils.h, lib/valueflow.cpp, test/testastutils.cpp, test/testvalueflow.cpp
With
```
enum FENUMS { NONE = 0, CB = 8 };
bool calc(int flag) {
if (!flag) {
return false;
}
if (flag & CB) {
return true;
}
return false;
}
```
Since flag is not a bool, we can't know its value in the second if.
However, isOppositeCond would still return true (since `!flag` and
`flag` really are opposite condition), and we would update flag with a
known value of `1`. This patch adds an additional check to prevent that
when we don't deal with a bool.
=> 10110: Fix FP knownConditionTrueFalse

build-pcre.txt
Previously macport is famous on macOS. but these days,
homebrew is more famous and popular than macport.
So I add how to install pcre by using homwbrew.
That's all
=> Add how to install pcre by using homebrew

lib/token.cpp
This will print whether an value is inconclusive. It also will print out the complete expression for lifetime values.
=> Improvements to debug output

tools/donate-cpu-server.py
`rindex()` raises an exception when the substring is not found - `rfind()` returns -1.
Fixes `ERR_CONNECTION_RESET` error when currently trying to view the crash report.
=> donate-cpu-server.py: fixed daca crash report

gui/cppchecklibrarydata.cpp, gui/cppchecklibrarydata.h, gui/test/cppchecklibrarydata/files/memory_resource_unhandled_element.cfg, gui/test/cppchecklibrarydata/files/memory_resource_valid.cfg, gui/test/cppchecklibrarydata/files/platform_type_unhandled_element.cfg, gui/test/cppchecklibrarydata/files/platform_type_valid.cfg, gui/test/cppchecklibrarydata/resources.qrc, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/cppchecklibrarydata/testcppchecklibrarydata.h
Add missing `platformtype` support (windows.cfg) to avoid configuration file load error.
Modify tests, add tests.
=> Fix library data platform type

lib/checkclass.cpp
Spotted  by daca:
http://cppcheck1.osuosl.org:8000/kactivities-stats
```
2021-01-26 16:31
ftp://ftp.de.debian.org/debian/pool/main/k/kactivities-stats/kactivities-stats_5.78.0.orig.tar.xz
cppcheck-options: --library=posix --library=gnu --library=boost --library=qt -j1 --showtime=top5 --check-library --inconclusive --enable=style,information --template=daca2 -rp=temp -D__GNUC__ --platform=unix64 temp
platform: Linux-4.4.180-102-default-x86_64-with-SuSE-42.3-x86_64
python: 3.4.6
client-version: 1.3.7
cppcheck: head 2.3
head-info: 987c8a854 (2021-01-25 22:51:50 +0100)
count: Crash! Crash!
elapsed-time: -11.0 -11.0
head-timing-info:
old-timing-info:
head results:
Checking temp/kactivities-stats-5.78.0/src/resultwatcher.cpp: __GNUC__=1...
Program received signal SIGSEGV, Segmentation fault. …
```
=> Fix crash in checkclass.cpp

.travis_suppressions
There are no such warnings any longer, so lets remove them.
=> travis_suppressions: Remove some temporary suppressions

tools/readme.md
astyle_client.py was removed in 946c5e4dbc3e071c, remove its description
in readme.md.
=> tools/readme.md: Remove astyle_client description

gui/cppchecklibrarydata.cpp, gui/cppchecklibrarydata.h, gui/test/cppchecklibrarydata/files/markup_mandatory_attribute_missing.cfg, gui/test/cppchecklibrarydata/files/markup_unhandled_element.cfg, gui/test/cppchecklibrarydata/files/markup_valid.cfg, gui/test/cppchecklibrarydata/resources.qrc, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/cppchecklibrarydata/testcppchecklibrarydata.h
Add missing support for markup configuration used by qt.cfg (fix for Trac issue 9134).
Library Editor loads all predefined configuration files without error now.
Add some tests.
=> Fix library data markup

cfg/wxwidgets.cfg
I could see use-retval potentially making since in a loop if I'm using the iterator version, but using the version that returns a ref to itself there's no reason to use that return value.
Simple example that reproduces this:
```c++
int main()
{
wxString str = GetString();
if (str.size() > 2)
str.erase(0, 2);
return str.size();
}
```
Output:
```
cppcheck.exe --enable=all --inconclusive --library=wxwidgets.cfg test.cpp
Checking test.cpp ...
test.cpp:5:9: warning: Return value of function str.erase() is not used. [ignoredReturnValue]
str.erase(0, 2);
^
```
=> Remove unnecessary use-retval from wxString::erase

lib/tokenize.cpp, test/testsimplifyusing.cpp
The using type aliases are a C++ 11 feature so only check for them in
C++ 11 or later.
Don't try to simplify a type alias when it can't be parsed.
=> minor simplifyUsing optimizations

lib/tokenize.cpp, test/testtokenize.cpp
After upgrade from 1.88 to 2.3, we noticed that the cppcheck started reporting syntax errors on [Blocks](https://en.wikipedia.org/wiki/Blocks_(C_language_extension)) code. For example:
```
main.cpp:31:51: error: syntax error: ^() [syntaxError]
dispatch_source_set_event_handler(source, ^() {
^
```
The syntax here is from Apple's C language extension, which is completely valid.
It looks like 382f21a5c926368dadb4be769c4dd238b83421cb is the commit which caused this regression. It appears that since 2.1 release, syntax validation happens before asm token simplification.
The only workaround I found is to put `void` inside the brackets, which keeps cppcheck happy:
```c++
dispatch_source_set_event_handler(source, ^(void) {
```
Thanks to @PKEuS recommendation, we manage to fix this issue by adding …
=> Fixed regression breaking support for Apple's C language extension

.github/workflows/CI-unixish-docker.yml, .github/workflows/CI-unixish.yml, .travis.yml
I omitted z3 from the docker builds for now and removed the build-agnostic validate step for now. There's more CI refactorings/cleanups coming which address that.
At some point we might also be able to merge the actual steps of `CI-unixish.yml` and `CI-unixish-docker.yml`
=> added docker builds for legacy/cutting edge platforms

tools/donate_cpu_lib.py
The additional report I added in https://github.com/danmar/cppcheck/pull/3139 shows the following:
```
Time report (slowest)
Package                                  Date        Time     2.3    Head 
kfreebsd-11                              2021-02-18 01:29  3600.1  3254.1
ngspice                                  2021-02-18 16:46  3344.1  2927.0
openjdk-11                               2021-02-18 19:04  2963.2  2770.4
mrboom                                   2021-02-18 14:12  2769.3  2724.7
zvmcloudconnector                        2021-02-16 17:56    10.3  2705.0
votca-xtp                                2021-02-16 13:34  1313.1  2649.8
blender                                  2021-02-16 23:48  2817.8  2529.1
wine-gecko-2.24                          2021-02-16 15:37  2577.1  2366.3
samba …
```
=> donate_cpu_lib.py: reduced daca timeout to 1800 seconds

appveyor.yml
Wo do not build for 32-bit in any of the other builds and Appveyor is our slowest (and mostly discarded because of that) build so it doesn't really make sense to do that. We should limit to a bare necessities build just to make sure it compiles and test for basic functionality since these are legacy compilers. It is quite unlikely some code will just be broken for a single configuration. We will move a few more things in upcoming PRs.
It might also make sense to not do release builds since we don't do that for most other platforms either but Visual Studio projects configurations for Debug/Release are completely separate and might be accidentally broken by incomplete changes so unfortunately we cannot really do that. I think having a single Release build on Visual Studio should be fine. So …
=> removed 32-bit Appveyor builds and sped up cygwin build a bit

appveyor.yml
The non-msbuild builds were always debug once so there's no need to run them in the release build.
The artifacts were not used at all and the GUI ones were also always debug ones.
I would also like to remove the Release build completely since we do this build in GitHub actions and that would be mainly done to see if the Visual Studio configuration is correct which the ones on the latest compiler already provide.
=> appveyor.yml: avoid duplicated debug builds and removed artifacts

lib/checkleakautovar.cpp, lib/checkleakautovar.h, test/testleakautovar.cpp
Improve leak detections in if-statements. This is done by checking for
leaks every time a scope is left. This allows cppcheck to catch more
memory leaks, as well as improve some error messages which now contain
the line where the variable goes out of scope, instead of the end of
the function.
=> Fix #10182 (FN memory leak with if-statement)

.github/workflows/scriptcheck.yml, tools/donate_cpu_lib.py
We will now just terminate all the child processes (which are the hanging files) - in case we are actually using multiple threads - so we get errors for the actual hanging files. I will evaluate the case with `-j1` later.
A result now looks like this:
```
cppcheck-options: --library=posix --library=gnu --library=openssl --library=zlib -j6 --showtime=top5 --check-library --inconclusive --enable=style,information --template=daca2 -rp=temp -D__GNUC__ --platform=unix64 temp
platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
python: 3.9.1+
client-version: 1.3.9
cppcheck: head 2.3
head-info: bc8eb164a (2021-02-26 18:30:17 +0100)
count: TO! TO!
elapsed-time: 60.0 60.0
head-timing-info:
old-timing-info:
head results:
temp/httrack-3.49.2/src/htsparse.c:0:0: error: Internal error: Child …
```
=> donate_cpu_lib.py: improved timeout reporting and process handling

tools/donate_cpu_lib.py
I am not sure how this happens. I still had a running child process locally and when I sent it `SIGTERM` it exited without any problem.
Here's the result:
```
2021-02-28 16:15
ftp://ftp.de.debian.org/debian/pool/main/g/gcc-arm-none-eabi/gcc-arm-none-eabi_8-2019-q3.orig.tar.xz
cppcheck-options: --library=posix --library=gnu --library=openmp --library=zlib -j6 --showtime=top5 --check-library --inconclusive --enable=style,information --template=daca2 -rp=temp -D__GNUC__ --platform=unix64 temp
platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
python: 3.9.1+
client-version: 1.3.9
cppcheck: head 2.3
head-info: 199f9608c (2021-02-27 04:33:16 +0100)
count: TO! TO!
elapsed-time: 53007.4 14918.1
head-timing-info:
old-timing-info:
head results: …
```
=> donate_cpu_lib.py: fixed potential hang in timeout handling

lib/checkleakautovar.cpp, test/testleakautovar.cpp
It's a little strange how this `const`-assignments are tokenized/simplified differently for pointers and for non-pointers. For example,
```
int x = mkstemp(tempFileName);
const int y = mkstemp(tempFileName);
const void * const p = malloc(5);
```
gets tokenized/simplified to
```
int x; x = mkstemp(tempFileName); // Simplified to declaration and assignment
const int y = mkstemp(tempFileName); // No change, this is why it previously failed
const void * const p; p = malloc(5); // Simplified to declaration and assignment despite the const, this is why memleaks like this are detected
```
Not sure it is a problem, but that's why `const int fd = mkstemp(f);` previously wasn't detected while `const void * const p = malloc(10);` was.
=> Fix #9139 (leak when variable has const qualifier)

lib/checkleakautovar.cpp, test/testleakautovar.cpp
Fix FPs where the return value of `open()` (and other functions returning non-negative values on success) was checked like this: `fd >= 0` (and also the perhaps less common check for failure: `fd <= -1`). On 100 packages with `test-my-pr`, 3 fewer FP were reported (and no FN were added).
=> Fix #10187 (memleak open with fd >= 0)

lib/tokenize.cpp, test/testtokenize.cpp, test/testtype.cpp
Fix faulty removal of parenthesis when "]" is followed by parenthesis
with a number inside, for example when calling a function pointer in
an array or (perhaps more common) in c++, calling operator ( on an
element in an array.
Fixes #8875 where such wrong simplification lead to a FP with too many
bits shifted due to "<<" was interpreted like a shift operator rather
than a stream output.
There was no change in warnings after trying 500 packages in `test-my-pr.py`.
=> Fix tokenizing of x[i](0) (Fixes #8875)

lib/templatesimplifier.cpp, lib/templatesimplifier.h, test/testsimplifytemplate.cpp
It is necessary to use a fake NameAndToken in
mTypesUsedInTemplateInstantiation rather than a Token pointer so the
template simplifiers internal state is kept valid when tokens are
deleted. This prevents a use after free.
=> partial revert of b1eaa3021f6018219245a95baa56856c91866d90

readme.md
Description on how to setup VS Code (https://code.visualstudio.com/) for building and debugging cppcheck using GNU toolchain from MSYS2 (https://www.msys2.org/).
=> Add description of setup for development in VS Code.

lib/tokenize.cpp, test/testsymboldatabase.cpp, test/testtokenize.cpp
Detects the alignas as attribute and strips it.
Overhauled simplifyCPPAttribute also allows template parameters
in signature of functions with attributes
Adding tests for alignas
=> simplifyCPPAttribute tokenizer strips alignas

lib/forwardanalyzer.cpp, lib/reverseanalyzer.cpp, lib/tokenize.cpp
Sometimes when analysis traverses to the next token using the AST, it can sometimes move in the wrong direction, which means it will repeat the token again causing a hang. This will now report an error instead of hanging which should help in diagnosing the issue.
=> Report an error if analysis becomes cyclic

.github/workflows/valgrind.yml
The dbgsym release key expired and the `ubuntu-dbgsym-keyring` has not yet been updated - see https://bugs.launchpad.net/ubuntu/+source/ubuntu-keyring/+bug/1920640
=> valgrind.yml: added workaround for expired dbgsym release key

lib/symboldatabase.cpp
```
/home/tkloczko/rpmbuild/BUILD/cppcheck-2.4/lib/symboldatabase.cpp: In member function ‘void SymbolDatabase::createSymbolDatabaseExprIds()’:
/home/tkloczko/rpmbuild/BUILD/cppcheck-2.4/lib/symboldatabase.cpp:1443:32: error: ‘numeric_limits’ is not a member of ‘std’
1443 |                 if (id == std::numeric_limits<nonneg int>::max()) {
|                                ^~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/cppcheck-2.4/lib/symboldatabase.cpp:1443:54: error: expected primary-expression before ‘int’
1443 |                 if (id == std::numeric_limits<nonneg int>::max()) {
|                                                      ^~~
/home/tkloczko/rpmbuild/BUILD/cppcheck-2.4/lib/symboldatabase.cpp:1443:47: error: expected ‘)’ before ‘int’
1443 |                 if (id == …
```
=> Another gcc11 fix

lib/tokenize.cpp, test/testvarid.cpp
The computation of the classname was not expecting templates. Simply
skipping the template part seems to fix the issue.
=> 10221: Fix setVarId in template code

cmake/findDependencies.cmake, lib/CMakeLists.txt
pcre.h may not be available using default system search paths (e.g. during cross-compilation),
thus have to be bootstrapped using CMAKE_STAGING_PREFIX/CMAKE_FIND_ROOT_PATH
=> try to find pcre.h for HAVE_RULES in any case

cfg/gtk.cfg
g_thread_join() consumes the reference to the passed-in thread .
This will usually cause the GThread struct and associated resources to be freed.
=> gtk: Mark g_thread_join as a dealloc for g_thread_new

.github/workflows/CI-unixish-docker.yml, .github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/scriptcheck.yml, .gitignore, .travis.yml, appveyor.yml, test/cli/test-clang-import.py, test/cli/test-helloworld.py, test/cli/test-inline-suppress.py, test/cli/test-more-projects.py, test/cli/test-proj2.py
The tests should be properly named `<name>_test.py` so they are automatically picked up by pytest and we don't have to specify any filenames at all.
=> some test/CI related refactoring and cleanup

lib/mathlib.cpp
The original fix will fail if building cppcheck with gcc and libc++.
=> Check for libc++ instead of clang to workaround a libc++ bug.

cfg/wxwidgets.cfg
These functions return a self ref and are not const so you shouldn't need to use the return value.
=> Remove incorrect use-retvals in wxwidgets.cfg

lib/checkclass.cpp, test/testclass.cpp
The bug was that `isNonCopyable` (now renamed to
`hasNonCopyableBase`) "forgot" that it found an
unknown class in the list if a known copyable
class was found later in the list.
As discussed on the Development mailing list: https://sourceforge.net/p/cppcheck/discussion/development/thread/223ac3df06/#5a8d
=> Fix noCopyConstructor with multiple inheritance

.github/workflows/CI-cygwin.yml, appveyor.yml
Unfortunately it is much slower than in appveyor but we were only piggy-backing it on the Visual Studio ones. I think we should use Appveyor just for legacy Visual Studio compilers.
=> moved cygwin build from appveyor to GitHub action

.github/workflows/CI-unixish.yml, .github/workflows/asan.yml, .github/workflows/ubsan.yml, lib/checkclass.cpp, lib/valueflow.cpp
This is to avoid potential findings we cannot fix - as observed with changes in #3177 .
I also think we should default back to the oldest standard if none is explicitly provided. It might report less but getting issues you are not actually able to fix is also not nice.
But either way we should issue an information message if no standard was provided hinting at unfixable warnings or omitted ones - depending on what the default is.
=> run self-checks with standard set to C++11

addons/misra.py, addons/test/misra/misra-test.c, addons/test/misra/misra-test.h
Due to incorrect indentation, we return "None" instead of an empty list, which causes the crash.
The problem was reported on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/e146b8d779/
=> misra: Fixed a crash in rule 8.2

.travis_suppressions, lib/checkuninitvar.cpp, lib/symboldatabase.cpp
The idea is to unclutter the generic `debug` and move some hard to fix/unfixable things out of the warning so we can at least enable it in the self-checks.
=> split "autoNoType" and "bailoutUninitVar" from more generic "debug"

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
This only fixes the crash. The templates that are instantiated are
correct but one template is left uninstantiated. Fixing the missing
instantiation is not easy and will be looked at later.
=> fix daca2 gdcm template simplifier crash

Makefile, lib/errorlogger.cpp, test/testerrorlogger.cpp
When `ErrorMessage::callStack` elements are serialized to XML they are saved in the reverse order. But when they read back from XML they are added at the end of the list. Thus the round trip via XML reverses the order of `ErrorMessage::callStack`.
From the user point of view it looks like the usage of the `--cppcheck-build-dir` option sometimes (when the file wasn't reanalyzed, but that is hard to spot) results in incorrect location info for some diagnostic messages.
Moreover, when the first location matches some suppression rule and the last doesn't match any (or vice versa), usage of `--cppcheck-build-dir` results in some diagnostic messages appearing and disappearing seemingly at random (again, depending on whether the file was reanalyzed or not).
=> Read error locations in the correct order from XML

lib/tokenize.cpp, test/testunusedvar.cpp, test/testvarid.cpp
Variables declared in the `if` condition (or in C++17 init-statement) are visible not only in the `if` body but also in the `else` body. But logic in `Tokenizer::setVarIdPass1()` handled such variables as if they were declared in the `if` body.
As the result they were removed from `variablesMap` by the time the `else` block was parsed and their uses in the `else` block were either given an incorrect `varId` from variables in some outer scope or not given a `varId` at all.
This then resulted in false positive unreadVariable errors for variables declared in the `if` condition (or init-statement) and used only in the `else` block.
=> Fix varId assignment for uses of variables declared in the if condition

addons/misra.py, addons/test/misra/misra-test.c
Fix false positives for the identifiers that contain `ul` in their names.
Reported on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/c326538221/
=> misra: Fix false positives for rule 7.3

lib/programmemory.cpp, test/testtype.cpp
The following input triggers an UBSan report because the undefined right-shift is actually performed:
`void f() { int x; x = 1 >> 64; }`
Copy the shift-width guard from the `<<` case over to `>>` to avoid this.
=> Fix UB on right-shift.

lib/checkautovariables.cpp
Spotted by coverity, tok can't be null here.
=> Remove unnecessary null check

lib/tokenize.cpp, lib/tokenize.h, test/testtokenize.cpp
Attempt to add support for comma-separated attributes. Recently discovered that attribute lists are being silently ignored in statements like these: \_\_attribute\_\_ (noreturn,format(printf,1,2)), seems that cppcheck detects only single attributes or their sequences  (e.g. \_\_attribute\_\_ ((noreturn)) or \_\_attribute\_\_((pure)) \_\_attribute\_\_((nothrow)) )
=> Attribute lists support

cfg/std.cfg, test/testfunctions.cpp
The following program results in a false positive invalid argument
report for the first argument of calloc:
void f() { auto x = calloc(0,0); }
But calloc has (implementation-)defined behavior analogously to
malloc/realloc if either argument is zero. Modify the valid range
for the first argument to match that of the second and the other
allocation functions.
=> Fix false positive invalidFunctionArg for zero arguments to calloc.

cfg/gnu.cfg
`gnu.cfg` defines `__builtin_bswap*` as macros which evaluate arguments
multiple times. As a result side effects in arguments, e.g.
`__builtin_bswap64(x++)`, lead to a bunch of false positive
`unknownEvaluationOrder` reports with `--library=gnu`.
This replaces the macro definitions with function definitions.
To use macro definitions instead without this issue, it would, as far as I am aware, be necessary to use a compiler extension such as GCC's statement expressions.
=> Fix FP unknownEvaluationOrder on  __builtin_bswap*.

lib/tokenize.cpp, lib/tokenize.h, test/testtokenize.cpp
Currently Cppcheck emits "syntax error: keyword 'try' is not allowed in global scope" on valid code like this:
```
void foo() try {} catch (int) {}
```
and skips the whole file where such code was found.
When function level try blocks are used with all functions except constructors and destructors they act as if the function body consisted of the following try-catch block. So additional simplification step is added that performs this transformation.
My main goal is to fix the syntax error that prevents analysis of the file.
=> Support function level try blocks

lib/tokenlist.cpp, test/testtokenize.cpp
The previous fix for the issue (43b58dbc9e) didn't seem to actually fix it because it added a check for `noexcept` without a condition, but when AST is created `noexcept` always has a condition due to simplification from `noexcept` to `noexcept(true)` in `Tokenizer::simplifyKeyword()`.
The issue from the ticket couldn't be reproduced neither on 43b58dbc9e nor on the previous commit, so it is hard to tell whether the fix was effective or not.
The issue appeared again after a refactoring of AST code in ac67049661.
Test added with the original fix was unable to catch that because it used `testAst()` helper function which skips most simplification steps.
To fix the issue we now check for `noexcept` with a condition and add a proper regression test that:
1. Uses `tokenizeAndStringify()` to …
=> Fixed #9729 (AST broken: lambda with noexcept keyword)

cli/filelister.cpp, test/cfg/posix.c, test/cfg/std.cpp
The first commit fixes the following warning when building with musl:
```
In file included from cli/filelister.cpp:182:                                  
/usr/include/sys/errno.h:1:2: warning: redirecting incorrect #include <sys/errno.h> to <errno.h> [-W#warnings]
#warning redirecting incorrect #include <sys/errno.h> to <errno.h>                                                                                            
^     
```
The second commit fixes some compilation errors occurring during `make checkcfg` with musl and libc++ instead of glibc and libstdc++.
=> Fix build warnings and checkcfg errors with musl and libc++.

lib/tokenlist.cpp, test/testtokenize.cpp
Currently sub-expressions like `decltype(x){}` break AST creation for subsequent tokens in the whole expression. In some cases this triggers validation checks in `validateAst()` and analysis on the file stops.
For example, code like this:
```
int x = decltype(0){} ? 0 : 1;
```
currently produces `internalAstError`.
To fix the issue `iscpp11init_impl()` was changed to recognize `{` preceded by `decltype(expr)` as a start of C++11 brace initialization expression.
=> Fix AST for brace initialization after decltype()

gui/scratchpad.ui
It looks like we can reuse CodeEditor class instead of QPlainTextEdit in a scratchpad.
Motivation:
1. Line# showing, much easy log to source code mapping for cases with > 10 lines and/or > 1 error message
2. keywords higlighting
=> Scratchpad uses CodeEditor class

lib/tokenlist.cpp
While testing gzip's sources on my system, I got a an internalAstError saying `AST broken, ternary operator missing operand(s)`.
It turns out that a file from gnulib exceeds the limit of `AST_MAX_DEPTH`, specifically [float+.h](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;f=lib/float%2B.h;hb=HEAD) has a macro with deeply nested ternary operators.
This PR doubles the value of `AST_MAX_DEPTH` and makes the code throw immediately with a clearer error message if it is exceeded instead of causing hard-to-follow errors down the line. If this behavior is not desired I would suggest at least maintaining a flag indicating whether the maximum depth was exceeded which can then be reported with other internalAstErrors to help diagnosis.
=> Increase max AST depth and throw error if exceeded

lib/checkmemoryleak.cpp, test/testmemleak.cpp
This fixes the following false positive leakNoVarFunctionCall:
void* f(size_t s) { return memset(xmalloc(s), 0, s); }
When assigning the pointer returned from memset, there already was no
report. This adds return statements to the excluded patterns.
---
The rule currently doesn't seem to care whether the function used is actually passing through the pointer. Maybe the `returnValue` function attribute can be used to limit the exclusion to functions that actually pass through the argument?
=> Fix FP leakNoVarFunctionCall with passthrough returns

lib/tokenize.cpp, test/testtokenize.cpp
This fixes the following daca@home report:
```
refind-0.12.0/refind/line_edit.c:0:0: error: Internal Error. MathLib::toLongNumber: characterLiteralToLL(''') => raw single quotes and newlines not allowed in character literals [cppcheckError]
```
due to the case range `case ' ' ... '~':` and some similar issues with escape sequences in case ranges.
---
I would like better though to remove the separation between the `%num%` and `%char%` cases. The `%num%` case can take care of both if it is acceptable that the newly-inserted `case`s use integer literals instead of character literals. Then some more unusual cases, such as wide characters, will also be handled correctly. At the moment I don't see any particular reason for the distinction.
=> Fix case ranges with single quotes and escape sequences

test/testleakautovar.cpp
When #10186 was fixed, the test case added didn't actually test what was
described in the ticket. Fix this by adding a cast and remove a
duplicated test case (essentially equal to TestLeakAutoVar::assign7).
Spotted when answering https://sourceforge.net/p/cppcheck/discussion/general/thread/cba4e2d026/
=> Fix test case for #10186

cfg/gtk.cfg
According to the documentation, both `g_strdup` and `g_strcmp0` allow for null pointer arguments. This removes the `not-null` attributes of these from `gtk.cfg`.
See https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html.
=> gtk.cfg: g_strdup and g_strcmp0 allow NULL args

lib/checkexceptionsafety.cpp, test/testexceptionsafety.cpp
Previous implementation of recursive function analysis just give up in case of meeting `try` token.
This patch should improve handling such cases. Still it has gap in lack of analysis of try scope (which types can be thrown and can be catched)
Testing for this incorporated in current test cases to avoid duplication
=> Better handling functions with try block for throwInNoexceptFunction

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Lack of simplification for templates instantiated with array types created problems during AST creation. Foe example a code like this:
```
template <class  > struct A {};
template <class T> struct B { A<T[]> x; };
template <class T> struct C : B<T> {};
C<B<int>> y;
```
generated an `internalAstError`:
```
test.cpp:2:33: error: Syntax Error: AST broken, binary operator '>' doesn't have two operands. [internalAstError]
```
=> Support array types in template simplifier

lib/checkexceptionsafety.cpp, lib/checkexceptionsafety.h, test/testexceptionsafety.cpp
This check should warn user about forgotten argument for `throw`. I guess it could be quite common in case if you go to look up the right type of exception or macro for it and got distracted or something.
Possible FP can be if rethrow which located inside a function which called from a catch block. But in this case it should be one place for entire project if code in not bad shape.
Standard references:
-  https://eel.is/c++draft/expr.throw
-  https://eel.is/c++draft/except.handle#def:exception_handling,currently_handled_exception
Also similar check presented in another analyzer: https://pvs-studio.com/en/docs/warnings/v667/
=> New check for rethrow without current handled exception

lib/checkexceptionsafety.cpp, lib/checkexceptionsafety.h
Make CheckExceptionSafety.(h|cpp) more consistent with other
=> Moving error reporting functions from header to source file for CheckExceptionSafety class

gui/cppcheck_de.ts, gui/cppcheck_es.ts, gui/cppcheck_fi.ts, gui/cppcheck_fr.ts, gui/cppcheck_it.ts, gui/cppcheck_ja.ts, gui/cppcheck_ko.ts, gui/cppcheck_nl.ts, gui/cppcheck_ru.ts, gui/cppcheck_sr.ts, gui/cppcheck_sv.ts, gui/cppcheck_zh_CN.ts, gui/help/preferences.html, gui/help/projectfiledialog.html, gui/projectfiledialog.cpp, gui/projectfiledialog.ui, gui/settings.ui
Names of MISRA and CERT should be written is uppercase, because they are abbrevations.
=> gui: Set the correct names for coding standards in UI elements. NFC.

gui/mainwindow.cpp
If user doesn't create a build directory, it is not possible to run add-ons, because they are trying to check dump files in non-existent build directory.
This commit also makes the icon of the 'Create build directory' dialog less confusing.
Before:
After:
=> gui: Handle errors when creating a build directory

tools/triage/mainwindow.cpp
Downloading and untaring big files freezes triage tool. To fix this problem properly, it should be redesigned in Qt style.
However, we could dispatch events manually in loop which allow us to show pop-up window(which locks all actions with main form) and keep user in touch.
Long story short, it's a hack, but it should be good enough for internal tool
Tested on Linux KDE
=> [triage tool] Keep UI alive while wget and tar execution

addons/misra_9.py
Add default parameter to next() to prevent StopIteration exception when no corresponding rawToken is found for '[' token.
Not sure why that happens since there is no code to reproduce the issue, but the rest of the code should be fine with this change.
=> Add default parameter to next() to prevent StopIteration exception

addons/misra_9.py, addons/test/misra/misra-test.c
This fixes the crash on with struct fields containing unknown types reported on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/d64551cc55/#5f0f.
The suggested patch doesn't handle the cases when there are struct fields with arrays containing unknown types. So the addon will not generate warnings in these cases. The problem is that Cppcheck doesn't generate `valueType-pointer` information for unknown types in the dump file. When adding this in *symboldatabase.cpp*, MISRA addon will generate a lot of false positives because we depend on the null value of `valueType`.
So I suppose it better to left this as is, to don't break the addon for such rare cases.
=> misra: Fixed crash with struct fields containing unknown types on 9.x rules

addons/cppcheckdata.py, addons/misra.py, addons/test/misra/misra-test.c, lib/symboldatabase.cpp
Fix false positives in rule 8.2 that occurred in cases when we have a function definition and declaration in the same file.
For example, the following code generated false positives before this commit:
```c
void f(uint8_t * const x);
void f(uint8_t * const x)
{ (void)x; }
```
We need to distinguish the declaration and the definition, so the dump file generation routine was extended to keep token where the definition of the function.
The analysis in the addon also been improved.
Closes Trac issue: https://trac.cppcheck.net/ticket/10219
=> misra: Fix 8.2 false positives

addons/misra.py
Example of the source file used to reproduce this crash:
```c
int misra_8_2_o(
const uint32_t a1,
const uint8_t *const a2
)
{ return *a2 + a1; }
int misra_8_2_p(
const uint32_t a1,
const uint8_t *const a2
);
```
```
File "/home/jubnzv/Dev/cppcheck/addons/misra.py", line 3474, in <module>
main()
File "/home/jubnzv/Dev/cppcheck/addons/misra.py", line 3418, in main
checker.parseDump(item)
File "/home/jubnzv/Dev/cppcheck/addons/misra.py", line 3244, in parseDump
self.executeCheck(802, self.misra_8_2, cfg, data.rawTokens)
File "/home/jubnzv/Dev/cppcheck/addons/misra.py", line 3179, in executeCheck
check_function(*args)
File "/home/jubnzv/Dev/cppcheck/addons/misra.py", line 1579, in misra_8_2
rawTokensFollowingPtr = getFollowingRawTokens(rawTokens, …
```
=> misra: Fix crash on rule 8.2

addons/misra.py, addons/test/misra/misra-test.c
The MISRA 2012 standard does not say anything about variadic functions in the definition of rule 2.7. Therefore, these cases should be considered as false positives.
=> misra: Don't consider variadic arguments as the violation of rule 2.7

addons/misra.py, addons/test/misra/misra-test.c
Make the MISRA addon emit extra warnings for unused arguments placed in lines other than the function definition. This makes it easier for the user to find violations.
=> misra: Emit more accurate warnings for unused arguments in rule 2.7

addons/misra.py, addons/test/misra/misra-test.c
This makes it easier for the user to find the violation.
Suggested in the forum: https://sourceforge.net/p/cppcheck/discussion/development/thread/801dc07e59/#a1a8/d3e9/c455/8915/747c/2525/0eb8/0f7d
=> misra: Improve warning messages for rule 8.2 when the missing arguments are on the next line

lib/cppcheck.cpp
The offending code can (and does) result in newlines at the end of InternalError messages, which are asserted to never happen.
=> Fix assertion failure in errorlogger.cpp

lib/checkfunctions.cpp, lib/checkfunctions.h, test/testfunctions.cpp
Returning objects by-value from function could[2] be optimized by Return Value Optimization by compiler. Using `std::move` could affect compiler behaviour in this case. [1] has general recommendation to avoid such expressions.
As an other optimizations it has a lot of vary from version to version, from platform to platform, e.g. *mandatory* case came with C++17. But as a motivation for adding this 
[1] https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-return-move-local
[2] https://en.cppreference.com/w/cpp/language/copy_elision
https://pvs-studio.com/en/docs/warnings/v828/
=> New check: [perf] Copy elision optimization can't be applied for `return std::move(local)`

addons/cppcheckdata.py, addons/test/misra/misra-test.c
The problem is that the variables from the anonymous union nested in a struct don't appear in the dump file. It doesn't matter, since they are not used in the analysis.
Reported in the forum: https://sourceforge.net/p/cppcheck/discussion/development/thread/fe109ee48f/?page=2&limit=25#ff97
=> cppcheckdata: Fix crash on a nested union

addons/cert.py, addons/misra.py, addons/test/test-cert.py, addons/test/test-misra.py, addons/test/test-y2038.py, addons/y2038.py
The problem is if we call argparse functions through pytest, the addon will treat pytest options from sysv as its own options and will fail.
For example, if we run a specific test with the following command:
```
PYTHONPATH=addons python3 -m pytest addons/test/test-misra.py -k test_loadRuleTexts_structure
```
The MISRA addon will fail because it considers `-k` as an argument for misra.py.
This commit decouples parser initialization and `parser.get_args()` logic from the implementation in addons.
=> addons: Fix arguments parser when running pytest

cli/filelister.cpp
When compiling on SunOs 11 with g++ (GCC) 10.2.0 NAME_MAX is not defined.
Use alternative MAXNAMLEN if it is defined
=> SunOs 11 needs alternative macro for NAME_MAX

lib/cppcheck.cpp
This allows rules to be added for include directives.
=> Add include directives to 'define' tokenlist

lib/checkfunctions.cpp, test/testfunctions.cpp
Removed a false positive:
```
error: Found a exit path from function with non-void return type that has missing return statement [missingReturn]
int main(void) {}
^
```
I have kept the error for C with a standard lower than C99, as there the return value is undefined. 
ANSI C:
2.1.2.2
Program termination
...
If the main function executes a return that
specifies no value, the termination status returned to the host
environment is undefined.
C99:
5.1.2.2.3
Program termination
If the return type of the main function is a type compatible with int, a return from the initial call to the main function is equivalent to calling the exit function with the value returned by the main function as its argument;**reaching the } that terminates the main function returns a value of 0.**
=> Remove a false positive - main function has no return value

lib/astutils.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/tokenize.cpp, lib/tokenlist.cpp, lib/valueflow.cpp, test/testsimplifytemplate.cpp, test/testsimplifytokens.cpp, test/testsimplifytypedef.cpp, test/testsymboldatabase.cpp, test/testtokenize.cpp, test/testvalueflow.cpp
Constexpr only implies `const` for variables. It doesn't imply `const` on functions.
=> Remove constexpr -> const simplification

lib/cppcheck.cpp
We could use reference type to prevent copying.
=> lib: Fix clang -Wrange-loop-construct warning

gui/projectfiledialog.cpp, gui/projectfiledialog.h
If the user enters the path that potentially could be relative, we are trying to replace it with the absolute one.
Reported in the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/311ed96e68/
Fixes Trac ticket [#10377](https://trac.cppcheck.net/ticket/10377).
=> gui: Fix suppressions by file with the relative paths

gui/erroritem.h, gui/resultstree.cpp
This is required because Cppcheck can return -1 as line number if the warning has no line. For example, `unmatchedSuppression` warnings behave this way.
Before:
After:
=> gui: Set signed int type for the error lines

gui/translationhandler.cpp
Upon the first start of cppcheck-gui, the following message appears,
if the language of the OS is English:
```
Failed to load the user interface language:
Failed to load translation for language English from file
cppcheck_en.qm
The user interface language has been reset to English.
```
- Update translationhandler.cpp and check if the language code starts
with "en". The code can be e.g. "en_US"
=> Fix Failed to load translation for English

.github/workflows/release-windows.yml
The mirror option has been removed from the
[jurplel/install-qt-action](https://github.com/jurplel/install-qt-action) [1]
- Fixes warning in release-windows GitHub Action:
`build`
`Unexpected input(s) 'mirror'`
[1] https://github.com/jurplel/install-qt-action/commit/49465b8
=> Remove mirror option from install-qt-action

lib/valueflow.cpp
This is already handled by `valueFlowCondition`.
=> Refactor: Remove extra analysis of container sizes in conditions

lib/valueflow.cpp, test/testbufferoverrun.cpp
This reverts commit 7a6d7f7c2de9846bd12a4bc5aab6c3bb2aba61ec. The formatting change makes cppcheck uncompilable and it breaks CI.
=> Revert "Formatted the code [ci skip]"

cli/cppcheckexecutor.cpp
Compilation error encountered on Fedora Rawhide.
=> Fix compilation with recent glibc where SIGSTKSZ is not constant.

lib/checkunusedvar.cpp, lib/library.cpp, lib/library.h, lib/symboldatabase.cpp, lib/symboldatabase.h, test/testautovariables.cpp, test/testsymboldatabase.cpp
- Type is set when accessing an element or buffer of a container
- Type is set when dereferencing a iterator
- Improve detecting smart pointer and make it its own type
- Type is set when dereferencing a smart pointer
=> Symboldatabase: Improve valuetypes for containers, iterators, and smart pointers

lib/token.cpp, lib/valueflow.cpp, lib/valueflow.h
- Provide the value bound
- Provide the lifetime scopes and kinds
- Provide the path id
- Rename symbolic values to avoid conflicts with `intvalue`
=> Add more ValueFlow info in the xml dumps

lib/astutils.cpp
getTokenArgumentFunction can be called many many times, and the vector
is not needed, but it can become quite costly.
This patch replaces getArguments with a function simply returning the
position of the token, if it is found in the arguments (thus saving the
cost of std::vector).
=> Remove usage of std::vector and getArguments from getTokenArgumentFunction

lib/symboldatabase.cpp, lib/symboldatabase.h, test/testsymboldatabase.cpp
Follow up to 0093452bed30f27a8a6366.
Give the proper end to getVariableList, since it might not be bodyEnd.
Before that, getVariableList would add the same variables in several
unrelated scopes, and all kind of false positive would follow.
For instance, with the case I added in the unit-tests, I had:
```
../code.cpp:15:18: warning: The struct 'is_A' defines member variable with name 'foo' also defined in its parent struct 'is_A_impl'. [duplInheritedMember]
static const int foo = 8;
^
../code.cpp:15:18: note: Parent variable 'is_A_impl::foo'
static const int foo = 8;
^
../code.cpp:15:18: note: Derived variable 'is_A::foo'
static const int foo = 8;
^
../code.cpp:15:18: style: struct member 'has_A::foo' is never used. [unusedStructMember]
static const int foo = 8;
^
../code.cpp:15:18: style: …
```
=> Fix handling of namespace scope with several bodystarts

lib/checkio.cpp, test/testio.cpp
For the following code:
```c++
#include <cstdio>
void foo(size_t s) {
::printf("%zi\n", s);
::scanf("%zi\n", &s);
}
```
I currently get the following nonsensical output:
```
Checking test.cc ...
test.cc:4:7: portability: %zi in format string (no. 1) requires 'size_t' but the argument type is 'size_t {aka unsigned long}'. [invalidPrintfArgType_sint]
::printf("%zi\n", s);
^
test.cc:5:7: portability: %zi in format string (no. 1) requires 'size_t *' but the argument type is 'size_t * {aka unsigned long *}'. [invalidScanfArgType_int]
::scanf("%zi\n", &s);
^
```
i.e. the required and expected type are seemingly equal. The warning is correct, though, because `%zi` expects a _signed_ integer, i.e. a `ssize_t`; I have adjusted the output accordingly, so that I get the less confusing
```
Checking …
```
=> Fix incorrect warning with `%zi` in format string

addons/cppcheckdata.py, addons/misra.py
Updated the isKeyword function
- add c11 keywords.
- use biggest list of keywords in case an invalid standard is used. (instead of an empty list)
Fixed some cosmetic things in cppcheckdata.py
=> Misra add c11 keywords

addons/misra.py, addons/test/misra/misra-test.c
Hi @danmar congrats for cppcheck!!! such a great tool. We are using it and we found some with MISRA rule 6.1.
This is an example of our code:
and this is the report:
as you can see, "unsigned int" is being accepted, but "uint16_t" not.
This is the official MIRSA 2012 rule:
(see in yellow that typedefs shall be accepted)
so I've been debuging your misra.py file......and I did a fix. Now It detects the sign for both conventions ("unsiged int" and "uint")
Thanks!!
Dani
=> Fix in MISRA rule 6.1 check

lib/valueflow.cpp, test/testautovariables.cpp
```
namespace test {
class Foo {};
struct Bar {
Foo *_foo;
};
int f(Bar *bar);
void g(Bar *bar) {
{
Foo foo;
bar->_foo = &foo;
bar->_foo = nullptr;
}
f(bar);
}
}
```
would give
```
a.cpp:15:5: error: Using pointer to local variable 'foo' that is out of scope. [invalidLifetime]
f(bar);
^
a.cpp:12:17: note: Address of variable taken here.
bar->_foo = &foo;
^
a.cpp:11:9: note: Variable created here.
Foo foo;
^
```
=> Fix FP due to namespace scope

lib/analyzer.h, lib/checkuninitvar.cpp, lib/checkuninitvar.h, lib/valueflow.cpp, lib/valueflow.h, test/testsuppressions.cpp, test/testuninitvar.cpp
This also fixes issues [10573](https://trac.cppcheck.net/ticket/10573) and [10554](https://trac.cppcheck.net/ticket/10554).
=> Propagate partially uninit variables in ValueFlow

cmake/compileroptions.cmake
The variable passed to `check_cxx_compiler_flag` is a cached variable which means it wont run a `try_compile` if it is already set. Instead, this makes a variable name from the flag so its unique to the flag being checked.
=> Use a unique variable name when checking if a flag is valid

lib/valueflow.cpp
This helps reduces the number of iteration valueflow needs to apply since its common for users to define functions before calling them. I see about a 20% speed improvement with debug builds of cppcheck when analyzing lib/clangimport.cpp.
=> Run valueFlowSubfunction in reverse order of functions

requirements.txt
From pcre's website:
> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.
=> Install pcre from github since the ftp.pcre.org site is no longer available

lib/tokenize.cpp, test/testsimplifytypedef.cpp
Without the patch, the test would give:
```
Expected:
namespace foo { class Bar ; } class Baz ; class C : Baz { } ;
Actual:
namespace foo { class Bar ; } class Baz ; class foo :: Bar : Baz { } ;
```
=> Don't simplify template for class names in declarations

lib/forwardanalyzer.cpp
Using std::function requires stepping through a bunch std calls to get to the lambda function. Using a template, the debugger will step directly to the lambda when stepping in, which makes debugging the forward analyzer much easier.
=> Refactor: Use a template instead of std::function in forward analyzer to help improve debugging

lib/checkclass.cpp, test/testclass.cpp
Cppcheck issues a warning if a virtual call is called from a constructor or destructor. If the method is just overridden and marked final, this is a false positive.
=> fix false positive of virtual function call

cli/cmdlineparser.cpp, cli/cppcheckexecutor.cpp, lib/importproject.cpp, lib/importproject.h, lib/settings.h, lib/utils.cpp, lib/utils.h
As discussed in https://sourceforge.net/p/cppcheck/discussion/general/thread/43471c7ea1/, I added support for passing multiple file filters.
=> Implement support for passing multiple file filters

lib/checkautovariables.cpp, test/testautovariables.cpp
daca reports new false positives after db4f94fdfea6 on the form:
void f() {
char *ptr = malloc(10);
char *empty_str = "";
if (ptr == NULL)
ptr = empty_str;
if (ptr != empty_str)
free(ptr);
}
Add a check that the value is not impossible to avoid this.
=> autovarInvalidDeallocation: Fix fp with impossible value

lib/astutils.cpp, test/testother.cpp
Not sure if this is the right fix. Maybe those values should not be set in the first place?
=> Fix #9570 duplicateValueTernary related to references to static variables

lib/checkautovariables.cpp, test/testautovariables.cpp
Do not warn for array arguments that are free'd, since they decay to
pointers.
=> Fix #10600: FP invalid dealloc of function array argument

lib/astutils.cpp, lib/astutils.h
Total Ir - before and after (note: I had all checks and valueflow disabled to speed up the testruns)
```
28,535,826,203
26,205,179,202
26,142,812,619
```
=> astutils.cpp: optimized isSameExpression() a bit - reduces average Ir from 294 to 213 when analyzing test folder

.github/workflows/scriptcheck.yml
The cache builds are removed after 7 days of not being accessed and the maximum storage is 10 GB. I stripped the binary since we don't need the debug symbols and we store less.
=> scriptcheck.yml: avoid duplicated cppcheck builds

lib/valueflow.cpp, test/testcondition.cpp
I have no idea what "noninvertible" means in this context. Maybe "potentially induces loss of information"? There could be other operators missing from the list.
Anyway, without the bailout, the impossible value `0` for `v16` was incorrectly propagated to `=` and `>>`.
=> Fix #9549 FP knownConditionTrueFalse (bitshift)

cfg/boost.cfg
Using assert in macros causes assertWithSideEffect in some cases, which is not
a valid issue for these macros.
Macros for test case/suite were causing unusedStructMember warnings because
the test function could not be parsed correctly. The new defines don't match
completely what the macros really do, but it seems to be a good enough
approximation.
=> Improve definitions for boost test macros

htmlreport/check.sh
=> htmlreport/check.sh: use less heavy input folder to reduce scriptcheck build times

.github/workflows/CI-unixish.yml
I will look into using `brew` instead when moving to the platform-provided Qt for the CI builds.
=> CI-unixish.yml: disabled GUI build on macos since Qt installation is flakey

.github/workflows/CI-unixish.yml
The CI-unixish job did not run at all.
=> CI-unixish.yml: fixed syntax error

.github/workflows/CI-unixish.yml, .travis_suppressions
We cannot fix findings in these files but they are real-world production files and the generator might emit faulty code. Also if we generate false positives on such code we should be aware of it.
There's already a ticket for the `simplifyUsing` warning - see https://trac.cppcheck.net/ticket/10252, And we still have several open tickets regarding the unknown execution scope so we should refrain from opening more until those are actually fixed.
=> CI-unixish.yml: added generated GUI files to self check and suppress known false positives for now

lib/tokenize.cpp, test/testunusedvar.cpp
There is still a FP for
~~~~
struct T { int i; };
void f() {
struct T t{};
t.i = 0;
g(t);
}
~~~~
since the `T` in `struct T t{};` gets removed by `removeMacroInClassDef()` because it looks like a macro. That heuristic should probably be improved.
=> Fix #10591 FP unusedStructMember with value-initialized struct and typedef

tools/donate-cpu.py, tools/donate_cpu_lib.py, tools/test-my-pr.py
Main changes:
* Bump client version
* Move try+retry logic to function try_retry to reduce duplication
* Use exponential backoff for try_retry
* git clone with --depth=1 to reduce bandwidth and disk use
* Use multiple worktree to work with multiple versions, instead of back-and-forth checkouts
Bandwith use for main+2.6 download: 
1.3.16: 114 Mio
1.3.17: 3.9 Mio
Disk usage for main+2.6 clone and build: 
1.3.16: 807 Mio
1.3.17: 581 Mio
=> Better git usage in donate-cpu.py to reduce bandwidth and disk usage

lib/tokenize.cpp, test/testsimplifytokens.cpp
When parsing attributes to remove them, we have to allow for
the case where the return type of the function that follows
the attribute has a namespaced C++ type, like foo::bar .
That means that :: has to be recognized as a valid token.
Fix this in simplifyAttribute, and add tests for this as well.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Fix the ability to recognize return types when simplifying attributes.

lib/astutils.cpp, test/testother.cpp
Which flags should actually be compared? Are the comparisons [here](https://github.com/danmar/cppcheck/blob/main/lib/astutils.cpp#L1282) complete?
=> Fix #7754 FP Same expression on both sides of '||'

tools/donate-cpu.py, tools/donate_cpu_lib.py
check_requirements: verify that module psutil is available. 
scan_package: collect crash callstack regardless of cppcheck_path and cppcheck version
=> donate_cpu_lib.py: fix callstack capture, fix dependency check

.github/workflows/clang-tidy.yml, cmake/compilerDefinitions.cmake, cmake/options.cmake
This matches what can be done with `Makefile`.
=> added CMake option CPPCHK_GLIBCXX_DEBUG to make usage of _GLIBCXX_DEBUG in Debug build configurable

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
I'm attempting to rewrap my head around #3014 and my first step is to extract some of the more incidental changes which aren't core to the main change.
This change captures the change described in https://github.com/danmar/cppcheck/pull/3014#discussion_r559088969. Hopefully the justification given in that comment is sufficient explanation.
=> remove nullScope from TestSymbolDatabase

lib/symboldatabase.cpp, test/testautovariables.cpp
Function parameters `const char* s` vs. `const char s[]` were not handled consistently in `Variable` and `ValueType`. I'm not sure that this is the right fix.
=> Fix #10469 FP returnTempReference with overloaded operator+=

cfg/googletest.cfg, test/cfg/googletest.cpp
This avoids assertWithSideEffect and follows more closely what the real macros
are doing, similar to the ones in boost.cfg and cppunit.cfg.
In theory the macros should also cause unreachableCode if the condition is always true, but that doesn't seem to work.
=> Improve definitions for googletest ASSERT_* macros

tools/reduce.py
With these changes I was not able to reduce the code I files https://trac.cppcheck.net/ticket/10708 from. After the first reduction it would hang and even handling the timeout did not help since a reduction which removed the assertion caused findings to appear and thus resulting is a non-0 exitcode.
These improvements will also enable us to integrate it with daca@home.
=> reduce.py: improved --segfault / added detection of "hang" caused by reduced code / cleanups

lib/symboldatabase.cpp, test/testautovariables.cpp, test/testclass.cpp
The fix for the test case is `if (vt.pointer == 0)`. But since `std::array` cannot decay to a pointer, I fixed that as well.
=> Fix regression: functionStatic related to overload resolution

lib/astutils.cpp
I tested this with `cli/filelister.cpp`. I wanted to test it with more files but with all the recent performance regressions it's agonizing slow while running in `valgrind`.
The initial Ir count was `353,306,619`.
Reducing the `std::stack` operations by not adding `nullptr` entries reduced it to `334,276,673` even though the checks added some overhead.
Switching the backend of the `std::stack` from `std::deque` to `std::vector` reduced it to `293,371,232`. The main problem is that the construction of a `std::deque` is much more expensive. The destruction cost stays the same.
So in total this saves us about 12% of the Ir count.
The main issue here still remains the creation and destruction of `std::stack` which still amounts to more than 22% of the total Ir count. So it's the same issue we …
=> astutils.cpp: optimized visitAstNodesGeneric() a bit

.github/workflows/CI-unixish.yml, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/xmlreportv2/testxmlreportv2.cpp
Using a fixed Qt version is convenient in the CI but this is not possible for users of the distro we are testing on. We should use the provided one to make sure we can actually build on that platform (in case of ubuntu-18.04 it did not...well, technically it failed linking).
The install of Qt is also faster than `jurplel/install-qt-action@v2` (installing *all* software on ubuntu takes about 45s whereas Qt alone took 1m15s before) and will obviously be more stable as well.
The remaining jobs which cannot do this will be updated to cache the Qt installation soon.
=> CI-unixish.yml: Use Qt version provided by the distro

tools/donate_cpu_lib.py, tools/test-my-pr.py
Two minor improvement to test-my-pr/donate-cpu.
First, since cppcheck needs a source file to process we can skip header-only packages. Second, when testing local changes with test-my-pr, it is sometimes desired to only process c++-packages, and not c-packages (for example when doing changes to checkclass.cpp), so add a flag for this.
=> Minor improvements to package selection in test-my-pr/donate-cpu

gui/cppcheck_de.ts, gui/cppcheck_es.ts, gui/cppcheck_fi.ts, gui/cppcheck_fr.ts, gui/cppcheck_it.ts, gui/cppcheck_ja.ts, gui/cppcheck_ko.ts, gui/cppcheck_nl.ts, gui/cppcheck_ru.ts, gui/cppcheck_sr.ts, gui/cppcheck_sv.ts, gui/cppcheck_zh_CN.ts, gui/test/benchmark/simple/benchmarksimple.cpp, gui/test/benchmark/simple/benchmarksimple.h, gui/test/data/benchmark/simple.cpp, gui/test/filelist/testfilelist.cpp, gui/test/filelist/testfilelist.h, gui/test/projectfile/testprojectfile.cpp, gui/test/projectfile/testprojectfile.h, gui/test/translationhandler/testtranslationhandler.cpp, gui/test/translationhandler/testtranslationhandler.h, gui/test/xmlreportv2/testxmlreportv2.cpp, gui/test/xmlreportv2/testxmlreportv2.h, tools/extracttests.py, tools/matchcompiler.py, tools/test_matchcompiler.py
I guess the translation files can just use `%1` but I have no idea how those work.
We probably also need to add more copyright headers to things like Python scripts and stuff.
=> more copyright fixes

.github/workflows/asan.yml, .github/workflows/ubsan.yml
This might cause an increase in compilation time but makes the test and selfcheck faster. The newer clang version should also improve the runtime since it produces better code for us. With these changes UBSAN is no longer the slowest job.
=> use the latest clang and -O2 for sanitizer jobs

lib/checkclass.cpp, test/testconstructors.cpp
The wording for this warning is slightly misleading. In the examples in the tests the classes in question _do_ have constructors. The problem being reported is really that they don't _declare_ constructors (i.e. the user has added data that probably needs to be initialized at construction but hasn't declared that anything special will happen at construction).
I think this slight change to wording could save users time figuring out what's going on or suppressing something they think is a false positive. My initial assumption when I encountered this message was that it was a false positive before giving a little more thought to what it was trying to tell me.
=> improve noConstructor message

gui/checkstatistics.cpp, gui/codeeditor.cpp, gui/codeeditstyledialog.cpp, gui/csvreport.cpp, gui/projectfiledialog.cpp, gui/resultstree.cpp, gui/statsdialog.cpp, gui/threadhandler.cpp, gui/threadhandler.h, gui/txtreport.cpp
I verified the version which made the replacements with the Qt documentation and only added version checks if necessary.
The remaining warning is
```
/mnt/s/GitHub/cppcheck-fw/gui/resultstree.cpp:829:34: warning: 'startDetached' is deprecated: Use QProcess::startDetached(const QString &program, const QStringList &arguments) instead [-Wdeprecated-declarations]
bool success = QProcess::startDetached(cmdLine);
^
```
This requires changes to our GUI code as well so I didn't fix it yet.
This will also help with some of the remaining Qt6 compilation errors.
=> fixed most of the Qt deprecation warnings

.github/workflows/release-windows.yml
I pulled this out of #3770 since the actual caching of the build is a bit tricky and needs more work.
=> release-windows.yml: disabled some unnecessary PCRE build options

lib/checkclass.cpp, test/cfg/std.cpp, test/testclass.cpp
Check if the iterator is assigned to a const_iterator or
const_revese_iterator, in which case it is possible the function can be
const. Unfortunately, it is not possible to remove the hard coding of
cbegin, cend, crbegin and crend due to the need to handle auto, as in
the following code snippet:
void cbegin_auto(void)
{
for (auto it = m_str.cbegin(); it != m_str.cend(); ++it) {;}
}
=> Fix #10671: functionConst FN with begin/end and const_iterator

gui/applicationlist.cpp, gui/main.cpp, gui/showtypes.cpp, gui/statsdialog.cpp, gui/statsdialog.h, gui/test/benchmark/simple/benchmarksimple.cpp, gui/test/benchmark/simple/benchmarksimple.h, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/cppchecklibrarydata/testcppchecklibrarydata.h, gui/test/filelist/testfilelist.cpp, gui/test/filelist/testfilelist.h, gui/test/projectfile/testprojectfile.cpp, gui/test/projectfile/testprojectfile.h, gui/test/translationhandler/testtranslationhandler.cpp, gui/test/translationhandler/testtranslationhandler.h, gui/test/xmlreportv2/testxmlreportv2.cpp, gui/test/xmlreportv2/testxmlreportv2.h, gui/translationhandler.h, tools/dmake.cpp
I was able to adjust the Qt mapping to work around the slowdown so I could at least partially clean up the includes. Full cleanup requires a fixed include-what-you-use.
=> cleaned up GUI includes based on include-what-you-use

.github/workflows/CI-windows.yml
No more need for Qt 5.9.9 since it is now covered by the `ubuntu-18.04` build. Also we need to update Windows to Qt 6.2 and drop 5.15.2 as well since 6.x versions are the only version we can get updates for as a non-paying "customer".
=> CI-windows.yml: added windows-2022, removed QT 5.9.9 and use msbuild instead of CMake for now

tools/reduce.py
This reverts commit 4f508c93c4c41e40464b09cff8de7ebd35e8afa3, which broke the reduce.py script. It used `time.perf_counter` which is not available in python 2, and this script doesn't work on python 3(due to mixing bytes and str together).
=> Python fixes for reduce.py

lib/programmemory.cpp, lib/programmemory.h, lib/valueflow.cpp
This gets rid of the extra unnecessary calls to `findExpression`. I see about ~11% improvement.
=> Refactor ProgramMemory to store the expression tokens instead of exprIds

tools/matchcompiler.py, tools/test_matchcompiler.py
fixes the following error in #3731:
```
File "tools/matchcompiler.py", line 720, in <module>
main()
File "tools/matchcompiler.py", line 717, in main
mc.convertFile(pi, po, line_directive)
File "tools/matchcompiler.py", line [6](https://github.com/danmar/cppcheck/runs/4872502058?check_suite_focus=true#step:6:6)20, in convertFile
line = self._replaceTokenMatch(line, linenr, srcname)
File "tools/matchcompiler.py", line 3[9](https://github.com/danmar/cppcheck/runs/4872502058?check_suite_focus=true#step:6:9)6, in _replaceTokenMatch
assert(len(res) == 3 or len(res) == 4)
AssertionError
```
=> matchcompiler.py: skip comments in _replaceTokenMatch()

lib/cppcheck.cpp
In the CppCheck::executeAddons function, a check that specifically tests for the misra add-on, was not taking into account the cases when the addon is identified with the '.py' extension or indirectly via json. This resulted in the add-on not being executed a second time which is needed to detected some of the misra violations. By using the AddonInfo class name field, the addon name is uniformized for all these cases and the add-on executed a second time.
I've raised the issue descrining how to reproduce the issue in a [sourceforge discussion post](https://sourceforge.net/p/cppcheck/discussion/general/thread/4422407807/).
=> Fix check for misra addon in executeAddons.

lib/astutils.cpp, lib/astutils.h
See https://blog.demofox.org/2015/02/25/avoiding-the-performance-hazzards-of-stdfunction/.
Testing with `cli/threadexecutor.cpp`:
GCC 11 `656,137,737` -> `582,567,111`
Clang 13 `605,911,420` -> `556,949,984`
=> inline visitAstNodes() calls

cfg/windows.cfg
It's probably copy-pasta, _atol_l and _wtol_l are configured below.
=> windows.cfg: Fix configuration for _atoi_l and _wtoi_l

.github/workflows/CI-cygwin.yml, .github/workflows/CI-mingw.yml, Makefile, readme.md, readmeja.md, tools/dmake.cpp
I removed `LDFLAGS` from the documentation since the `Makefile` sets it implicitly.
Somehow the MinGW setup in the CI contains `which` and `uname` which are not available if I install MinGW locally. So even though the build works in the CI we need to adjust the detection and configuration in the `Makefile`. These are more reasons which would justify dropping the `Makefile` in favor of CMake (but I am not prepared to do that for several reasons...yet).
This is in preparation of natively running daca@home on Windows via MinGW.
=> added MinGW to CI and fixed local MinGW build

cfg/std.cfg, test/testleakautovar.cpp
`freopen()` doesn't have leak-ignore, but the `temp` leak is still reported.
=> Add leak-ignore for fopen_s(), test cases

cli/threadexecutor.cpp, cli/threadexecutor.h
I came across this while trying to align the handling of suppressions in single-threaded and multi-threaded/process analysis.
This is the first step of making the `ErrorLogger` usage a bit clearer. There's several layers of `ErrorLogger` implementations which are hard to follow and possibly even unnecessary,
It also gets rid of implementation-specific stuff in the header.
I think we could also provide a thread-based implementation for non-Windows with a simple change which would enable use to use TSAN or `valgrind` for checking for multi-threading issues.
=> de-coupled ErrorLogger interface from ThreadExecutor

lib/checkclass.cpp, lib/symboldatabase.cpp, test/testclass.cpp, test/testconstructors.cpp
Also:
Fix FN for members with c++11 initializers not assigned in copy constructor/operator=
Fix FN for virtual function call from copy constructor
=>  Fix #10360 FP uninitMemberVar from copy constructor [inconclusive]

addons/misra.py, addons/test/misra/misra-ctu-1-test.c, addons/test/misra/misra-ctu-2-test.c, addons/test/misra/misra-ctu-test.h, lib/tokenize.cpp
The fixed false positive violations are reported in trac tickets [#10751](https://trac.cppcheck.net/ticket/10751), [#10814](https://trac.cppcheck.net/ticket/10814) and [#10820](https://trac.cppcheck.net/ticket/10820).
The PR also includes a fix for when sometimes the inline keyword was being ignored as detailed in this [sourceforge thread](https://sourceforge.net/p/cppcheck/discussion/general/thread/368fc732dc/#bf40).
=> Misra false positive fixes for rules 8.7 and 5.9

Makefile, cli/threadexecutor.cpp, cli/threadexecutor.h, test/testsuppressions.cpp, test/testthreadexecutor.cpp, test/testutils.h
This gets rid of the test-only code, simplifies the handling and also now unit tests the actual production code.
I am not too happy about the `ScopedFile` implementation but without `std::filesystem` it is bound to be a bit awkward. :(
This is another steps towards `ErrorLogger`, suppression handling etc. unification since it was using a `CppCheck::check()` overload which can probably be moved/cleaned up.
=> removed ThreadExecutor::addFileContent()

lib/calculate.h, lib/checkother.cpp, lib/summaries.cpp, lib/symboldatabase.cpp, lib/valueflow.cpp
All the issues are fixed now so we can remove those. 
FYI `unmatchedSuppression` is still disabled in the selfcheck because of the existing issues with it.
=> removed unnecessary varid0 inline suppressions
