gui/checkthread.cpp
gui/cppcheck_de.ts
gui/cppcheck_es.ts
gui/cppcheck_fi.ts
gui/cppcheck_fr.ts
gui/cppcheck_it.ts
gui/cppcheck_ja.ts
gui/cppcheck_ko.ts
gui/cppcheck_nl.ts
gui/cppcheck_ru.ts
gui/cppcheck_sr.ts
gui/cppcheck_sv.ts
gui/cppcheck_zh_CN.ts
gui/librarydialog.cpp
gui/mainwindow.cpp
gui/projectfiledialog.cpp
gui/resultstree.cpp
gui/resultsview.cpp
gui/statsdialog.cpp

These didn't come up until compiling with Qt 6.x (as deprecation warnings and compiler errors) so I wasn't able to address those before.

avoid usage of deprecated Qt APIs

---

lib/tokenlist.cpp
test/testincompletestatement.cpp
test/testtokenize.cpp

I don't know what those tests in `TestTokenizer::astpar()` are doing, because it looks like gibberish to me. However, I would argue that the AST from `--debug -v` is less wrong now, e.g. for `f({X, {Y, abc == false ? C : D}});`:
~~~
(
|-f
`-{
`-,
|-X
`-{
`-,
|-Y
`-?
|-== 'bool'
| |-abc
| `-false 'bool'
`-:
|-C
`-D	
~~~
vs. before
~~~
(
|-f
`-{
`-,
|-X
`-{
~~~

Fix #10880 FP constStatement with init list in function call

---

lib/tokenlist.cpp
lib/valueflow.cpp
test/testtokenize.cpp
test/testuninitvar.cpp

The AST for `A* a = new A{};` still looks odd, is this correct?.
~~~
##AST
[bar.cpp:3]
*
|-A
`-a '*'
[bar.cpp:3]
= '*'
|-a '*'
`-new
`-{
`-A
~~~
Edit: probably just the split variable declaration.

Fix #10698 FP uninitvar with new and braced initializer

---

Makefile
lib/cppcheck.cpp
lib/suppressions.cpp
lib/suppressions.h
test/cli/test-inline-suppress.py
test/cli/trac5704/trac5704a.c
test/cli/trac5704/trac5704b.c
test/testsuppressions.cpp

I hope this is an OK way to solve it. The problem with adding this flag is that you more need to do full flow to get the result you want from functions like Suppressions::getUnmatchedLocalSuppressions().

Fix unmatched suppression (#5704)

---

lib/checkclass.cpp
test/testclass.cpp

From `kdevelop-5.6.2/kdevplatform/sublime/areaindex.cpp`.

Fix crash with defaulted destructor

---

lib/valueflow.cpp
test/cfg/windows.cpp

We have lifetime analysis to handle pointer aliasing so this check is no longer necessary.

Remove old pointer alias check

---

htmlreport/cppcheck-htmlreport

Some plugins of cppcheck (e.g. MISRA) may use error ids that are not valid css selectors. When the javascript script of htmlreport tries to use these ids as selectors to display/hide categories of errors, this produces an error inside the user's browser. The solution is to transform the error ids that will be used as selectors in order to remove the invalid characters. This transformation doesn't apply to what is displayed, so that from a reader point of view, nothing is changed.
See also https://sourceforge.net/p/cppcheck/discussion/development/thread/960c995e3a/

Fix invalid css selectors in htmlreport

---

.github/workflows/release-windows.yml
gui/CMakeLists.txt
gui/cppcheck_de.ts
gui/cppcheck_es.ts
gui/cppcheck_fi.ts
gui/cppcheck_fr.ts
gui/cppcheck_it.ts
gui/cppcheck_ja.ts
gui/cppcheck_ko.ts
gui/cppcheck_nl.ts
gui/cppcheck_ru.ts
gui/cppcheck_sr.ts
gui/cppcheck_sv.ts
gui/cppcheck_zh_CN.ts
gui/readme.txt

For some reason passing the option in CMake causes a lot of `unfinished` entries to be shown in the translations and thus breaking them.
There's also the `-no-ui-lines` option but I have no idea what the impact would be so I didn't apply that (yet).

make sure we remove obsolete entries from translations

---

cli/cli.vcxproj
lib/cppcheck.vcxproj
test/testrunner.vcxproj

This fixes e.g. missing function names when profiling a Release build among possible other things.

generate a program database in all Visual Studio configurations

---

.github/workflows/release-windows.yml

This was split from #3939 since there are issues with missing MSMs for Visual Studio 2022 in the CI runners.

release-windows.yml: set up Visual Studio environment and added missing exitcode checks

---

cli/cli.vcxproj
cmake/compilerDefinitions.cmake
cmake/compileroptions.cmake
lib/cppcheck.vcxproj
test/testrunner.vcxproj

I aligned the options which were different in-between the Visual Studio configurations (i.e. `Release`/`Release-PCRE` and `Debug`/`Debug-PCRE`). If these were changed manually and are matching the default value they will also be shown as changed so there's possibly a few we can drop and clean up things a bit more in the future.
I also reviewed all the options in the Visual Studio projects which are being highlighted as changed (the bold ones) and added them to CMake. Some of the option did not show a corresponding command-line option so those still need to be looked into at a later date.
This also fixes the remaining build issues of #3919 and #3925 caused by (yet another) incorrect C++ standard in the Visual Studio `Debug-PCRE` configuration of `cppcheck`.

aligned build options of Visual Studio project configurations and added them to CMake

---

test/CMakeLists.txt

The default template does give better information than using this template.

Use default template in the cfg tests

---

lib/checkother.cpp
test/testother.cpp

The test case had only been changed in https://github.com/danmar/cppcheck/pull/4018. It seems that we cannot warn reliably about higher-order pointers

Fix FP with ptr to ptr const

---

lib/cppcheck.cpp

Generated plist files contain errors from files that are listed in the suppressions-list with this commit this errors are filtered out.

Don't add suppressed errors to plist output

---

man/cppcheck.1.xml

The option --std=posix is was removed back in 2019 in commit cb06aebdab894c2ca767869889df8e1175aeb379.
The manpage as it is now is misleading, since the --std=posix is no longer supported.
BTW, in commit cb06aebdab894c2ca767869889df8e1175aeb379 it is suggested to use --library=posix instead. It will probably also be useful to add that to the manpage eventually.

Remove --std=posix option from the manpage

---

.github/workflows/release-windows.yml
win_installer/config.wxi
win_installer/readme.txt

We have been using `windows-2022` in the CI for a while without any issues. I have been using it locally as the Windows compiler of choice as well.
Since we might switch to Qt6 is the next release it would be good to do the compiler switch first so we don't have too many major version bumps in a single release.
The updated MSM location is documented at https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/redistributing-visual-cpp-files.md#locate-the-redistributable-files.

release-windows.yml: use windows-2022

---

.github/workflows/clang-tidy.yml
cmake/clang_tidy.cmake
gui/resultstree.cpp
gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp
gui/test/cppchecklibrarydata/testcppchecklibrarydata.h
gui/test/translationhandler/CMakeLists.txt
gui/translationhandler.cpp
lib/astutils.h
lib/config.h
lib/importproject.cpp
lib/suppressions.h
lib/valueflow.cpp
oss-fuzz/main.cpp

`clang-tidy` will also report compiler warnings which we were currently suppressing since we treat all warnings as errors.
We should make sure our code is free of warnings. So we should fail the build in the CI (not by default) if one is encountered.
Leveraging the existing `clang-tidy` step saves us an additional explicit step in the CI for a `clang` build.

fail `run-clang-tidy` in case of compiler warnings / fixed Clang warnings / cleanups

---

.github/workflows/scriptcheck.yml
htmlreport/cppcheck-htmlreport

pygments 2.12.0 changed the signature of the HtmlFormatter.wrap()
method. As we don't actually care about the arguments to wrap we can
use packing/unpacking to maintain compatability with older versions of
pygments.

fix html report generation with pygments >= 2.12.0

---

lib/checkother.cpp
test/testother.cpp

From `llvm-toolchain-snapshot_15~++20220509105605+460fc79a080b/clang/test/CXX/drs/dr21xx.cpp`

Fix crash in checkPassByReference()

---

lib/checkleakautovar.cpp
test/testleakautovar.cpp

Similar to how we do for assignments outside if-statements, bail out
since we do not track multiple variables.

Fix #9966: FP memleak with multiple assignments in if-statement

---

lib/astutils.cpp
lib/astutils.h

See https://blog.demofox.org/2015/02/25/avoiding-the-performance-hazzards-of-stdfunction/ - similar to #3828.
Testing an `-O2` build with `--enable=all --inconclusive` on `mame_regtest` code (with some additional local speed hacks applied as well as Boost `SmallVector`):
GCC 11 `32,597,380,507` -> `22,418,156,771`
Clang 13 `27,462,468,325` -> `18,463,123,276`

inlined `findAstNode()` calls

---

lib/token.cpp

Testing an `-O2` build with `--enable=all --inconclusive` on `mame_regtest` code (with some additional local speed hacks applied as well as Boost `SmallVector`):
GCC 11 `1,779,504,569` -> `1,779,385,063` -> `1,722,982,958` -> `1,720,215,885`
Clang 13 `1,767,925,002` -> `1,756,502,888` -> `1,699,929,669` -> `1,696,929,972`
Any further usage of `strchr()` or removal of the redundant code lead to reduced performance. So did changing the order of `strchr()` and the `tok->next()` calls. This and the difference in gains between the compilers is something to dig into and report upstream.
This is mainly to improve the performance of `CheckUnusedVar::checkStructMemberUsage()` - see https://trac.cppcheck.net/ticket/11106.

small `Token::Match()` optimizations

---

.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/asan.yml
.github/workflows/buildman.yml
.github/workflows/clang-tidy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/iwyu.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/ubsan.yml
.github/workflows/valgrind.yml

`ubuntu-22.04` is the new LTS release. Some jobs now start a 22.04 docker container on a 22.04 system but those will be updated with 22.10 when it becomes available.
I also already reference `ubuntu:22.10` in `CI-unixish-docker.yml` which is not yet ready to be used but will be in the future.

use `ubuntu-22.04` as main/base distro in CI

---

addons/naming.py
addons/namingng.py
addons/test/naming_test.cpp

Currently, move/copy constructors are checked as function names.
For example, if someone does not name their functions with the same standard as their class names, the tool will report an error.
This fix makes the function name-checking ignore both copy and move constructors.

Ignore copy/move constructors for function naming checks

---

lib/astutils.h

This is an intermediate solution until `SmallVector` is able to avoid these allocation when not utilizing Boost. As it already provides a sizable improvement without the need for any external dependency I decided to go with this for now.
Testing an `-O2` build with `--enable=all --inconclusive` on `mame_regtest` code (with some additional local speed hacks applied):
GCC 11 `37,875,483,481` -> `33,842,501,109`
Clang 13 `35,459,791,724` -> `28,694,901,787`

astutils.h: reserve `std::vector` space in `visitAstNodes()` to avoid excess allocations

---

CMakeLists.txt

This loses the ability to run these in parallel but that should not be an issue.
Also this stops at the first failing command. Previously they were run in parallel so it *might* have caught more than one failure in a single build but never all of them at once (maybe something to consider as improvement). So it's simply more deterministic now.

avoid unnecessary `validateCFG-*` targets in CMake

---

lib/platform.cpp
test/testplatform.cpp

Merged from LCppC.As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck, starting with those I backported and sent do danmar a year ago, but were not applied to cppcheck for unknown reasons.
In this case, I showed the patch in the associated ticket in addition to sending it in in january 2021, but danmar just changed the milestone from release to release instead of cherry picking it...

LCppC backport: Implemented error handling in cppcheck::Platform::loadFromXmlDocument()

---

cli/filelister.cpp
lib/mathlib.cpp

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck.
MSVC 2012 is not supported anymore according to the readme. And Borland C++ should be irrelevant nowadays. Does anybody even know if cppcheck still compiles with it?

LCppC backport: Removed compatibility hacks for outdated compilers

---

lib/library.cpp
test/testsymboldatabase.cpp

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck, starting with those I backported and sent do danmar a year ago, but were not applied to cppcheck for unknown reasons.
In this case, the feature in LCppC (support for iterators in ValueType) was added to cppcheck by someone else meanwhile. This adds the unit test from LCppC.

LCppC backport: ValueType: Added additional unit test

---

lib/preprocessor.cpp
lib/preprocessor.h
lib/tokenlist.cpp
lib/tokenlist.h

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck, starting with those I backported and sent do danmar a year ago, but were not applied to cppcheck for unknown reasons.

LCppC Backport: Improved calculation of CRC32.

---

lib/tokenize.cpp
lib/tokenize.h
lib/valueflow.cpp
test/testvarid.cpp

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck, starting with those I backported and sent do danmar a year ago, but were not applied to cppcheck for unknown reasons.

LCppC backport: Set varId for variables with global scope operator ::

---

lib/checkbufferoverrun.cpp
lib/checkbufferoverrun.h
releasenotes.txt
test/testbufferoverrun.cpp
test/testfunctions.cpp

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck.

LCppC backport: Restored Check: Detect negative VLA and allocation (new[]) sizes

---

lib/tokenize.cpp
test/testsimplifytokens.cpp

LCppC backport: C++20 support: Support consteval and constinit

---

lib/library.cpp

Following up on fc6c203b0e76, replace auto with the correct types to
clairfy the code. Note the use of const on the first type in the pair,
which allows us to use a reference.

Library: Replace auto with real types

---

man/cppcheck.1.xml

As title says, there is a small typo in the manpage which made me scratch my head for a bit.

Update manpage to fix typo in --max-ctu-depth cli option.

---

cfg/cppcheck-cfg.rng
cfg/gnu.cfg
cfg/posix.cfg
lib/checkbufferoverrun.cpp
lib/checkother.cpp
lib/checkother.h
lib/library.cpp
lib/library.h
lib/tokenize.cpp
lib/tokenize.h
test/testbufferoverrun.cpp
test/testlibrary.cpp
test/testother.cpp

As a follow-up to the discussion in PR4143, I am starting to provide a few fixes/improvements from LCppC to cppcheck, starting with those I backported and sent do danmar a year ago, but were not applied to cppcheck for unknown reasons.

LCppC backport: Replaced check for pipe() buffer size by ordinary CheckBufferOverrun

---

lib/checkother.cpp
test/testother.cpp

Test case #8717 was actually a FP as well.

Fix FP constVariable with 2D array

---

gui/cppchecklibrarydata.cpp
gui/cppchecklibrarydata.h
gui/test/cppchecklibrarydata/files/container_valid.cfg
gui/test/cppchecklibrarydata/files/smartptr_valid.cfg
gui/test/cppchecklibrarydata/resources.qrc
gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp
gui/test/cppchecklibrarydata/testcppchecklibrarydata.h

Avoid configuration load failure due to unhandled element (e.g. qt.cfg).
Avoid data loss during configuration save.
Update smart pointer test.

Library Data: Add support for optional smart pointer element 'unique'

---

cfg/gtk.cfg

Add a number of missing macros from the configuration, including:
* `G_DEFINE_TYPE()`
* `G_DEFINE_FINAL_TYPE()`
* `G_DEFINE_FINAL_TYPE_WITH_PRIVATE()`
* `G_DEFINE_FINAL_TYPE_WITH_CODE()`
* `G_DEFINE_DYNAMIC_TYPE()`
* `G_DEFINE_DYNAMIC_TYPE_EXTENDED()`
* `G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC()`
* `G_DEFINE_AUTO_CLEANUP_FREE_FUNC()`
* `G_DEFINE_AUTOPTR_CLEANUP_FUNC()`

gtk.cfg: add more type definition macros

---

gui/codeeditor.cpp

* Single line comment can be treated as multi-line in case of asterisk line: `//*****`
* Some keywords has an invisible Unicode char: `u+00ad`, which breaks keyword highlighting
Old:
New:

Codeeditor: multi-line comment fix

---

lib/programmemory.cpp
test/testuninitvar.cpp

This fixes some false positives, e.g. in the following code
```c
void f(void) {
char *c;
char x;
while (true) {
c = &x;
break;
}
++c;
}
```
which originally resulted in
```
$ ./cppcheck --enable=warning x.c
Checking x.c ...
x.c:7:7: warning: Uninitialized variable: c [uninitvar]
++c;
^
x.c:3:12: note: Assuming condition is false
while (true) {
^
x.c:7:7: note: Uninitialized variable: c
++c;
^
```
For some reason, I could not get the false positive to fire in a checkUninitVar testcase though.

Correctly interpret boolean literals in `execute()`

---

lib/pathanalysis.cpp

In some cases, like when you have an assignment in an if condition, the loop in PathAnalysis::forwardRange() will continue outside the condition it is supposed to check. That is because the assignment check will put and on the token ), which is also the end token, and then do a tok->next() and check against endToken. This is an extra check if we already on the endToken.
This is probably a solution for trac item #10933. Because that example contains 'many' if statements with assignment in the condition. This makes the run very recursive.
All tests sill passes.

Try to stop range overflow in forwardRange()

---

Makefile
cli/cppcheckexecutor.cpp
lib/preprocessor.cpp
test/CMakeLists.txt
test/testpreprocessor.cpp

Part of this code will go away again with #3229 but this makes sure the existing code actually works as expected.

some `missingInclude`/`missingIncludeSystem` fixes and tests

---

cli/cppcheckexecutor.cpp
lib/analyzer.h
lib/checknullpointer.h
lib/checkother.cpp
lib/checkstl.cpp
lib/checkstl.h
lib/checkuninitvar.cpp
lib/cppcheck.cpp
lib/importproject.cpp
lib/library.h
lib/path.cpp
lib/preprocessor.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/templatesimplifier.h
lib/token.h
lib/tokenize.cpp
lib/tokenize.h
tools/dmake.cpp

Using an existing empty string object makes sense if it is used as a `const std::string&` - also as default parameter. See https://godbolt.org/z/bEfTr1r43.
Returning it from a function is actually more expensive than using the implicit construction from a literal. See https://godbolt.org/z/o9aT4Trz9.
This is not a problem with a local non-`const` object since those will be implicitly moved (FYI that's what the `performance-move-constructor-init` warning is about).
An `const std::string` cannot be used as `const QString&` so I did not change the GUI code.
I will file tickets about such suboptimal cases we might be able to detect.

use `emptyString` more consistently

---

tools/donate-cpu.py
tools/donate_cpu_lib.py
tools/test-my-pr.py

`ftp://ftp.de.debian.org/debian/pool/main/v/vlc/vlc_3.0.17.4.orig.tar.xz`
Before:
`Found libraries: ['posix', 'gnu']`
After:
`Found libraries: ['posix', 'gnu', 'bsd', 'gtk', 'lua', 'motif', 'opencv2', 'opengl', 'qt', 'wxwidgets', 'zlib']`
This also gets rid of various hard-coded instances of the scan folder name.

donate-cpu: fixed library detection

---

lib/checkother.cpp
test/testother.cpp

This has a known test failure, but I actually do not know, why. In LCppC, this works, because Z::b.a gets a varid. In cppcheck it does not (anymore). Do you know, why, and if this is wanted how to workaround it?

LCppC backport: Support member variables in CheckOther::checkIncompleteArrayFill()

---

addons/cppcheckdata.py

This adds a `match` function to addons, it supports:
* `|` for either-or tokens(ie `struct|class` to match either `struct` or `class`)
* `!!` to negate a token
* It supports the `%any%`, `%assign%`, `%comp%`, `%name%`, `%op%`, `%or%`, `%oror%`, and `%var%` keywords
* It supports `(*)`, `{*}`, `[*]`, and `<*>` to match links
* `@` can be added to bind the token to a name
This returns `MatcherResult` when can be used as a boolean or you can read the bound tokens:
```python
r = match(tok, "%name%@ftok (*)")
if (r.ftok.str == "strlen"):
...
```

Add match function to addons

---

.github/workflows/CI-cygwin.yml
.github/workflows/CI-mingw.yml

This should shave a few minutes (4 for Cygwin / 2 for MinGW) off each build.
The linking itself could be sped up as well by using `lld` instead. Several projects (e.g. MAME) do that. That should save another minute or two.

speed up MinGW and Cygwin CI builds by avoiding repeated linking

---

cfg/qt.cfg
gui/helpdialog.cpp
gui/helpdialog.h
lib/checkmemoryleak.cpp
test/cfg/qt.cpp

Although `connect()` was missing leak-ignore, the FP came up since windows.cfg also has a `connect()`.
The warning for HelpDialog looks like a true positive to me.

Fix FP leakNoVarFunctionCall with Qt object

---

lib/valueflow.cpp

Testing an `-O2` build with `--enable=all --inconclusive` on `mame_regtest` code (with some additional local speed hacks and Boost `SmallVector` applied):
Clang 13 `18,349,224,671` -> `18,347,635,685`
We might also be able to use `std::move()` in `addErrorPath()` and `reanalyze()`.

valueflow.cpp: avoid some copies related to `ErrorPath`

---

lib/valueflow.cpp

These were encountered by looking at the changes suggested by the upcoming `misc-const-correctness` clang-tidy check and reviewing similar code. More PRs are coming.

some cleanups

---

gui/csvreport.h
gui/printablereport.h
gui/scratchpad.h
gui/txtreport.h
gui/xmlreportv2.h
lib/errortypes.h
lib/library.h
lib/mathlib.h
lib/symboldatabase.h
lib/templatesimplifier.h
lib/valueflow.h

I did not enable the headers in `.clang-tidy` yet since there are some warnings I am not sure how to suppress. This will be done within #4100.

mitigated most clang-tidy warnings in headers

---

cli/processexecutor.cpp
lib/checkcondition.cpp
lib/checkother.cpp
lib/checkstl.cpp
lib/preprocessor.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/tokenize.cpp
lib/valueflow.cpp
test/testsuite.cpp

We are not interested in `bugprone-assignment-in-if-condition` as it's something we use intentionally. I did fix two cases where it was unnecessary though.
We also encountered two false positives with it. The first one is filed as https://github.com/llvm/llvm-project/issues/56729.
The `modernize-use-emplace` false negatives already have upstream tickets:
https://github.com/llvm/llvm-project/issues/56721
https://github.com/llvm/llvm-project/issues/55870
https://github.com/llvm/llvm-project/issues/55869
https://github.com/llvm/llvm-project/issues/55856

fixed some `modernize-use-emplace` false negatives and some `bugprone-assignment-in-if-condition` warnings

---

cli/cmdlineparser.cpp
gui/help/projectfiledialog.html
man/manual.md

The CERT addon was removed in 92316b07c8.
Clean up a few places which still referenced the CERT addon.

CERT addon removal cleanup

---

cli/processexecutor.cpp

Fix #11196 Enable use of getloadavg() on Cygwin

---

.github/workflows/CI-windows.yml

`v3` of `jurplel/install-qt-action` is currently broken and apparently was never ready for production - see https://github.com/jurplel/install-qt-action/issues/153. So go with `v2` for now.

CI-windows.yml: use `jurplel/install-qt-action@v2` (fixes QT installation)

---

lib/checkautovariables.cpp

Fixed typo in checkautovariables.cpp: getPointerDepth()

---

cli/cmdlineparser.cpp
gui/threadhandler.cpp
lib/library.h
lib/preprocessor.cpp
lib/tokenize.cpp

More things discovered by reviewing the suggestions of the upcoming `misc-const-correctness` clang-tidy check.

avoid unnecessary copies with `insert()`

---

lib/config.h

Fixes `-Wsuggest-attribute=noreturn` warnings on CentOS 7 and Ubuntu 18.04.

config.h: implemented `NORETURN` for GCC < 5

---

addons/cppcheckdata.py

Doing `match(tok, "**;")` will match until the semicolon. 
This also fixes the incorrect slicing for `!!` match as well.

Add ** to match until in addons

---

Makefile
cmake/compileroptions.cmake
tools/dmake.cpp

This helps when using I/O limited systems (e.g. WSL) and just makes sense.
Using WSL1 Kali Linux on my system shows the following:
Before
```
real    3m21.765s
user    13m6.438s
sys     4m33.578s
```
After
```
real    2m54.161s
user    12m29.188s
sys     3m19.578s
```

specify `-pipe` for GCC to use pipes instead of temporary files - greatly reduces I/O usage

---

lib/checkunusedvar.cpp

Performing a `--enable=all --inconclusive` scan on `mame_regtest` with `DISABLE_VALUEFLOW=1`:
GCC 12 `2,391,227,591` -> `2,388,134,902`
Clang 14 `2,484,649,991` -> `2,481,264,565`

refs # 11106 (optimize CheckUnusedVar::checkStructMemberUsage()) - added missing loop breaks

---

cli/cmdlineparser.cpp
cli/cppcheckexecutor.cpp
cli/processexecutor.cpp
lib/checkcondition.cpp
lib/checkfunctions.cpp
lib/checkio.cpp
lib/checkother.cpp
lib/checktype.cpp
lib/checkunusedfunctions.cpp
lib/clangimport.cpp
lib/cppcheck.cpp
lib/ctu.cpp
lib/errorlogger.cpp
lib/importproject.cpp
lib/library.cpp
lib/mathlib.cpp
lib/preprocessor.cpp
lib/summaries.cpp
lib/suppressions.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/token.cpp
lib/tokenize.cpp
lib/valueflow.cpp

We currently get these transitively from a header.
These might have been erroneously removed in the past or have not been added since include-what-you-use is bad in determined from which include certain stream originate - see https://github.com/include-what-you-use/include-what-you-use/issues/683.

added missing `sstream` includes

---

lib/mathlib.h
test/testmathlib.cpp

The hot calls are coming from `TokenList::calculateHash()`.
Scanning `mame_regtest` with `--enable=all --inconclusive` and `DISABLE_VALUEFLOW=1`:
Clang 14 `2,319,237,712` -> `2,091,818,009`
GCC 12 `2,251,016,968` -> `2,027,414,164`

mathlib.h: replaced slow `std::ostringstream` with `std::to_string()` in `MathLib::toString()`

---

Makefile
lib/checkstl.cpp
lib/checkunusedvar.cpp
lib/library.cpp
lib/library.h
test/testlibrary.cpp

Analyzing `mame_regest` with `--enable=all --inconclusive` and `DISABLE_VALUEFLOW=1`:
GCC 12 `2,388,141,397` -> `2,251,016,968`
Clang 14 `2,481,264,733` -> `2,319,237,712`

refs #10663 - sped up `Library::detectContainerOrIterator()` by iterating the containers only once

---

lib/smallvector.h

This changes bakes the `reserve()` call into the non-boost implementation `SmallVector` construction as it would cause a performance regression with the `boost::small_vector` implementation (see #3919).
I tested the build with Clang, GCC, MinGW and Visual Studio.
Replacing the `std::vector` + `resreve()` appraoch with `SmallVector` in `visitAstNodes()` will now yield the same performance when using Clang.
In case of GCC the code actually gets faster since (according to valgrind) it was previously using `std::vector<>::reserve(unsigned long)` whereas it now uses `operator new(unsigned long)` just like Clang does. Possibly another issue to report upstream.
Clang 14 `2,481,264,505` -> `2,481,270,375`
GCC 12 `2,388,141,113` -> `2,359,483,453`
This patch does not replace the usage yet - that …

smallvector.h: bake `reserve()` into the non-boost `SmallVector` implementation

---

lib/templatesimplifier.cpp
lib/templatesimplifier.h

`TemplateSimplifier::TokenAndName` has a user-defined constructor so the implicit move constructor is deleted and `std::move()` will copy this instead. See https://github.com/llvm/llvm-project/issues/57266 and https://trac.cppcheck.net/ticket/11274.

implemented move constructor for `TemplateSimplifier::TokenAndName`

---

tools/donate-cpu.py
tools/donate_cpu_lib.py

This allows both to build binaries and run the analysis successfully. Obviously they are not fully supported yet so I added a check which prevents uploads from happening for now.
A small assortments of TODOs (I will possibly file tickets for some of them):
- handling of crashes/asserts/signals - https://trac.cppcheck.net/ticket/11255
- stack trace generation
- proper `NDEBUG` configuration - https://trac.cppcheck.net/ticket/10736
- exitcode handling
- handling of timeouts - https://trac.cppcheck.net/ticket/1124
- process termination
- process vs. thread usage in binary
- proper coexistence of multiple build systems/compiler on same machine
- possible `clang`, `clang-cl` support - https://trac.cppcheck.net/ticket/10542
- newly added source TODOs
`mingw32-make`
```
cppcheck-options: …
```

donate-cpu: added support for `mingw32-make` and improved support for `msbuild.exe`

---

lib/checkclass.cpp
lib/checktype.cpp
lib/clangimport.cpp
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/valueflow.cpp

This avoids the expensive C++-specific `Library::detect*()` calls in `parsedecl()` for C code. See https://trac.cppcheck.net/ticket/10663 and https://trac.cppcheck.net/ticket/11104 for more details of the underlying issues.
There's possibly more parsing which could be disabled as well as passing the `isCpp` flag in all cases (see remaining amount of unnecessary calls below).
Scanning https://github.com/firewave/mame_regtest with `DISABLE_VALUEFLOW=1` and `--enable=all --inconclusive`:
Clang 13 `2,469,788,235` -> `2,147,720,747`
`   14,138,979 ( 0.66%)  /mnt/s/GitHub/cppcheck-fw/lib/library.cpp:Library::detectContainerOrIterator(Token const*, bool*) const [/mnt/s/GitHub/cppcheck-fw/cmake-build-relwithdebinfo-wsl-kali-clang-13/bin/cppcheck]`
GCC 12 `2,374,494,090` -> `2,094,093,681`
` …

refs #11104: do not do C++ processing for C code in `parsedecl()`

---

lib/astutils.cpp

These were spotted by just reviewing some of the code.
I didn't touch the order of matches with lighter checks when `&&` is involved since it implies `nullptr` checks and improves readability. If we encounter this in a hot path we can adjust those.
Performing a `--enable=all --inconclusive` scan on `mame_regtest`.
With `DISABLE_VALUEFLOW=1`:
GCC 12 `2,391,227,591` -> `2,368,284,558`
Clang 14 `2,484,649,991` -> `2,460,817,593`
With Valueflow enabled:
GCC 12 `55,716,578,653` -> `55,693,545,730`
Clang 14 `51,927,946,590` -> `51,907,086,379`
And scanning `cli` with `--enable=all --inconclusive -Ilib -D __GNUC__` and `DISABLE_VALUEFLOW=1`
GCC 12 `3,390,595,958` -> `3,372,663,114`
Clang 14 `3,352,177,977` -> `3,335,028,847`
Scanning `cli` with Valueflow is unfortunately too slow even outside of …

astutils.cpp: some small optimizations

---

.github/workflows/asan.yml
.github/workflows/clang-tidy.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

http://apt.llvm.org provides the latest stable and nightly packages - so we can also use the latest stable one immediately instead of waiting for a distro to pick it up. This also gets rid of the need for docker to have a recent distro which provides the latest version. It might also speed up the build a bit since less dependencies need to be installed.
Since the resulting binaries are only used in the CI and not in production it should not cause any problems that we might use bleeding-edge stable builds.
The current version is already available in the images and the base repo but they are being updated with the ones from the other repo:
```
Unpacking clang-14 (1:14.0.6~++20220816122211+f28c006a5895-1~exp1~20220816122246.108) over (1:14.0.0-1ubuntu1) ...
...
Unpacking clang-tidy-14 …
```

install latest clang from `apt.llvm.org` repo

---

.github/workflows/asan.yml
.github/workflows/clang-tidy.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

This requires #4355 and #4372 to be merged first.
Clang 15 has not been released yet but this is stable enough for the things we do - it is planned for September 6: https://discourse.llvm.org/t/llvm-15-0-0-release-schedule/63495

updated CI to clang-15

---

.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

moved deprecated `ubuntu-18.04` from `CI-unixish.yml` to `CI-unixish-docker.yml`

---

.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml

```
+ ccache -s
cache directory                     /home/runner/work/cppcheck/cppcheck/.ccache
primary config                      /home/runner/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats updated                       Sat Aug 27 08:31:25 2022
stats zeroed                        Sat Aug 27 08:31:21 2022
cache hit (direct)                    [67](https://github.com/danmar/cppcheck/runs/8049138565?check_suite_focus=true#step:9:68)
cache hit (preprocessed)               1
cache miss                             1
cache hit rate                     98.55 %
called for link                        1
cleanups performed                     0
files in cache                       139
cache size                          60.7 MB
max cache size …
```

added initial usage of `ccache` in the CI

---

.github/workflows/codeql-analysis.yml

`Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/`

codeql-analysis.yml: updated actions to v2

---

cmake/compileroptions.cmake

Not all versions of clangs have this option.

Use safe compile option

---

htmlreport/check.sh

Two tests were using `test/cfg` as input which takes a minute to process which is almost the complete time the step consumes - so use the lighter `test/synthetic` instead. The actual input is irrelevant since we just verify the syntax of the output.

htmlreport/check.sh: use less heavy input for tests

---

.github/workflows/CI-unixish-docker.yml

This is in preparation of #4411 to be able to use `ccache` in more cases. It also allows for more builds in parallel and separates parts of the workflow which do not depend on each other. The same should be done for `CI-unixish.yml`.
The refactoring is horrible and introduces lots of redundant code in terms of setting up things but it appears there's no better way to do it. You cannot use a prerequisite job to set up those things since all the jobs start with a clean filesystem and you need to transfer all files between them which is obviously a problem if you installed packages. There's also "composite actions" (see https://stackoverflow.com/a/71570847/532627) but those seem to require external files which doesn't improve things either.

CI-unixish-docker.yml: perform make and CMake builds in parallel

---

.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml

More refactoring to enable more `ccache` usage later on.
`selfcheck` is being deferred until `build` is done so we know all the tests are successful. If we actually don't care about that we don't need to do that. In that case we could move it out of here into the selfcheck workflow.

CI-unixish.yml: split workflow into parallel jobs

---

.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/coverage.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/valgrind.yml

CMake builds currently don't work with it - possibly related to the matchcompiled files.
Windows support isn't straight-forward.
Macos I haven't looked into yet.
Support for custom compilers (i.e. clang) I haven't look into either.

use `ccache` for Linux gcc make CI builds

---

.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/format.yml
.github/workflows/selfcheck.yml

This currently only caches files which do not rely on precompiled headers. Apparently it can be configured to work with those.

use `ccache` for Linux gcc CMake CI builds

---

lib/astutils.cpp

`tok` is known to be non-null since we check it at the beginning in the function so we can perform a lighter check first.
Scanning `mame_regtest` with `--enable=all --inconclusive` and `DISABLE_VALUEFLOW=1` it reduces the amount of calls (not instructions!) of the match function by almost half:
`match51(Token const*)` - `1 130 084` -> `690 156`
Clang 14 `1,901,904,224` -> `1,901,377,920`

optimized `isSameConstantValue()` a bit

---

lib/astutils.cpp
lib/checkclass.cpp
lib/checkunusedfunctions.cpp
lib/clangimport.cpp
lib/cppcheck.cpp
lib/ctu.cpp
lib/errorlogger.cpp
lib/importproject.cpp
lib/infer.cpp
lib/preprocessor.cpp
lib/summaries.cpp
lib/suppressions.cpp
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/token.cpp
lib/tokenize.cpp
lib/tokenlist.cpp
lib/tokenlist.h
lib/valueflow.cpp

It turns out this did not introduce any regressions. I accidentally used different sources for comparing runs.
This is the last step before trying to apply the `misc-const-correctness` fixes.
Performing a `--enable=all --inconclusive` scan on `mame_regtest`.
With `DISABLE_VALUEFLOW=1`:
Clang 14 `1,901,388,751` -> `1,901,336,996`
GCC 12 `1,849,957,590` -> `1,849,623,077 `
With Valueflow enabled:
Clang 14 `50,988,014,175` -> `50,979,722,552`
GCC 12 `54,791,127,461` -> `54,791,108,211`
And scanning `cli` with `--enable=all --inconclusive -Ilib -D __GNUC__` and `DISABLE_VALUEFLOW=1`
Clang 14 `3,172,193,354` -> `3,170,450,670`
GCC 12 `3,216,157,495` -> `3,214,864,491`

avoid unnecessary copies with `push_back()` and `push_front()`

---

cli/cmdlineparser.cpp
cli/processexecutor.cpp
cli/threadexecutor.cpp
lib/check.cpp
lib/check.h
lib/cppcheck.cpp
lib/library.cpp
lib/preprocessor.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/tokenize.cpp
lib/valueflow.cpp

This is split from similar changes for `push_back()` as some of those caused sizable regressions which need to be investigated first :( This is another step in preparation of applying the `misc-const-correctness` clang-tidy-16 fixes.
The impact is neglectable but there are no regressions.
Performing a `--enable=all --inconclusive` scan on `mame_regtest`.
With `DISABLE_VALUEFLOW=1`:
GCC 12 `1,849,957,730` -> ` 1,849,441,950`
Clang 14 `1,901,388,783` -> `1,901,388,929`
With Valueflow enabled:
Clang 14 `50,981,418,024` -> `50,988,014,183`
GCC 12 `54,791,127,471` -> `54,794,443,556`
And scanning `cli` with `--enable=all --inconclusive -Ilib -D __GNUC__` and `DISABLE_VALUEFLOW=1`
GCC 12 `3,216,157,747` -> `3,215,371,284`
Clang 14 `3,178,610,619` -> `3,178,527,042`

avoid unnecessary copies with `emplace_back()`

---

addons/misra.py

I removed error throwing when misra rules text file is missing. If the file is present the rules text will be displayed, if not it will let the user know the file is missing. 
This improves the experience when [misra.json](https://github.com/dzid26/StepperServoCAN/blob/retropilot_S42B/firmware/misra.json) is distributed together with a project. 
Currently, in order not to break static analysis checker configuration (in my case realtime editor checker [flylint](https://marketplace.visualstudio.com/items?itemName=jbenden.c-cpp-flylint)), I need to provide [dummy ](https://github.com/dzid26/StepperServoCAN/blob/retropilot_S42B/firmware/misra_rules_set_cppcheck.txt)rules file (due to licensing). But that gets annoying for version control, when the file is replaced locally with proper rules …

Missing misra rule-text-file should still allow for the analysis

---

cli/processexecutor.h
cli/threadexecutor.h
gui/checkthread.h
gui/codeeditstylecontrols.h
gui/erroritem.h
gui/resultstree.h
gui/resultsview.h
gui/threadhandler.h
gui/threadresult.h
lib/check.h
lib/ctu.h
lib/errorlogger.h
lib/programmemory.h
lib/suppressions.h
lib/symboldatabase.h
lib/token.h
lib/tokenize.cpp
lib/tokenlist.h
test/testutils.h

Unfortunately we still cannot enable the headers - see #5189 for more details.
The `modernize-pass-by-value` fixes possibly allow for more unnecessary copies to be eliminated but I was only able to review a part of the usage of those constructors.

mitigated some clang-tidy warnings in headers

---

lib/sourcelocation.h

Without the change build on upcoming gcc-13 fails as:
In file included from lib/symboldatabase.h:28,
from lib/astutils.h:36,
from test/testastutils.cpp:20:
lib/sourcelocation.h:52:10: error: 'uint_least32_t' in namespace 'std' does not name a type
52 |     std::uint_least32_t m_line = 0;
|          ^~~~~~~~~~~~~~

lib/sourcelocation.h: add missing <cstdint> include

---

.github/workflows/coverage.yml

`v1` has been deprecated and is considered "no longer function[ing]" since February - see https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1

coverage.yml: updated `codecov/codecov-action` to `v3`

---

lib/valueptr.h

A shared_ptr object does not have .release() member function, therefore .reset() should be used instead. More information on [https://en.cppreference.com/w/cpp/memory/shared_ptr](url).
We encountered the following error message when inspecting this file:
```
"c:\cppcheck-after\lib\valueptr.h", line 57: error: class "std::shared_ptr<Analyzer>" has no member "release"
return mPtr.release();
^
detected during instantiation of "ValuePtr<T>::pointer ValuePtr<T>::release() [with T=Analyzer]" 
```

Fix the release function in the ValuePtr class

---

cfg/std.cfg

As we discussed in #4495 with @chrchr-github, re-implemented it cfg file

std.cfg std exception types added to unusedvars section

---

lib/cppcheck.cpp

`mAnalyzerInformation` is only used in `CppCheck::checkFile()` if `!mSettings.buildDir.empty()`.
`mFileInfo` is only used in `CppCheck::analyseWholeProgram()` which is only called in `CppCheckExecutor::check_internal()` when `settings.jobs == 1`.
This obviously needs be to be gated away more clearly.

cppcheck.cpp: only call `getFileInfo()` if necessary

---

lib/checkleakautovar.cpp
lib/preprocessor.cpp
lib/utils.h
tools/dmake.cpp

Scanning `mame_regtest` with `--enable=all --inconclusive` and `DISABLE_VALUEFLOW=1`:`
Clang 14 `1,901,904,224` -> `1,899,570,897` -> `1,899,550,337`

replaced `static const`/fixed `std::vector` containers with `std::array`

---

.github/workflows/selfcheck.yml

Using the `unusedFunction` self-check for profiling gives us a very basic case which involves the core functionality without the valueflow or most of the checks which should be a pretty good canary for speed improvements/regressions. Although the Ir does not translate directly into actual real time speed it would affects other jobs like the sanitized builds and would give an indication if it has any impact at all.

selfcheck.yml: added `callgrind` step for basic (core) performance tracking

---

.github/workflows/asan.yml
.github/workflows/valgrind.yml

The valgrind workflow no longer experiences the package installation issues.
ASAN should have never been disabled. It being killed actually indicates excessive memory/CPU usage (this is what we experience as `-9` crashes in daca).
Edit: Turns out ASAN is way too slow to be enabled. It actually got much slower. It was once at around 20 minutes and the last time I checked it was 40 minutes but now we broke the one hour barrier. (I think we introduced another 10% Ir regression recently).

re-enabled valgrind in CI

---

lib/checkclass.cpp
lib/clangimport.cpp
lib/importproject.cpp
lib/templatesimplifier.cpp
test/testfilelister.cpp

Since C++11 the `erase()` call returns the new iterator.

modernized `erase()` calls

---

.github/workflows/valgrind.yml

```
W: GPG error: http://ddebs.ubuntu.com jammy-updates Release: The following signatures were invalid: BADSIG C8CAB6595FDFF622 Ubuntu Debug Symbol Archive Automatic Signing Key (2016) <ubuntu-archive@lists.ubuntu.com>
E: The repository 'http://ddebs.ubuntu.com jammy-updates Release' is not signed.
```

fixed `valgrind` workflow

---

.github/workflows/selfcheck.yml
lib/cppcheck.cpp

This is to avoid unnecessary checks being performed as well as speeding up things. See https://trac.cppcheck.net/ticket/10648 and https://trac.cppcheck.net/ticket/10727.

added environment variable `UNUSEDFUNCTION_ONLY` to make sure only the `unusedFunction` check is being executed

---

.github/workflows/selfcheck.yml

I still wanted to remove this from #4362 but it suddenly got merged.
This re-enables all the core checks (i.e. the ones you cannot disable at all) and it makes sense to track the performance of those. Since it doesn't affect the runtime of the CI step that much you are able to do this. I also already have an optimization for one of those checks lined up.
This increases the Ir from `77,388,361,498` to `81,935,225,940` though.

selfcheck.yml: re-enable core checks in `callgrind` step

---

lib/checkother.cpp
test/testother.cpp

Reduces Ir when scanning `cli` with `DISABLE_VALUEFLOW=1` and `--enable=all --inconclusive` from `2,063,423,080` to `2,022,871,311`. Not reflected in the CI since this check is not enabled by default.

optimized `CheckOther::checkDuplicateBranch()` a bit

---

lib/checkmemoryleak.cpp
lib/symboldatabase.cpp
lib/tokenlist.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp

All code after certain defaulted or deleted functions was skipped altogether, because in `SymbolDatabase::addNewFunction` it ended up setting `*tok = nullptr`, effectively skipping to the end.
Case 1:
```cpp
struct S { ~S(); };
S::~S() = default;
void g() {
int j; ++j; // no warnings were shown on uninitialized values
}
```
Case 2:
```cpp
std::string f() = delete;
void g() {
int j; ++j; // no warnings were shown on uninitialized values
}
```
Case 1 is an out-of-line defaulted destructor, which should behave similar to an out-of-line constructor.
Case 2 needed a scoped return type to fail. First, during tokenization, treat a deleted function similar to regular functions (skipping the function call from the AST). Then during the symboldatabase phase, make sure the token and scope continue …

Fix defaulted and deleted functions

---

cfg/mfc.cfg

More MFC macros
These MFC macros are commonly used in C++ windows MFC code.
You can see the definition of this macros with below URLs:
https://learn.microsoft.com/en-us/cpp/mfc/reference/run-time-object-model-services?view=msvc-170
https://learn.microsoft.com/en-us/cpp/mfc/reference/event-sink-maps?view=msvc-170
Best regards

Update mfc.cfg with more MFC macros

---

lib/tokenize.cpp
test/testtokenize.cpp

The following example gave an internal error
```cpp
using namespace std;
//template<std::same_as<int> T> // <= works
template<same_as<int> T>        // <= didn't work
void f()
{}
```
The line I modified, used to match to `< same_as <`, and therefore skip creating links. The `%op% %name% <` already feels a bit like a workaround. So adding the condition that `$op$` shouldn't be `<` (so not a comparison operator, but part of the template), seemed reasonable to me

Fix #11319 - Internal error on constrained template (concept) with multiple type parameters

---

lib/checkclass.cpp
lib/checkclass.h
test/testconstructors.cpp

For check operatorEqVarError (members variables missing in an `operator=`), I cppcheck bails out when a member function without a body is encountered, reasoning that that function _might_ initialize some/all member variables.
However, I feel it bails out a bit too soon: 
- when such a function is `const` or `static`, it will probably not initialize member variables (although member variables could be `mutable` and thus be initialized in a `const` function; and a static function could be passed `*this` to initialize members, although this latter case isn't any different than calling any free function, in which case currently cppcheck doesn't bail out).
- when `operator=` of a base class is called, I think it is fair to say the base class will initialize its own members (and of its …

Fix couple issues with missing operatorEqVarError

---

lib/tokenlist.cpp
test/testtokenize.cpp

Exception is thrown since 6a01fa9b (my own commit).
I found the issue by looking into http://cppcheck1.osuosl.org:8000/diff-internalAstError, checking a few cases there.
Example case where it failed: https://github.com/google/googletest/blob/main/googletest/test/gtest_main_unittest.cc
Possibly fixes some more cases

Fix internal error "Unexpected tokens in initializer" with anonymous namespace

---

lib/checkother.cpp
test/testother.cpp

Thanks for fixing 11383 so quick (#4581)!
However, when I ran the fix on my code base, the issue was still there, due to multiple captures in the lambda (which resulted in multiple `,`-ast-parents between `=` and `[`).
This PR fixes that

Improve fix for #11383 FP selfAssignment: lambda capture

---

tools/donate-cpu-server.py
tools/donate-cpu.py
tools/donate_cpu_lib.py

This stores the list of packages which do not contain any files to process on the server so we don't keep handing them out.

fix #10159 - donate-cpu: collect and avoid packages with no files to process

---

.github/workflows/CI-unixish.yml
Makefile
tools/dmake.cpp

`pcre` suddenly disappeared from the `macos-*` runner images so install it manually.

fixed macos build by manually installing `pcre`

---

.github/workflows/CI-cygwin.yml

```
Starting cygwin install, version 2.924
mbox : Cygwin is not supported on 32-bit Windows
```
It is a bit strange though since the support is being removed in 3.4.0 which has not yet been released. No idea which version it tries to install. It also doesn't seem to apply to all runners yet since some builds still succeeded.

CI-cygwin.yml: removed `x86` since it is no longer supported

---

lib/checkleakautovar.cpp
test/cfg/posix.c

I ran 273 packages with `test-my-pr.py` with no differences (but if I run it on the package in trac ticket 11873 the doublefree warning is gone).

Fix 11396, doublefree on munmap in if-statement

---

lib/checknullpointer.cpp
test/testnullpointer.cpp

Fix FP with nullpointer dereference in `alignof`. `alignof` is a compile time operator which only looks at the type of the variable (and therefore does not cause a nullpointer dereference, similar to `sizeof`).
To do this, unify the check for these types of operators in the various nullpointer checks. Then add `alignof`, the c version `_Alignof` and various compiler versions of it. Note that the report in #11401 is about the gcc extension `__alignof__`.

Fix #11401 nullpointer dereference with alignof

---

tools/donate-cpu.py
tools/donate_cpu_lib.py

This avoids invoking the build for `main` when no changes were detected. The impact is low for `make` on Linux but on Windows with Visual Studio it has a bigger impact.
Below are some performance values. I bailed out before any of the analysis steps were started. I used WSL Kali Linux.
`hyperfine 'python3 donate-cpu.py -j6 --no-upload --package=ftp://ftp.de.debian.org/debian/pool/main/a/adns/adns_1.6.0.orig.tar.gz'`
When avoiding a build when there are no changes:
```
Benchmark 1: python3 donate-cpu.py -j6 --no-upload --package=ftp://ftp.de.debian.org/debian/pool/main/a/adns/adns_1.6.0.orig.tar.gz
Time (mean ± σ):      2.557 s ±  0.375 s    [User: 0.409 s, System: 1.023 s]
Range (min … max):    2.239 s …  3.505 s    10 runs
```
Still invoking a build with the `git rev-parse` calls intact: …

donate-cpu: avoid unnecessary build invocation for `main`

---

test/cfg/runtests.sh

Sometimes I find myself wanting to run the cfg-tests on a specific file (since running all of them takes time and it might be hard to spot a specific error message among all the output).
Refactor `runtests.sh` to accept optional arguments to make it possible to check just a few files without having to do local hacks. With these changes, you can run `runtests.sh bsd.c std.c` to just check those two files. The behavior of `make checkcfg` is unchanged.

Refactor runtests to allow to specify files on command line

---

externals/simplecpp/simplecpp.cpp
externals/simplecpp/simplecpp.h

Scanning `mame_regtest` with `DISABLE_VALUEFLOW=1` and `--enable=all --inconclusive`
Clang 14 `2,015,012,279` -> `2,012,304,007`
GCC 12 `1,919,686,733` -> `1,916,926,979`
Scanning `cli/filelister.cpp` with `DISABLE_VALUEFLOW=1` and `--enable=all --inconclusive -Ilib -D__GNUC__`
Clang 14 `88,461,658` -> `87,596,261`
GCC 12 `87,505,725` -> `86,581,855`

bump simplecpp

---

cli/filelister.cpp
lib/errorlogger.cpp
lib/errorlogger.h
lib/preprocessor.cpp
lib/suppressions.cpp
lib/suppressions.h
lib/utils.cpp
test/testerrorlogger.cpp

When analyzing [ruby-lapack](http://cppcheck1.osuosl.org:8000/ruby-lapack) it will rarely use all the available processes because the files are being analyzed very fast and produce a lot of output which requires parsing thus preventing from new processes being spawned fast enough.
I came across this quite a while ago but didn't have an actual case to test it with.
This improves things but there's more to be optimized. Will go into some less straight forward things in other PRs as well as tickets.

optimized deserializing of `ErrorMessage` and related main process code

---

tools/test-my-pr.py

It makes no sense to specify both arguments at the same time.

test-my-pr, mark --c-only and --cpp-only mutually exclusive

---

Makefile
tools/dmake.cpp

For some reason which I have not figured out yet `dmake` got much slower. Since it is a fixed dependency in CMake builds it slows things down quite a bit. These changes greatly improve the run-time of it without changing the output.
We still show figure out when it got slow to fix the actual root cause.
Before:
```
Benchmark 1: ./dmake
Time (mean ± σ):     12.244 s ±  0.727 s    [User: 0.571 s, System: 11.501 s]
Range (min … max):   11.643 s … 13.440 s    5 runs
```
After:
```
Benchmark 1: ./dmake
Time (mean ± σ):      1.081 s ±  0.101 s    [User: 0.162 s, System: 0.911 s]
Range (min … max):    0.989 s …  1.251 s    5 runs
```
This was tested using GCC 12 on WSL1 Kali Linux.

greatly sped up `dmake`

---

lib/symboldatabase.cpp
lib/symboldatabase.h
test/testsymboldatabase.cpp

Got a syntax error on the following use case:
```cpp
void f() {
using customComparator = decltype([] (const X& lhs, const X& rhs) { return lhs.CompareTo(rhs); });
std::map<X, int, customComparator> m;
}
```
The issue being that the semicolon _inside_ the lambda was matched as the end of the `using`-statement, instead of the semicolon at the end of the line
This PR fixes this case

Fix syntaxError on lambda inside decltype

---

lib/utils.cpp
lib/valueflow.cpp

Found while looking into the fixes for the upcoming `performance-unnecessary-copy-on-last-use` clang-tidy check.

avoid some unnecessary copies

---

tools/donate-cpu.py
tools/donate_cpu_lib.py

This occurred if you cancelled the script while the `main` compilation was performed. If you start the script again and no changes were done in-between it would have used the old binary until the next changes occur.

donate-cpu: fixed resume of interrupted `main` branch compilation

---

gui/resultsview.cpp
gui/statsdialog.cpp
lib/checkbufferoverrun.cpp
lib/checkclass.cpp
lib/checknullpointer.cpp
lib/checkuninitvar.cpp

This were found during manual code review of `misc-const-correctness` warnings.

add/preserve `const` in `dynamic_cast`

---

tools/donate-cpu-server.py

I made a mistake in the calculation when `time_base` is `0.0` which leads to faulty entries this in the "improved" time report:
```
Package                                  Date             Time        2.9       Head     Factor
proftpd-mod-autohost                     2022-12-25      53859        0.0        0.1       0.10
```
This also causes these entries to be missing from the "regressed" report.
Treating a change from `0.0` to `0.1` as an increase in 100% (as `0.1` is the lowest possible value) that should result in an factor of `2.0` (`0.0` being the initial 100% with additional one added on top).
`0.0 0.1 2.00` - additional 100% with a total of 200%
`0.0 0.2 3.00` - additional 200% with a total of 300%
`0.0 0.4 5.00` - additional 400% with a total of 500%
In comparison with a …

donate-cpu-server.py: fixed factor calculation when base time is 0.0

---

cmake/compilerDefinitions.cmake

I followed the documentation from https://libcxx.llvm.org/DesignDocs/DebugMode.html#using-the-debug-mode which refers to `LIBCXX_ENABLE_DEBUG_MODE`. But that is a CMake define you are supposed to pass when building `libc++`. Also the debug mode needs the library to be built with it which is not something we do. So as suggested we should enable the assertions via `_LIBCPP_ENABLE_ASSERTIONS=1` instead - see https://libcxx.llvm.org/UsingLibcxx.html#assertions-mode.

compilerDefinitions.cmake: specify proper define for "safe libc++"

---

.github/workflows/CI-unixish.yml
cfg/qt.cfg
test/cfg/qt.cpp
test/cfg/runtests.sh

Not sure why `#include <QTest>` is not found.

Improve qt.cfg: unreadVariable for macro parameter

---

.github/workflows/valgrind.yml

This will fetch all the necessary debuginfo and will also avoid CI failures caused by invalid keys used for the ddebs packages:
```
W: GPG error: http://ddebs.ubuntu.com/ jammy-proposed Release: The following signatures were invalid: BADSIG C8CAB6595FDFF622 Ubuntu Debug Symbol Archive Automatic Signing Key (2016) <ubuntu-archive@lists.ubuntu.com>
E: The repository 'http://ddebs.ubuntu.com/ jammy-proposed Release' is not signed.
```

valgrind.yml: use `debuginfod-find` instead of manually installing debug symbols

---

lib/checkunusedfunctions.cpp
test/testunusedfunctions.cpp

The issue with the undefined order of the error messages could also be avoid by splitting the test into two.

Fix #11486 FN unusedFunction when enum value with same name exists

---

tools/donate-cpu-server.py

The intention of the package list was to be able to re-run a certain amount of packages to get an easy feedback if the issues were resolved. Including version-only crashes is not useful since we cannot affect those results.

donate-cpu-server.py: only include packages which crash on head in the crash report package list

---

Makefile
cli/cmdlineparser.cpp
lib/settings.cpp
lib/settings.h
man/cppcheck.1.xml
releasenotes.txt
test/testcmdlineparser.cpp
test/testrunner.vcxproj
test/testsettings.cpp

I excluded `error` and added special handling for it since it is always enabled and cannot be controlled via the command-line options.
This allows `style` to be actually being used on its own by specifying `--enable=style --disable=warning,performance,portability`.
As the options are being processed from left to right it would also allow to do some tuning in case you have a hard-coded command-line (i.e. in the CLion plugin).
I will deprecated the implicit enabling of the other checks in another PR.

added command-line option `--disable=<id>` to disable individual checks

---

CMakeLists.txt
cli/CMakeLists.txt
cli/cmdlineparser.cpp
lib/platform.cpp
lib/platform.h
test/CMakeLists.txt
test/testcmdlineparser.cpp

Extracted from #4325.
This is the first step in getting rid of hard-coded platforms and should have no effect at all beside making it consistent (and uncovering issues).

fixed `platforms` lookup / set proper platform type for `unix32-unsigned` and `unix64-unsigned` / copy `platforms` in CMake

---

lib/tokenlist.cpp
test/testtokenize.cpp

From `gcc-riscv64-unknown-elf-8.3.0.2019.08+dfsg/gcc/testsuite/g++.dg/cpp0x/auto16.C`

Fix crash in iscpp11init_impl()

---

cli/cmdlineparser.cpp
cli/cmdlineparser.h
releasenotes.txt
test/cli/test-helloworld.py
test/testcmdlineparser.cpp
test/testplatform.cpp

This is not documented or easily visible. It is also causing determinism issue when trying to reproduce results across platforms (I encountered this various times).
The awkward added code and tests is only temporary until this can be removed.

deprecate non-`native` platform being used by default in Windows builds

---

tools/donate-cpu.py
tools/donate_cpu_lib.py

Make `test-my-pr.py` a little more robust by retrying if `get_package()` or `get_package_count()` fails. For `get_package()`, this meant moving the retry-logic already present in `donate-cpu` to the library (this fixes trac ticket [#11045](https://trac.cppcheck.net/ticket/11405)). For `get_package_count()`, which is only used in `test-my-pr`, this meant adding the retry-logic to the function.

test-my-pr robustification

---

cfg/std.cfg
test/cfg/runtests.sh
test/cfg/std.cpp
test/testautovariables.cpp

Basic information about std::span type, I was not sure how to approach its std::dynamic_extent so I omitted it

Added cfg information about std::span

---

lib/checkexceptionsafety.cpp
lib/checkexceptionsafety.h

Those were the only global ones.

CheckExceptionSafety: moved `CWE` objects into source file

---

Makefile
lib/preprocessor.cpp
lib/settings.cpp
lib/settings.h
test/helpers.cpp
test/helpers.h
test/testpreprocessor.cpp
test/testrunner.vcxproj

This is necessary for the missing include tests to work.
This is not working properly if Cppcheck is being used to scan multiple projects within the same execution (e.g. when using it as a library).
This requires https://github.com/danmar/simplecpp/pull/282 and https://github.com/danmar/simplecpp/pull/287 merged first.

improved testing of missing includes / made it possible to clear the include cache in simplecpp

---

cfg/gnu.cfg

See https://www.gnu.org/software/gnulib/manual/html_node/c_002dstrcasestr.html to verify

gnu.cfg: strcasestr wrong return type

---

lib/astutils.cpp
lib/checkunusedvar.cpp
lib/clangimport.cpp
lib/templatesimplifier.cpp
lib/token.cpp
lib/token.h
lib/tokenize.cpp
lib/tokenlist.cpp
lib/valueflow.cpp

Token: do not return non-`const` pointer from `const` methods - part 1

---

lib/platform.h
test/fixture.h
test/testcharvar.cpp
test/testclangimport.cpp
test/testcondition.cpp
test/testfilelister.cpp
test/testio.cpp
test/testother.cpp
test/testplatform.cpp
test/testpreprocessor.cpp
test/testsimplifytemplate.cpp
test/testsimplifytokens.cpp
test/testsimplifytypedef.cpp
test/testsimplifyusing.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp
test/testtype.cpp
test/testunusedfunctions.cpp
test/testunusedprivfunc.cpp
test/testvalueflow.cpp
test/testvarid.cpp

Another step in the endless journey to get rid of hard-coded platform stuff.

improved setting of platform in tests / also improved platform tests

---

cfg/std.cfg
test/cfg/std.cpp

Easy fixes for `--check-library` warnings from our selfcheck - see https://trac.cppcheck.net/ticket/11313#comment:12:
`std::unordered_set::emplace()`
`std::unordered_set::insert()`
`std::unordered_map::insert()`
`std::multimap::count()`
`std::unordered_map::count()`

std.cfg: added support for more container methods

---

lib/cppcheck.cpp
test/cli/test-helloworld.py

This adds the process ID for the cppcheck process to the filenames of the .dump and .ctu-info files that the process generates.
So
lib/cppcheck.cpp.dump
becomes
lib/cppcheck.cpp.<PID>.dump
For example:
lib/cppcheck.cpp.2637871.dump
The reason for this change is that if there is a buildsystem which supports concurrency, multiple instances of cppcheck may be run for the same file.  For example, if the same file is compiled in multiple build variants, or for multiple targets.
If running the MISRA plugin over such a project with concurrency enabled in the buildsystem, the plugin ends up crashing as multiple jobs attempt to create/trample/delete the same files while other jobs are using them.
For more information see:
https://sourceforge.net/p/cppcheck/discussion/general/thread/02c757b4af/

dump: Fix concurrency problem with dump files

---

cmake/compileroptions.cmake

This fixes commit a586b9e8ee6a973da89383de75ecb1e3e5c0d0ff.

compileroptions.cmake: fixed workaround for Clang >= 14

---

lib/valueflow.cpp
test/testautovariables.cpp

My current understanding is that views are treated as references - there is an issue that for references each of them has its own lifetime but view always uses lifetime of container it is 'viewing'. Lifetime of variable is done by comparing end of scopes where function is declared at and where it is used. Since those are 2 separate functions and not lambda FP is observed

Fix FP#11508

---

lib/path.cpp
lib/path.h
lib/platform.cpp
lib/symboldatabase.cpp
lib/valueflow.cpp
test/testpath.cpp

I ran into issues because some functions returned the native separator and some didn't.

improved `Path` handling of mixed separators

---

lib/token.cpp

The calling function `multiCompare()` already explicitly checks that those characters are not present so we don't need to handle them in the switch.
It also seems to lead to better inlining and improve the performance by a few percent.

token.cpp: removed unreachable cases from `multiComparePercent()`

---

.gitignore

clangd currently uses .cache/clangd/index directory to store its files: https://reviews.llvm.org/D83099

Add ignoring of .cache directory

---

tools/triage_py/triage_version.py

Before the error messages did not include the ID requiring a manual lookup of it.

triage_version.py: extend template for 1.x versions with error ID

---

lib/symboldatabase.cpp
test/testsymboldatabase.cpp

`findFunction13()` did not compile, so I removed the offending lines.
We do not consider that
- conversion between float types is a better match than conversion from a float type to an integral type
- conversion from char* to void* is better than conversion from char* to bool
If this seemed to work before, it was due to a dependency on the order of the function declarations.

Fix #11531 FP constParameter with const/non-const overload / #8700 FP functionConst

---

Makefile
lib/cppcheck.vcxproj
lib/keywords.cpp
lib/keywords.h
lib/lib.pri
lib/tokenlist.cpp
lib/tokenlist.h

There are various hard-coded lists of these across the code. Some of them are even incomplete, contain non-keywords or attribute keywords to a standard they do not belong to.
This is in preparation so those instances can be incrementally be replaced with these proper global lists.

added clean C/C++ keyword lists and use them in `TokenList`

---

lib/keywords.cpp

This is really bad. I guess I accidentally deleted a line while updating the branch during the long time it was active.
I am very curious as to why not a single testcase failed though.

keywords.cpp: fixed accidental omissions in C++03 keywords / added missing keywords in latest standards

---

lib/analyzer.h
lib/ctu.h
lib/importproject.h
lib/infer.h
lib/valueflow.cpp

The remaining warnings will implicitly be fixed by #4791 and #4723.

fixed some `-Wdeprecated-copy-dtor` Clang compiler warnings

---

lib/checkclass.cpp
lib/checkmemoryleak.cpp
lib/settings.h
test/testautovariables.cpp
test/testbufferoverrun.cpp
test/testclass.cpp
test/testcondition.cpp
test/testconstructors.cpp
test/testerrorlogger.cpp
test/testfunctions.cpp
test/testio.cpp
test/testleakautovar.cpp
test/testlibrary.cpp
test/testmemleak.cpp
test/testother.cpp
test/testplatform.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp

I only aligned `Settings::library` and `Settings::libraries` where necessary. That will be improved in #4798.

improved library loading in tests

---

lib/token.cpp
lib/valueflow.cpp

Recognized this while profiling our tests. Did not fix all potential occurrences as some code blocks are way too big to verify it by review. Some control flow adjustments would make that easier but there's for later. An upcoming clang-tidy check will also detect these more savely.

ValueFlow: avoid unnecessary `Value` copies

---

lib/preprocessor.cpp
lib/preprocessor.h
test/testpreprocessor.cpp

The finding can never be triggered `Preprocessor::validateCfg()` bails out when the define contains a `=` (e.g. `DEF_1=1`). 
I came across this as I was trying to write a unit test for this and failed to trigger this.
`cfg` is generated by calling `Preprocessor::createDUI()`. That calls `splitcfg(mSettings.userDefines, dui.defines, "1")` to generate that config but as the last parameter shows it will set a default value of `1` if it is not specified. So it is not possible to generate a configuration which contains defines without any values and `Preprocessor::validateCfg()` will not be able to report any warnings.
I assume the configuration string was changed at some point rending that validation void.

Preprocessor: removed unreachable `ConfigurationNotChecked` finding

---

lib/tokenlist.cpp
lib/tokenlist.h
lib/valueflow.cpp

It was only used in `valueflow.cpp` where we already have the `Settings` available so just use those instead. It might have returned `nullptr` (although not in the context where the ValueFlow is called) and was immediately dereferenced unchecked.
It is unlikely (as there only is one `Settings` object) but it might have also led to two different settings being used within the ValueFlow.

removed `TokenList::getSettings()` and replaced usage in ValueFlow with provided settings

---

cli/processexecutor.cpp
cli/threadexecutor.cpp
lib/cppcheck.cpp
lib/suppressions.cpp
lib/suppressions.h
test/helpers.h

There is no need to generate a `Suppressions::ErrorMessage` when no suppressions exist.

optimized suppression lookups a bit when no suppressions exist

---

Makefile
cli/cppcheckexecutor.cpp
cli/executor.cpp
cli/executor.h
cli/processexecutor.cpp
cli/threadexecutor.cpp
cli/threadexecutor.h
lib/timer.cpp
test/fixture.cpp
test/redirect.h
test/testprocessexecutor.cpp
test/testthreadexecutor.cpp

This is a step on the way to hopefully fixing the suppression issues when using multiple threads. It might also allow us to share more code between the thread and process implementations.

simplified `ThreadExecutor` class by moving some code out of it / fixed some thread safety issues

---

cli/cmdlineparser.cpp
man/cppcheck.1.xml

`for futher details` -> `for further details`

cli: correct typo in help message

---

cli/cmdlineparser.cpp
cli/cmdlineparser.h
cli/cppcheckexecutor.cpp
test/testcmdlineparser.cpp

This avoids unchecked pointer dereferences within the class.

made `CmdLineParser::mSettings` a reference

---

lib/templatesimplifier.cpp
lib/templatesimplifier.h
lib/tokenize.cpp

This avoids unchecked pointer dereferences within the class.

TemplateSimplifier: made `mTokenizer` and `mSettings` references

---

lib/forwardanalyzer.cpp
lib/forwardanalyzer.h
lib/reverseanalyzer.cpp
lib/reverseanalyzer.h
lib/valueflow.cpp

This avoids unchecked pointer dereferences within the class.

made `ForwardTraversal::mSettings` and `ReverseTraversal::mSettings` references / adjusted some calling code to use references as well

---

lib/astutils.cpp
test/testvalueflow.cpp

From `flang-20181226/flang-driver/test/Analysis/lifetime-extension.cpp`

Fix crash in isTemporary()

---

cli/threadexecutor.cpp

This moves all the logic from the actual thread implementation into `ThreadData` so it can be used by `ProcessExecutor` as well.

ThreadExecutor: refactoring in preparation of sharing code

---

cli/cmdlineparser.cpp

The `main` build is broken . This was bound to happen that there's a non-conflicting breakage with all those things I do in parallel.
@danmar Please refrain from merging any more PRs until this has been merged. I will be out for the evening so somebody else has to merge it through.

cmdlineparser.cpp: fixed compilation

---

lib/checkbufferoverrun.cpp
lib/checkother.cpp
lib/checkuninitvar.cpp
lib/errortypes.h
test/testbufferoverrun.cpp
test/testother.cpp
test/testuninitvar.cpp

Both were never really used and could not be enabled. 
`safe` did not seem to have any effect at all.
But `experimental` was essentially disabling code for more than 9 years. So I removed the checks and just disabled it straight away with adjusting the very few tests it affected.
For more details see:
https://trac.cppcheck.net/ticket/5586
22a5881beea1794de9a7056ae48e383ed2b2356b
https://trac.cppcheck.net/ticket/5076
9ce7efc6e4acc601bb07f7b0ef7ae8732fc8e33f

removed `experimental` and `safe` from `Certainty`

---

lib/symboldatabase.cpp

It seems we cannot trigger this warning in any test, since `setValueTypeInTokenList()` is only called with `reportDebugWarnings == true` by `simplifyTokens1()`.

Fix #10946 Debug warning: autoNoType with lambda

---

test/fixture.cpp
test/testnullpointer.cpp

Since the `TODO_ASSERT_*` macros are essentially xfail/xpass we also need to fail if those do not return the expected results.

testrunner: fail if `TODO_ASSERT_*` succeeds

---

readme.md

I rewrote this so I can link to it in the initial setup documentation of the CLion plugin. It also doesn't make scene to me to maintain such generic information in external repository.
I also filed https://trac.cppcheck.net/ticket/11641 about the state of the Snap package.
On a side note I think we should remove the Japanese `readmeja.md` as that is not maintained by us and is most very out-of-date.

readme.md: rewrote `Packages` section [skip ci]

---

cfg/qt.cfg
test/cfg/qt.cpp

cf https://codebrowser.dev/qt5/qtbase/src/corelib/global/qglobal.h.html#_M/Q_UNUSED

qt: fix Q_UNUSED macro defintion

---

readme.md

As discussed in https://github.com/danmar/cppcheck/pull/4854#issuecomment-1460658523.

readme.md: removed defunct (and unnecessary) GitHub Actions badge [skip ci]

---

tools/donate-cpu-server.py

The reports have broken "Time" columns:
```
Package                                  Date        Time    2.10    Head     Diff
openexr                                  2023-03-22 64437    1312    1691   -2+381
openfortivpn                             2023-03-22 27706      10      10
```
The stale report is currently broken:
```
File "/var/daca@home/donate-cpu-server.py", line 1024, in run
html = staleReport(self.resultPath)
File "/var/daca@home/donate-cpu-server.py", line 350, in staleReport
dt = dateTimeFromStr(datestr)
File "/var/daca@home/donate-cpu-server.py", line 72, in dateTimeFromStr
return datetime.datetime.strptime(datestr, '%Y-%m-%d %H:%M')
File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = …
```

donate-cpu-server.py: only use more precise timestamp for logging - will unbreak "Time" columns and stale report

---

lib/valueflow.cpp
test/testuninitvar.cpp
test/testvalueflow.cpp

Some test cases where the uninitialized variable is used in dead code have become a TODO. The test cases dont seem to be good examples of real-world code though. I think this can be addressed in a future PR.

ValueFlow: Improve the starting point for uninitialized variables to find more uninitialized usages after many conditionals

---

lib/checkunusedvar.cpp
test/testunusedvar.cpp

I think showing a warning for the code from #10684 is reasonable.

Fix #11577 FN unusedStructMember when casting address (regression, reverts #10684)

---

lib/checkother.cpp
releasenotes.txt
test/cfg/std.cpp
test/fixture.h

Since we warn for local variables as well as references and pointers using a different ID will help users globally suppress the warnings.

Update constVariable IDs for references and pointers

---

lib/templatesimplifier.cpp
tools/donate-cpu-server.py

Split so we can separately disable/track it from the other debug warnings.

split `templateInstantiation` from `debug` warnings

---

Makefile
cli/cli.vcxproj
cli/cppcheckexecutor.cpp
cli/cppcheckexecutor.h
cli/executor.cpp
cli/executor.h
cli/processexecutor.cpp
cli/singleexecutor.cpp
cli/singleexecutor.h
cli/threadexecutor.cpp
lib/checkunusedfunctions.cpp
lib/color.cpp
lib/color.h
lib/cppcheck.cpp
lib/cppcheck.h
lib/library.h
lib/settings.cpp
lib/settings.h
test/main.cpp
test/testprocessexecutor.cpp
test/testrunner.vcxproj
test/testsingleexecutor.cpp
test/testsuppressions.cpp
test/testthreadexecutor.cpp
tools/dmake.cpp

This will allow us to use shared more code between the three different executors as well as making them all behave the same in follow-up patches.

extracted single job execution into `SingleExecutor` / improved testing / do not unconditionally apply colors to output

---

Makefile
cli/cmdlineparser.cpp
cli/cppcheckexecutor.cpp
lib/color.cpp
lib/errorlogger.cpp
lib/errorlogger.h
lib/library.cpp
test/testcmdlineparser.cpp
test/testcolor.cpp
test/testerrorlogger.cpp
test/testrunner.vcxproj

The colors and special characters are fixed replacements which will be identical for each message so we can simply replace those once instead of doing it for each message.
We cannot re-use the new logic from `replace()` for the other fields as the generation of the map is slower than the repeated scanning of the string.

optimized template string substitutions a bit

---

addons/misra.py

When a .ctu-info file contains many macro definitions, the MISRA checks can take a long time (hours). 
In our case, we are using [libdivide](https://github.com/ridiculousfish/libdivide) which includes tens of thousands of machine generated macros.
The slow down is a result of the duplicate checks for `MisraTypedefInfo`, `MisraTagName `and `MisraMacro` values, implemented as nested loops in `analyse_ctu_info`. 
This PR replaces the nested loops with a temporary dictionary, keyed on the item name.

MISRA: Speed up analysis of .ctu_info files

---

.github/workflows/CI-windows.yml
gui/projectfile.cpp

Now that Qt 6.5 has been released there will be no more updates for 6.4 so no need to keep that in the CI.

CI-windows.yml: updated to Qt 6.5.0

---

addons/misra.py

The following rules will not be implemented for cppcheck premium:
1.4
10.1
10.2
10.3
10.4
10.5
10.6
10.7
10.8
The Misra amendment #3  rules are implemented in cppcheck premium.

Update script to not run few rules for cppcheckpremium

---

cli/cppcheckexecutor.cpp
cli/cppcheckexecutor.h
gui/newsuppressiondialog.cpp
lib/cppcheck.cpp
lib/cppcheck.h
test/testcppcheck.cpp

That function is basically just parsing the command-line options into the settings so no need for a `CppCheck` object yet. Also moved the object down to the actual usage.
Preparation for moving the `Settings` ownership out of `CppCheck` in #4964.

removed `CppCheck` dependency from `CppCheckExecutor::parseFromArgs()`

---

lib/tokenize.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp

when skipping a CPP attribute skipCPPOrAlignAttribute returns a token for the last ']'  in '[[xxxx]]'.  This works out well with iterators in loops, but wasn't accounted for when scanning ahead when multiple CPP attributes exist, e.g.
`[[noreturn]] [[gnu::format(printf, 1, 2)]] void fatal(const char*, ...);`
As a result the noreturn attribute above won't be set, e.g. in 2.10.3.
This seems worthy of a test case, but I haven't figured out how your tests work.

fix skipping of cpp attributes.

---

lib/cppcheck.cpp
lib/preprocessor.cpp
lib/preprocessor.h
test/cli/test-other.py
test/testclass.cpp
test/testcondition.cpp
test/testgarbage.cpp
test/testother.cpp
test/testpreprocessor.cpp
test/testtokenize.cpp
test/testunusedvar.cpp

`Preprocessor::missingInclude()` was implementing the suppression logic which already exists in the `ErrorLogger`. `TestPreProcessor::inline_suppression_for_missing_include()` was relying on this logic but it was not testing the actual production code but the simplified `Preprocessor::getcode()` which is a testing-only implementation. I added Python tests to test this instead.
On a side note - we have several simplified preprocessing implementations which are only used in tests and do not reflect what the actual production code is doing. We need to get rid of these or at least consolidate them.

Preprocessor: relaxed dependency on `Suppressions`

---

.github/workflows/CI-unixish.yml
democlient/democlient.cpp

This only adds the compilation of the single democlient source file to make sure it doesn't break.
I have a potentially upcoming change which would have omitted the democlient changes.

CI-unixish.yml: added step to compile democlient

---

Makefile
lib/preprocessor.cpp
lib/preprocessor.h
test/helpers.cpp
test/helpers.h
test/testpreprocessor.cpp
test/testtokenize.cpp

I couldn't wrap my head around it while trying to merge those functions. I also had some weird issue I could not resolve.
I also think the `Preprocessor`/`Settings` object in the tests should not be shared between all tests. I think it is not reset properly.

moved test-only `Preprocessor::getcode()` out of `lib`

---

lib/valueflow.cpp

Scanning `EGM9615.h` now takes less than 1 min.
This might affect code like
~~~
int f() {
const int a[1] = {};
//const int i[] = { 0, (3, 4), 0 }; // no warning at all
const int i[3] = { 0, (3, 4), 0 };
return a[i[1]];
}
~~~
but we already show an incorrect warning
~~~
bar.cpp:4:10: error: Array 'a[1]' accessed at index 3, which is out of bounds. [arrayIndexOutOfBounds]
return a[i[1]];
^
~~~
There's also a FN constStatement.
GCC and clang detect both:
https://godbolt.org/z/Pxann8T4s

Fix #11649 Hang in setTokenValue() on huge array

---

lib/symboldatabase.cpp

This gives a speedup of ~2x, but still scales as O(N^2).

Optimize createSymbolDatabaseExprIds()

---

lib/cppcheck.cpp

This was introduced in 9a102702cbf5d643dee70abc03e0af51008be8b8 and it doesn't really make sense IMO.
It will also be the last write usage of the settings after #4964 is done and allows us to make the settings const and eliminate a copy which is a minor hot spot when using `ThreadExecutor` and will enable us to use the shared Executor code in all cases without performance regressions.

CppCheck: removed changing of `debugwarnings` for non-accepted files

---

lib/checktype.cpp
lib/errorlogger.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp

I came across this by manually reviewing the surrounding code of the changes in #4665.

avoid some unnecessary code execution

---

tools/donate-cpu-server.py

The `information` messages are stored separately so they need to be processed separately. This could be merged into the regular reports later on. Also there is no diffs generated for those messages so I did not add that report.

donate-cpu-server.py: added support for basic `information` reports / some cleanups

---

cli/cppcheckexecutorsig.cpp
cli/processexecutor.cpp
gui/common.h
gui/mainwindow.cpp
gui/projectfile.h
gui/projectfiledialog.cpp
gui/resultstree.h
gui/translationhandler.cpp
lib/checkother.cpp
lib/checkstl.cpp
lib/checkuninitvar.h
lib/color.h
lib/cppcheck.h
lib/forwardanalyzer.cpp
lib/library.h
lib/preprocessor.h
lib/programmemory.h
lib/reverseanalyzer.cpp
lib/reverseanalyzer.h
lib/settings.h
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/token.cpp
lib/token.h
lib/tokenize.h
test/cfg/boost.cpp
test/helpers.h

I am open to keeping some things but I had these changes sitting in a branch for well over a year now and those things are still not used yet so it should be fair game to remove them.

fixed some CLion inspection warnings

---

lib/cppcheck.cpp
lib/cppcheck.h

This leverages the new interface introduced with https://github.com/danmar/simplecpp/pull/244 to avoid usage of C++ `std::ifstream` in favor of the C `FILE` I/O which has less overhead.
This is already used internally for include files opened via simplecpp and this also uses it for the actual input files.

parse files with `simplecpp` without providing a stream

---

cli/cppcheckexecutor.cpp
cli/cppcheckexecutor.h

No functional change is intended.
This is a preparation to make qml handling work again

Refactoring: Break out loadLibraries() function. 

---

test/fixture.cpp
test/fixture.h
test/testastutils.cpp
test/testbufferoverrun.cpp
test/testcharvar.cpp
test/testclangimport.cpp
test/testclass.cpp
test/testcondition.cpp
test/testconstructors.cpp
test/testfunctions.cpp
test/testgarbage.cpp
test/testio.cpp
test/testleakautovar.cpp
test/testother.cpp
test/testpreprocessor.cpp
test/testprocessexecutor.cpp
test/testsimplifytemplate.cpp
test/testsimplifytokens.cpp
test/testsimplifytypedef.cpp
test/testsimplifyusing.cpp
test/testsingleexecutor.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp
test/testtype.cpp
test/testuninitvar.cpp
test/testunusedfunctions.cpp
test/testunusedprivfunc.cpp
test/testunusedvar.cpp
test/testvalueflow.cpp
test/testvarid.cpp

TODOs will be fixed in a separate PR so the fixes don't get lost in all the refactoring.

testrunner: more `SettingsBuilder` usage and `const` cleanups

---

Makefile
test/fixture.cpp
test/fixture.h
test/testbufferoverrun.cpp
test/testclass.cpp
test/testconstructors.cpp
test/testexceptionsafety.cpp
test/testfunctions.cpp
test/testleakautovar.cpp
test/testlibrary.cpp
test/testother.cpp
test/testsymboldatabase.cpp
test/testuninitvar.cpp
test/testunusedfunctions.cpp
test/testunusedvar.cpp
test/testvalueflow.cpp
test/testvarid.cpp

I will look at deduplicating the check implementations and need to specify default parameters in later PR(s).
`Library::loadxmldata()` has not completely been moved as there are some cases which cannot be changed (yet).

testrunner: even more `SettingsBuilder` usage and `const` cleanups

---

lib/checkother.cpp

This rule seems to have been removed: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=88046335

Remove dead URL

---

readme.txt

The header file 'picojson.h' isn't found and compilation fails with g++12 on Ubuntu 22.04 if you don't specify:
-Iexternals/picojson

header file path required for picojson

---

lib/tokenize.cpp

Single character fix removing extra semi colon.

[nit] Fixed lib/tokenize.cpp:2815:2: warning: extra ‘;’ [-Wpedantic]

---

gui/mainwindow.cpp
lib/importproject.cpp
lib/importproject.h

Selection of VS configurations did not work. Instead, always the first Debug configuration was picked.
I added a method to ImportProject that allows to pass multiple configurations to be checked and called this method (instead of selectOneVsConfig) from MainWindow.

Fix #11727 Limit check to selected VS configurations does not work

---

lib/checkunusedfunctions.cpp
test/cli/proj-inline-suppress/template.cpp
test/cli/test-inline-suppress.py

There are no tests at all for `--cppcheck-build-dir`

#11733 FP unusedFunction with templates and --cppcheck-build-dir

---

lib/checkuninitvar.cpp
test/testuninitvar.cpp

Stop interpreting struct fields in designed initializers as usage of local variables which can happen if they share the same name.
```
$ cat test.c
struct a { int b; };
int main() {
char *b;
extern int foo(struct a *);
return foo(&(struct a){.b = 0});
}
$ cppcheck --quiet test.c
test.c:5:27: error: Uninitialized variable: b [legacyUninitvar]
return foo(&(struct a){.b = 0});
```

Fix uninitvar false positive in designed initializers

---

lib/checkunusedvar.cpp
test/testunusedvar.cpp

Using types declared with TAILQ_HEAD() from OpenBSD occasionally causes cppcheck to report unused struct members. This in turn is caused by the usage of queue. If one never access the first element through TAILQ_FIRST() for instance, tqh_first will be reported as being unused.
This is a bit annoying as the definition of the struct is beyond one's reach. Not sure this is the best way to do it but it gets problematic as the struct expanded by TAILQ_HEAD() could be named anything. I therefore ended up prefixing the suppressed fields with `::`.

Suppress unused struct members from types expanded from macros

---

lib/valueflow.cpp

`const std::array<unsigned char, 222236> a{{ 0x00, ... }};`
E.g. https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/system_archive/data/font_chinese_traditional.cpp
Init list with operators, e.g.
https://github.com/ClickHouse/ClickHouse/blob/master/contrib/consistent-hashing/popcount.cpp

Fix hang on huge array (followup to #11649)

---

cfg/qt.cfg
cfg/std.cfg
cfg/wxwidgets.cfg
lib/library.cpp
test/cfg/openssl.c
test/cfg/qt.cpp
test/cfg/std.cpp
test/testclass.cpp
test/testfunctions.cpp

We used to treat any nullary function as a library function.

Fix #9104 reopened Improve check: missing virtual destructor

---

gui/cppcheck_zh_TW.ts
gui/gui.pro
gui/translationhandler.cpp
win_installer/cppcheck.wxs

* Add gui/cppcheck_zh_TW.ts
* Add cppcheck_zh_TW.ts to gui/gui.pro
* Add 'Chinese (Traditional)' to gui/translationhandler.cpp
* Add cppcheck_zh_TW.qm to win_installer/cppcheck.wxs

GUI: Add zh_TW translation

---

cfg/std.cfg
test/cfg/std.cpp

This caused many `arithOperationsOnVoidPointer` false positives in my project which uses `std::vector<uint8_t>` in many places.

Fixed `std::vector::data` return type

---

cmake/compilerDefinitions.cmake
cmake/compileroptions.cmake
gui/CMakeLists.txt
readme.md
tools/triage/CMakeLists.txt

Use generator expressions rather than if statements when adding compiler options or definitions.
Side note: The CMake support seems outdated and may need rework - but probably by someone who knows CMake better than me...

Fix #11081 GUI: Windows release build crashes

---

cfg/std.cfg
lib/astutils.cpp
test/cfg/std.cpp
test/testclass.cpp

`get()` is actually const (https://en.cppreference.com/w/cpp/memory/unique_ptr/get), but that makes it hard to model ownership.

Don't suggest const for smartptr::get()

---

lib/checkleakautovar.cpp
test/testleakautovar.cpp

Introduced in commit 69116c838 ("Fix #11758 Regression: memleak / Fix #11746 FN: deallocuse (#5139)").

Fix FP deallocuse regression

---

lib/smallvector.h

#5015 seems to have stalled, but the fix is already being used downstream.
We should probably add gcc13 to our CI.

Add missing rebinding trait to TaggedAllocator (complete #5015)

---

.github/workflows/scriptcheck.yml

Python 2.7 is not supported anymore in github actions runners.
See:
https://github.com/actions/setup-python/issues/672

CI: python 2.7 tests needs to run in a container

---

cfg/std.cfg
test/testcondition.cpp

There is special handling for `size_t` in `ValueType::fromLibraryType()`, which gets preempted if it is also configured as a podtype.

Fix #11789 FP knownConditionTrueFalse with std::vector::size()

---

lib/checkcondition.cpp
test/testcondition.cpp

Usage of zero valued enum entries can be used for documenting purposes and should be ignored just like zeroes expanded from macros.

Ignore zero valued enum entries from badBitmaskCheck

---

cli/cmdlineparser.cpp
cli/cmdlineparser.h
lib/settings.h
test/testcmdlineparser.cpp

It's a time offset not a size. It should not have value SIZE_MAX that makes it ineffective (overflow in calculation of stop time).

Update type for Settings::checksMaxTime.

---

lib/checkclass.cpp
test/testclass.cpp

We should probably use `getDuplInheritedMemberFunctionsRecursive()` as part of the `duplInheritedMember` check.

Fix FP uselessOverride with shadowed member functions

---

lib/valueflow.cpp
test/teststl.cpp

We didn't warn for the TODO even before this change.

Fix #11828 False positive when getting a span via an out argument

---

cli/cmdlineparser.cpp

ususedFunction check is enabled if cppcheck build dir is used. Warning about disabled unusedFunction check should not be printed in such case.

unusedFunction disabled warning is not printed if --cppcheck-build-dir is used

---

lib/tokenlist.cpp

Added https://trac.cppcheck.net/ticket/11847 about the false negative.

tokenlist.cpp: fixed GCC `-Wunused-variable` warning

---

lib/checkclass.cpp

The goal is to use keywords like "converting constructor" and "implicit conversion" that will help users further study what this warning is about. I think that the old message provided no context to the uninitiated.

noExplicitConstructor - Verbose error message edit

---

.github/workflows/asan.yml
.github/workflows/clang-tidy.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

From https://github.com/llvm/llvm-project/issues/64182#issuecomment-1658085767

Workaround for CI failure

---

tools/donate-cpu.py
tools/donate_cpu_lib.py
tools/test_donate_cpu_lib.py

We were only matching each library once as the entry was removed from the container stored in the class as we did not modify a copy but a reference.

donate-cpu: fixed #11276 (donate-cpu: Improve library detection) / respect `--no-upload` in "nodata" uploads

---

test/CMakeLists.txt
test/helpers.h
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

I need to add parameters to some `check()` functions in the tests and things are already pretty messy with having to specify all the default values - readability aside.
I found this on https://stackoverflow.com/a/49572324/532627 - apparently the CC BY-SA license by StackOverflow allows the usage within GPL.

testrunner: use structs with designated initialization to pass options

---

cli/cmdlineparser.cpp
lib/path.cpp
lib/path.h
test/testcmdlineparser.cpp

Cppcheck does not report that cppcheck build dir does not exist and also does not report any write issues to the non-existent directory. 
This means that cppcheck build dir is actually not used.
We should either create the directory or fail.

Check if --cppcheck-build-dir exists

---

lib/checkclass.cpp

I think that context needs to be provided as to why it is an issue that a variable is not initialized.

Edit verbose warning message for uninitVarError

---

cli/cppcheckexecutor.cpp
cli/cppcheckexecutor.h

This starts to untangle the `ErrorLogger` implementation in `CppcheckExecutor` which handles three different cases and makes things unnecessarily complicated.

CppcheckExecutor: use dedicated ErrorLogger for printing error messages XML

---

test/helpers.h
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

This fixes the compile error introduced in 5d201c4.

testrunner: fix clang compile error related to `dinit`

---

gui/checkthread.h
gui/threadhandler.cpp

Seems current code for worker threads termination is too brutal which leads to crash on termination:
```
QThread::start: Thread termination error: No such process
Segmentation fault (core dumped)
```
Seems better to use `quit()` and `wait()`, like in an example:  https://doc.qt.io/qt-6/qthread.html#details
tested: Ubuntu Linux 20

Do not crash on GUI shutdown

---

lib/config.h
lib/settings.h
test/fixture.cpp
test/fixture.h
test/testbufferoverrun.cpp
test/testclass.cpp
test/testcondition.cpp
test/testexceptionsafety.cpp
test/testfunctions.cpp
test/testleakautovar.cpp
test/testprocessexecutor.cpp
test/testsimplifytemplate.cpp
test/testsimplifytokens.cpp
test/testsimplifytypedef.cpp
test/testsimplifyusing.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp
test/testvarid.cpp

The check for redundant settings cannot be enabled by default as we have cases where the values are configurable. It might be possible to clean up some of those and use immutable objects instead.

avoid some redundant and unused settings in tests among other cleanups / added and used `WARN_UNUSED` attribute

---

lib/checkcondition.cpp
test/testcondition.cpp

If one operand is another binary expression, recursively ensure that no nested operands are expanded macros.

Fix FP badBitmaskCheck in nested binary expressions

---

cli/processexecutor.cpp
lib/errorlogger.cpp

With `-D__GNUC__ --debug-warnings --template=daca2 --check-library -j2 ../test/testsymboldatabase.cpp` this reduces the IR needed for serializing/writing to a third (down from ~17,000). On the reading side there is not much of an improvement. But this will help a lot with daca as we are generating and processing millions of errors.

optimized pipe writing/reading and `ErrorMessage` serialization a bit

---

lib/checkuninitvar.cpp
lib/valueflow.cpp
test/testuninitvar.cpp

This also removes the termination checking in `valueFlowUninit` as this causes a lot of FNs.

Add special function to match lifetimes

---

cli/cmdlineparser.cpp
test/testcmdlineparser.cpp

In cppcheck 2.11.1 (macOS), using `-j 0` actually causes cppcheck to do nothing–it stalls indefinitely.
I could only find one place where `mSettings.jobs` was validated against > 0 and it's simply an assert, so you wouldn't hit it in a release build.
- Require -j >= 1 ✅
- Cap -j at 1024, not 10000 ✅ (I don't even know what would happen if you created 10,000 threads, but nothing good; likely exhaust virtual memory or grind the process to a halt). 1024 is still obscene but there may be some hypercomputers out there that have that many logical cores.

-j 0 causes indefinite hang. require >= 1

---

lib/library.cpp
lib/library.h

Scanning `cli/filelister.cpp` with `DISABLE_VALUEFLOW=1` and `--enable=all -Ilib -D__GNUC__`
Clang 15 `111,300,996` -> `106,883,955`
GCC 13 `110,555,879` -> `105,983,608`

optimized `Library::detectContainerInternal()` a bit

---

lib/astutils.cpp
lib/checkbufferoverrun.cpp
lib/checkclass.cpp
lib/checkcondition.cpp
lib/checkother.cpp
lib/checkstl.cpp
lib/cppcheck.cpp
lib/ctu.cpp
lib/errorlogger.cpp
lib/mathlib.cpp
lib/mathlib.h
lib/suppressions.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/token.cpp
lib/tokenize.cpp
lib/tokenlist.cpp
lib/valueflow.cpp
lib/vfvalue.cpp
test/testgarbage.cpp
test/testmathlib.cpp
test/testvarid.cpp

It was also used inconsistently and seemed to imply there is some special handling which wasn't the case. It was just an alias for `std::to_string()` for non-`double` types. So there was no need for it.

fixed #6316 (Use std::to_string() in place of MathLib::toString() ...) - deleted default implementation of `Mathlib::toString()`

---

cli/cmdlineparser.cpp
releasenotes.txt
test/testcmdlineparser.cpp

Both are bugprone since they just take the next parameter which doesn't start with `-`.
Also `--template` has not been documented since 17842394c00fd0288abfed509baad76aa3a5f2e9 back in 2011(!). And `--template-location` has never been documented since its induction in f058d9ad083a6111e9339b4b3506c5da7db579e0. That's also why we can have a short deprecation period.

CmdLineParser: deprecated `--template <template>` and `--template-location <template>`

---

lib/token.cpp
lib/token.h

Scanning `mame_regtest` with `DISABLE_VALUEFLOW=1` and `--enable=all --inconclusive`:
Clang 15 `1,170,770,173` -> `1,167,227,434`
GGC 12 `1,370,070,422` -> `1,366,775,852`

optimized `Token::Match()` a bit by always inlining `Token::multiCompare()`

---

lib/astutils.cpp
lib/astutils.h
lib/checkcondition.cpp
lib/checkcondition.h
lib/checkother.cpp
lib/checkother.h
lib/forwardanalyzer.cpp
lib/token.cpp
lib/token.h
lib/valueflow.cpp
releasenotes.txt
test/testastutils.cpp
test/testcondition.cpp
test/testother.cpp

This adds a new checker to check for pointer to bool conversions that are always known. I removed the previous knownConditionTrueFalse checks since this was too noisy.

Fix 11579: false negative: knownConditionTrueFalse with non-bool as bool parameter

---

gui/applicationlist.cpp
gui/checkstatistics.cpp
gui/codeeditstyledialog.cpp
gui/common.cpp
gui/helpdialog.cpp
gui/mainwindow.cpp
gui/resultstree.cpp
gui/resultsview.cpp
gui/settingsdialog.cpp

Regarding the "normalized signatures" see https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-not-normalized.md and https://doc.qt.io/qt-6/qmetaobject.html#normalizedSignature.

fixed some Clazy `level0` warnings

---

addons/misra.py
addons/test/misra/misra-test.c

https://trac.cppcheck.net/ticket/11878#ticket

Fix #11878 FP misra-c2012-18.7 on function pointer parameter with array-type args

---

addons/misra.py
addons/test/misra/misra-test-avr8.c
addons/test/misra/misra-test.c

I also changed the comment header to run tests on misra-test-avr8.c because I thought that was the intention to use it like misra-test.c; if not, I can revert.

Fix #11877 FP misra 10.4 On array member comparison

---

lib/symboldatabase.cpp
lib/valueflow.cpp
test/testclass.cpp

Or maybe we should just limit the recursion depth.

Fix #11886 performance regression (hang) in 2.12dev

---

cfg/std.cfg
test/testother.cpp

Commit 73251544a ("Fix #11842 FN constParameterPointer with library function (#5257)") most likely introduced a regression for (C) function pointers passed to functions provided by the standard library that cppcheck has knowledge about.

Fix constParameterPointer regression

---

cfg/qt.cfg
test/cfg/qt.cpp

Treat Q_PROPERTY as variadic macro to avoid preprocessorErrorDirective with associative container templates itroducing a "," like for example `QHash<QString, int>`. Using templates is totally fine in the context of a moc compiler.
The macro Q_PROPERTY is defined as variadic in qobjectdefs.h/qtmetaobject.h when not compiling using the moc compiler.
See following references:
* For Qt 5.15 https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobjectdefs.h?h=5.15#n104
* For Qt 6.6 https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qtmetamacros.h?h=6.6#n5

qt library: Make Q_PROPERTY a variadic macro to avoid preprocessorErrorDirective

---

lib/checkvaarg.cpp
lib/clangimport.cpp
lib/symboldatabase.cpp
lib/symboldatabase.h
test/testclangimport.cpp

Still ran into an assert failure in `Tokenizer::hasIfdef()`, since some checks assume that the tokenizer is always present. Seems like clangimport is yet another rogue under-tested feature...

Fix use-after-free crash when using --clang

---

.github/workflows/CI-unixish-docker.yml

Forgot to update this in #4992.

CI-unixish-docker.yml: use `ubuntu:23.04` in `build_make`

---

lib/matchcompiler.h

These do not show up in the CI since we only scan the non-matchcompiled code.

matchcompiler.h: fixed some clang-tidy warnings

---

addons/misra_9.py
addons/test/misra/crash_misra9_parseInitializer.c
addons/test/test-misra.py

This fixes a crash with following error:
```
File "/usr/local/share/Cppcheck/addons/runaddon.py", line 8, in <module>
runpy.run_path(addon, run_name='__main__')
File "<frozen runpy>", line 291, in run_path
File "<frozen runpy>", line 98, in _run_module_code
File "<frozen runpy>", line 88, in _run_code
File "/usr/local/share/Cppcheck/addons/misra.py", line 4737, in <module>
main()
File "/usr/local/share/Cppcheck/addons/misra.py", line 4679, in main
checker.parseDump(item)
File "/usr/local/share/Cppcheck/addons/misra.py", line 4335, in parseDump
self.executeCheck(902, self.misra_9_2, cfg)
File "/usr/local/share/Cppcheck/addons/misra.py", line 4246, in executeCheck
check_function(*args)
File "/usr/local/share/Cppcheck/addons/misra.py", line 2104, in …
```

fix crash while checking misra_9 when initializing a union with {{0,0}}

---

lib/cppcheck.cpp
lib/errorlogger.cpp
lib/symboldatabase.cpp
lib/token.cpp
lib/tokenize.cpp
lib/utils.h
test/testutils.cpp

Scanning the `cli` folder with `DISABLE_VALUEFLOW=1` `Tokenizer::dump()` will consume almost 25% of the total Ir count when an addon is specified. This is mainly caused by the usage of `std::ostream`.
Encountered while profiling #4958.

sped up `Tokenizer::dump()`

---

cli/cppcheckexecutor.cpp
lib/cppcheck.cpp
lib/errorlogger.cpp
lib/errorlogger.h
releasenotes.txt
test/cli/test-other.py
test/cli/testutils.py

Encountered while investigating https://trac.cppcheck.net/ticket/11708.
This has been like this since the introduction of `internalError` in b6bcdf29363a25112b8884fc9944237f1461402d (almost ten years ago to the day). Logging internal errors which bail out(!) of the analysis simply to `std::cout` for them possibly never to be seen (and also not affected the exitcode) is pretty bad IMO. They should always be visible.
I also removed the filename from the message as it is already available (and thus redundant) and its existence should be defined by the template.

report `internalError` when command execution returns errorcode / also some related cleanups and tests

---

Makefile
cli/cli.vcxproj.filters
cli/cppcheckexecutor.cpp
gui/checkstatistics.cpp
gui/checkstatistics.h
gui/mainwindow.cpp
gui/mainwindow.h
gui/resultsview.cpp
gui/resultsview.h
gui/statsdialog.cpp
gui/statsdialog.ui
lib/checkers.h
lib/checkersreport.cpp
lib/checkersreport.h
lib/cppcheck.cpp
lib/cppcheck.vcxproj
lib/cppcheck.vcxproj.filters
lib/errorlogger.cpp
lib/lib.pri
releasenotes.txt
test/testrunner.vcxproj.filters
tools/get_checkers.py

This primarily adds the corresponding report in the GUI that we have in the command line already

Fix #11897 (Safety: show what checks are enabled/disabled)

---

lib/symboldatabase.cpp
lib/token.cpp
lib/tokenize.cpp
lib/utils.h
test/testutils.cpp

The id string should just be a unique value. There is no need that this value is equal to the pointer. And there is no requirement to use the same hexadecimal output format as the ostringstream implementation. Therefore the code to generate the id can be simplified.

Refactor: The code to generate id string from pointer can be simplified

---

.github/workflows/CI-cygwin.yml
.github/workflows/CI-mingw.yml
.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/asan.yml
.github/workflows/buildman.yml
.github/workflows/clang-tidy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml
.github/workflows/valgrind.yml

This will prevent duplicated workflows from being invoked for pushes into pull requests made from branches in the root (`danmar`) repository branches.

avoid duplicated workflow invocations for pushes in PRs made from root repository branches

---

.github/workflows/CI-windows.yml

The Windows jobs are along the longer jobs to run (~14 minutes) by splitting these up we reduce the peak time to about half of that.

CI-windows.yml: perform debug and release builds in separate jobs

---

.github/workflows/CI-mingw.yml
lib/checkleakautovar.cpp
test/testleakautovar.cpp

This used to be one of the longest running jobs because of the slow setup and linking. Now it will take only ~2 minutes if everything is cached with half the time taken up by the tests.

CI-mingw.yml: use pre-installed MinGW / also use `lld` and `ccache` for faster builds

---

tools/donate-cpu-server.py
tools/donate_cpu_lib.py

This provides a report of the top incomplete variables reported by the ValueFlow analysis. This is based on the implementation of the existing `--check-library` reports.

fixed #11930 (Create daca report for `valueFlowBailoutIncompleteVar`)

---

Makefile
cli/cmdlineparser.cpp
gui/checkthread.cpp
lib/astutils.cpp
lib/checkleakautovar.cpp
lib/checkunusedvar.cpp
lib/clangimport.cpp
lib/cppcheck.cpp
lib/errorlogger.cpp
lib/importproject.cpp
lib/library.cpp
lib/path.cpp
lib/preprocessor.cpp
lib/suppressions.cpp
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/timer.cpp
lib/tokenize.cpp
lib/utils.h
lib/valueflow.cpp
test/cli/test-more-projects.py
test/testcmdlineparser.cpp
test/testsimplifyusing.cpp
test/testutils.cpp
tools/dmake.cpp

This makes the code much more readable. It also makes it less prone to errors because we do not need to specify the length of the string to match and the returnvalue is clear.
The code with the bad returnvalue check was never executed and I added a test to show that.

utils.h: added `startsWith()` and started using it

---

Makefile
lib/CMakeLists.txt
lib/cppcheck.vcxproj
lib/lib.pri
tools/dmake.cpp

This will mainly help if you only build the `cppcheck` targets and the more threads you utilize for compilation.

fixed #11925 (build slowest files first)

---

lib/checkassert.h
lib/checkautovariables.h
lib/checkbool.h
lib/checkboost.h
lib/checkbufferoverrun.h
lib/checkcondition.h
lib/checkexceptionsafety.h
lib/checkfunctions.h
lib/checkinternal.h
lib/checkleakautovar.h
lib/checknullpointer.h
lib/checkother.h
lib/checksizeof.h
lib/checkstl.h
lib/checkstring.h
lib/checktype.h
lib/checkunusedfunctions.h
lib/checkvaarg.h
test/fixture.h
test/testbufferoverrun.cpp
test/testclass.cpp
test/testio.cpp
test/testnullpointer.cpp
test/testuninitvar.cpp

We were calling several interface functions through their inherited classes instead of using the base classes requiring us to add `friend` declarations to make the implementations accessible. This adjusts several of those cases.

adjusted tests to reduce the amount of `friend` declarations necessary

---

cmake/findDependencies.cmake

I'm suggesting this patch from the conan recipe: https://github.com/conan-io/conan-center-index/blob/afcf3ba/recipes/cppcheck/all/patches/0003-pcre-debuglib-name.patch
I just added the latest version without applying it to see if it works: https://github.com/conan-io/conan-center-index/pull/19724

Consider pcre debug suffix for Windows

---

lib/symboldatabase.cpp

This is a warning we found during static analyis with CodeSecure CodeSonar.
It flagged a suspicious copy-paste error, where it finds code that seems to have been copied from another location, with some, but not all, variables substituted.
Unclear to me if this truly is a problem, or intentional, but I wanted to provide the feedback as I am not sure how to test this.
Lines 5614 to 5619 in lib/symboldatabase.cpp are a copy from 5597-5602 with vartok replaced by valuetok, except for line 5616

Fix copy-paste-error

---

lib/sourcelocation.h

Sometimes the compiler supports the intrinsic even if the C++ runtime doesnt yet.

Use intrinsics for source location if available

---

lib/importproject.cpp
test/testimportproject.cpp

Projects created with GUI contain project-name tag. The tag was not supported by cmd line importer,
which caused cppcheck to fail.
My use case was:
1. Create the project with GUI on Windows
2. Run cppcheck on multiple cores with _-j_ flag

Support importing projects with project-name

---

.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/scriptcheck.yml

`--strict` ensures e.g. all the markers are known and `-vv` provides more verbose output making it easier to see why a test failed.

added `--strict` and `-vv` to pytest calls

---

test/testfilelister.cpp

Not a proper fix yet but at least it prevents the hang and gives some feedback.

refs #11993 - error out in `TestFileLister::recursiveAddFiles()` instead of looping infinitely when repository root directory is not found

---

tools/donate-cpu-server.py

This also fixes the missing results for `;` and filters out outdated results.

donate-cpu-server.py: added `pkgs` query parameter to `check_library-*`, `incomplete_var-*` and `unknown_macro-*` reports

---

tools/donate-cpu-server.py

This broke with a late variable name cleanup I did in `check_library_report()` after testing it locally.

donate-cpu-server.py: fixed "top x" reports / some cleanups

---

Makefile
cli/cmdlinelogger.h
cli/cmdlineparser.cpp
cli/cmdlineparser.h
cli/cppcheckexecutor.cpp
test/testcmdlineparser.cpp

This is in preparation of avoiding accessing `std::cout` directly as well as streamlining and improving the logging during the settings parsing. There are no functional changes yet.

perform logging in `CmdLineParser` through an interface

---

lib/cppcheck.cpp

Scanning `common` from `xrdp` project with `DISABLE_VALUEFLOW=1` and `-D__GNUC__ --addon=misra`:
Clang 16 `627,748,337` -> `541,852,912`

CppCheck: avoid expensive `std::ostringstream` usage in `checkFile()`

---

cfg/gtk.cfg

These are annotated as `(transfer none)`.

gtk: add g_file_info_get_* exceptions

---

lib/checkcondition.cpp
lib/checkfunctions.cpp
lib/checkleakautovar.cpp
lib/checkother.cpp
lib/checkstring.cpp
lib/checkuninitvar.cpp
lib/clangimport.cpp
lib/library.cpp
lib/mathlib.cpp
lib/mathlib.h
lib/programmemory.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/tokenize.cpp
lib/valueflow.cpp
man/writing-rules-3.docbook
test/testmathlib.cpp

The name was misleading as it was actually a `long long` and also if we ever move to an (optional) 128-bit value it wouldn't even less fitting. We should name it to match our alias type.

MathLib: renamed `to{U}LongNumber()` to `toBig{U}Number()`

---

cfg/windows.cfg
test/cfg/windows.cpp

This fixes a FP: `Variable 'path' can be declared as const array [constVariable]`
The reason was the wrong direction attribute of GetModuleHandle()

windows.cfg: Fixed wrong configuration of GetModuleHandle(A|W)-functions

---

cfg/windows.cfg
test/cfg/windows.cpp

After flushing, the function returns. Before it was configured to not-return.
A proper regression test was added.

windows.cfg: Fix wrong FlushConsoleInputBuffer configuration

---

test/testcondition.cpp

I got error messages while building `cppcheck 2.12.0` for RISC-V Arch Linux:
```
Testing Complete
Number of tests: 4420
Number of todos: 331
Tests failed: 2
/usr/src/debug/cppcheck/cppcheck/test/testcondition.cpp:4501(TestCondition::alwaysTrue): Assertion failed. 
Expected: 
[test.cpp:6]: (style) Condition 'o[1]=='\0'' is always false\n
Actual: 
[test.cpp:4] -> [test.cpp:6]: (style) Condition 'o[1]=='\0'' is always false\n
_____
/usr/src/debug/cppcheck/cppcheck/test/testcondition.cpp:5014(TestCondition::alwaysTrueContainer): Assertion failed. 
Expected: 
[test.cpp:5]: (style) Condition 'buffer.back()=='\0'' is always false\n
Actual: 
[test.cpp:3] -> [test.cpp:5]: (style) Condition 'buffer.back()=='\0'' is always false\n
```
I found out the reason is that the testcases were designed for …

Improve testcases for unsigned char platforms

---

addons/test/misra/misra-test.c
cfg/std.cfg

The replacements should be platform dependent. And I am skeptic that i.e. UINT32_C(10L) should be replaced with 10LUL i.e. making it a long long.

std.cfg: remove wrong macro replacements for UINT32_C etc.

---

lib/symboldatabase.cpp
lib/symboldatabase.h
lib/templatesimplifier.cpp
lib/templatesimplifier.h

Warnings:
```
lib/symboldatabase.h:549:27: error: Guarantee that container indices and iterators are within the valid range [premium-cert-ctr50-cpp]
return mDimensions[index_].num;
^
lib/symboldatabase.h:557:27: error: Guarantee that container indices and iterators are within the valid range [premium-cert-ctr50-cpp]
return mDimensions[index_].known;
^
lib/symboldatabase.cpp:2193:20: error: Guarantee exception safety. An exception during allocation would violate the exception safety rules. [premium-cert-err56-cpp]
mValueType = new ValueType(*var.mValueType);
^
lib/symboldatabase.cpp:2191:5: note: Deallocated mValueType
delete mValueType;
^
lib/symboldatabase.cpp:2193:20: note: Reallocated mValueType
mValueType = new ValueType(*var.mValueType);
^
lib/symboldatabase.cpp:2350:16: error: …
```

Fix Cert C++ warnings reported by Cppcheck Premium

---

cli/processexecutor.cpp
test/cli/test-more-projects.py

No changes in tests since the intercepted invocation function in called in a forked process. The clang-tidy integration is also broken.

fixed #12016 - ProcessExecutor: added missing invocation of clang-tidy

---

test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

The allocation invokes some heavy ValueFlow computations. We just want to generate an unconditional error from the analysis so use some lighter code which does the same.
`TestThreadExecutorFiles::deadlock_with_many_errors`
Before:
```
real    0m23.517s
user    0m33.453s
sys     0m2.297s
```
After:
```
real    0m5.051s
user    0m6.234s
sys     0m0.422s
```

fixed #12063 - use less heavy code in executor tests

---

lib/valueflow.cpp
test/testsimplifytokens.cpp
test/testsimplifytypedef.cpp
test/testsymboldatabase.cpp
test/testtokenize.cpp
test/testvalueflow.cpp

This is unnecessary since we only issue it from a single location. It also leads to a lot of unnecessary noise in the daca diff reports.

ValueFlow: omit unnecessary location information from `valueFlowBailoutIncompleteVar`

---

tools/donate-cpu.py
tools/donate_cpu_lib.py

- added timing information to "finished" log message in `scan_package()`
- adjusted some log messages
- avoid unnecessary `git checkout` invocation if non-`main` binary already exists

donate-cpu: some small improvements

---

cmake/dynamic_analyzer_options.cmake
releasenotes.txt

GCC does not support `-fsanitize=nullability`

fixed #12113 - made CMake build work with UBSAN and GCC

---

addons/misra.py
addons/test/misra/misra-test.c

Fix #9488: MISRA addon: False positive for rule 10.6 in test for rule 10.1

---

cli/cmdlineparser.cpp
cli/cppcheckexecutor.cpp
cli/processexecutor.cpp
cli/singleexecutor.cpp
cli/threadexecutor.cpp
gui/mainwindow.cpp
lib/cppcheck.cpp
lib/settings.h
test/testcmdlineparser.cpp
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

`ImportProject` is not needed outside of the command-line parsing so we do not need it inside the `Settings` at all. We only use the `fileSettings` in the executors.

moved `ImportProject` out of `Settings` and only store `fileSettings`

---

cli/filelister.cpp

The code which was using this was removed in 8b309a882941f5960793413b3a4af192d3e0ef3e.

filelister.cpp: removed unused `NAME_MAX` related code

---

.github/workflows/CI-unixish.yml

Removed all `macos-11` builds as `brew` no longer supports it and we use it in most steps:
```
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or …
```

CI-unixish.yml: removed `macos-11` builds and no longer build with qmake on MacOS

---

.github/workflows/CI-windows.yml
.github/workflows/clang-tidy.yml
.github/workflows/selfcheck.yml

Updates for the Qt 6.2.x and 6.5.x LTS versions are only being provided to commercial customers so the latest version is the only feasible one to use.
Builds with older 6.x versions are still being tested implicitly by using the Qt versions provided by the various distros.

updated Qt in CI to 6.6.0 and removed commercial-only LTS Qt versions

---

lib/checkbufferoverrun.cpp
lib/checkbufferoverrun.h
lib/checknullpointer.cpp
lib/checkuninitvar.cpp
lib/checkuninitvar.h
lib/ctu.cpp
lib/ctu.h
lib/valueflow.cpp

The `Check` objects were just created for that purpose so they basically just were wrappers for the pointers passed into them and were unnecessary.

removed the need for `Check` object in `CTU::getUnsafeUsage()` callback / some CheckUninitVar cleanups

---

Makefile
cli/cmdlineparser.cpp
cli/cmdlineparser.h
cli/cppcheckexecutor.cpp
cli/cppcheckexecutor.h
cli/executor.cpp
cli/executor.h
cli/processexecutor.cpp
cli/processexecutor.h
cli/singleexecutor.cpp
cli/singleexecutor.h
cli/threadexecutor.cpp
cli/threadexecutor.h
gui/checkthread.cpp
gui/mainwindow.cpp
lib/cppcheck.cpp
lib/cppcheck.h
lib/settings.h
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testsuppressions.cpp
test/testthreadexecutor.cpp

Moved the `FileSettings` out of the `Settings` and pass them around explicitly. They can never be specified at the same time and are used exclusively. The code hasn't been fully adjusted to reflect this as this is only the refactoring without any functional changes.

moved `fileSettings` out of `Settings`

---

cli/cmdlineparser.cpp
cli/cppcheckexecutor.h

As we now fail early on loading of all libraries we no longer need to explicitly bail out on mandatory ones. This would have also caused `libraries` and `library` to go out-of-sync and possibly lead to duplicated loading of the library. It also allows for a `CppCheckExecutor` to be made private.

do not explicitly load `windows.cfg` during command-line parsing

---

lib/tokenize.cpp
test/testsimplifytypedef.cpp

Why do we even split any declarations in the first place?

Fix  #12166 debug: varid0 with reference typedef

---

cli/cppcheckexecutor.cpp
cli/singleexecutor.cpp
test/cli/test-other.py
test/cli/test-qml.py
test/cli/testutils.py
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

This is not completely fixing the issue yet. `test-qml.py` still fails when using multiple threads.

refs #12167 - moved ordering of markup files into shared code / removed related test cases from executor tests

---

lib/config.h

When building with /Od - default cmake debug build for me, the __assume(false); trick does not work to get rid of the C4714 warnings
https://godbolt.org/z/a6xGnfP7d
D:\tmp\cppcheck\lib\keywords.cpp(205): warning C4715: 'Keywords::getOnly': not all control paths return a value
D:\tmp\cppcheck\lib\keywords.cpp(226): warning C4715: 'Keywords::getOnly': not all control paths return a value
D:\tmp\cppcheck\lib\keywords.cpp(168): warning C4715: 'Keywords::getAll': not all control paths return a value
D:\tmp\cppcheck\lib\keywords.cpp(188): warning C4715: 'Keywords::getAll': not all control paths return a value
Proposed fix: also define NORETURN to [[noreturn]] when according to __has_cpp_attribute [[noreturn]] is supported https://en.cppreference.com/w/cpp/feature_test
(For previous discussion …

Minor: fix msvc warning "not all control paths return a value"

---

.github/workflows/iwyu.yml
cli/singleexecutor.cpp
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp
test/testtokenlist.cpp

As usual when the base clang version of a distro changes iwyu ends up broken and needs additional packages and/or options applied to work again.

iwyu.yml: fixed `include-what-you-use` job / cleaned up includes

---

lib/programmemory.cpp
lib/vfvalue.cpp
lib/vfvalue.h

Scanning `common/file.c` of the `xrdp` project with `--force --std=c11 --std=c++11 --inline-suppr --enable=warning`:
Clang 16 `4,208,373,435` -> `4,156,024,955`
GCC 13 `4,336,042,153` -> `4,277,293,971`

optimized `ProgramMemory` a bit

---

lib/checkleakautovar.cpp
test/cfg/gnu.c

I wonder if it is worth trying to get this right. We also have FPs when the return value is assigned to a variable, and that seems much harder to fix.

Fix FP memleak with outparam allocation (f'up to #12186)

---

.clang-tidy
clang-tidy.md
gui/.clang-tidy
tools/triage/.clang-tidy

There are some clang-tidy warnings which cannot properly handle the extensions used in the Qt code so the produce lots of false positives and were previously enabled. With clang-tidy now offering the possibility to inherit the parent configuration we can enable these across the project and simply disable them for the GUI code.
No additional warnings were found as they were already fixed in earlier commits without enabling the checks in question.

enabled some clang-tidy warnings for non-GUI code

---

cmake/compilerDefinitions.cmake

also fixes `<command line>(7,9): error : macro name must be an identifier` with `clang-cl` allowing the build to complete

compilerDefinitions.cmake: fixed faulty `add_compile_definitions()` value for MSVC

---

man/manual.md

Since Bear 3.0 (releasedin 2020) the call needs an additional "--".

Tell correct syntax to call bear in manual

---

test/helpers.cpp
test/testcmdlineparser.cpp
test/testsettings.cpp

The tests which are failing were in introduced in #5712. Those were not included in #5710 which updated `picojson` that resulted in the different lines being reported in the error messages.
I also added some checks to `ScopeFile` which will indicate that a temporary file already exists highlighting multi-threading issues and leftover files from previously aborted testruns. I ran into his while looking into these failing tests

fixed tests by adjusting results for `picojson` update

---

lib/checkunusedvar.cpp
test/testunusedvar.cpp

Fixed #12260 (false positive: unusedVariable with side effects in member initialization)

---

lib/checkbufferoverrun.cpp
lib/checkclass.cpp
lib/checknullpointer.cpp
lib/checkuninitvar.cpp

This is actually just a workaround as it seems the issue is an upstream Clang one.

fixed #12108 - Crash in `CTU::FileInfo::getErrorPath()` with Clang-built binary

---

lib/cppcheck.cpp

I also suppressed the unwanted output from the `system()`.

fixed #12264 - auto-detection of Python in Visual Studio built binaries when `python3.exe` does not exist

---

cli/cmdlineparser.cpp
test/testcmdlineparser.cpp

Small adjustment of the log of the error.
- printed only when there was `--enabled=information` and no mentioning of `missingInclude`

#12263: Constant Error 'missingInclude'

---

Makefile
cli/cppcheckexecutor.cpp
cli/executor.cpp
cli/executor.h
lib/cppcheck.cpp
lib/cppcheck.h
lib/errorlogger.cpp
test/helpers.h
test/testcppcheck.cpp
test/testprocessexecutor.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp

The handling in `CppCheck::reportErr()` and `Executor::hasToLog()` was slightly different. I hope this can somehow be shared after the executor reworking.
We were also using a very inappropriate container for the error list which caused a lot of overhead.
`-D__GNUC__ --debug-warnings --template=daca2 --check-library -j2 ../test/testsymboldatabase.cpp`
Clang 15
main process  `284,218,587` -> `175,691,241`
worker process `9,123,697,183` -> `8,951,903,360`

aligned and optimized unique error handling

---

addons/cppcheckdata.py

The attribute movedValue is misspelled with an uppercase V, this leads to errors when printing token values:
```
$ python3 runaddon.py test.py test.c.dump 
Checking test.c.dump...
Checking test.c.dump, config ...
line 2 str=""lala\n""
File "/home/eric/tools/cppcheck/addons/runaddon.py", line 11, in <module>
cppcheck.runcheckers()
File "/home/eric/tools/cppcheck/addons/cppcheck.py", line 39, in runcheckers
c(cfg, data)
File "test.py", line 9, in func
print(f'    {value}')
File "/home/eric/tools/cppcheck/addons/cppcheckdata.py", line 907, in __repr__
", ".join(("{}={}".format(a, repr(getattr(self, a))) for a in attrs))
File "/home/eric/tools/cppcheck/addons/cppcheckdata.py", line 907, in <genexpr>
", ".join(("{}={}".format(a, repr(getattr(self, a))) for a …
```

fix casing in variable name

---

lib/preprocessor.cpp
lib/token.cpp

As reported in https://sourceforge.net/p/cppcheck/discussion/general/thread/fa43fb8ab1/ removeContradiction() minValue/maxValue.remove(..) can access free'd memory as it removes all matching values by iterating over the complete list. Creating a full copy instead of a reference avoids this issue.

Fix #12272 (removeContradiction() Avoid use-after-free on multiple remove)

---

htmlreport/cppcheck-htmlreport

This is a cosmetic change. When the user enters text to either the "File" or "Filter" option, a clear button is shown now.

cppcheck-htmlreport: Added clear button inside 'File' and 'Filter' text box

---

addons/namingng.py

This patch allows a config file to have RE_VARNAME and RE_FUNCTIONNAME without the corresponding var_prefixes and function_prefixes keys. The namingng.py processing function would otherwise raise an exception trying to get these keys, while they are not strictly necessary, if no prefixes are required.

addons/namingng.py: allow function/variable name test without prefixes

---

lib/addoninfo.cpp
test/cli/test-other.py

In case a user accidentally uses a wrong JSON file (e.g. naming.json, which is the config file for namingng.py), the code could give a confusing exception. This happens when the key 'script' is not defined as a string.
This is solved by testing the key for existence and type. In case 'script' is not a key or refers to a type other than a string, a clear error is given, stating for example: 'Loading naming.json failed. script must be set to a string value.'
The message is kept in line with other messages. Maybe it can be clarified further, e.g. 'Loading naming.json failed. A key "script" must be set with a string value referring to a Python script.' - in which case the errors relating to other keys may also be clarified.

lib/addoninfo.cpp: When loading a JSON addon, test 'script' key.

---

gui/codeeditor.cpp
gui/common.cpp
gui/compliancereportdialog.cpp
gui/cppchecklibrarydata.cpp
gui/csvreport.cpp
gui/librarydialog.cpp
gui/main.cpp
gui/mainwindow.cpp
gui/printablereport.cpp
gui/projectfiledialog.cpp
gui/resultstree.cpp
gui/resultsview.cpp
gui/statsdialog.cpp

Chained QString::arg, replace inclusion of QtCore

Fix two types of Clazy warnings

---

addons/namingng.py

(note: comment updated after force push; initial PR was incomplete)
namingng.py attempted to derive the source filename from the name of the dumpfile. However, the dumpfile is not necessarily named according to this pattern, e.g. cppcheck will add the pid to the filename, making RE_FILE rules
fail. Taking the first item of data.files seem to be more robust.
To get the basename of the file, `os.path.basename()` is used. This solves (theoretical) issues on platforms with a different path separator.
With this patch, all filenames are checked, not just those provided on the cppcheck command line. This is useful as header files will now also be part of this check, even if not explicitly specified on the command line.
The "RE_FILE" key of the configuration JSON may contain a list of regular …

addons/namingng.py: Improve file name checking feature.

---

addons/namingng.config.json
addons/namingng.py
test/cli/test-other.py

Include guard naming can be validated against various patterns:
- prefixes/suffixes (`_FILE_H`, `PROJECT_FILE_H`, `FILE_H_`)
- basename/full path (`FILE_H`, `SUB_DIR_INC_FILE_H`)
- upper- or lowercase (`FILE_H`, `file_h`)
- any combination of the above (`project_sub_dir_inc_file_h_`)
A regexp can be specified to match header filenames. The example matches any filename not starting with / and ending with `.h`, intended to match C header files while exluding system files.
The test is not limited to naming only; validity and presence of include guards can also be tested by setting `"required":true` in the config file.
Enabling this feature requires adding the key `"include_guard"` to the namingng config file used.
The namingng unit test is extended to test various features of the include …

addons/namingng.py: Add tests for include guards, config file validation.

---

addons/ROS_naming.json
addons/namingng.py
test/cli/test-other.py

`namingng.py` somewhat supported specifying a dict instead of a list for regular expressions, until the feature was broken by a patch of mine recently. This PR contains a patch rewriting the feature and expanding relevant unit tests.
To improve maintainability, a second patch is added that refactors the code for better readability and structure.

addons/namingng.py: Reinstate dict-with-regexps, cosmetic overhaul.

---

cfg/gtk.cfg
test/cfg/gtk.c

In particular, the missing definition of `g_assert_nonnull()` can cause false positives because it's not recognized as `assert(expr != NULL)` by cppcheck.

gtk.cfg: Add more definitions for assert macros

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/numeric/math/lgamma

Add support for InvalidFunctionArg lgamma()

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/numeric/math/tgamma

std.cfg: Added support for invalidFunctionArg check to tgamma().

---

test/cli/test-other.py

test_showtime_top5_file() assumes that all reported elements, of which the "top 5" are validated, end with the string "- 1 result(s))".
This is clearly not the case when viewing the entire list:
```bash
$ cppcheck --showtime=summary --quiet empty.c  |grep "2 result"
valueFlowLifetime(tokenlist, errorLogger, settings): 3.4e-05s (avg. 1.7e-05s - 2 result(s))
valueFlowEnumValue(symboldatabase, settings): 3e-06s (avg. 1.5e-06s - 2 result(s))
```
As the order of items is non-deterministic, this test makes CI workflows randomly fail.
This patch addresses the issue by adjusting the expected string to the reported item.

test/cli/test-other.py: Fix test_showtime_top5_file.

---

lib/clangimport.cpp
lib/clangimport.h
lib/cppcheck.cpp
test/testclangimport.cpp

The `Tokenizer` and `TokenList` objects which are passed around always need to exist so pass them by reference.

ClangImport: avoid unchecked pointer dereferences

---

Makefile
cli/cmdlineparser.cpp
gui/resultstree.cpp
gui/resultsview.cpp
lib/config.h
lib/cppcheck.cpp
lib/path.cpp
lib/path.h
lib/preprocessor.cpp
lib/tokenize.cpp
lib/tokenlist.cpp
test/testpath.cpp
test/testvarid.cpp

None of the `Path::is*()` function is working as expected or consistent (detailed via additional unit tests and deprecation comments).
I tried to fix them but that would have made made cases with headers quite awkward to implement so I opted to generate a new function. This also optimized `Path::acceptFile()` a file.
I am not 100% happy with including `settings.h` but I didn't see a place to move this to. If #3774 gets merged we might be able to move the `enum` into `keywords.h` (that could also be renamed).
I kept the old function in case somebody else is using these (they are in the API after all) and will remove them after the next release.

added `Path::identify()`/`Path::isHeader2()` and deprecated flawed `Path::isCPP()`, `Path::isC()` and `Path::isHeader()`

---

cli/cmdlineparser.cpp
releasenotes.txt
test/cli/helloworld_test.py
test/cli/other_test.py
test/fixture.cpp
test/testcmdlineparser.cpp

It was already used in several places and I need it in some test cleanups I am currently working on.

added `--template=simple`

---

lib/astutils.cpp
test/testastutils.cpp

For the `isSameExpression()` test we were tokenizing the code as C++ but were treating it as C later on.

TestAstUtils: fixed consistency of language being used in `isSameExpressionTest` / added a few language checks

---

lib/checkunusedvar.cpp
test/testgarbage.cpp

Happened with the IDE integration while I was typing code.

CheckUnusedVar: fixed potential crash with incomplete code in `doAssignment()`

---

lib/checkfunctions.cpp
lib/checkleakautovar.cpp
test/testfunctions.cpp
test/testleakautovar.cpp

I wonder why both `%name%` and `%type%` match `return`.

Fix #12365 checkLibraryFunction for std::string constructor

---

.github/workflows/CI-unixish-docker.yml

See
https://github.com/danmar/cppcheck/actions/runs/7677304162/job/20926809147?pr=5917
https://github.com/hendrikmuhs/ccache-action/issues/178

CI-unixish-docker.yml: fixate `hendrikmuhs/ccache-action` on `1.2.11` to fix older images

---

Makefile
lib/forwardanalyzer.cpp
lib/forwardanalyzer.h
lib/reverseanalyzer.cpp
lib/reverseanalyzer.h
lib/settings.cpp
lib/settings.h
lib/valueflow.cpp
test/CMakeLists.txt
test/cfg/runtests.sh
test/fixture.cpp
test/fixture.h
test/testcondition.cpp
test/testsimplifytypedef.cpp
test/testsymboldatabase.cpp
test/testvalueflow.cpp

I have executed test-my-pr.py on 532 packages
number of "main" warnings: 
```
egrep -v valueFlow my_check_diff.log | egrep "^main " | wc -l
277
```
number of "your" warnings (genomicepidemiology-kma timed out without these changes): 
```
egrep -v valueFlow my_check_diff.log | egrep "^your " | egrep -v genomicepidemiology-kma | wc -l
90
```
=> There are some false negatives. But it's rougly  ~ 190 in 532 packages.. so it's not a major problem imho.
I can see a speedup. For the packages that took more than 1 second to analyze the timing factor was:
```
$ egrep -v " 0.[0-9][0-9] " my_check_diff_timing.log | sed 's/.* //' | egrep -v Factor | sort
0.04
0.08
0.10
0.10
0.13
0.18
0.19
0.20
0.21
0.21
0.23
0.24
0.25
0.26
0.26
0.27
0.28
0.28
0.29
0.31
0.31
0.31
0.31
0.31
0.32
0.33
0.34
0.35
0.35 …
```

Fix #12266 (Performance: valueFlowCondition slowdown)

---

.github/workflows/coverity.yml

this  requires adding a variable `COVERITY_SCAN_TOKEN` to [settings](https://github.com/danmar/cppcheck/settings/secrets/actions/new)
also, I'd suggest issue new token since current one (or is it fake ?) exposed in   https://github.com/danmar/cppcheck/blob/eed9c4d0b4c1e9f08ea2a20e57758fd290ddbe3b/tools/run-coverity.sh#L15

CI: add coverity scan scheduled

---

.github/workflows/CI-mingw.yml
.github/workflows/CI-unixish.yml
.github/workflows/asan.yml
.github/workflows/coverage.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml
.github/workflows/valgrind.yml

As the work on https://github.com/hendrikmuhs/ccache-action/issues/178 and https://github.com/hendrikmuhs/ccache-action/issues/179 has stalled roll back all usages to the previous version for now. This prevents the steps from running into a 2 minutes timeout.

fixated all usages of `hendrikmuhs/ccache-action` to `v1.2.11` for now

---

cfg/gnu.cfg
test/cfg/gnu.c
test/testlibrary.cpp

I'm not sure all libraries must work together (some legitimate clashes are to be expected), but we could test some likely combinations.

Fix error when loading both gnu.cfg and bsd.cfg

---

addons/misra_9.py
addons/test/misra/misra-test.c

Revert changes made for [#12298](https://trac.cppcheck.net/ticket/12298)

Additional fix for #12298: Rule 9.3: Allow only { 0 } form of initializer

---

lib/checkstl.cpp
test/teststl.cpp

…r to get reference to container

Fix #11093, #12377 FP mismatchingContainerIterator

---

readme.md

See title as i was developing on Linux didn't found the option for building the test binary. With some feedback and examination of the Actions i found that the BUILD_TESTS flag should be enabled. Added that to Readme.

Add BUILD_TESTS Flag to Readme for CMake [skip ci]

---

lib/tokenize.cpp
test/testsimplifytypedef.cpp
test/testsymboldatabase.cpp

Trying to Fix the issue described here: https://sourceforge.net/p/cppcheck/discussion/general/thread/5775ff1666/
For the small example purpose script it works. Actually it shows the `valueType-originalTypeName`. But i am not 100% sure, what is done. I printed the tok2 and tok3 and in my simple case both where the same. And if i add either of both the originalName it also works. But for now i couldn't deduct what exactly tok2 and tok3 are doing

Add Original Name to types for Typedefs

---

lib/checkclass.cpp
lib/checkother.cpp
test/testclass.cpp
test/testother.cpp

work in progress...
* change selfAssignment from warning to style => it's not about undefined behavior
* don't claim that code such as `a = b|c;`  is a condition.

Fix #12431 (Style warnings are reported when only --enable=warning is used)

---

addons/cppcheckdata.py

The Token class documents that the type ("name/op/...") is accessible to the Addon which wasn't the case.
It was only read locally to set other variables.

Addon: cppcheckdata.py Fix bug that token type was not a accacable from outside.

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/filesystem/exists

std.cfg: Added support for std::filesystem::exists()

---

Makefile
cmake/options.cmake
releasenotes.txt
tools/dmake/dmake.cpp

I accidentally specified `MATCHCOMPILER=1` and only later realized that the matchcompiler was not being used as it requires `yes` instead. So bail out on this.

bail out on invalid `MATCHCOMPILER` (make) and `USE_MATCHCOMPILER` (CMake) values / Makefile: removed deprecated `SRCDIR`

---

test/fixture.h
test/testcmdlineparser.cpp
test/testerrorlogger.cpp
test/testlibrary.cpp
test/testsingleexecutor.cpp
test/testthreadexecutor.cpp
test/testtoken.cpp
test/testvalueflow.cpp

If only one case explicitly specified the enum it would have compiled with `ASSERT_EQUALS` but we would be have an implicit conversion and would not have detected a type mismatch.

testrunner: stop comparing mismatching types in generic `assertEquals()` / added `ASSERT_EQUALS_ENUM`

---

test/testcmdlineparser.cpp
test/testpreprocessor.cpp

These used to be necessary in `TestCmdlineParser` when we were still using the same `Settings` object for all tests cases.

testrunner: removed some bogus initializations of settings

---

addons/misra.py
addons/test/misra/misra-test.c

https://trac.cppcheck.net/ticket/12457#ticket

Fix #12457: use essential type category in 21.16

---

.github/workflows/CI-unixish.yml
Makefile
cli/cli.vcxproj
cli/cli.vcxproj.filters
cli/cppcheckexecutor.cpp
cli/signalhandler.cpp
cli/signalhandler.h
cli/stacktrace.cpp
cli/stacktrace.h
test/CMakeLists.txt
test/signal/CMakeLists.txt
test/signal/test-signalhandler.cpp
test/signal/test-signalhandler.py
test/signal/test-stacktrace.cpp
test/signal/test-stacktrace.py
test/testrunner.vcxproj
test/testrunner.vcxproj.filters
tools/dmake/dmake.cpp

See https://github.com/danmar/cppcheck/pull/5540#pullrequestreview-1676126131 for related discussion.

cleaned up signal handler and improved stack trace generation

---

lib/checkstl.cpp
test/teststl.cpp

Or should this be fixed elsewhere?
If `::` represents the container, `isSameExpression()` should handle that.
If `::` is not the container, then it shouldn't be set as `tokvalue`.

Fix #12443 FP mismatchingContainers with container in namespace

---

cli/cppcheckexecutor.cpp

This fixes build on FreeBSD. Not sure if preprocessor condition is 100% correct though.

Include sys/wait.h for WIF* macros

---

lib/library.cpp
test/testfunctions.cpp

Inspired by https://github.com/danmar/cppcheck/pull/4834

Fix checkLibraryFunction warning when deriving from std::vector

---

cfg/qt.cfg

Reference: https://doc.qt.io/qt-6/qrectf.html

qt.cfg: Added support for QRectF members

---

lib/cppcheck.cpp
lib/tokenize.cpp
lib/tokenize.h
test/helpers.cpp
test/testsimplifytemplate.cpp

These were used inconsistently. Also `Tokenizer::list` is public and used directly across the code already.

Tokenizer: removed some wrapper functions

---

lib/checkautovariables.cpp
lib/checkcondition.cpp
lib/checkfunctions.cpp
lib/checkmemoryleak.cpp
lib/checkother.cpp
lib/checkstring.cpp
lib/checkuninitvar.cpp
lib/symboldatabase.cpp
lib/token.cpp
lib/token.h

Each `Token` (should) be connected to a `TokenList`. `Tokenizer` just encapsulates that so we have no need to check the `Tokenizer` but can simply ask the `Token`.
Also if we have function calls we pass in a flag to tell it if it is C/C++ we can get rid of that flag and simply ask the `Token`.

reduced `Tokenizer::isC()` usage

---

cli/cmdlineparser.cpp
lib/suppressions.cpp
test/testcmdlineparser.cpp
test/testerrorlogger.cpp
test/testlibrary.cpp
test/testplatform.cpp
test/testsuppressions.cpp

This is based on a Coverity finding in `SuppressionList::parseXmlFile()`. `--suppress-xml` was actually crashing when a XML without a root node was provided.

improved handling/testing of XMLs without a a root node / added some TODOs

---

test/fixture.cpp
test/fixture.h
test/options.cpp
test/options.h
test/scripts/testrunner-single.sh
test/testastutils.cpp
test/testbufferoverrun.cpp
test/testclass.cpp
test/testmemleak.cpp
test/testnullpointer.cpp
test/testoptions.cpp
test/testsummaries.cpp
test/testtoken.cpp
test/testtokenize.cpp
test/testtokenrange.cpp
test/testtype.cpp

This script runs each test case separately so we can uncover cases where it depends on left-over data on the previous one. `CTest` is only running the fixtures separately so that does not.

testrunner: added options `-n` (no summary) and `-d` (dry run) / added script to run test cases separately / adjusted some tests

---

.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/asan.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml
lib/cppcheck.cpp
test/cli/helloworld/main.c
test/cli/testutils.py

This is currently disabled since a lot of tests still fail. I did fix some low hanging fruits though.

added environment variable `TEST_CPPCHECK_INJECT_CLANG` to inject `--clang` into the cppcheck invocation of Python tests

---

lib/tokenize.cpp
test/testsimplifyusing.cpp

Why do `%type%` and `%name%` match keywords?

Fix syntaxError with using namespace ::std (f'up to #8454)

---

lib/astutils.cpp
lib/astutils.h
lib/checkautovariables.cpp
lib/checkbool.cpp
lib/checkbufferoverrun.cpp
lib/checkclass.cpp
lib/checkcondition.cpp
lib/checkfunctions.cpp
lib/checkleakautovar.cpp
lib/checkmemoryleak.cpp
lib/checkother.cpp
lib/checkstl.cpp
lib/checkstring.cpp
lib/checktype.cpp
lib/checkuninitvar.cpp
lib/checkunusedvar.cpp
lib/checkvaarg.cpp
lib/ctu.cpp
lib/forwardanalyzer.cpp
lib/fwdanalysis.cpp
lib/fwdanalysis.h
lib/programmemory.cpp
lib/reverseanalyzer.cpp
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/tokenize.cpp
lib/tokenlist.cpp
lib/valueflow.cpp
test/testastutils.cpp

Each `Token` (should) be connected to a `TokenList`. `Tokenizer` just encapsulates that so we have no need to check the `Tokenizer` but can simply ask the `Token`.
Also if we have function calls we pass in a flag to tell it if it is C/C++ we can get rid of that flag and simply ask the `Token`. In several cases we were only passing that flag to be used in some underlying calls making it completely unnecessary in the top call.

reduced `Tokenizer::isCPP()` usage / SymbolDatabase: removed `mIsCpp` and `isCPP()`

---

lib/checkfunctions.cpp
lib/checktype.cpp
lib/symboldatabase.cpp
lib/tokenize.cpp

`Settings::Standards` are always both set so we cannot simply check that but need to combine with an check for the actual language being used.

added some missing language checks and adjusted some others

---

cfg/posix.cfg
test/cfg/posix.c

This fix is similar to https://github.com/danmar/cppcheck/pull/6108

posix.cfg: Fixed FP for getdelim and array

---

cfg/wxwidgets.cfg
test/cfg/wxwidgets.cpp

Reference: https://docs.wxwidgets.org/3.0/classwx_version_info.html

wxwidgets.cfg: Added support for wxVersionInfo

---

cfg/wxwidgets.cfg
test/cfg/wxwidgets.cpp

Reference: https://docs.wxwidgets.org/3.0/classwx_region.html

wxwidgets.cfg: Added support for wxRegion

---

oss-fuzz/Makefile
tools/dmake/dmake.cpp

I tested all builds beforehand but I worked from a branch which already removed the code generation.

oss-fuzz/Makefile: re-added `translate` target and fixed `no-fuzz` build

---

.github/workflows/CI-unixish.yml
cfg/qt.cfg
test/cfg/qt.cpp
test/cfg/runtests.sh

Reference: https://doc.qt.io/qt-6/qregion.html

qt.cfg: Added support for QtRegion

---

cfg/windows.cfg
lib/tokenize.cpp
lib/valueflow.cpp
test/CMakeLists.txt
test/cfg/gnu.c
test/cfg/googletest.cpp
test/cfg/gtk.c
test/cfg/opencv2.cpp
test/cfg/posix.c
test/cfg/qt.cpp
test/cfg/runtests.sh
test/cfg/std.c
test/cfg/std.cpp
test/cfg/windows.cpp
test/testcondition.cpp
test/testvalueflow.cpp

The bailout was moved out of an inner loop in a3617fe5739a66e37d197568a44e1c7cf6fe2c21 but it kept the previous `break`. This caused it to bail out completely instead of just skipping the function.
References for the added defines:
https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventexa#parameters
https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids

fixed #12526 - corrected bailout in `valueFlowConditionExpressions()` / restored `valueFlowBailoutIncompleteVar` in daca

---

test/CMakeLists.txt
test/cfg/boost.cpp
test/cfg/bsd.c
test/cfg/cppunit.cpp
test/cfg/gnu.c
test/cfg/googletest.cpp
test/cfg/libcurl.c
test/cfg/opencv2.cpp
test/cfg/posix.c
test/cfg/qt.cpp
test/cfg/runtests.sh
test/cfg/std.c
test/cfg/std.cpp
test/cfg/windows.cpp
test/cfg/wxwidgets.cpp

`unmatchedSuppression` was suppressed globally which obviously has the effect that we got no feedback when an expected warning was not being reported.

made all suppressions in `cfg` tests inline / added TODOs

---

lib/valueflow.cpp

as we only pass a default constructed object, `varId` will always be 0 and thus never be used

valueflow.cpp: removed unnecessary parameter from deprecated `valueFlowReverse()`

---

cfg/windows.cfg

Reference: https://learn.microsoft.com/de-de/cpp/c-runtime-library/reference/utime-utime32-utime64-wutime-wutime32-wutime64?view=msvc-170

windows.cfg: Added support for _utime-functions

---

lib/forwardanalyzer.cpp

This was reported on the first line which is just wrong and misleading. As we currently only report it on the file-level (having it on the function-level would be good but probably very spammy) it should be consistent with existing messages like that.

forwardanalyzer.cpp: fixed location and adjusted message of `normalCheckLevelMaxBranches` / added TODO

---

cfg/wxwidgets.cfg
test/cfg/wxwidgets.cpp

Reference: https://docs.wxwidgets.org/latest/group__group__class__gdi.html

wxwidgets.cfg added more GDI objects

---

cfg/std.cfg

Although the values are implementation dependent and thus not documented, they reflect the common values of 0 and positive non-0 for success/failure. For the analysis it is also not important that these are correct but that they are being consistent across the code.
https://en.cppreference.com/w/cpp/utility/program/EXIT_status

std.cfg: added `EXIT_SUCCESS` and `EXIT_FAILURE`

---

cli/cmdlineparser.cpp
cli/cmdlineparser.h
releasenotes.txt
test/testcmdlineparser.cpp

I chose to not add it in the help output. But I don't have a strong opinion it can be added there also.
This option was added for the safety certification. It could be very bad if a user runs one version of cppcheck and thinks that he runs another version.

Fix #12505 (cli: Add option --check-version to pin cppcheck version)

---

cfg/windows.cfg

Reference: https://learn.microsoft.com/en-us/cpp/c-runtime-library/obsolete-functions?view=msvc-170

windows.cfg: Added support for some obsolete functions

---

.github/workflows/coverage.yml

The `v3` action appears to use the `v4` API:
```
[2024-04-07T11:12:15.874Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.6-uploader-0.7.2&token=*******&branch=windows_cfg_added_more_obsolte_functions&build=8586929612&build_url=https%3A%2F%2Fgithub.com%2Fdanmar%2Fcppcheck%2Factions%2Fruns%2F8586929612%2Fjob%2F23532898031&commit=5f9e79c47e8f116481df6fb981dc67eef975344e&job=Coverage&pr=6251&service=github-actions&slug=danmar%2Fcppcheck&name=danmar%2Fcppcheck&tag=&flags=unittests&parent=
[2024-04-07T11:12:16.167Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github …
```

coverage.yml: temporarily disabled because of permanent upload failures

---

cli/cppcheckexecutor.cpp
lib/cppcheck.cpp
lib/settings.h

This caused the `unmatchedSuppression` for an inline `unusedFunction` suppression not to be reported with `-j2` when using `--executor=thread`.

fixed checks related to `unusedFunction` check enablement

---

.github/workflows/iwyu.yml

Starting with Qt 6.7.0 we no longer require the Qt mappings because IWYU annotations have been added to the headers upstream (see https://bugreports.qt.io/browse/QTBUG-119505).

iwyu.yml: use Qt 6.7.0 for `include-what-you-use`

---

cli/filelister.cpp
test/cli/other_test.py

#4748 exposed a different order of files using the Windows code. This was caused by it only sorting the files in case of recursive parsing.  But we need to sort all the files and not just the directory contents as the directory order might also be different dependent on the filesystem. This also allows the code to be a bit closer between the implementations.

FileLister: ensure sorting of files / some cleanups

---

oss-fuzz/Makefile
tools/dmake/dmake.cpp

The Python test is using a 5 seconds timeout. I probably lowered it locally for some tests and accidentally put those in the Makefile.

oss-fuzz: aligned timeout in targets with what we are actually testing with

---

oss-fuzz/main.cpp

this allows the tool to be used as a "micro" benchmark of sorts for the analysis.
Using a single run is also not good for profiling because it includes all the static initializations which is misleading.

no-fuzz: added (optional) execution count command-line argument

---

cfg/gnu.cfg

Reference: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

gnu.cfg: Added support for __builtin_unreachable ()

---

cfg/kde.cfg
test/cfg/kde.cpp
tools/donate_cpu_lib.py

see https://api.kde.org/frameworks/ki18n/html/prg_guide.html

kde.cfg: added some `*i18n()` and `*i18nc()` functions

---

lib/valueflow.cpp
test/testcondition.cpp

While truncating integer values for upper/lower bounds, underflows/overflows must be handled correctly by
inverting the bound.

Fix 12681: FP: knownConditionTrueFalse

---

Makefile
lib/astutils.cpp
lib/checkfunctions.cpp
lib/library.cpp
lib/library.h
lib/symboldatabase.cpp
test/testlibrary.cpp
test/testnullpointer.cpp

This ensures that we do not modify the library directly. And the implementations are moved in preparation of moving all the data into an implementation class.

Library: made all members private and moved implementations to source file

---

lib/valueflow.cpp

```
lib/valueflow.cpp: In function ‘const Token* ValueFlow::solveExprValue(const Token*, const std::function<std::vector<long long int>(const Token*)>&, Value&)’:
lib/valueflow.cpp:8405:28: warning: ‘intval’ may be used uninitialized [-Wmaybe-uninitialized]
8405 |             value.intvalue /= intval;
|             ~~~~~~~~~~~~~~~^~~~~~~~~
lib/valueflow.cpp:8383:21: note: ‘intval’ was declared here
8383 |     MathLib::bigint intval;
|                     ^~~~~~
```

valueflow.cpp: fixed `-Wmaybe-uninitialized` GCC warning in optimized build

---

lib/cppcheck.cpp
lib/tokenlist.cpp
lib/tokenlist.h
test/cli/other_test.py

cherry pick from 9c21862159cffc02adc8c0c1c6f5272973068966

fixed #12763 - do not assert in markup processing for `unusedFunction` when a language is enforced

---

readme.md
tools/donate-cpu-requirements.txt

Hey
I tried to use `donate-cpu.py` to be useful for you, but script require `psutil` and `packaging` pip packages.
So, I added `tools/donate-cpu-requirements.txt` and update `readme.md`

Added requirements.txt for donate-cpu.py

---

lib/astutils.cpp
lib/checkassert.cpp
lib/checkboost.cpp
lib/checkbufferoverrun.cpp
lib/checkclass.cpp
lib/checkcondition.cpp
lib/checkexceptionsafety.cpp
lib/checkleakautovar.cpp
lib/checkmemoryleak.cpp
lib/checknullpointer.cpp
lib/checkother.cpp
lib/checkstl.cpp
lib/checkstring.cpp
lib/checkuninitvar.cpp
lib/checkunusedvar.cpp
lib/forwardanalyzer.cpp
lib/pathanalysis.cpp
lib/symboldatabase.cpp
lib/templatesimplifier.cpp
lib/tokenize.cpp
lib/tokenlist.cpp
lib/valueflow.cpp

Fixes from https://github.com/danmar/cppcheck/pull/6472

Replaced 'tok->next()->link()' by 'tok->linkAt(1)'

---

Makefile
gui/erroritem.cpp
gui/erroritem.h
gui/resultstree.cpp
gui/xmlreportv2.cpp
lib/cppcheck.cpp
lib/cppcheck.h
lib/errorlogger.cpp
lib/errorlogger.h
lib/preprocessor.cpp
lib/preprocessor.h
man/manual.md
releasenotes.txt
test/helpers.cpp
test/helpers.h
test/testerrorlogger.cpp
test/testpreprocessor.cpp

cherry picked from main branch to 2.14.x branch 
bd694dbbb5e22ee5ded588fb9fb8036339194342

Fix #12610 (Justifications for warnings using comments in the code)

---

.github/workflows/CI-windows.yml
.github/workflows/asan.yml
.github/workflows/scriptcheck.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

To work around https://github.com/actions/setup-python/issues/886.

temporally fixated Python 3.12 in CI to 3.12.3

---

test/cfg/boost.cpp

Include `boost/bind/bind.hpp` instead of `boost/bind.hpp` to get rid of the message about deprecated placeholders

Fix message about deprecated placeholders

---

cli/cmdlineparser.cpp
lib/analyzerinfo.cpp
lib/errorlogger.cpp
lib/importproject.cpp

`Path::simplifyPath()` includes the operation

removed redundant `Path::fromNativeSeparators()` calls

---

cfg/emscripten.cfg
test/CMakeLists.txt
test/cfg/emscripten.cpp
test/cfg/runtests.sh
tools/donate_cpu_lib.py

Leaving the emscripten macros, returning a value, empty was leading to syntax errors
The pointer returned by `EM_ASM_PTR` must be freed by calling `free` see
https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=em_asm_ptr#c.EM_ASM_PTR

Fix emscripten config

---

lib/vf_settokenvalue.cpp
test/testcondition.cpp

Performing arithmetic on two pointers is not guaranteed to always yield a non-zero value.
Introduced in commit ac0bd6d2fa30 ("Fix 12760: FN knownConditionTrueFalse for pointer + offset (#6491)").

Fix #12833 FP knownConditionTrueFalse regression

---

cfg/boost.cfg
cfg/windows.cfg
test/cfg/boost.cpp
test/cfg/windows.cpp

**Fix defines for boost test macros**
The _MESSAGE macros were causing an unusedScopedObject warning because
the created string was not used. Casting the message to void fixed the
warnings.
Add missing `BOOST_AUTO_TEST_CASE_TEMPLATE` macro accidentally removed
with d1b3670017e101a89c7eb11198d741c5199d42d4
**Fix wrong defined in windows.cfg**
INVALID_HANDLE_VALUE is defined as `-1` in the windows sdk
INVALID_SOCKET is defined as `~0` in the windwos sdk
Add missing generic rights

Fix wrong config defines in boost/windows.cfg

---

lib/valueflow.cpp
lib/vf_common.cpp
lib/vf_common.h
lib/vf_settokenvalue.cpp
test/testcondition.cpp
test/testvalueflow.cpp

This PR fixes a similar bug than [#11591](https://trac.cppcheck.net/ticket/11591) fixed in PR https://github.com/danmar/cppcheck/pull/6331.

Truncate value of increment operator

---

test/testother.cpp

Reference: https://trac.cppcheck.net/ticket/11175

Added test for #11175 - FN: zerodiv

---

cfg/windows.cfg
test/cfg/windows.cpp

References:
- https://learn.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-updatetracea
- https://learn.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-updatetracew

windows.cfg: Added support for obsolete UpdateTraceW()/UpdateTraceA().

---

gui/common.h

```
In file included from /mnt/s/GitHub/cppcheck-fw/gui/common.cpp:20:
/mnt/s/GitHub/cppcheck-fw/gui/common.h:55:25: error: no type named 'uint8_t' in namespace 'std'; did you mean simply 'uint8_t'?
55 | enum class ReportType : std::uint8_t { normal=0, autosar=1, certC=2, certCpp=3, misraC=4, misraCpp2008=5, misraCpp2023=6 };
|                         ^~~~~~~~~~~~
|                         uint8_t
/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h:24:19: note: 'uint8_t' declared here
24 | typedef __uint8_t uint8_t;
|                   ^
```
I have no idea why this does not happen in the CI.

fixed `common.cpp` compilation for `test-translationhandler`

---

lib/cppcheck.cpp

this only fixes the check which was broken back in ea905c9a360f224d8e1d676fc3a0d70e443fa85a.

refs #12348 - fixed missing parsing of markup files when a build dir is specified

---

.github/workflows/CI-unixish.yml

The existing usage of `--showtime=top5_summary` is broken and also would not provide any context of which file the data belongs to.

CI-unixish.yml: show check time for each file in selfcheck

---

.pylintrc
addons/cppcheckdata.py
addons/misc.py
addons/misra.py
addons/misra_9.py
addons/namingng.py
addons/test/misra_test.py
addons/test/y2038_test.py
addons/y2038.py
htmlreport/cppcheck-htmlreport
test/cli/fuzz_test.py
test/cli/helloworld_test.py
test/cli/other_test.py
test/cli/performance_test.py
test/cli/premium_test.py
test/cli/proj2_test.py
test/cli/samples_test.py
test/cli/suppress-syntaxError_test.py
test/cli/testutils.py
test/signal/test-signalhandler.py
test/signal/test-stacktrace.py
tools/MT-Unsafe.py
tools/compare-normal-exhaustive.py
tools/daca2-download.py
tools/donate-cpu-server.py
tools/donate_cpu_lib.py
tools/reduce_test.py
tools/test-my-pr.py

Co-authored-by: kloczek <kloczek@users.noreply.github.com>

enabled and mitigated part of the remaining pylint messages

---

lib/programmemory.cpp

`infer()` will exit early if any of the list of given values is empty. so there is no need to call it (and copy the values with the call) if we know that beforehand.

programmemory.cpp: avoid unnecessary `infer()` calls in `Executor::executeimpl()`

---

lib/programmemory.h

This avoids copy-on-write with range loops.

ProgramMemory: no longer offer mutable iterators

---

CMakeLists.txt

Since CMake 3.0 it is set implicitly to NEW, cppcheck requires CMake 3.5
https://cmake.org/cmake/help/latest/policy/CMP0048.html

[cmake] Do not set CMP0048 explicitly

---

lib/checkunusedfunctions.cpp
lib/token.h
lib/tokenize.cpp
test/testunusedfunctions.cpp

Gets rid of FPs when a static function is only used with attribute cleanup.

Fix #12989: Honor attribute cleanup in unusedFunction

---

cppcheckpremium-suppressions
lib/analyzer.h
lib/importproject.h
lib/library.cpp
lib/library.h
lib/symboldatabase.cpp
lib/symboldatabase.h
lib/valueptr.h

Fix #12992 (Refactoring: Use l-value reference specifier for assignment operators to prevent misuse)

---

lib/astutils.cpp

The function is too big to automatically be inlined. By forcing the inlining we mainly save the overhead associated with calling the function.

astutils.cpp: always inline `isMutableExpression()` with Clang

---

cppcheckpremium-suppressions
lib/checkleakautovar.h
lib/programmemory.cpp
lib/programmemory.h
lib/valueptr.h

Misra C++ 2023 rule 18.4.1: Exception-unfriendly functions shall be noexcept

Refactoring: Use NOEXCEPT for swap methods

---

test/fixture.cpp
test/fixture.h
test/testmemleak.cpp

Greatly improves the start-up time because it no longer needs to create all the implementations before it runs any test.
The following times are using a debug build.
Before: `bin/testrunner TestColor  1,16s user 0,07s system 99% cpu 1,235 total`
After: `bin/testrunner TestColor  0,00s user 0,00s system 88% cpu 0,009 total`

refs #12080 - testrunner: do not create test implementation until it is used

---

.github/workflows/CI-mingw.yml
.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/asan.yml
.github/workflows/coverage.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml
.github/workflows/valgrind.yml

This fixes the two minute hang in the `Post ccache` step.

changed `ccache-action` GitHub action to `v1.2` for most workflows

---

test/CMakeLists.txt

The `macos-*` runners are much slower than the other leading to sporadic timeouts when running CTest with a debug build in the CI.

test/CMakeLists.txt: bumped CTest timeout to accommodate `macos-*` runner slowness

---

tools/donate-cpu-server.py

If the upload result is too large it's better that the old result on the disk is removed. The old result on the disk will be invalid/deprecated in one way or another.

Fix #13027 (daca@home does not handle well when results are too large)

---

lib/importproject.cpp
lib/importproject.h
test/cli/more-projects_test.py
test/cli/shared-items-project/Main/Main.vcxproj
test/cli/shared-items-project/Main/MainFile.cpp
test/cli/shared-items-project/Shared/Shared.vcxitems
test/cli/shared-items-project/Shared/TestClass.cpp
test/cli/shared-items-project/Shared/TestClass.h
test/cli/shared-items-project/Solution.sln

At work (Areus Gmbh), we use Shared Items Projects in order to deduplicate code. In contrast to conventional project files (`.vcxproj`), the compilation configuration is set by the "includee", which makes the code-reuse of the project more flexible.
This pull-request adds support for Shared Items Projects (`.vcxitems`) in Visual studio projects / solutions. 
The idea is that for each `.vcxproj`, we check for referenced shared items projects. When all the source files and include paths are build, we add the ones defined in the referenced `.vcxitems`. 
The implementation probably isn't 100% robust, but this works for our projects and could serve as a starting point :)
I apologize for the commit history - it's a bit wonky as we currently still use 2.11. I tried to merge the changes to the …

Added Support for Shared Items Projects

---

lib/valueflow.cpp
test/testcondition.cpp

@pfultz2 Is there a better way to handle this?

Fix #12937 FP knownConditionTrueFalse for flags linked by condition

---

cli/CMakeLists.txt

`FILESDIR_DEF` is an actual path which should be used for installation, while `FILESDIR` is an option with default value of `OFF` which leads to files installed to `${CMAKE_INSTALL_PREFIX}/OFF/{addons,cfgs,platforms}`

fixed #13083 - correct addons and cfgs install locations

---

cli/CMakeLists.txt

`FILESDIR_DEF` is an actual path which should be used for installation, while `FILESDIR` is an option with default value of `OFF` which leads to files installed to `${CMAKE_INSTALL_PREFIX}/OFF/{addons,cfgs,platforms}`
(cherry picked from commit 5ad1d3909a2c8e633f573b862c790e06ac411aa3)

fixed #13083 - correct addons and cfgs install locations (#6764)

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/utility/format/format_error

std.cfg: Added support for std::format_error

---

lib/tokenize.cpp
test/testsimplifytypedef.cpp

We have a block `// Special handling of function pointer cast` but the simplifications are incorrect.

Fix #13094 internalError for function pointer typedef

---

test/cfg/boost.cpp

Fixes potential syntax checking in cfg tests on `macos-12` as some runners might now have Boost installed:
```
Boost found and working, checking syntax with g++ now.
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:90:49: error: expected ';' after expression
BOOST_SCOPED_ENUM_DECLARE_BEGIN(future_errc) {
^
;
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:90:37: error: use of undeclared identifier 'future_errc'
BOOST_SCOPED_ENUM_DECLARE_BEGIN(future_errc) {
^
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:92:9: error: use of undeclared identifier 'no_state'
no_state
^
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:94:47: error: expected ';' after expression
BOOST_SCOPED_ENUM_DECLARE_END(future_errc)
^
; …
```

test/cfg/boost.cpp: added missing include for `BOOST_SCOPED_ENUM_DECLARE_*`

---

Makefile
tools/dmake/dmake.cpp

see https://www.gnu.org/software/make/manual/make.html#Override-Directive

fixed #13066 - Makefile: need to use `override` when appending to variable specified on the command-line

---

.github/workflows/clang-tidy.yml
.github/workflows/iwyu.yml
.github/workflows/selfcheck.yml

```
Building CXX object gui/CMakeFiles/cppcheck-gui.dir/cmake_pch.hxx.pch
clang++-19: warning: no such include directory: '/home/runner/work/cppcheck/cppcheck/cmake.output/gui/cppcheck-gui_autogen/include' [-Wmissing-include-dirs]
```

fixed `-Wmissing-include-dirs` warning by running autogen before PCH generation in CI

---

lib/symboldatabase.cpp
test/testvarid.cpp

I wonder why all those special cases are necessary.

Fix #13139 Assert failure in valueflow.cpp::setSymbolic()

---

lib/checkersreport.cpp

Reported in https://sourceforge.net/p/cppcheck/discussion/development/thread/df3ac15077/.

checkersreport.cpp: fixed typo

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/utility/variant/monostate

std.cfg: Added support for 'std::monostate' for unusedScopedObject-check

---

cfg/qt.cfg

The compilation warnings macros disable the warning during compilation
for a certain platform and can thus be disregarded from cppcheck.

Add missing Qt compiler warning macros

---

cfg/qt.cfg

The macro `QT_USE_NAMESPACE` should expand to nothing for most Qt builds, i.e. built with an empty `QT_NAMESPACE` variable.
However if Qt is built using a custom namespace then all forward declarations must be wrapped with `QT_BEGIN_NAMESPACE` and `QT_END_NAMESPACE`. Today CppCheck defines these macros as empty, thus `QT_USE_NAMESPACE` should be empty as well.
Reference:
https://wiki.qt.io/Qt_In_Namespace

Add QT_USE_NAMESPACE macro

---

cfg/qt.cfg

The macros `QT_BEGIN_HEADER` and `QT_END_HEADER` was removed from Qt in 2012.
Empty since 2012: 
https://github.com/qt/qtbase/commit/ba3dc5f3b56d1fab6fe37fe7ae08096d7dc68bcb#diff-25c4cd4ef98b78f1b822c473dbbb29beb03092d0629b2c82982260ade1aa8521L143-L148
Removed completely in Qt6.0: 
https://github.com/qt/qtbase/commit/2584998c66f866770e0d4237828f119213aae663#diff-25c4cd4ef98b78f1b822c473dbbb29beb03092d0629b2c82982260ade1aa8521L213-L216

Add QT_BEGIN_HEADER & QT_END_HEADER macros

---

cli/cmdlineparser.cpp

this is also done in `Path::simplifyPath()`

cmdlineparser.cpp: removed unnecessary `Path::fromNativeSeparators()` call

---

Makefile
tools/dmake/dmake.cpp

this is a left-over from its removal in a17f2a6f05feb09d5e163b38e0e313396201b76b

Makefile: removed obsolete `CFGDIR` code

---

lib/checkmemoryleak.cpp
lib/tokenize.cpp
test/cfg/bsd.c

Caused inconsistent results in https://github.com/danmar/cppcheck/pull/6889

Remove simplification in combineOperators()

---

gui/resultstree.cpp

It doesn't work with Qt6.
Qt5 `QProcess::startDetached(const QString &command)` was removed and replaced with:
`QProcess::startDetached(const QString &program, const QStringList &arguments = {},
const QString &workingDirectory = QString(),
qint64 *pid = nullptr)`
Due to Qt6 default arguments, build doesn't break but we end up feeding it the wrong arguments.

fixed #13238 - GUI: Fix start application with Qt6

---

.github/workflows/CI-unixish.yml
.github/workflows/asan.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

this got excluded when I moved it to its own folder

re-added dmake sources to selfcheck

---

gui/cppcheck_ja.ts

Update Japanse translation only

Update Japanese Translation for 2.16.0

---

lib/library.cpp

As suggested by the compiler:
```
/home/runner/work/eni.os.dev/eni.os.dev/cppcheck/lib/library.cpp: In member function ‘Library::Error Library::load(const char*, const char*, bool)’:
/home/runner/work/eni.os.dev/eni.os.dev/cppcheck/lib/library.cpp:205:61: warning: useless cast to type ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’} [-Wuseless-cast]
205 |                 std::cout << "looking for library '" + std::string(fullfilename) + "'" << std::endl;
|                                                             ^~~~~~~~~~~~~~~~~~~~
```
It's already a _std::string_:
https://github.com/danmar/cppcheck/blob/main/lib/library.cpp#L201

library.cpp: avoid useless cast

---

gui/CMakeLists.txt

(cherry picked from commit a8b5307918fd76ab1b85022e38b16185d43b353b)

fixed #13298: fixed missing executable icon on Windows (#6999)

---

lib/tokenize.cpp
test/testsimplifyusing.cpp

Something like `s s;` where `s` is a type is legal C++, so I don't think we lose anything there.

Fix #13295 syntaxError with using

---

readme.md

This makes it easier to spot if these builds are actually working. And it also sneakily provides a link to the nightly build (portable and installer) for Windows.

readme.md: added badges for the scheduled jobs [skip ci]

---

.github/workflows/CI-cygwin.yml
.github/workflows/CI-mingw.yml
.github/workflows/CI-unixish-docker.yml
.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/asan.yml
.github/workflows/buildman.yml
.github/workflows/clang-tidy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/coverity.yml
.github/workflows/cppcheck-premium.yml
.github/workflows/format.yml
.github/workflows/iwyu.yml
.github/workflows/release-windows.yml
.github/workflows/scriptcheck.yml
.github/workflows/selfcheck.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml
.github/workflows/valgrind.yml

based on [zizmor ](https://github.com/woodruffw/zizmor) analysis

do not persist checkout credentials in GitHub workflows

---

lib/checkleakautovar.cpp
test/testleakautovar.cpp

Work in progress.
Just wanted to check if I'm heading in the right direction and using the
internal API correctly.
Is there a way to check if a variable is a pointer to a pointer?

fix #11542: FP memleak when using memcpy() with pointer

---

lib/astutils.cpp
lib/astutils.h
lib/checkother.cpp
lib/token.cpp
lib/token.h
test/testother.cpp

Would love to get som feedback on this since it's making quite bold assumptions about expression that depend on template arguments.

Fix #13326: FP shiftNegative for template argument

---

cfg/googletest.cfg
test/cfg/googletest.cpp

Add `TYPED_TEST` and `TYPED_TEST_P` macro definitions (see http://google.github.io/googletest/reference/testing.html).

googletest: add TYPED_TEST macros

---

lib/checkstl.cpp
test/teststl.cpp

Co-authored-by: Paul Fultz II <pfultz2@yahoo.com>

Fix #13327 FN mismatchingContainers for struct member and c_str()

---

.github/workflows/CI-unixish.yml
.github/workflows/CI-windows.yml
.github/workflows/asan.yml
.github/workflows/tsan.yml
.github/workflows/ubsan.yml

these steps were added after I opened the initial PR

added missing `pytest-xdist` usage in CI

---

lib/checkother.cpp
test/testother.cpp

_Static_assert (deprecated in C23) should be treated like static_assert.

Ignore knownConditionTrueFalse in static assertions

---

lib/checkother.cpp
test/testother.cpp

Correct previous by honoring _Static_assert (introduced in C11) in C.

Fix detection of _Static_assert() in C

---

lib/checkcondition.cpp

exposed by compiler error with `USE_BOOST_INT128` enabled

checkcondition.cpp: fixed signedness in conversion in `checkIncorrectLogicOperator()`

---

.gitignore
test/cli/proj2_test.py

fixes potential issues when tests are run in parallel

fixed #13461 - test/cli/proj2_test.py: use temporary folders to run tests

---

cfg/std.cfg
test/cfg/std.cpp

Reference: https://en.cppreference.com/w/cpp/algorithm/clamp

std.cfg: Added support for std::clamp()

---

lib/checkother.cpp
lib/fwdanalysis.cpp
lib/infer.cpp
lib/library.cpp
lib/mathlib.cpp
lib/pathanalysis.cpp
lib/programmemory.cpp
lib/tokenize.cpp
lib/valueflow.cpp
lib/vf_analyzers.cpp
lib/vf_common.cpp
lib/vf_settokenvalue.cpp

fixes some compiler warnings with `USE_BOOST_INT128` as those implicit conversions are not allowed

explicitly convert `MathLib::big{u}int` to/from other types / small cleanup

---

cfg/gnu.cfg

Reference: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

gnu.cfg: Added support for __builtin_bit_cast

---

cfg/std.cfg

References: 
- https://en.cppreference.com/w/cpp/filesystem/create_hard_link
- https://en.cppreference.com/w/cpp/filesystem/create_symlink

std.cfg: Added support for std::filesystem::create_* functions

---

.github/workflows/CI-unixish-docker.yml

(cherry picked from commit 4b60f81cfa812101f23b7072bca7b1deb88866e4)

CI-unixish-docker.yml: removed `ubuntu:16.04` and `ubuntu:18.04` (#6965)

---

test/testleakautovar.cpp

suddenly started to exit `testrunner` with error 2816 in the CI

disabled `TestLeakAutoVarRecursiveCountLimit` on Cygwin as well

---

lib/checkunusedfunctions.cpp
lib/checkunusedfunctions.h
samples/AssignmentAddressToInteger/bad.c
samples/AssignmentAddressToInteger/good.c
samples/autoVariables/bad.c
samples/autoVariables/good.c
samples/incorrectLogicOperator/bad.c
samples/incorrectLogicOperator/good.c
test/testunusedfunctions.cpp

Currently limited to C as I assume the anonymous namespace should be favored for C++.

Detect C functions that can be declared with static linkage

---

lib/symboldatabase.cpp
test/testother.cpp

The same logic also exists in `setArrayDimensionsUsingValueFlow()` (not changed yet).

Fix #13537 FP passedByValue for template type

---

cfg/protobuf.cfg

The value of this appears to be effecting the exectuable layout, so settings its value to an empty string should be fine.
It appears when generating protobuf sources sometimes.

Add PROTOBUF_PRAGMA_INIT_SEG to protobuf.cfg

---

CMakeLists.txt
cmake/findDependencies.cmake
cmake/options.cmake
readme.md
test/signal/CMakeLists.txt

and do associated cleanups.
Fixes #13343
Recent CMake versions emit:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```

fixed  #13343 - Bump `cmake_minimum_required()` to 3.13

---

gui/test/resultstree/CMakeLists.txt
gui/test/translationhandler/CMakeLists.txt
gui/test/translationhandler/testtranslationhandler.cpp

tests which require a display are now run with the `offscreen`  platform plugin.

run all Qt-based tests (in CI)

---

lib/astutils.cpp
lib/tokenlist.cpp
test/teststl.cpp

This reverts commit 841baa302eb821f2c18ca7e8929dd3779306c07a.

Revert "Fix #9157 False negative: stlOutOfBounds, cast (#7233)"

---

lib/checkclass.cpp
lib/checkinternal.cpp
lib/checkother.cpp
lib/checkother.h
lib/checkstl.cpp
lib/checkuninitvar.cpp
lib/errorlogger.h
lib/preprocessor.cpp
lib/tokenize.h

these can be considered cold paths in the optimal case i.e. no errors

removed usage of `emptyString` from error messages

---

lib/tokenize.cpp
test/testtokenize.cpp

`fp_t const fp` was previously simplified to `void (*const) () fp`, now it's `void (*const fp) ()`.

fix #12135: internalAstError with function pointer typedef

---

cfg/boost.cfg
test/cfg/boost.cpp

The **BOOST_REQUIRE** macros would not exit early and in case of a possible null pointer assignment in the condition, it would not get caught in the macro definition.
This would show false positives in next usages of the condition and show a `nullPointerOutOfMemory` warning, whereas the **BOOST_REQUIRE** would have thrown an exception.
Mimic **BOOST_REQUIRE** behavior in the macro.
Added a test for this, also the warning would not show when using `std::malloc`, but does show up when using `malloc`.

Fix BOOST_REQUIRE false positives

---

lib/token.cpp
lib/token.h
lib/tokenize.cpp
lib/tokenlist.cpp

like we do with `Token::mOriginalName`

only create or set `Token::mMacroName` if necessary

---

addons/misra.py
addons/test/misra_test.py

Added a STDLIB_IDENTIFIERS for C11 as well as updated the C99 once based on,
C99: https://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf
C11: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf
in the misra.py

Add missing STD Library Identifiers

---

lib/templatesimplifier.cpp
lib/tokenize.cpp

The function is supposed to take a simple list of characters to look for but some callers were providing a `Token::Match()`-like expression.

fixed some `Tokenizer::isFunctionHead()` parameters

---

htmlreport/cppcheck-htmlreport
test/tools/htmlreport/test_htmlreport.py

This is to fix the bug:
https://trac.cppcheck.net/ticket/8089
Title: 
feature request: Show date/time of check in HTML report
Description:
Cppcheck HTML report is a helpful tool to automate checking. It could be extended by the date/time information, when the checking was finished. This date/time information assists developers in fixing issues.

Fix #8089 (feature request: Show date/time of check in HTML report)

---

Makefile
cli/cppcheckexecutor.cpp
cli/executor.cpp
lib/cppcheck.cpp
samples/unreadVariable/out.txt
test/cli/other_test.py
test/cli/whole-program_test.py
test/testcppcheck.cpp
test/testexecutor.cpp
test/testrunner.vcxproj

The code which checks for unique error messages did not apply the template configuration which lead to suppression of unique messages:
```
(information) Cppcheck cannot find all the include files (use --check-config for details)
nofile:0:0: information: Cppcheck cannot find all the include files (use --check-config for details) [missingInclude]
```
```
(information) Cppcheck cannot find all the include files (use --check-config for details)
nofile:0:0: information: Cppcheck cannot find all the include files (use --check-config for details) [missingIncludeSystem]
```
The latter was omitted since the messages are identical.
There is possibly a different approach which would be including the ID if no template is specified. Or use the same format as when no template is specified and added the …

fixed #6366 - some unique errors were omitted

---

lib/valueflow.cpp
test/testvalueflow.cpp

Right now it just evaluates `is_void`, `is_lvalue_reference`, and `is_rvalue_reference`. More work needed to handle library types in the type traits

Evaluate type traits in valueflow

---

lib/templatesimplifier.cpp

```
/home/runner/work/cppcheck/cppcheck/lib/templatesimplifier.cpp:824:42: error: Loss of sign in implicit conversion [clang-analyzer-alpha.core.Conversion,-warnings-as-errors]
824 |                 const unsigned int pos = getTemplateNamePosition(tok);
|                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

templatesimplifier.cpp: fixed `clang-analyzer-alpha.core.Conversion` warning in `getTemplateInstantiations()`

---

.github/workflows/CI-windows.yml
.github/workflows/format.yml
.github/workflows/release-windows.yml
.github/workflows/selfcheck.yml
externals/pcre.patch

CMake 4.0 removed support for projects targeting versions prior to 3.5.

fixed building outdated (pre-3.5) CMake projects in CI

---

cfg/cppcheck-cfg.rng
cfg/gtk.cfg
gui/cppchecklibrarydata.cpp
gui/cppchecklibrarydata.h
gui/test/cppchecklibrarydata/files/memory_resource_valid.cfg
gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp
lib/library.cpp
lib/library.h
lib/valueflow.cpp
test/cfg/gtk.c

For example GLib and GTK abort on most allocation failures, making the nullPointerOutOfMemory check produce lots of false positives.
To fix this, introduce a new allocator attribute "no-fail" to notify that this allocator cannot fail and that this check is thus irrelevant for it.

Add library attribute for no-failure allocators

---

cli/processexecutor.cpp
gui/checkthread.cpp
lib/cppcheck.cpp
lib/suppressions.cpp
lib/suppressions.h
test/cli/inline-suppress_test.py
test/cli/other_test.py
test/cli/proj-inline-suppress/cfg.c
test/testsuppressions.cpp
test/tools/htmlreport/check.sh

This was initially introduced for inline suppressions but was actually used beyond that.

fixed #13660 - `SuppressionList::Suppression::checked` was not properly set in all cases

---

gui/CMakeLists.txt

brew updated Qt to 6.9.0 so we are now hitting https://bugreports.qt.io/browse/QTBUG-135637

fixed macOS Qt build

---

cmake/cxx11.cmake

this is not necessary since CMake is setting C++17 for the GUI files (regardless of the compiler)

cmake/cxx11.cmake: dropped explicit setting of C++17 for Visual Studio with Qt6

---

lib/symboldatabase.cpp
test/testsymboldatabase.cpp

Fix  #12910 FP containerOutOfBounds with overloaded template function

---

externals/tinyxml2/CMakeLists.txt
lib/xml.h

```
In file included from /home/user/cppcheck/externals/tinyxml2/tinyxml2.cpp:24:
/home/user/cppcheck/externals/tinyxml2/tinyxml2.h:442:26: warning: useless cast to type ‘size_t’ {aka ‘long unsigned int’} [-Wuseless-cast]
442 |         char    itemData[static_cast<size_t>(ITEM_SIZE)];
|                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

avoid `-Wuseless-cast` GCC warnings with TinyXML-2

---

lib/checkclass.cpp
test/testconstructors.cpp

Re `uninitVarUnion2()`: I don't see why there should be a bailout like that for unions, or any other members.

Fix  #13816 FN uninitMemberVar with union (regression)

---

lib/tokenlist.cpp
test/testtokenize.cpp

Compiling an empty initializer list as a binary operator would previously take too many tokens from the operand stack.

 fix #13775: internalError with operator new

---

addons/misra.py
addons/test/misra/misra-test.c

I am not sure why the misra check for 17.3 was reduced to while and if statements but i think that shouldn't be the case.
Now it should detect more / all functions which are implicitly called.
I had a bit of a issue with function pointer defintion as the tokens
```
int16_t ( * misra_8_2_p_a ) ()
```
cause the detection to trigger on the int16_t. But i filtered these false function pointer detection's explicitly.
I also updated the test with the expected errors. As C89 is used i needed to add more expected 17.3 as needed.
* printf_s
* UINT32_C
* va_copy
are all not present in C89. But even if we bump up to C11 this PR https://github.com/danmar/cppcheck/pull/7325 would need to be merged before hand to actually get all the needed Identifiers.

Misra 17.3 checks finds implicit function calls

---

cfg/qt.cfg

Docs at:
https://doc.qt.io/qt-6/qqmlintegration-h-qtqml-proxy.html
All macros are more or less defined to a series of Q_CLASS_INFO and a bit of extra magic mostly for the QML engine at runtime, so nothing important to expand to

Teach qt.cfg about qml integration macros

---

lib/tokenize.cpp
test/testnullpointer.cpp
test/testsimplifyusing.cpp

This
```
using A::a;
int x = B<T>::a;
```
would previously be simplified to
```
int x = B<T>A::a;
```
in `simplifyUsing`.

fix #13881: Stack overflow in findTokensSkipDeadCodeImpl()

---

lib/astutils.h

astutils.h: removed unnecessary `std::stack` usage from `visitAstNodes()`

---

lib/checkclass.cpp
lib/checkother.cpp
lib/checktype.cpp
lib/library.cpp
lib/token.cpp
lib/valueflow.cpp
lib/valueflow.h
lib/vf_analyzers.cpp
lib/vf_common.cpp
lib/vf_settokenvalue.cpp
test/testother.cpp
test/testvalueflow.cpp

Fixes https://trac.cppcheck.net/ticket/13696 + https://github.com/danmar/cppcheck/pull/6257#issuecomment-2923965239 
One could argue that the size of a member of an unknown type should be 1 instead of 0 because the member will be at least 1 byte large (if not empty and annotated with `[[no_unique_address]]`)

ValueFlow: don't reset the struct size if there is a unknown member + empty structs have a size of 1

---

Makefile
lib/cppcheck.cpp
lib/cppcheck.h
test/testcppcheck.cpp

Include addon info and premium args in analyzerinfo hash function, fixes #13889.

Fix #13889 (cached misra results are shown after removing --premium=misra-c-2012 option)

---

Makefile
lib/analyzerinfo.cpp
lib/analyzerinfo.h
test/cli/premium_test.py
test/testanalyzerinformation.cpp

Analyzer info is scanned for invalid license errors before the cache is used. Fixes https://trac.cppcheck.net/ticket/13832.

Fix #13832 (cppcheck build dir: do not reuse cached results if there were invalidLicense errors)

---

gui/threadhandler.cpp
gui/threadhandler.h

Create new `QThread`s for each check, as well as for whole-program analysis, instead of restarting finished threads which is undefined behavior (see https://doc.qt.io/qt-6/qthread.html#create). Fixes Trac #13852.

Fix #13852 (GUI does not finish analysis properly)

---

htmlreport/cppcheck-htmlreport

In cppcheck html report, points to libera.chat rather than freenode.net

IRC chan is now on libera.chat

---

cfg/qt.cfg
test/cfg/qt.cpp

Add the bool isValid() signature.
bool isValid(int, int, int) is already there.

Fix #13970 cfg/qt.cfg - add definition for QDate::isValid()

---

lib/importproject.cpp
test/cli/lookup_test.py

fixed #13941 - do not overwrite addons from CLI in GUI project import

---

.github/workflows/CI-mingw.yml

Added custom timeout for `build_mingw` job of the `CI-mingw` workflow based on historical data.
Over the last 7456 successful runs, the `build_mingw` job has a maximum runtime of 13 minutes (mean=4, std=2).
However, there are failed runs that fail after reaching the threshold of 6 hours that GitHub imposes. In other words, these jobs seem to get stuck, possibly for external or random reasons. 
One such example is [this](https://github.com/danmar/cppcheck/actions/runs/14355314540/job/40243296664) job run, that failed after 6 hours. More stuck jobs have been observed over the last six months, the first one on 2025-01-01 and the last one one on 2025-04-09, while more recent occurences are also possible because our dataset has a cutoff date around late May. With the proposed changes, a total …

Added custom timeout to ci

---

gui/resultstree.cpp

The recheck and hide options in the context menu now show how many files or errors are affected. If no files or errors are selected, the pertinent option is disabled. I've opted to count top-level header files as well since the recheck option is effective on them, they're rechecked as part of the file that included them.

Fix #1420 (GUI: Clarify results view context menu)

---

AUTHORS
lib/utils.cpp
test/testsuppressions.cpp
test/testutils.cpp

https://github.com/danmar/cppcheck/pull/7645 added support for `**` matching path separators, but didn't update `isValidGlobPattern` for `--suppress` to enable it.
This also updates test cases and makes `isValidGlobPattern` more correct and robust overall. In particular multiple consecutive `?` for a glob is absolutely valid and frequently useful to ensure exactly or at least some number of characters.

Make isValidGlobPattern recognize `**`

---

cli/filelister.cpp
lib/pathmatch.cpp
lib/pathmatch.h
lib/suppressions.cpp
test/testpathmatch.cpp

This is an addendum to #7645 that adds the ability to specify directory-only matching in PathMatch patterns with a trailing slash. I originally didn't add this because I wanted to keep PathMatch purely syntactic, and this feature seemed like it would require filesystem calls in the PathMatch code.
This PR solves that problem by lifting the responsibility of file mode checking to the caller, thus keeping PathMatch purely syntactic while still supporting directory-only matching.
Previously `/test/foo/` would match `/test/foo` even if `foo` is a regular file. With this change the caller can specify the file mode of the file named by the provided path, and `/test/foo` will only match when the file mode is directory.
The semantics of patterns that do not have a trailing slash is unchanged, …

Fixup #14021 (Add file mode specifier to PathMatch)

---

lib/token.cpp

```
/Users/runner/work/cppcheck/cppcheck/lib/token.cpp:1611:21: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
1611 |                     sprintf(str, "\\x%02x", c);
|                     ^
/Applications/Xcode_16.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
| ^ …
```

token.cpp: use `snprintf()` to fix `-Wdeprecated-declarations` AppleClang warning

---

test/signal/test-signalhandler.cpp
test/signal/test-signalhandler.py

```
/Users/runner/work/cppcheck/cppcheck/test/signal/test-signalhandler.cpp:20:9: error: macro is not used [-Werror,-Wunused-macros]
20 | #define _GNU_SOURCE // required to have feenableexcept()
|         ^
```

test-signalhandler.cpp: fixed `-Wunused-macros` warning on macOS

---

gui/CMakeLists.txt
gui/test/resultstree/CMakeLists.txt

example:
```
/home/runner/work/cppcheck/cppcheck/cmake.output.tinyxml2/gui/test/resultstree/__/__/moc_threadhandler.cpp: In static member function ‘static void ThreadHandler::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/runner/work/cppcheck/cppcheck/cmake.output.tinyxml2/gui/test/resultstree/__/__/moc_threadhandler.cpp:100:51: error: useless cast to type ‘using _t = void (class ThreadHandler::*)()’ {aka ‘void (class ThreadHandler::*)()’} [-Werror=useless-cast]
100 |             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&ThreadHandler::done)) {
|                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

avoid `-Wuseless-cast` GCC warnings in Qt mocs

---

lib/path.cpp

building with the GUI enabled will implicitly switch the standard to C++17.
```
/home/runner/work/cppcheck/cppcheck/lib/path.cpp: In function ‘bool hasEmacsCppMarker(const char*)’:
/home/runner/work/cppcheck/cppcheck/lib/path.cpp:246:40: error: useless cast to type ‘char*’ [-Werror=useless-cast]
246 |         const char * const res = fgets(const_cast<char*>(buf.data()), buf.size(), fp);
|
```

path.cpp: fixed `-Wuseless-cast` GCC warning with C++17

---

Makefile
tools/dmake/dmake.cpp

this was blowing some builds (including the selfcheck) in the CI.

Makefile: disabled usage of `_GLIBCXX_DEBUG` for now

---

cmake/compileroptions.cmake

```
error: include location '/usr/local/include' is unsafe for cross-compilation [-Werror,-Wpoison-system-directories]                               ^
```

disabled `-Wpoison-system-directories` AppleClang warnings until version 15

---

man/manual.md

Tables apparently need an empty line above. Also added some missing pipes for consistency.

fix #14153: Table of .cfg files is broken in manual.pdf

---

tools/matchcompiler.py

```
/home/user/CLionProjects/cppcheck/cmake-build-relwithdebinfo-clang/lib/build/mc_checkinternal.cpp:7:20: warning: unused function 'match1' [-Wunused-function]
7 | static inline bool match1(const Token* tok) {
|                    ^~~~~~
```

mitigated `-Wunused-function` Clang warnings with code added by matchcompiler
