test/testsymboldatabase.cpp
The current code simply does nothing
=> Resolve CID 1265723

lib/valueflow.cpp
The current code is unreasonably hard to debug
=> Cache and reuse value

lib/checkbufferoverrun.cpp
These casts seem to serve no purpose and only clutter the code
=> Remove redundant casts

gui/applicationlist.h, gui/checkstatistics.h, gui/checkthread.h, gui/csvreport.h, gui/erroritem.h, gui/logview.h, gui/platforms.h, gui/project.h, gui/projectfile.h, gui/report.h, gui/resultstree.h, gui/resultsview.h, gui/scratchpad.h, gui/statsdialog.h, gui/threadhandler.h, gui/translationhandler.h, gui/txtreport.h, gui/xmlreport.h, gui/xmlreportv1.h, gui/xmlreportv2.h, lib/check.h, lib/checkclass.cpp, lib/checkclass.h, lib/tokenlist.h, lib/valueflow.cpp, lib/valueflow.h, test/testclass.cpp, test/testsuite.h
Hello,
My name is Jakub Melka and I want to help with the CppCheck development. I tried to create a patch for ticket #695 - new check for explicit constructors. I hope it will be helpful.
Best regards,
Jakub Melka
=> Ticket #695: new style check : explicit declaration of ctor

Cppcheck.xcodeproj/project.pbxproj
Hi,
Though I use it very rarely now, I've noticed that the XCode project file was outdated. This trivial patch synchronises the source file list and enables C++11 mode, which restores the build from the IDE. Thanks to consider merging.
Cheers,
Simon
=> Update XCode project

lib/checkbufferoverrun.cpp
This was introduced with merging https://github.com/danmar/cppcheck/pull/559
=> Avoid value truncation

gui/gui.pro, gui/main.ui, gui/mainwindow.cpp, gui/mainwindow.h, gui/printablereport.cpp, gui/printablereport.h, gui/resultsview.cpp, gui/resultsview.h
Added Print... and Print Preview... actions to main window
Added PrintableReport responsible for formatting of ErrorItems and
exposing of the formatted text as QString that can be used for printing (through a QTextDocument)
=> #2274 GUI: Printing support

gui/resultstree.cpp, gui/resultstree.h
Note: This also fixes the Copy full path context menu item (was only
putting file name into clipboard)
=> Added context menu item Open containing folder (Ticket #2913)

test/testbool.cpp, test/testother.cpp
Hi,
The two cases in this ticket have been fixed by some past commit, and this patch adds them to the unit test suite. Thanks to consider merging.
Cheers,
Simon
=> Ticket #6588: Added test cases since the initial issue is fixed

test/testuninitvar.cpp
Hi,
This ticket is a duplicate of #6680 that's now fixed (see https://github.com/danmar/cppcheck/pull/594), and this PR adds the reported case to the test suite. Thanks to consider merging.
Cheers,
Simon
=> Ticket #6463 (dupe of #6680): Added test case.

test/testbool.cpp
Hi,
This ticket is a duplicate of #6588 that's now fixed (see https://github.com/danmar/cppcheck/pull/608), and this PR adds the reported case to the test suite. Thanks to consider merging.
Cheers,
Simon
=> Ticket #6665 (dupe of #6588): Added test case.

lib/checkcondition.cpp
Profiling shows the function gets about 10 percent faster on some random ton of code.
=> Run cheaper checks first

lib/checkother.h
This was erroneously submitted as an earlier PR.
=> Remove unimplemented method

gui/projectfile.ui
Added tooltip with explanation on how to separate defines.
=> GUI Projectfiledialog: Added tooltip

cfg/microsoft_sal.cfg
Added parameters where they were missing. Added some more annotations.
Renamed _Deref_inout_range_(low, hi) to _Deref_ret_range_(low, hi), the
MSDN seems to be wrong here as no sal.h i know contains the first one,
but the latter one.
=> microsoft_sal.cfg Bugfixes and enhancement

lib/symboldatabase.h, lib/token.cpp, lib/token.h
`static_cast` can be used to add `const` but `const_cast` is more explicit for that. Also `startTok` better explains the parameter meaning.
=> Use const_cast to add const, better variable name

lib/checkclass.cpp, test/testclass.cpp
Hi,
This test case highlights some logic issue in https://github.com/danmar/cppcheck/pull/650, that this patch fixes. Sorry for the oversight, and thanks a lot to @amai2012 for the report!
Cheers,
Simon
=> Ticket #6953: Fixed flawed logic in PR#650.

lib/errorlogger.cpp
Current implementation would not advance past replaced part as explained here https://github.com/danmar/cppcheck/commit/969b1bfbe933e7f73ded221d3949930321b693fb#commitcomment-13018142
=> Further fix search replace

lib/checkother.cpp
This makes the function about five times faster on some random pile of code
=> Quick check to omit useless heavy matches

lib/checkother.cpp, lib/checkstring.cpp, lib/tokenize.cpp
These changes make containing functions run 2-5 times faster
=> Omit unneeded match checks

lib/tokenize.cpp
All these casts back and forth and minus one plus one magic are rather hard to understand and not necessary in the first place.
=> Simplify overengineered search-replace code

lib/checkio.cpp
This makes code slightly easier to read and debug
=> Temp variables, better names

lib/tokenize.cpp
These changes make the function run about 7 percent faster on some random pile of code and also make it much easier to debug.
=> Use temp variables, better variable names

lib/checkunusedvar.cpp, lib/checkunusedvar.h, test/testunusedvar.cpp
I find it extremely annoying that the program knows if it's struct or union and still says "struct or union" as if "you go find it out".
=> Tell if it's struct or union

Cppcheck.xcodeproj/project.pbxproj
Fix xcode project file and project build, which was broken in commits:
c2a15ac2869a25d6850c514ddba9ce9e413708e2
57d1196386ffee93d1946f34fb105d64ae5e1742
b1385dd95146f451e1f3a43f7814981ad6b04cc9
96c3c111fcd5a94fd30c5374cf40bbbeb546ee60
=> Fix xcode project file

lib/symboldatabase.cpp
Now that these two pieces of code do exactly the same, extract duplicate code into a function.
=> Extract duplicate code

gui/cppcheck_ja.ts
Update Japanese translation xml file in gui/cppcheck_ja.ts , thanks a lot
=> add translations in Japanese

lib/preprocessor.cpp
This makes code a bit cleaner and consistent with surroundings
=> Use arrow as in surrounding code

lib/checkclass.cpp, lib/checkclass.h
I'm not sure but looks like list is being used as a set for no good in the original code.
=> Use set instead of list

lib/checkclass.cpp
The call to `find()` inside `if (!baseDestructor) {` was redundant because no null pointers were ever added to the set.
=> Cleanup variable names, omit redundant actions

lib/tokenize.cpp
This notably reduces number of `Match()` calls by about one fourth and deduplicates the match patterns and the code which changes the token attributes.
The original code would not remove `std::` for  `uintmax_t/intmax_t` which is most likely a bug.
=> Merge overlapping patterns

gui/cppcheck_fr.ts
It is just a clean version of this previous request (#762).
I added new French translations.
Everything in one commit.
=> New translations (french)

man/manual-ja.docbook, man/manual.docbook
add literal tags and fix Japanese sentences
=> Fix man ja

man/manual.docbook
a description of "severity" is too short to understand
=> add short description

man/manual-ja.docbook
update manual.docbook in English and then re-translate it into Japanese
=> fix manual.docbook in Japanese

lib/tokenize.cpp, test/testsimplifytypedef.cpp
typedef expansion in cast operator was not processed correctly
=> - fix for #5749 defect: internal error

gui/translationhandler.cpp
Check Qt version on compile time, and translate text for current Qt version.
=> Translate text for current Qt(not both Qt4 & Qt5).

gui/cppcheck_ru.ts
=> Updated russian translation.

test/testunusedvar.cpp
https://github.com/danmar/cppcheck/pull/833 also fixed this ticket, hence just added the test case
=> Ticket #7557: Test case added since the fix for #7541 also fixed this.

addons/cppcheckdata.doxyfile, addons/y2038/README, cli/cppcheckexecutor.h, gui/test/data/benchmark/simple.cpp, lib/checkassert.cpp, lib/checkbufferoverrun.cpp, lib/tokenize.cpp, lib/tokenize.h, lib/tokenlist.cpp, lib/valueflow.cpp, test/test64bit.cpp, test/testcondition.cpp, test/testgarbage.cpp, test/testincompletestatement.cpp, test/testnullpointer.cpp, test/testother.cpp, test/testsimplifytemplate.cpp, test/testsimplifytokens.cpp, test/testtokenize.cpp, test/testtype.cpp, test/testvalueflow.cpp
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos in comments (found by codespell)

lib/importproject.cpp
--project option will now accumulate defines/includes of all applicable
item definition groups, and will push back FileSetting items per project
configurations only
=> Fixed #7791 (Cppcheck does not expand Visual Studio macros):

tools/daca2.py
Use `argparse` and `logging` modules to clean up daca2 a bit.
=> daca2: Few cleanup changes

lib/symboldatabase.cpp, test/testtokenize.cpp
Trivial patch for this crash on valid C code.
=> Ticket #7850: Properly handle C functions called "class".

lib/cppcheck.natvis, lib/cppcheck.vcxproj, lib/cppcheck.vcxproj.filters
It beautifies debug information in "Watch" panel.
**Before:**
**After:**
=> Added cppcheck.natvis file for human readable debug information in Visual Studio

test/testclass.cpp
The issue reported in this ticket is not present anymore. I'm just adding the associated snippet as a test case.
=> Ticket #7465: Added test case highlighting the issue has been fixed

lib/symboldatabase.cpp
Print out ValueType for variables and function return type.
Print out complete type for variables and function return type.
Print out ValueType for variable auto token.
=> Add ValueType and auto type information to debug output.

lib/path.cpp
=> Add OpenCL support

cfg/wxwidgets.cfg
- Added more string constant encapsulation macros (required for format string check to work with these macros)
- Added more format string functions (including log functions)
- Added assert macros
- Added type limits and definitions
=> Updates to wxwidgets.cfg file

cli/cppcheckexecutor.cpp, lib/checkbufferoverrun.cpp, lib/utils.h
Rebased and used macro instead of template function. Hope I'm not wrong with macro - I'm not any good in writing them.
=> Fix warnings

lib/timer.cpp, lib/timer.h
=> Add Timer copy constructor

lib/importproject.cpp
Fixed importing vcxproj that contains files with absolute pathes.
=> Fix absolute pathes import from vcxproj

cli/cppcheckexecutor.cpp, lib/path.cpp, lib/path.h
=> Return non-const object

lib/checkfunctions.cpp, lib/platform.h, lib/valueflow.cpp
@danmar Any objections against such change? Perhaps the new functions should have some other names?
=> Extract and reuse char limits computation

lib/checkleakautovar.cpp, test/testleakautovar.cpp
I ran into an issue where conditional allocation inside an if-condition was not tracked properly resulting in missed leaks and a false positive double free. 
I have added a couple of test cases and a fix for these.
=> Fix for conditional memory allocation inside if-condition

test/testio.cpp
Will push this myself if tests pass
=> Improve test coverage for unsigned ptrdiff_t used as scanf read target

lib/tokenize.cpp, test/testgarbage.cpp
Trivial patch fixing #8255. Please consider merging.
=> Ticket #8255: Don't crash upon invalid code while checking conditions.

gui/resultsview.cpp, gui/resultsview.h
Add custom context menu to analysis log with an entry to clear the log.
=>  GUI: Add clear log context menu entry

gui/resultsview.cpp, gui/resultsview.h
*Add context menu entry for copying selected log entry
*Add context menu entry for copying the complete log
*Do not show context menu if analysis log is empty
*Renamed function log_clear to logClear so it matches the coding style
in the GUI
=> GUI: Enhance context menu for analysis log

test/cfg/std.c
Add tests for verifying that the bufferoverrun tests are correct.
=> Add missing tests for strncpy

lib/token.cpp, test/testgarbage.cpp
We were not trying hard enough to detect cycles in AST. This patch fixes this.
=> Ticket #8352: Properly detect AST cycles.

lib/cppcheck.cpp, test/testcppcheck.cpp
purgedConfiguration was not showing up in the GUI supression list.
=> Add purgedConfiguration to list of error ids.

AUTHORS
My last name and my first name were written twice.
Let me clarify:
- my first name is Luxon
- my last name is Jean-Pierre
--
=> AUTHORS: fix my name

gui/cppcheck_fr.ts
GUI: added new french translations
=> new french translations

cfg/windows.cfg, test/cfg/windows.cpp
Add Windows Socket 2 type/function configuration. There are still many
(microsoft specific) socket functions that are not yet configured.
Add configuration for GetUserName(), GetWindowText() and _fileno().
On Windows __wchar_t is a synonym for wchar_t, so an according define is
added.
=> windows library: Mainly add socket functions, some other stuff and tests

gui/cppcheck_ja.ts, man/manual-ja.docbook
Japanese Translation updated to 1.82
=> Cppcheck_ja.ts is updated 

lib/platform.cpp
I suggested this change here:
https://trac.cppcheck.net/ticket/8242#comment:7
=> platform.cpp: Fix that platform files on Windows are not found

gui/resultstree.cpp, gui/resultstree.h
As requested in ticket 7947 (https://trac.cppcheck.net/ticket/7947) also
copying the line nr is implemented.
=> GUI: Add context menu entry for copying line nr

gui/mainwindow.cpp, gui/scratchpad.ui
This adds labels with short explanations on how the scratchpad can be
used.
=>  GUI: Scratchpad: Add help texts; run astyle

cfg/windows.cfg
Additionally a few minor issues are fixed.
=> windows.cfg: Add missing documentation and returnValue types

cfg/windows.cfg, test/cfg/windows.cpp
I am not really happy with the tests of the new macros, but otherwise do
not know how to improve them at the moment.
=> windows.cfg: Add some commonly used macros

lib/valueflow.cpp, test/testvalueflow.cpp
This doesn't add limit to the valueflow type, but it at least adds the boundary conditions as known values.
=> Improve valeflow analysis with comparison operators

cfg/qt.cfg
I have not found any issues with the macros other than the one I
reported here: https://trac.cppcheck.net/ticket/8479 (no show stopper,
but would be nice to work properly).
=> qt.cfg: Add/Enhance Qt macros and functions

cfg/posix.cfg
Add not-bool function argument configuration where appropriate to catch errors like this: https://github.com/git-for-windows/git/commit/df4ca5fb72ad062480fa1ba6556e2f7ca8da5acb
=> posix.cfg: Add not-bool to last arguments where appropriate.

addons/misra.py, addons/test/misra-test.c
Added Misra C rule 5.2 (Ticket 8554)
=> Added rule 5.2

cfg/windows.cfg, test/cfg/windows.cpp
Reference: https://msdn.microsoft.com/en-us/library/windows/desktop/ms647492(v=vs.85).aspx
=> windows.cfg: Add lstrlen() configuration and tests.

addons/misra.py, addons/test/misra-test.c
I have tried implementing rules 21.6 and 21.10.
=> Added rule 21.6 and 21.10

addons/misra.py, addons/test/misra-test.c
=> Updated rule 10 4

addons/cppcheckdata.py, addons/misra.py, addons/test/misra-test.c
=> Modified rule 11.4

lib/checkleakautovar.cpp, lib/checkleakautovar.h, test/testleakautovar.cpp
checkleakautovar.cpp:
* added `isFunctionCall` (supports template functions)
* smart pointer check in `functionCall`
* updated test case
=> Fixed #8262: false positive memleak (`shared_ptr` in function argument)

addons/cppcheckdata.py, addons/misra.py
I have to add global var to misra.py but there already was other related to suppression.
Also I had to fix some errors in cppcheckdata itself, but because there were even some syntax errors I do not think any other addon will be affected.
=> MISRA - support for per file/line error suppression

lib/checkbool.h, lib/checkother.h, lib/checkstl.h
Partly fixes https://trac.cppcheck.net/ticket/7772.
=> Add some missing errors to --errorlist output.

gui/cppcheck_ja.ts
update Japanese Translation file cppcheck_ja.ts for v 1.84
=> update cppcheck_ja.ts for 1.84

cfg/gnu.cfg, cfg/posix.cfg, test/cfg/gnu.c, test/cfg/posix.c
Reference: http://man7.org/linux/man-pages/man2/gethostname.2.html
=> posix.cfg,gnu.cfg: Add (get|set)hostname functions.

cfg/posix.cfg, test/cfg/posix.c
References:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html
=> posix.cfg: Add some pthread_mutex_* functions.

.gitignore, CMakeLists.txt, cmake/compileroptions.cmake
=> Minor Cleanups

cfg/bsd.cfg, test/cfg/bsd.c
Reference: https://www.freebsd.org/cgi/man.cgi?query=arc4random
=> bsd.cfg: Add arc4random* functions with tests.

lib/checkother.cpp, test/testother.cpp
This will know report `Expression 'x == 3' is always true because the value of 'x' and '3' are the same.`
=> Improve message for same expressions

lib/astutils.cpp, test/testcondition.cpp, test/testother.cpp
After merging #1362, this should fix the crashes with followVar.
=> Reenable followVar

addons/misra.py
Allow rule excludes to be specified via cppcheck suppressions list
=> MISRA: Support Per file excludes from cppcheck

lib/astutils.cpp, lib/checkother.cpp, lib/checkother.h, test/testcondition.cpp, test/testother.cpp
This will fix the false negative from issue [8501](https://trac.cppcheck.net/ticket/8501).
=> Enable followVar for opposite expressions

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Only check for instantiation of template being processed rather than
count of all instantiations.
=> Fix specialized template regression.

gui/cppcheck_ja.ts
The translation file cppcheck_ja.ts is updated to v1.85.
=> cppcheck_ja.ts is updated

addons/misra.py, addons/test/misra-suppressions1-test.c, addons/test/misra-suppressions2-test.c, addons/test/path1/misra-suppressions1-test.c, addons/test/path1/misra-suppressions2-test.c, addons/test/suppressions.txt
@danmar More testing found a few issues with the per-file suppressions.
@orbitcowboy I added new test files that allow for the testing of various forms of suppression.
=> Fix per file excludes

lib/checkfunctions.cpp, test/testfunctions.cpp
Seen for example in http://cppcheck.osuosl.org:8000/cdw
=> Fix false positive: Invalid string argument with array

lib/checkcondition.cpp, test/testcondition.cpp
This fix issues [8801](https://trac.cppcheck.net/ticket/8801) and [8815](https://trac.cppcheck.net/ticket/8815).
=> Fix FPs with return conditions

lib/valueflow.cpp, test/testcondition.cpp
Fixes FP in:
```cpp
void foo(int i) {
if (i==42)
{
bar();
}
if (cond && (42==i))
return;
}
```
=> Fix issue 8841: FP knownConditionTrueFalse - Dont treat unknown function as noreturn

lib/astutils.cpp, lib/checkautovariables.cpp, lib/checkcondition.cpp, lib/checkmemoryleak.cpp, lib/checkuninitvar.cpp, lib/symboldatabase.cpp, lib/token.cpp, lib/token.h, lib/valueflow.cpp, test/testautovariables.cpp
This fixes FP with:
```cpp
void f(bool b) {
std::string s;
if(b) {
char buf[3];
s = buf;
}
std::cout << s;
}
```
=> Fix FP when copying pointer to string

lib/tokenize.cpp, test/testtokenize.cpp
Fixes https://trac.cppcheck.net/ticket/8870
=> Fix handling of `sizeof &var`

cfg/qt.cfg
Reference:
https://wiki.qt.io/D-Pointer#Q_DECLARE_PRIVATE_and_Q_DECLARE_PUBLIC
=> qt.cfg: Add macro Q_DECLARE_PRIVATE

cfg/windows.cfg
References:
https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilea
https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew
=> windows.cfg: Add support for CreateFileA and CreateFileW

.travis.yml, Makefile, tools/dmake.cpp
Clean up redundant actions in travis jobs.
=> Clean up redundant actions in travis jobs

appveyor.yml
=> Build GUI version on appveyor

tools/donate-cpu-server.py
=> donate-cpu-server.py: Provide HEAD report (similar to diff report)

tools/donate-cpu.py
There should not be functional changes.
=> donate-cpu.py: Fix some PEP 8 and other warnings

tools/donate-cpu.py
It is interesting what libraries, how many jobs, ... were used during analysis.
=> donate-cpu.py: Add Cppcheck cmd line options to the output

tools/donate-cpu-server.py
There should be no functional changes.
=> donate-cpu-server.py: Fix some PEP 8 and other warnings

tools/donate-cpu-server.py
Changes:
- Rename "time" page to "time.html" to avoid conflict with "time" package
- Output content as HTML instead of plain text
- Format head row of preformatted table bold
- Show factor for total time now too
Tested locally
=> donate-cpu-server.py: Time report: Further improvements and fixes

tools/donate-cpu.py
Save some system information which could help debugging the donate-cpu scripts and Cppcheck.
=> donate-cpu.py: Save some system / platform information

tools/triage/mainwindow.cpp, tools/triage/mainwindow.h, tools/triage/mainwindow.ui, tools/triage/readme.txt
The user now can choose to "Load from file" or "Load from clipboard".
readme.txt has been updated.
=>  triage tool: Add "Load from clipboard" functionality

tools/donate-cpu-server.py
Column width can now be easily changed via the `column_width` array.
Increased column width for the packages column so it is more likely that the date is not dropped.
Increased the column width for the number of results since there are packages which have about 100000 results.
=> donate-cpu-server.py: Enhance formatting of latest.html output

test/testcondition.cpp
Ticket #6904 was fixed in 34dbc3c00ceac490c54e68e767104c04341e3f58.
Add a regression test to make sure it doesn't reappear.
=> Add regression test for #6904

test/testcondition.cpp, test/testother.cpp
Ticket #6906 was fixed in f65cf220ba05c84a0dc0c8376c29455939408197.
Add a test to make sure there are no regressions.
=> Add regression test for #6906 and #7284

test/testother.cpp
Add a regression test for [#8205](https://trac.cppcheck.net/ticket/8205). Also fix the reference to the Trac ticket referenced in the test case added in 8356ec677490b119231cf25c93693dc2751ff8d6 (as pointed out by @firewave).
=> 8205 regression test

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Use right token when searching for template type alias to delete.
=> template simplifier: fix crash on windows

cfg/qt.cfg, test/cfg/qt.cpp
=> qt.cfg: Add support and tests for QFile::exists function

test/testclass.cpp
Ticket #7714 was fixed in ea215c3b7b338f3b88f49c517de00bc0bf306ffc.
Add a regression test to make sure it stays fixed.
=> Add regression test for #7714

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/container/map/count
Found via daca@home
=> std.cfg: Add support for std::map::count()

tools/donate-cpu.py
Using a list and join it in the end is really much faster when there are several hundred or thousands of strings.
=> donate-cpu.py: Optimize string concatenation (use list)

man/manual-ja.docbook
version up only : v1.87 dev to v1.87
=> change version number on manual-ja.docbook

cfg/std.cfg, test/cfg/std.cpp
Reference: https://en.cppreference.com/w/cpp/string/basic_string/assign
=> std.cfg: Add support for std::string::assign()

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/string/basic_string/replace
=> std.cfg: Add support for std::string::replace()

cfg/qt.cfg, test/cfg/qt.cpp
Reference:
https://doc.qt.io/qt-5/qtglobal.html#forever
https://doc.qt.io/qt-5/qtglobal.html#Q_FOREVER
=> qt.cfg: Add support for macros `forever` and `Q_FOREVER`

tools/triage/main.cpp, tools/triage/mainwindow.cpp, tools/triage/mainwindow.h
These are mainly readability and optimization changes.
=> triage: Implement Clang-Tidy and Clazy hints

tools/donate-cpu.py
As discussed here https://github.com/danmar/cppcheck/commit/bdfc20a482ed1b9639e0e47fa916b63485ebd583
=> donate_cpu: Refactor library checks

cfg/boost.cfg
Many updates to the boost library. The definition of boost containers introduces a dependency on std.cfg.
=> Boost library definitions

cfg/cppcheck-cfg.rng, cfg/motif.cfg, cfg/windows.cfg, cfg/wxwidgets.cfg
This fixes https://trac.cppcheck.net/ticket/8985 at least for the
function configuration.
Errors in configuration files found by the new relaxng file are fixed.
=> Library configuration validation: Enhance relaxng file, fix *.cfg files.

cfg/std.cfg
References:
https://en.cppreference.com/w/cpp/container/vector/swap
https://en.cppreference.com/w/cpp/algorithm/swap
=> std.cfg: Add support for std::vector::swap() and std::swap()

cfg/qt.cfg
Add two Qt macros that were missing
=> Add missing Qt macros

cfg/std.cfg
Reference:
https://en.cppreference.com/w/cpp/container/vector/assign
=> std.cfg: Add support for std::vector::assign().

test/options.cpp, test/options.h
=> test/options: Rename member variables

lib/checknullpointer.cpp
When 2019 is about to end and it's time to summarize the most important changes in cppcheck during the year, please don't forget this PR.
=> checknullpointer: Remove duplicated include

cfg/qt.cfg
=> qt.cfg: add logging macro definition

.travis.yml
As tested by @matthiaskrgr in the branch
https://github.com/matthiaskrgr/cppcheck/commits/travis_xenial
=> .travis.yml: update to xenial; add jobs for ubsan and asan

readmeja.md
readmeja.md is Japanese version of readme.md
=> add readme translation in Japanese

cfg/gtk.cfg, test/cfg/gtk.c
Also add / improve corresponding function configurations and some tests.
=> gtk.cfg: Add support for g_new() and similar macros.

.travis.yml, addons/naming.py, addons/test/naming_test.c
Crash has been reported in the forum:
https://sourceforge.net/p/cppcheck/discussion/development/thread/138788ac6b/
A small test has been added to avoid regression.
=> addons/naming.py: Fix crash on unnamed arguments, add regex validation.

lib/astutils.cpp
This limits the recursion depth as a last line of defense to avoid stack
overflows when there are really huge arrays.
See https://trac.cppcheck.net/ticket/8922
=> Fix #8922 (SIGSEGV below exprDependsOnThis - stack overflow?)

tools/donate-cpu.py
If a command in daca@home crashes, execute it again within gdb to get a stack trace.
=>  donate-cpu.py: add stack traces for daca@home crashes / bugfixes

addons/misra.py
The misra rules files categorizes the severity of each rule.  This patch parses this information and maps it to the cppcheck violation severities.
See also https://github.com/eivindt/cppcheck/tree/misra_extra_summary_table for a patch that uses this to extend the MISRA rule violation summary.
=> Map MISRA violation categories to cppcheck categories

addons/cppcheckdata.py
=> Fix typo on readmeja.md

lib/checkbufferoverrun.cpp, lib/checkmemoryleak.cpp, lib/checkother.cpp, lib/tokenize.cpp, lib/valueflow.cpp
Note that the changes in `checkmemoryleak.cpp` were found by using the improved check in #1789.
=> Fix CheckInternal warnings

lib/valueflow.cpp, test/testvalueflow.cpp
I just reused (modified for const only, of course) the static global flow.
=> Implement #7597 - valueflow: global constant

lib/token.h, lib/valueflow.cpp, test/testnullpointer.cpp
=> Fix issue 9120: crash in valueflow smart pointers

lib/checkbool.cpp, test/testbool.cpp
Also break up the tests to smaller tests.
=> Fix #9128 (FP in return non bool with class declared in function)

htmlreport/cppcheck-htmlreport
add a "toggle all" to the html report to help filtering defects especially if you have a lot of defects.
=> add "toggle all" to the html report

lib/tokenize.cpp, lib/tokenize.h, test/testsimplifytemplate.cpp, test/testtokenize.cpp
This replaces the type intrinsic with the equivalent type trait.
=> Fix issue 9144: Syntax error with type intrinsics

lib/astutils.cpp, lib/astutils.h, lib/valueflow.cpp, test/testunusedvar.cpp
This fixes the unreadVariable FP, but it doesn't fix the stlFindInsert FN.
=> Fix issue 9150: FP with unreadVariable

lib/templatesimplifier.cpp, lib/templatesimplifier.h
Declaration to specialization mapping is still not perfect.
=> template simplifier: improve populating template specialization maps

cfg/windows.cfg
Reference:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getdlgitem
=> windows.cfg: Add GetDlgItem()

addons/cppcheckdata.py
I am not sure but it looks like "self." is missing here.
And the attribute "inconclusive" is initialized as a "bool", so i guess
"True" should be assigned here?
=> addons/cppcheckdata.py: Fix missing self, and wrong assignment.

gui/codeeditor.cpp
Styling change missed in #1913.
=> Propagate Monospaced Font to Line Number Area in Code Editor

lib/checkbool.cpp, test/testbool.cpp
=> Fix FP #9165

lib/templatesimplifier.h
Trivial error in documentation
=> Wrong argument name used in documentation

cfg/gtk.cfg
=> gtk.cfg: Add/improve g_ascii_*() functions

cfg/posix.cfg
=> posix.cfg: Add setsockopt() and getsockopt()

lib/astutils.cpp, lib/astutils.h, test/testunusedvar.cpp
Skip local class/struct definition in FwdAnalysis when looking for
reassignments.
=> Fix false positive 9167

cfg/openmp.cfg, test/cfg/openmp.c, test/cfg/runtests.sh, tools/donate-cpu.py
=> openmp.cfg: Add library configuration for OpenMP

cfg/sqlite3.cfg
Some were found missing by daca@home
=> sqlite3.cfg: Add more function configurations

cfg/qt.cfg
=> qt.cfg: Add "addWidget()" for classes Q(V|H|)BoxLayout and QGridLayout.

addons/misra.py, addons/test/misra-test.c
Rationale: https://github.com/danmar/cppcheck/commit/3ff7ef091829835be19f268310ad5a10a392e7f4#commitcomment-34225915
=> Fix MISRA 5.1 check

cfg/gtk.cfg
References:
https://developer.gnome.org/gtk3/stable/GtkBox.html#gtk-box-new
https://developer.gnome.org/gtk3/stable/GtkHBox.html#gtk-hbox-new
https://developer.gnome.org/gtk3/stable/GtkVBox.html#gtk-vbox-new
Found by daca@home
=> gtk.cfg: Add gtk_box_new(), gtk_hbox_new() and gtk_vbox_new()

cfg/std.cfg
Reference:
https://en.cppreference.com/w/cpp/utility/functional/mem_fn
=> std.cfg: Add mem_fn()

cfg/qt.cfg
Reference:
https://doc.qt.io/qt-5/qdate.html
Found by daca@home
=> qt.cfg: Add functions of class QDate

cfg/gtk.cfg
Reference:
https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html#g-object-set
=> gtk.cfg: Add g_object_set()

cfg/qt.cfg
Reference:
https://doc.qt.io/qt-5/qmap.html
=> qt.cfg: Add functions of class QMap

lib/errorlogger.h
Shortening extremely long lines in file to improve readability.
=> Edit Change lib/errorlogger.h

gui/cppcheck_ja.ts, readmeja.md
This pull request add some Japanese translation on gui/cppcheck_ja.ts only.
=> Update japanese translation

cfg/qt.cfg
This class is also used by the Cppcheck GUI.
=> qt.cfg: Add some functions of class QXmlStreamWriter

cfg/qt.cfg
This class is also used by the Cppcheck GUI.
=> qt.cfg: Add some functions of class QXmlStreamAttributes

.travis.yml, addons/pylintrc
=> Run pylint on addons providing a buld breaker on travis

cfg/qt.cfg
Reference: https://doc.qt.io/qt-5/qregexp.html
This class is also used by the Cppcheck GUI.
=> qt.cfg: Add functions of class QRegExp

cfg/qt.cfg
Some were reported missing by daca@home.
=> qt.cfg: Add/enhance functions of class QString

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/iterator/back_inserter
=> std.cfg: Fix function configuration for std::back_inserter

cfg/std.cfg
Reference:
https://en.cppreference.com/w/cpp/iterator/next
https://en.cppreference.com/w/cpp/iterator/prev
=> std.cfg: Add std::next() and std::prev()

lib/templatesimplifier.cpp, lib/tokenize.cpp, test/testsimplifytemplate.cpp, test/testsimplifytokens.cpp
Also simplify decltype of bool and numeric literals in template
arguments.
=> Fix ternary operator simplification to accept template parameters.

cfg/qt.cfg
=> qt.cfg: Add functions of class QDomElement

cfg/std.cfg
Reference:
https://en.cppreference.com/w/cpp/string/basic_string/copy
http://www.cplusplus.com/reference/string/string/copy/
=> std.cfg: Add std::string::copy() and std::wstring::copy()

cfg/qt.cfg, test/cfg/qt.cpp
Reference: https://doc.qt.io/qt-5/qvector.html
=> qt.cfg: Add container and function configurations for QVector

lib/valueflow.cpp, test/testnullpointer.cpp, test/testother.cpp, test/teststring.cpp, test/testtype.cpp, test/testvalueflow.cpp
This also fixes the FP with:
```cpp
void f(int *p, int *q) {
if (p == nullptr)
return;
else if (q == nullptr)
return;
*q = 0;
}
void g() {
f(nullptr, nullptr);
}
```
=> Re-enable valueFlowSubFunction

lib/token.h
[lib/token.h:964]: (style) Consider using std::any_of algorithm instead of a raw loop.
=> Use std::any_of in token.h

lib/valueflow.cpp, test/testnullpointer.cpp, test/testvalueflow.cpp
Example code:
```cpp
void f(int size) {
if(size>16){ 
x = size;  // possible value 42
}
}
void main(){
f(42);
}
```
=> Fix issue 8296: ValueFlow: value not set in conditional scope in subfunction

test/testcondition.cpp
Add regression test for 8634. This was most likely fixed by PR #2054.
=> Issue 8634: false negative: (style) Condition '...' is always true

cfg/qt.cfg, test/cfg/qt.cpp
Reference: https://doc.qt.io/qt-5/qbytearray.html
=> qt.cfg: Add QByteArray container configuration (similar to QString)

cfg/qt.cfg
Return values are different for these functions.
=> qt.cfg: Fix QList::at and QStringList::at configuration

cfg/qt.cfg, test/cfg/qt.cpp
Reference: https://doc.qt.io/qt-5/qlinkedlist.html
=> qt.cfg: Add QLinkedList container configuration and some tests.

cfg/gtk.cfg, test/cfg/gtk.c
Add/enhance:
g_once_init_enter(), g_once_init_leave() and g_signal_emit_by_name()
=> gtk.cfg: Add/enhance function configurations and tests.

cfg/sdl.cfg
Add/enhance types, macros, functions, …
=> sdl.cfg: Enhance SDL library configuration 

tools/donate-cpu.py
Check if fetching and updating the cppcheck sources are successful. If
not successful after five retries, print an error message and terminate
the script to avoid reporting results with old cppcheck versions.
If the script fails to update the cppcheck sources, check_call() will
print the error message and the user will have to act accordingly.
=> donate-cpu.py: Fail if unable to update cppcheck

tools/donate-cpu.py
Add more commonly used includes for SDL headers.
=> donate-cpu.py: Improve detection of SDL library usage.

.travis.yml, cfg/libcurl.cfg, test/cfg/libcurl.c, test/cfg/runtests.sh, tools/donate-cpu.py
Add most of the curl_easy* functions.
Reference: https://curl.haxx.se/libcurl/c/
=> libcurl.cfg: Add library configuration for libcurl

lib/valueflow.cpp, test/testuninitvar.cpp
This also fixes a FP with `setjmp` and `longjmp`.
=> Add more tests for valueFlowUninit

lib/templatesimplifier.cpp, lib/templatesimplifier.h, test/testsimplifytemplate.cpp
friend templates were interpreted as variable templates
=> template simplifier: ignore friend templates

lib/checkuninitvar.cpp
https://github.com/danmar/cppcheck/pull/2129#issuecomment-526916467
=> Clarify valueFlowUninit

tools/donate-cpu.py
There is no point in checking which libraries to use for each cppcheck
version since there is no change. Refactor the checking to a separate
function and run that once instead. This halves the time it takes to
check for libraries.
In the grand scheme of things, this is not going to speed up the donate_cpu
script a lot though.
=> donate-cpu: Only check libraries once

cfg/qt.cfg, test/cfg/qt.cpp
=> qt.cfg: Add some missing macro definitions

cfg/windows.cfg, test/cfg/windows.cpp
Add/fix some missing/incorrect function configurations found by
analyzing the TortoiseGit project.
Add some macros.
=> windows.cfg: Enhance/fix Windows configuration

.travis.yml, cfg/cairo.cfg, test/cfg/cairo.c, test/cfg/runtests.sh, tools/donate-cpu.py
Reference: https://www.cairographics.org/
=> cairo.cfg: Add library configuration/tests/... for cairo library

cfg/python.cfg
Add configurations for functions reported by daca@home.
Remove redundantly configured functions.
Add/improve some other function configurations.
=> python.cfg: Improve Python C API configuration

lib/exprengine.h, test/testrunner.vcxproj, test/testrunner.vcxproj.filters
Add export of executeAllFunctions() in exprengine.h
=> Windows testrunner: Add testexprengine.cpp

lib/checkleakautovar.cpp, test/testleakautovar.cpp
This was most likely introduced when the checks were changed to run on
the full tokenlist instead of the simplified one.
=> Fix #9343 (memleak FP when return with cast)

lib/checkbool.cpp, test/testbool.cpp
Detect incrementing boolean expressions involving pointer dereferences,
array element accesses, etc.
=> Fix false negatives in checkIncrementBoolean

lib/astutils.cpp, lib/astutils.h, lib/checkio.cpp, lib/checknullpointer.cpp, lib/checkuninitvar.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/valueflow.cpp, test/testnullpointer.cpp
This makes sure this works when checking for null pointers. It requires the struct to be defined since we cant know whether a variable implicitly depends on `this` without the struct definition.
=> Fix issue 2153: valueFlowAfterCondition: struct member

.travis_suppressions, lib/checkbool.cpp, lib/checkbool.h, test/testbool.cpp
Use AST-based tests in favor of token-based tests for greater coverage.
=> Fix false negatives in checkBitwiseOnBoolean

test/cfg/std.c
Related tickets:
https://trac.cppcheck.net/ticket/9408
https://trac.cppcheck.net/ticket/9410
=> test/cfg/std.c: Add nullPointer tests for vsnprintf()

cfg/gnu.cfg, test/cfg/gnu.c
Reference:
https://sourceware.org/glibc/wiki/Style_and_Conventions#Branch_Prediction
=> gnu.cfg: Add support for __glibc_likely() and __glibc_unlikely()

cfg/windows.cfg, test/cfg/windows.cpp
Reference:
https://docs.microsoft.com/en-us/cpp/cpp/alignof-operator?view=vs-2019
=> windows.cfg: Add support for `__alignof()`

cfg/kde.cfg, test/cfg/kde.cpp, test/cfg/runtests.sh, tools/donate-cpu.py
=> kde.cfg: Add KDE configuration and tests

cfg/std.cfg, test/cfg/std.cpp
Reference: https://en.cppreference.com/w/cpp/algorithm/fill_n
=> std.cfg: Add support for std::fill_n()

tools/donate-cpu-server.py
Added 2 commands to donate-cpu-server to allow client request url of any package for manual testing feature which would be implemented.
Also string strip for packages urls moved to initialization step for optimization.
=> donate cpu server: added 2 commands

addons/cppcheckdata.py, addons/misra.py, addons/test/misra/misra-test.c, lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Add MISRA R21.1 and R21.12.
These improvements were sponsored on kickstarter: https://www.kickstarter.com/projects/3300446/improve-misra-checking-2.
=> Add MISRA checks for rules 21.1 and 21.12

.travis.yml, cfg/libsigc++.cfg, test/cfg/libsigc++.cpp, test/cfg/runtests.sh, tools/donate_cpu_lib.py
Reference: https://libsigcplusplus.github.io/libsigcplusplus/
=> libsigc++.cfg: Add configuration for library libsigc++

cfg/openssl.cfg, test/cfg/openssl.c, test/cfg/runtests.sh, tools/donate_cpu_lib.py
Reference: https://www.openssl.org/docs/man1.1.1/man3/
=> openssl.cfg: Add OpenSSL library configuration with tests

tools/triage/mainwindow.cpp, tools/triage/mainwindow.h, tools/triage/mainwindow.ui
Changes:
* ui elements renamed from standard names to something logical
* find in files: show all entries in one file (dosbox has interface and impl in one file)
* added hints for file extensions filter checkboxes
* added 'your' to the version's regexp
* codestyle improvements
=> Triage cleanup

addons/cert.py, pylintrc_travis, tools/test-my-pr.py
The plan is to enable more and more useful messages and fix the issues
step by step to improve the code quality.
=> pylintrc_travis: Enable more messages and fix issues

tools/donate_cpu_lib.py
- Keep Visual Studio Solution/Project files
- Remove Linux library configurations
- Use correct path to solution file
=> Donate CPU client: Fix TortoiseSVN analysis

addons/test/misra/misra-test.cpp
https://github.com/danmar/cppcheck/commit/dbe23f878bd0b4089ef78d88088ca047d4fdc698#commitcomment-35929965
=> misra.py: Add regression test for R21.1 crash

addons/cert.py, addons/test/cert-test.c
Reference: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177
=> cert.py: Add ENV33-C

tools/dmake.sln, tools/dmake.vcxproj
This also fixes syntax errors for modern code that is not supported
by old Visual Studio IDEs/compilers.
=> dmake: Update Visual Studio solution and project

test/cfg/openssl.c
This is to test that the fix actually works in Travis
=> Fix -Wint-conversion warning

addons/test/misra/misra-test.c
Add some more tests for rule 10.1. They are given as examples in the
MISRA document.
=> misra-test.c: Add more tests for rule 10.1 (including FP and FN)

test/cfg/gnu.c
This is to test if it works in Travis
=> Fix conversion warning

gui/checkthread.cpp
This adds an entry to the "Analysis Log" and prints a message via
`qWarning()` when the execution of an addon fails because either the
process failed to finish normally (for example if python binary is not
found) or because the script has issues (for example because of an
unhandled exception).
=> GUI: Print and log messages when addon execution fails

gui/cppcheck_ja.ts
=> update translation in Ja

lib/tokenize.cpp, test/testgarbage.cpp, test/testtokenize.cpp
**Problem**
extern "C" typedef void function();
Resulted in syntax error. 
This will fix the garbageCollection and adds a test for it
=> Fix extern c typedef syntax error

addons/misra.py, addons/test/misra/misra-test.c
This will close [Trac9489](https://trac.cppcheck.net/ticket/9489).
=> misra.py: Fix false negative for rule 10.1

addons/misra.py, addons/test/misra/misra-test.c
This will close https://trac.cppcheck.net/ticket/9544.
=> misra.py: Fix 12.3 FP

lib/config.h
This is to test how it builds in Travis
=> Use "override" keyword in clang

lib/cppcheck.vcxproj, lib/cppcheck.vcxproj.filters, lib/symboldatabase.cpp, lib/symboldatabase.h
```
Checking lib/check.cpp: __CPPCHECK__=1...
lib/symboldatabase.h:719:5: warning: Class 'Function' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
Function(const Token *tokenDef);
^
Checking lib/templatesimplifier.cpp: __CPPCHECK__=1...
lib/symboldatabase.cpp:1754:33: warning: Condition 'settings' is always true [knownConditionTrueFalse]
const Library * const lib = settings ? &settings->library : nullptr;
^
lib/symboldatabase.cpp:1751:9: note: Assuming that condition '!settings' is not redundant
if (!settings)
^
lib/symboldatabase.cpp:1754:33: note: Condition 'settings' is always true
const Library * const lib = settings ? &settings->library : nullptr;
```
=> Fix github CI

cfg/googletest.cfg, test/cfg/googletest.cpp
As the pr title says, I added googletest MATCHER support. Also included a test for it. I am not 100% sure if it is correct.
=> googletest.cfg; add MATCHER

addons/misra.py, addons/test/misra/misra-test.c
See: [trac9581](https://trac.cppcheck.net/ticket/9581).
=> misra.py: Fix R12.3 FP in initializer lists

htmlreport/cppcheck-htmlreport
While at it, I see a lot of seemingly unused CSS.
I also want to switch to classes for styling.
So, are `#menu`, or `#content` used?
=> htmlreport: fix sticky sidebar

appveyor.yml
It **should** work, but let's see...
=> Appveyor: silence testrunner

tools/donate-cpu-server.py
Also, increase the size of the package field to match the setting for
the other pages (some packages are too small to fit at the moment).
=> daca@home: Add links to packages on time page

tools/donate_cpu_lib.py
Probably easiest to view the diff without whitespace changes (since most of it is indentation).
=> donate_cpu: Use with ... as

addons/misra.py, addons/test/misra/misra-test.c
See added test case.
This commit will fix [Trac9604](https://trac.cppcheck.net/ticket/9604)
=> misra.py: Handle spaces in directive arguments

addons/misra.py, addons/test/misra/misra-test.c
This will close [Trac9609](https://trac.cppcheck.net/ticket/9609)
=> misra.py: Fix rule 20.2 false negative

lib/forwardanalyzer.cpp, test/testvalueflow.cpp
I also refactored the functions so I can reuse them for both analyze and update paths.
=> Fix issue 9637: false positive: Condition 'i<2U' is always true

addons/misra.py, addons/test/misra/misra-test.c
This will close [Trac9616](https://trac.cppcheck.net/ticket/9616)
=> misra.py: Check switch-clauses in R15.3

lib/valueflow.cpp, test/testnullpointer.cpp, test/testuninitvar.cpp
This will forward all values to the function together rather than one-by-one. 
This will fix issue 8005 and 9573.
=> Enable valueFlowSubfunction for multiple parameters

.github/workflows/coverage.yml
Upload to codecov-io.
Provide lcov results as download artifact.
=> Add code coverage to Github Actions

.travis.yml, CMakeLists.txt, externals/simplecpp/CMakeLists.txt, externals/tinyxml/CMakeLists.txt, lib/CMakeLists.txt, oss-fuzz/CMakeLists.txt, oss-fuzz/main.cpp
I am not sure if the Travis CI integration is fine this way. I can remove it.
=> fixed OSS-Fuzz builds and added CMake targets

addons/cert.py
fix for false positive if c89/c99 code is checked with cert-STR07-C
=> False positive fix

.github/workflows/CI-windows.yml
Build default target using MSBuild for now
=> GitHub action: add Windows CLI build

.github/workflows/irc.yml
Implement a notification to #cppcheck IRC channel
=> Implement IRC notification

gui/csvreport.cpp
Added a fix to place a header row in the CSV report.  The report rows also contain the Id column making it useful for sorting and finding various types of errors (for example sorting on misra types of errors).
=> Added a header row including the ID to the CSV report.

cfg/gtk.cfg
=> gtk.cfg: Add some missing macro/function configurations

addons/misra.py, addons/test/misra/misra-test.c
This will close [Trac#9673](https://trac.cppcheck.net/ticket/9673)
This example in test suite: https://github.com/jubnzv/MISRA-Example-Suite/blob/master/R_20_07.c#L29
=> misra.py: Fix 20.7 FP for struct members

addons/misra.py, addons/test/misra/misra-test.c
This will close [Trac#9703](https://trac.cppcheck.net/ticket/9703)
=> misra.py: Fix false positive for rule 15.6

tools/test-my-pr.py
Inspired by #2640, I resurrected an old branch of mine that adds a timing report per package to `test-my-pr`. I'm not sure why I never actually sent a PR when I wrote it, I think I meant to add some statistics at the end but never got around to it. I'm not sure what statistics would be good? Overall time? Average slowdown/speedup? Number of packages that increase/decrease execution time?
Sample output (comparing #2640 rebased on current master). The package column is really wide, that's because there are some packages that have a really long ftp-address pointing to them). Make sure you scroll to the right to see the numbers. 
```
Package                                                                                                                                       master    your …
```
=> test-my-pr: Add timing info

tools/matchcompiler.py
The change in token.cpp was done in f6788c047
This should fix the failures in travis.
=> Update matchcompiler after change in Token::Match

lib/checkother.cpp, lib/checkother.h, test/testother.cpp
Implemented according to [#9528](https://trac.cppcheck.net/ticket/9528)
=> feat: add modulo of one check (#9528)

gui/cppcheck_ja.ts
Add translations for Japanese only
=> Update Japanese Translation to 2.0

tools/donate_cpu_lib.py
Fixes the pylint error in the Travis build.
=> donate_cpu_lib.py: fixed Python error

addons/misra.py, addons/test/misra/misra-test.c
This will fix [Trac#9634](https://trac.cppcheck.net/ticket/9634).
=> misra.py: Fix false positives for rule 20.7

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/buildman.yml
- use upload-artifact@v2 instead of upload-artifact@v2-preview
- use -j $(nproc) on linux/macos
- provide artifacts for linux/macos
=> Githubactions update

.github/workflows/scriptcheck.yml
So far the results are presented in the log only.
=> Add github action to check shell and python scripts

cfg/microsoft_unittest.cfg
=> microsoft_unittest.cfg: Add support for Microsoft CppUnitTest library

addons/misra.py, addons/test/misra/misra-test.c
See: https://trac.cppcheck.net/ticket/9633#comment:3
=> misra.py: Fix 20.7 false positive for multi-character arguments

gui/checkthread.cpp, lib/forwardanalyzer.cpp, lib/programmemory.cpp, lib/programmemory.h, lib/token.cpp, lib/valueflow.cpp, test/cfg/qt.cpp, test/cfg/wxwidgets.cpp, test/teststl.cpp, test/testvalueflow.cpp
This also fixes issue [9243](https://trac.cppcheck.net/ticket/9243).
=> Use ForwardAnalyzer for container forward

cfg/wxwidgets.cfg
This corrects a few issues I found when using wxwidgets.cfg on my project.
=> Corrected a few macros and functions from wxWidgets

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Addresses https://github.com/danmar/cppcheck/commit/08ea6435ac01672503d8f87546636786e58d36e2#commitcomment-42013762
=> make result of <<|>> an xvalue

lib/valueflow.cpp, test/testnullpointer.cpp
=> Fix issue 9842: ValueFlow: wrong handling of ?, seems to think that the whole expression is a condition

cfg/emscripten.cfg
This adds the `EM_JS` and `EM_ASM` macros which takes javascript.
=> Add emscripten cfg

lib/checkcondition.cpp, test/testcondition.cpp
Introduced by e2a81a382f5333ba03d3d0b83be1d06728dc0f3b.
=> Fix regression in CheckCondition

addons/misra.py, addons/test/misra/misra-test.c
See: https://github.com/danmar/cppcheck/commit/79b9dd5345f0a777bc915ee215330ad6164ed6bb#commitcomment-43637256 and [trac#9958](https://trac.cppcheck.net/ticket/9958)
=> Fix and impove MISRA 6.1 and 6.2 rules

lib/checkunusedfunctions.cpp, test/testunusedfunctions.cpp
* Add test
* Ignore templates with trailing return type as well
=> Fix #9805 (False positive; Unused function (template))

.github/workflows/codeql-analysis.yml
See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
=> Add github action for Codeql analysis

addons/misra.py, addons/test/misra/misra-test.c
Closes [trac#9969](https://trac.cppcheck.net/ticket/9969)
=> misra.py: Fix R7.2 crash on va_args

lib/valueflow.cpp, test/testvalueflow.cpp
Also, add some test cases that were missing.
=> getSizeOf: Handle long double

man/manual.md
- Removal of superfluous parentheses.
- Wrap lines, albeit occasionally.
- Stylistic changes, notably legibility and sentence structure.
- Harmonise spelling, such as Cppcheck with capital C.
=> documentation updates

lib/symboldatabase.cpp
See https://en.cppreference.com/w/c/keyword and https://en.cppreference.com/w/cpp/keyword
=> updated C/C++ keywords

gui/cppcheck_ja.ts
- Add 1 new Japanese translation for newly added section
- Remove unfinished tag from Japanese translation
=> Add Japanese Translation only

.github/workflows/CI-windows.yml
and some minor refactoring of CI-windows.yml
=> Use Z3 4.8.9

.github/workflows/CI-unixish.yml, .github/workflows/asan.yml, .github/workflows/buildman.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/irc.yml, .github/workflows/scriptcheck.yml, .github/workflows/ubsan.yml
Also simplify workflow files a bit by removing matrix with single configuration.
=> Update ubuntu workflows to 20.04

appveyor.yml
Update z3 to 4.8.9 for appveyor build
=> Update z3 for appveyor build

addons/misra.py, addons/misra_9.py, addons/test/misra/misra-test.c
Implemented 9.3 and 9.4, and reimplemented 9.2 and 9.5 with this new algorithm.
=> MISRA 9.2 to 9.5

lib/checkclass.cpp, lib/checkclass.h, test/testclass.cpp
Now the check is recursive so it traverse through inheritance tree in depth first manner
=> Checking in fix for issue 9957 -  - False negative: duplInheritedMember

lib/exprengine.cpp
See: https://github.com/Z3Prover/z3/issues/4905
=> ExprEngine: Add workarounds for z3 bugs with FP comparisson

lib/exprengine.cpp, lib/exprengine.h, test/testexprengine.cpp
This PR will finish work started in https://github.com/danmar/cppcheck/pull/2956.
I added the condition branches to the loops which can be executed depending on `canBeTrue`/`canBeFalse` conditions.
=> ExprEngine: Add condition branches for the while loops

lib/valueflow.cpp
These classes can then be reused for beforeCondition in the future.
=> Refactor afterCondition handlers into to seperate classes

lib/valueflow.cpp
Not sure which we still needed to check for `__cplusplus` - possibly necessary for older compiler versions with incomplete implementations. Would be great if we know which are actually affected so it is documented next to the preprocessor checks.
I ran it locally and the following warnings came up:
```
/mnt/s/GitHub/cppcheck-fw/lib/platform.h:46:24: debug: valueflow.cpp:1337:valueFlowTerminatingCondition bailout: Skipping function due to incomplete variable LLONG_MIN [valueFlowBailoutIncompleteVar]
return LLONG_MIN;
^
/mnt/s/GitHub/cppcheck-fw/externals/tinyxml2/tinyxml2.cpp:1903:39: debug: valueflow.cpp:1337:valueFlowTerminatingCondition bailout: Skipping function due to incomplete variable OPEN [valueFlowBailoutIncompleteVar]
if ( !p || !*p || _closingType != OPEN ) {
^ …
```
=> split "valueFlowBailoutIncompleteVar" from more generic "valueFlowBailout"

.travis.yml
I wasn't able to re-open the old PR #2580 since the `master` branch no longer exists.
=> .travis.yml: use all available threads for CI builds

addons/misra_9.py, addons/test/misra/misra-test.c
=> misra: Fix crash on rule 9.x

lib/checkleakautovar.cpp, lib/checkleakautovar.h, test/testleakautovar.cpp
Mark realloced variables as realloced instead of freed. This allows
improved checking for code with realloc error handling.
If cppcheck finds an if-statement which checks the validity of the
allocated memory or resource, check if the memory/resource is
reallocated from another variable. If so, we can add checking of that
variable in the if-statement instead (or else, depending on how the
check is written). This allows to check that variable for memleaks and
double frees and other related memory errors.
This fixes #9292 and #9990 which both concern FPs with double frees
after correct error handling of realloc.`
Tested by running 500 packages with `test-my-pr`. Result is one extra memory leak detected (TP), and 10 FPs removed (5 deallocret and 5 doubleFree).
=> Improve handling of realloc in memory leak checker

lib/astutils.cpp, lib/programmemory.cpp
It reduces the total Ir from 11,102,485,396 to 9,814,777,023 when analyzing the `cli` folder.
=> various optimizations

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/release-windows.yml
See https://github.com/jurplel/install-qt-action/issues/78#issuecomment-763069838
=> use mirror for install-qt-action

test/cfg/runtests.sh
I had the fix on the branch for the other PR but hadn't pushed it yet since the Qt stuff was still broken and I was waiting for that to be merged first.
=> runtests.sh: fixed check for cppunit

.github/workflows/CI-unixish.yml, .travis_suppressions
This should mainly report `symbolDatabaseWarning`.
=> CI-unixish.yml: perform self check with --debug-warnings

lib/library.cpp, lib/library.h, lib/tokenize.cpp
Reduces the Ir from 9,511,011,013 to 9,476,122,641 when analyzing the `cli` folder.
=> some minor optimizations

lib/symboldatabase.cpp
I could not reduce the code that crashes so there is no test.
=> fix daca crash in openfst fst_test.cc

addons/cert.py, addons/misra.py, addons/misra_9.py, addons/test/test-misra.py, htmlreport/cppcheck-htmlreport, htmlreport/test_htmlreport.py, test/bug-hunting/cve.py, test/bug-hunting/itc.py, test/cli/test-clang-import.py, test/cli/test-helloworld.py, test/cli/test-inline-suppress.py, test/cli/test-proj2.py, test/cli/test-suppress-syntaxError.py, test/cli/testutils.py, tools/compare_ast_symdb.py, tools/daca2-getpackages.py, tools/donate-cpu.py
The most interesting thing is that some tests which were not run since there were functions with identical names. I tried to give them proper names on what they do and the commit messages but they could probably get more accurate names.
=> some Python cleanups based on PyCharm inspections

gui/cppchecklibrarydata.cpp, gui/cppchecklibrarydata.h, gui/test/cppchecklibrarydata/files/container_unhandled_element.cfg, gui/test/cppchecklibrarydata/files/define_valid.cfg, gui/test/cppchecklibrarydata/files/reflection_mandatory_attribute_missing.cfg, gui/test/cppchecklibrarydata/files/reflection_unhandled_element.cfg, gui/test/cppchecklibrarydata/files/reflection_valid.cfg, gui/test/cppchecklibrarydata/files/undefine_valid.cfg, gui/test/cppchecklibrarydata/resources.qrc, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, gui/test/cppchecklibrarydata/testcppchecklibrarydata.h
- Add support for reflection used by qt.cfg .
- Add some tests to TestCppcheckLibraryData.
=> Fix library data reflection

lib/tokenize.cpp, test/testsimplifyusing.cpp
This only fixes the problem in the example code. A TODO has been added for a more complex version of the example that isn't fixed but will be in follow on patches.
=> fix #10136 (debug: Executable scope 'x' with unknown function.)

tools/donate-cpu-server.py
- HTML escape the traces
- handle traces without a code line
- handle frames without a source file
- handle frames without an address
=> fixed #9965: improved stack trace overview in daca crash report

cfg/boost.cfg, test/cfg/boost.cpp
=> Additional macros

tools/donate-cpu-server.py
- added time report which lists the 50 slowest packages (excluding timeouts)
- fixed formatting of time report
- ignore *.diff files when generating reports
- cleanups
=> various daca@home improvements

.github/workflows/CI-unixish-docker.yml, .github/workflows/CI-unixish.yml, .github/workflows/asan.yml, .github/workflows/coverage.yml, .github/workflows/scriptcheck.yml, .github/workflows/ubsan.yml, .travis.yml, Makefile
I am trying to move all what we are doing in the Travis build to the GitHub actions so we can get rid of it.
=> various CI refactorings and cleanups

lib/exprengine.h, lib/valueflow.h, test/testsimplifytemplate.cpp, test/testsuite.cpp, test/testsuite.h, test/testvalueflow.cpp
This aims to fix some msvc warnings including preemptively fixing warnings caused by #3056.
=> Fix some warnings

lib/tokenize.cpp
=> fix more daca simplifyUsing hangs

tools/donate-cpu.py, tools/donate_cpu_lib.py, tools/test-my-pr.py
I pulled the safe stuff out of the other PR so they can be applied. Will update the other one as soon as I had some more time to test that stuff.
=> various daca@home client cleanups

tools/donate-cpu-server.py
This is regarding donate-cpu functionality.
=> Use v2.4 as old for comparing against latest

win_installer/cppcheck.wxs
Reported on the forum: https://sourceforge.net/p/cppcheck/discussion/general/thread/472acd6a13
=> win_installer: Add misra_9.py

test/cfg/gtk.c
As requested in comment on commit eee27b9.
=> Regression tests for PR #3258

lib/tokenize.cpp, test/testtokenize.cpp
Previously only a single regular label before a compound statement was allowed in `simplifyAddBracesPair()` after `if`/`switch`/`do`/`while`/`for`.
This patch adds support for:
* case-labels;
* labels before a single statement;
* labels before `try`/`catch` blocks;
* multiple consecutive labels.
Additionally the code for skipping a `case` label was extracted into a separate function from `simplifyLabelsCaseDefault()` and reused in `simplifyAddBracesPair()`.
=> Improve support for labels in simplifyAddBraces step

addons/misra.py, addons/test/misra/misra-test.c
Reported in the forum: https://sourceforge.net/p/cppcheck/discussion/development/thread/801dc07e59/?page=1&limit=25#a1a8
=> misra: Fix false positives for rule 8.2

gui/cppcheck_ja.ts
Add new Japanese translation for v2.5 and fix some translation only.
=> Add Japanese translation for v2.5

Makefile, cfg/std.cfg, cmake/compileroptions.cmake, lib/analyzer.h, lib/astutils.cpp, lib/astutils.h, lib/checkcondition.cpp, lib/clangimport.cpp, lib/reverseanalyzer.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/valueflow.cpp, test/testnullpointer.cpp, test/testvalueflow.cpp
Unify single value analysis with `ExpressionAnalyzer`.
=> Refactor: Remove variable analyzer

addons/misra.py
See [this topic on sourceforge](https://sourceforge.net/p/cppcheck/discussion/development/thread/f33f6138ad/)
=> Misra: improve misra.py

cli/cppcheckexecutor.cpp, cli/threadexecutor.cpp
Adding support for Haiku.
[](https://www.haiku-os.org/)
=> Add support for Haiku

lib/astutils.cpp, lib/reverseanalyzer.cpp, lib/token.cpp, lib/valueflow.cpp, lib/valueflow.h, test/testvalueflow.cpp
A symbolic value is a reference to the token and a delta. Currently, this only creates symbolic values from assignments. This will use the symbolic values to compute comparisons and subtraction.
=> Add symbolic values to ValueFlow

cfg/boost.cfg
Fix syntax error when using those macros.
=> Add macros for data and template tests

addons/misra.py, addons/misra_9.py
When trying the last cppcheck, I noticed some issues. And I managed to trace it back to a check that wants to use an attribute that is not filled in.
The fix solves the issue I saw. And I assume it would also not break the check in any way.
=> Fix issue in misra 9 x

lib/symboldatabase.cpp, test/testother.cpp, test/testsymboldatabase.cpp
This also fixes Trac ticket #10612.
=> SymbolDatabase: Fix valuetype with constexpr and auto

htmlreport/cppcheck-htmlreport
-CSS grid layout
-scrollbars
-fixed header/footer
-severity filtering
-double escaped XML entities
-git blame fix and cmd line config
-"Toggle All" behavior
=> Various changes

.github/workflows/CI-unixish.yml, .gitignore, .travis_suppressions, cli/cmdlineparser.cpp, gui/main.cpp, gui/test/filelist/filelist.pro, gui/test/projectfile/projectfile.pro, gui/test/projectfile/testprojectfile.cpp, gui/test/translationhandler/translationhandler.pro, gui/test/xmlreportv2/xmlreportv2.pro, lib/importproject.cpp, lib/importproject.h, test/cli/test-project.py, test/cli/testutils.py, test/testimportproject.cpp
It is now possible to run the Python tests from the CMake build folder.
=> Fix #9162 (Invalid --project files do not give any error)

man/manual.md
This PR fixes a deadlink in the documentation.
=> Fix deadlink in documentation

htmlreport/cppcheck-htmlreport
Some minor visual changes, additional options to filter issues and most importantly optimizations to reduce the git blame calls. Previously, there would be one (very slow) call for each issue. Now there will be only one per file. In cases where several files have many issues, this can make report generation several times faster.
=> Htmlreport changes

.gitignore, gui/cppcheck_zh_CN.ts
* Update zh_CN translation
* Add debian folder to gitignore
=> Update zh_CN translation

lib/astutils.cpp, lib/astutils.h, lib/reverseanalyzer.cpp, lib/valueflow.cpp, test/testtokenize.cpp
Function name modified. Let's see if this will pass through CI
=> Typos found by running "codespell"

lib/checkclass.cpp, test/testclass.cpp
Fix FP functionConst with extra parentheses
=> Fix FP functionConst with extra parentheses

tools/donate-cpu-server.py
These errors are (mostly) representing bugs which need to be tracked and fixed.
=> donate-cpu-server.py: added links to some important errors to overview

addons/cert.py, addons/test/cert-test.c
Closes issue [10782](https://trac.cppcheck.net/ticket/10782).
=> cert: Fix INT-31 false positive on pointer types

lib/checkclass.cpp, test/cfg/std.cpp, test/testclass.cpp
This time with the necessary check if `variable()` is null or not.
=> 10671 fix const iterator function const take two

lib/tokenize.cpp, test/testgarbage.cpp
Reduced from gcc/gcc/testsuite/g++.dg/template/crash54.C
=> Fix crash on garbage code

lib/checkclass.cpp, test/testconstructors.cpp
Not sure what `isInit()` and `hasDefault()` mean exactly. Maybe there is something amiss here?
=> Fix #10770 FP noConstructor with function pointer member

lib/symboldatabase.cpp, test/testclass.cpp
=> Fix FP missingOverride with unnamed parameters

lib/tokenlist.cpp, test/testtokenize.cpp
Regression from https://github.com/danmar/cppcheck/commit/3630e9c49d3beb34158bd18179c9536e7893a929
Found in `qsopt-ex-2.5.10.3/qsopt_ex/editor.c`.
=> Fix AST cyclic dependency [cppcheckError]

lib/astutils.cpp, lib/valueflow.cpp, test/teststl.cpp, test/testvalueflow.cpp
This also fixes some other TODO tests as well.
=> Fix 10867: false negative: containerOutOfBounds with std::array (regression)

lib/checkother.cpp, test/testincompletestatement.cpp
From `choreonoid-1.1.0+dfsg/src/Util/Vector3Seq.cpp`.
=> Fix FP constStatement with comma operator

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
Regression from https://github.com/danmar/cppcheck/commit/557263acde16f23e73dfab1505a8a8cbb105be87
=> Fix regression: wrong member variable

cli/cmdlineparser.cpp, lib/checkleakautovar.cpp, lib/suppressions.cpp, lib/tokenize.cpp, lib/valueflow.cpp, test/testsymboldatabase.cpp, test/testunusedfunctions.cpp
I filed https://trac.cppcheck.net/ticket/10881 about detecting this since it is not just a readability thing but might also affect the performance.
=> use std::string::empty()

lib/checksizeof.cpp, test/testsizeof.cpp
From `gpick-gpick-0.2.6/source/gtk/ColorComponent.cpp`.
=> Fix FP divideSizeof

lib/checkcondition.cpp, test/testcondition.cpp
incorrectLogicOperator/knownConditionTrueFalse for constexpr
=> Fix #9954 incorrectLogicOperator/knownConditionTrueFalse for constexpr

externals/simplecpp/simplecpp.cpp
This is required to finally get #3212 merged.
=> bump simplecpp

lib/valueflow.cpp, test/testvalueflow.cpp
This matches the assumption done in `CheckUninitVar::checkScopeForVariable` data flow analysis.
=> ValueFlow: Assume constant is nonzero when its negated

.github/workflows/format.yml, lib/checkclass.cpp
Idea from https://github.com/WayfireWM/wayfire/issues/1252
Output: https://github.com/chrchr-github/cppcheck/runs/6294862587?check_suite_focus=true
=> Show uncrustify diff in CI

.github/workflows/valgrind.yml
=> Disable valgrind on CI

lib/token.cpp, test/testsymboldatabase.cpp
From `guitarix-0.44.1+dfsg1/src/faust/bass_enhancer_ui.cc`.
=> Fix crash on nullptr deref

lib/token.cpp, lib/tokenlist.cpp, tools/matchcompiler.py
I see about a 5% to 7% improvement when analyzing symboldatabase.cpp.
=> Check tokType in match compiler

lib/checkstl.cpp, test/teststl.cpp
https://sourceforge.net/p/cppcheck/discussion/development/thread/3d20f2db34/
=> Fix FP containerOutOfBounds with std::map

lib/checkfunctions.cpp, test/testfunctions.cpp
Form https://sourceforge.net/p/cppcheck/discussion/general/thread/c0f52fad4e/
=> Fix FP returnStdMoveLocal

.github/workflows/scriptcheck.yml, addons/test/test-misra.py, addons/test/test-y2038.py, tools/donate-cpu.py, tools/donate_cpu_lib.py, tools/test-my-pr.py, tools/test_donate_cpu_lib.py
`ftp://ftp.de.debian.org/debian/pool/main/v/vlc/vlc_3.0.17.4.orig.tar.xz`
Before:
```
real    0m46.384s
user    0m24.469s
sys     0m18.953s
```
After:
```
real    0m31.549s
user    0m21.047s
sys     0m7.453s
```
The measurements are just for the commit which improves the `LibraryIncludes.get_libraries()` performance and I exited the process before the actual analysis.
=> donate-cpu: greatly improved `LibraryIncludes.get_libraries()` performance / some optimizations and cleanups

addons/cppcheckdata.py
* This adds `forward` and `backward` to traverse tokens.
* `astParents` to traverse parent nodes
* `astTop` to get top
* `tokAt` to get token at index
* `linkAt` to get link at index
=> Add methods to token class in addons

CMakeLists.txt, Makefile, tools/dmake.cpp
=> added make target `validatePlatforms` to CMake

lib/checkmemoryleak.cpp, lib/cppcheck.cpp, lib/preprocessor.cpp, lib/valueflow.cpp
Another piece of preparation before applying `misc-const-correctness` fixes.
=> reduced scope of some variables and avoided some copies

gui/test/data/benchmark/simple.cpp, lib/checkinternal.cpp, lib/checkinternal.h, lib/symboldatabase.cpp, lib/tokenize.cpp, lib/utils.cpp
A ticket about this has been filed upstream: https://github.com/llvm/llvm-project/issues/56996.
=> fixed some `modernize-use-emplace` false negatives with `std::stack` / removed `internalStlUsage` check

.github/workflows/CI-cygwin.yml, .github/workflows/CI-mingw.yml, .github/workflows/CI-unixish-docker.yml, .github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/asan.yml, .github/workflows/buildman.yml, .github/workflows/clang-tidy.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/format.yml, .github/workflows/iwyu.yml, .github/workflows/release-windows.yml, .github/workflows/scriptcheck.yml, .github/workflows/selfcheck.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml, .github/workflows/valgrind.yml
See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
=> reduced permissions of GitHub actions

.github/workflows/codeql-analysis.yml
See https://github.com/github/codeql-action#usage
=> codeql-analysis.yml: added missing permission

tools/donate_cpu_lib.py
I used the includes mentioned in https://trac.cppcheck.net/ticket/11276 as well as the ones used by our own code to extend the list.
I also filed a ticket about improving the library detection which might also involve tool-driven generation of these header lists as https://trac.cppcheck.net/ticket/11287.
=> fixed #11276 (donate-cpu: Improve library detection)

lib/astutils.cpp, lib/astutils.h, lib/checkcondition.cpp, lib/valueflow.cpp, test/testcondition.cpp
The logic was getting quite complicated and a lot of it was duplicating checks we were already doing.
=> Refactor knownConditionTrueFalse check and isUsedAsBool function

.github/workflows/CI-unixish.yml
The others still have various issues which need to be addressed first so I split this from #4418.
=> CI-unixish.yml: use `ccache` for some macos builds / cleanups

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, .github/workflows/asan.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml, .gitignore, .selfcheck_suppressions, test/cli/test-helloworld.py, test/cli/test-other.py, test/testbool.cpp, test/testsimplifytokens.cpp, test/testtokenize.cpp, test/testvalueflow.cpp, tools/triage/triage.pro
This also includes xfail tests for https://trac.cppcheck.net/ticket/11283.
=> selfcheck : cleaned up some suppressions, fixed warnings and some cleanups

.github/workflows/CI-windows.yml
This also gets rid of the dummy steps which did nothing.
=> CI-windows.yml: untangled Qt and regular builds

lib/valueflow.cpp, test/testvalueflow.cpp
From `nitrokey-authenticator-1.2.3/test/qt_specific/nitrokeyprovidertest.cpp`.
=> Fix ValueFlow crash

test/testcmdlineparser.cpp
Extracted from #4464 as it uncovered a bunch of issues.
- added more `--platform=` tests
- check output of all tests
- mitigated some TODOs partially by adding additional proper tests
- added some TODOs
- disabled some faulty/flaky tests (fixes will be provided in different PRs)
=> improved `TestCmdlineParser`

lib/analyzerinfo.cpp, test/testanalyzerinformation.cpp
per: https://sourceforge.net/p/cppcheck/discussion/development/thread/93b085f970/
(added unit tests)
=> Fix sense of test (.analyzerinfo files get placed in wrong directory)

.github/workflows/CI-unixish.yml, .github/workflows/asan.yml, .github/workflows/release-windows.yml, .github/workflows/selfcheck.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml, .github/workflows/valgrind.yml
This doesn't do anything at the moment since we don't use `SmallVector` yet.
=> enabled Boost usage in optimized CI builds

cfg/boost.cfg, cfg/wxwidgets.cfg, lib/tokenlist.cpp, test/testtokenize.cpp
=> Fix #10802 Broken AST lambda inside for loop

cfg/std.cfg, lib/checkmemoryleak.cpp, test/testmemleak.cpp
From `mstflint-4.21.0/mlxfwops/lib/fw_ops.cpp`
=> Fix leakNoVarFunctionCall FP

gui/cppcheck_ja.ts
Signed-off-by: fu7mu4 <fu7mu4@gmail.com>
=> Add few Japanese translations only

lib/templatesimplifier.cpp, test/testsimplifytemplate.cpp
Handle more variadic template arguments
=> #11351 follow-up: Handle more variadic template arguments

tools/donate-cpu.py, tools/donate_cpu_lib.py
This should prevent the client script from exiting in some cases of a single connection issue.
=> donate-cpu: improved client stability by consistently re-trying remote calls / cleanups

lib/tokenize.cpp, test/testtokenize.cpp
https://sourceforge.net/p/cppcheck/discussion/development/thread/42d3bd58fb/
Does that make sense as a fix? I'm not really sure yet but it does pass all the test including my syntax failure case.
=> Fix lambda capture template syntax error

lib/valueflow.cpp
This will turn the crash in 11423 into an internal error.
=> Throw internal error when tokens are not in order

.github/workflows/CI-windows.yml, .github/workflows/clang-tidy.yml, .github/workflows/release-windows.yml, .github/workflows/selfcheck.yml
This fixes the remaining Node.js 12 deprecation warnings in the CI.
=> updated workflows to `jurplel/install-qt-action@v3`

tools/bisect/README.md, tools/bisect/bisect.sh, tools/bisect/bisect_common.py, tools/bisect/bisect_hang.py, tools/bisect/bisect_res.py
An idea would be to provide a daca result file as input file. Depending on the data it could determine what to do without interaction.
=> added a script to bisect regressions

test/testautovariables.cpp
From `cbmc-cbmc-5.12/src/util/simplify_expr_int.cpp`
=> Add test for FP fixed by e8c3a80

lib/tokenlist.cpp, test/testtokenize.cpp
From `gcc-arm-none-eabi-12.2.rel1/gcc/testsuite/g++.dg/cpp23/init-stmt1.C`
=> Don't crash on C++23 code

lib/symboldatabase.cpp, test/testother.cpp
From https://sourceforge.net/p/cppcheck/discussion/general/thread/69ab14909d/
=> Fix FP constVariable with reference to std::array

lib/valueflow.cpp, test/testcondition.cpp
If this is an acceptable solution, values probably need to be inverted in other places as well.
=> Fix #11558 FP knownConditionTrueFalse when checking for zero character

test/testio.cpp
See https://trac.cppcheck.net/ticket/10663 about the actual culprit `Library::detectContainer()`.
Clang 15 `4,445,753,404` -> `3,551,472,880`
before:
```
Benchmark 1: bin/testrunner TestIO
Time (mean ± σ):      2.262 s ±  0.048 s    [User: 2.107 s, System: 0.154 s]
Range (min … max):    2.205 s …  2.325 s    10 runs
```
after:
```
Benchmark 1: bin/testrunner TestIO
Time (mean ± σ):      1.838 s ±  0.043 s    [User: 1.670 s, System: 0.165 s]
Range (min … max):    1.773 s …  1.941 s    10 runs
```
=> sped up `TestIO` a bit by only processing code as C++ if necessary

lib/astutils.cpp, lib/checkclass.cpp, lib/checktype.cpp, lib/clangimport.cpp, lib/symboldatabase.cpp, lib/symboldatabase.h, lib/tokenize.cpp, lib/valueflow.cpp, test/testsymboldatabase.cpp
This avoids unchecked pointer dereferences within the class.
=> SymbolDatabase: made `mTokenizer` and `mSettings` references

lib/valueflow.cpp, test/testvalueflow.cpp
From `tkrzw-1.0.25/tkrzw_build_util.cc`
=> Fix crash in valueFlowForwardLifetime()

lib/symboldatabase.cpp, test/testsymboldatabase.cpp
From https://sourceforge.net/p/cppcheck/discussion/general/thread/224a63be83/
=> Fix FP missingOverride

test/testnullpointer.cpp
This regressed again with #4912 so we need to restore it. This partially reverts #4911.
CC @pfultz2
=> testnullpointer.cpp: restored TODO assert in `nullpointerStdStream`

lib/infer.cpp, lib/valueflow.cpp, test/testother.cpp, test/testvalueflow.cpp
This will enable us to diagnose cases like this:
```cpp
int f(int x, int y) {
if (x == y) {}
return 1 / (x-y);
}
```
=> ValueFlow: Infer possible symbolic values

cli/filelister.cpp
Trac ticket created: #11703
Found by Coverity: CID 1474932
=> File lister: Fix possible resource leaks

gui/mainwindow.cpp
keep SETTINGS_LAST_CHECK_PATH while file dialog select nothing, e.g on cancel button is pressed
=> keep SETTINGS_LAST_CHECK_PATH on no selected files

lib/checkclass.cpp, lib/checkother.cpp, lib/tokenize.cpp, test/testconstructors.cpp, test/testother.cpp, test/testsimplifytokens.cpp, test/testtokenize.cpp
Also reduce simplifications of anonymous structs/unions so we don't loose important information
=> Fixed #11013 (FP overlappingWriteUnion with anonymous struct in union)

test/testuninitvar.cpp
Test case is from: https://trac.cppcheck.net/ticket/10681#comment:10
=> Added a regression test for FP #10681 uninitvar.

Makefile, test/testcheck.cpp, test/testcppcheck.cpp, test/testrunner.vcxproj
=> added `TestCheck` and moved some tests from `TestCppcheck`

.clang-tidy, .github/workflows/asan.yml, .github/workflows/clang-tidy.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml, clang-tidy.md, cmake/clang_tidy.cmake, lib/tokenlist.cpp
The development just started but this is to keep track of the changes early. We already have already encountered false positives in clang-tidy.
=> updated CI to Clang 17

AUTHORS
https://github.com/danmar/cppcheck/pull/5370
=> Update AUTHORS [skip ci]

.github/workflows/CI-unixish.yml, .github/workflows/CI-windows.yml, lib/astutils.cpp, lib/token.h, lib/valueflow.cpp, test/cli/test-more-projects.py, test/cli/test-other.py
Analysis has slowed down a lot when there are many strings in an array.
=> Fixed #11901 (Performance regression: large array with strings)

gui/cppcheck_ja.ts
=> Add Japanese for Sep 6th 2023 [skip ci]

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/numeric/math/FP_categories
=> Added floating point categories to handle the return value from fpclassify()

.github/workflows/buildman.yml
```
Invalid workflow file: .github/workflows/buildman.yml#L42
You have an error in your yaml syntax on line 42
```
=> buildman.yml: fixed `manpage` job

tools/donate_cpu_lib.py
This reverts 7ff58dacff524ec8ddedb55ae6b2bb66550b4ca0.
=> fixed #12099 - daca: missing diff entries

Makefile, cmake/compilerDefinitions.cmake, tools/dmake.cpp
Updated version of https://github.com/danmar/cppcheck/pull/5145
=> Removed -DTIXML_USE_STL flag

.github/workflows/scriptcheck.yml
This is essentially an unit test for the `FileLister` so we should make sure we have proper coverage.
=> scriptcheck.yml: make dmake a separate job and run it on multiple platforms

.github/workflows/CI-unixish.yml, .selfcheck_suppressions
We deprecated qmake so we should no longer use it ourselves.
=> CI-unixish.yml: removed usage of qmake from selfcheck

.github/workflows/iwyu.yml
This will run the workflow every Monday at 00:00. This makes sure it doesn't break and also provides some regular output.
=> iwyu.yml: run the workflow once a week [skip ci]

cli/cmdlineparser.cpp, cli/cmdlineparser.h
no test!!
the test will be added separately.
=> Partial fix for #12254 (cppcheck.cfg can't be loaded from relative paths anymore)

test/testunusedvar.cpp
=> REOPENED #12260 (false positive: unusedVariable with side effects in member initialization)

tools/donate_cpu_lib.py
the daca script will think that analysis crashed otherwise.
=> daca@home: use --unsafe-exitcode

.github/workflows/CI-unixish.yml, CMakeLists.txt, Makefile, cli/cmdlineparser.cpp, cli/cppcheckexecutor.cpp, gui/resultstree.cpp, gui/resultsview.cpp, htmlreport/check.sh, lib/cppcheck.cpp, lib/settings.h, lib/suppressions.cpp, lib/suppressions.h, releasenotes.txt, test/cli/test-other.py, test/cli/test-suppress-syntaxError.py, test/cli/testutils.py, test/testsuppressions.cpp, tools/dmake.cpp, tools/donate_cpu_lib.py, tools/extracttests.py, tools/run_more_tests.sh
This reverts commit 7c316fb76ddb0a7226c4467dc4b76763eeb8bb70.
=> Revert "Fixed #12071 (suppressing critical error, no indication to user that analysis of file fails) (#5771)"

gui/cppcheck_ja.ts
This is just adding Japanese translation only.
Happy holidays
=> Add Japanese translation for 2.13.0

cfg/posix.cfg, test/cfg/posix.c
Reference: 
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/strxfrm_l.html
=> posix.cfg: Added support for strxfrm_l

gui/codeeditor.cpp, gui/common.cpp, gui/compliancereportdialog.cpp, gui/cppchecklibrarydata.cpp, gui/csvreport.cpp, gui/librarydialog.cpp, gui/mainwindow.cpp, gui/printablereport.cpp, gui/resultstree.cpp, gui/resultsview.cpp, gui/statsdialog.cpp
This partially reverts commit 4a9b921c
=> Fixed #12316 - partially revert "Fix two types of Clazy warnings (#5807)"

cfg/windows.cfg
Reference: 
https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regcreatekeyexa
=> windows.cfg: Added constants from <winreg.h>.

addons/misra.py, addons/test/misra/misra-ctu-1-test.c, addons/test/misra/misra-ctu-2-test.c, addons/test/misra/misra-ctu-test.h
…not recognized as function usage
=> Fix #12362: False positive: misra 8.7: taking function by address is not recognized as function usage

lib/forwardanalyzer.cpp
this one caught me off guard 😆😆
=> forwardanalyzer.cpp: Fix typo

cfg/std.cfg
Support has been added for: std::ifstream::bad(), std::ifstream::fail() and std::ifstream::good()
=> std.cfg: Added configuration for std::ifstream functions

cfg/wxwidgets.cfg
Reference: https://docs.wxwidgets.org/trunk/classwx_log.html
=> wxwidgets.cfg: Added support for some wxLog functions

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/io/basic_istream/tellg
=> std.cfg: Added support for std::istream::tellg()

cfg/wxwidgets.cfg
Reference: https://docs.wxwidgets.org/trunk/classwx_rect.html#a8d62df83787d4e1acdcf7a12fc97e5e6
=> wxwidgets.cfg: Added functions from wxRect

cfg/qt.cfg, cfg/wxwidgets.cfg
Reference: https://doc.qt.io/qt-6/qpoint.html
=> qt.cfg: add some QPoint functions

cfg/qt.cfg
Reference: https://doc.qt.io/qt-6/qrect.html
=> qt.cfg: Added some members fo QRect

cfg/wxwidgets.cfg
Reference: https://docs.wxwidgets.org/latest/classwx_log_gui.html
=> wxwidgets.cfg: Added more wxLog members

cfg/wxwidgets.cfg
Reference: https://docs.wxwidgets.org/latest/classwx_popup_transient_window.html#afecca9a60c60ac4f87de19e0a4a25dde
=> wxwidgets.cfg: Fixed wrong configuration

cfg/qt.cfg
Reference: https://trac.cppcheck.net/ticket/8479
=> qt.cfg: Activated commented out configuration, since #8479 was fixed

cfg/wxwidgets.cfg, test/cfg/wxwidgets.cpp
Reference: https://docs.wxwidgets.org/3.0/classwx_colour.html
=> wxwidgets.cfg: Added support for wxColour

gui/resultstree.cpp
as requested in https://sourceforge.net/p/cppcheck/discussion/general/thread/039fd8d1a8/
=> fixed #12549: sinceDate showing formatting string

.github/workflows/coverage.yml
This reverts commit d43a1b35660f11642eb0aff8ad113a28887c903d.
=> Revert "Codecov v4 (#6271)"

test/testmemleak.cpp
Reference: https://trac.cppcheck.net/ticket/12253
=> Added regression test for #12253

test/testmemleak.cpp
Reference: https://trac.cppcheck.net/ticket/11246
=> Added regression test for #11246

.github/workflows/scriptcheck.yml
(cherry picked from commit 1943b4dd7e64ae9c30501c82c2d0d6d42d5e4d52)
=> Deactivate failing scriptcheck using Python 3.5 (#6396)

lib/checkother.cpp, lib/checkother.h, test/testother.cpp
cherry picked 9d4d1187dda0e3374822c59415a6493a4038975e
=> Fix #12726: Update for CheckOrderEvaluation

gui/projectfiledialog.cpp
cherry picked fom ab9def971a17aa2eb0ecc60a09c514d783834de0
=> Fix #12780: Enable Macro TextBox in Gui

lib/token.h, lib/tokenize.cpp, test/testtokenize.cpp
cherry pick b84bc8d4b93bf57f82db684e2731c64f94509c25 from main branch
=> Fix #12807 (dump file: provide alignas expressions)

lib/preprocessor.cpp, test/testpreprocessor.cpp
I added comparison of both lines and columns so if any exta spaces/new lines were added we can adjus our report accordingly
=> Fix #12383: cppcheck build dir: changed line numbers in source file

test/cli/whole-program/whole1.c, test/cli/whole-program/whole2.c, test/cli/whole-program_test.py
added Python tests showing inline suppressions not working with whole program analysis and -j2 as well as tests for missing whole program analysis execution for addons
=> refs #12835/#12839 - added Python tests for known issues with whole program analysis

lib/tokenize.cpp, test/testsymboldatabase.cpp, test/testtokenize.cpp
=> Fix #12813 (Tokenizer: handle alignas in C11 code)

gui/cppcheck_ka.ts, gui/gui.pro
Hello,
Adding Georgian translation for Cppcheck
=> Add Georgian translation

test/testcondition.cpp
This issue has been fixed with https://github.com/danmar/cppcheck/commit/84782ccf8d52bd88d1b612486aa16b9b09a5c7b4
=> Added regression test for Ticket 11822 - FP knownConditionTrueFalse

.github/workflows/CI-unixish-docker.yml
https://github.com/actions/checkout/issues/1590
https://github.com/actions/checkout/issues/1809
=> Workaround for docker CI failure

.github/workflows/CI-windows.yml, .github/workflows/asan.yml, .github/workflows/scriptcheck.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml
This reverts commit 019a240ebdc3e1e89f66d10dd68bb4bb619e1d7f.
=> Revert "temporally fixated Python 3.12 in CI to 3.12.3 (#6502)"

cli/cmdlineparser.cpp, cli/processexecutor.cpp, lib/checkclass.cpp, lib/clangimport.cpp, lib/importproject.cpp, lib/symboldatabase.cpp, lib/templatesimplifier.cpp, lib/tokenize.cpp
if you are only modifying the container itself and not the actual contents you can still use `const_iterator`.
=> more `const_iterator` usage

gui/cppcheck_ja.ts
This change update Japanese translation only
=> Update Japanese Translation (#6779)

test/cli/clang-import_test.py
this should fix running the tests with multiple workers
=> test/cli/clang-import_test.py: create files in temporary folder / some cleanups

lib/checkleakautovar.cpp, test/testleakautovar.cpp
=> fix #8109: False positive: memory is freed twice (overloaded delete)

cfg/qt.cfg
Adding missing QtClassHelperMacros
https://doc.qt.io/qt-6/qtclasshelpermacros-qtcore-proxy.html
=> Add missing QtClassHelperMacros

lib/valueflow.cpp
restores the changes lost in #6991
=> restored ValueFlow changes

cfg/posix.cfg, test/cfg/posix.c
Reference: https://www.man7.org/linux/man-pages/man2/nice.2.html
=> posix.cfg: Improved support for nice().

cfg/posix.cfg
Reference: https://www.man7.org/linux/man-pages/man3/dlerror.3.html
=> posix.cfg: Added support for dlerror()

cfg/gnu.cfg
Reference: https://www.man7.org/linux/man-pages/man3/dlmopen.3.html
=> gnu.cfg: Added support for dlmopen()

cfg/windows.cfg
Reference: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/stricmp-wcsicmp-mbsicmp-stricmp-l-wcsicmp-l-mbsicmp-l?view=msvc-170
=> windows.cfg: Added strcmpi()

cfg/gnu.cfg
Reference: https://man7.org/linux/man-pages/man3/dlsym.3.html
=> gnu.cfg: Added support for dlvsym().

cfg/std.cfg
Reference: https://en.cppreference.com/w/cpp/io/c/tmpfile
=> std.cfg: Added support for std::tmpfile()

cfg/std.cfg, test/testleakautovar.cpp
Reference: https://en.cppreference.com/w/cpp/error/uncaught_exception
=> std.cfg: Added support for std::uncaught_exception().

releasenotes.txt
=> Mention staticFunction in releasenotes.txt [skip ci]

gui/CMakeLists.txt, gui/cppchecklibrarydata.cpp, gui/cppchecklibrarydata.h, gui/mainwindow.h, gui/test/cppchecklibrarydata/testcppchecklibrarydata.cpp, tools/triage/CMakeLists.txt
=> replaced `QPair` with `std::pair`

.github/workflows/CI-windows.yml, .github/workflows/asan.yml, .github/workflows/clang-tidy.yml, .github/workflows/iwyu.yml, .github/workflows/release-windows.yml, .github/workflows/selfcheck.yml, .github/workflows/tsan.yml, .github/workflows/ubsan.yml
this causes the existing Python installation to be overridden
=> do not install Python via `jurplel/install-qt-action` in CI

cfg/gtk.cfg, test/cfg/gtk.c
This merge was already something which was already a long time on my backlog.
Please feel free to correct it further
=> cfg/gtk.cfg - extend and improve gtk.cfg

cfg/qt.cfg
7 months ago, C was partially expanded to Class, but was forgotten in two instances.
=> Fix Q_DISABLE_COPY macros
