- lib/tokenize.cpp
- test/testsimplifytokens.cpp
This is https://github.com/danmar/cppcheck/pull/504 resubmitted after (presumably) dealing with gcc warning mentioned here https://github.com/danmar/cppcheck/pull/504#issuecomment-72323919 and resolving tons of merge conflicts
> Calling a function using Class::func() syntax should not be simplified

- lib/checkcondition.cpp
The code removed is executed unconditionally before the `if`.
> Remove completely redundant code

- lib/templatesimplifier.cpp
- test/testtokenize.cpp
Hi,
This patch reverts what I did to fix #6181 because it caused two regressions (#6354 and #6414) that I don't have much time to look at those days. It also adds those tickets' test cases so as to track that we don't regress again when fixing again #6181. Please consider merging.
Thanks,
Simon
> Revert fix for #6181, that caused #6354 and #6414.

- test/testpath.cpp
Earlier commit included the same test twice. That's not what was intended.
> Deduplicate a multislash test

- lib/symboldatabase.cpp
No idea why this was marked as false positive - the analyzer is right that `first` is guaranteed to be non-null at that point, so code can be simplified.
> Resolve CID 1037075

- lib/checkbufferoverrun.cpp
This is https://github.com/danmar/cppcheck/pull/529 resubmitted with the original check near the message emission kept in place.
> Don't run the checks which will be silenced later anyway

- lib/tokenize.cpp
- test/testsimplifytemplate.cpp
- test/testtokenize.cpp
Hi,
This patch is another fix for this ticket, where C++11's ">>" closing parameter list syntax is not properly handled (previous attempt was in https://github.com/danmar/cppcheck/pull/484). The idea is to turn this syntax into the legacy one early enough so that we don't need "Token::Match(..., ">|>>")" constructs all over the place (I plan to work on code cleanup via a separate PR).
Note that I reworked one test in TestSimplifyTemplate that was completely invalid, with the same identifier used as a template parameter, its default value and the template class being defined...
Cheers,
Simon
> Ticket #6181: Normalize '>>' into '> >' when it's closing a C++11 template parameter list

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
Hi,
Even though the initial issue reported in this ticket was fixed via https://github.com/danmar/cppcheck/pull/539, there was still a "bailiing out" debug trace emitted due to the fact that TemplateSimplifier::getTemplateNamePosition does not support template member functions. This patch fixes this and removes the warning in that particular case.
There are still cases I need to work on (nested class members and template class members), hence two TODO tests, however I believe this patch is already an improvement. Thanks to consider merging.
Cheers,
Simon
> Ticket #6567: Handle member functions in TemplateSimplifier::getTemplateNamePosition

- lib/checkother.cpp
I see no reason for deep copy of that `std::set` inside the function. Also the parameter reference should be const.
> Remove unneded deep copy, make reference const

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
Hi,
This ticket highlights the fact that the way we simplify "0 + ..." expressions might delete tokens we have a reference to, leading to a crash. This patch fixes this by reviewing how the 0 and + tokens are removed. Thanks to consider merging.
Cheers,
Simon
> Ticket #6347: Fix use after delete when simplifying template instantiations

- lib/templatesimplifier.cpp
- lib/tokenize.cpp
Hi,
This is a follow-up to https://github.com/danmar/cppcheck/pull/539 (that replaces ">>" by "> >" when it closes template parameter lists) with code simplification that this normalisation allows. Thanks to consider merging.
Cheers,
Simon
> Code simplification now that ">>" is turned into "> >" when it closes template argument lists

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
Hi,
Given that we currently fail to extract the template name in template specialisations, we fail to simplify all instantiations, hence this ticket. This patch fixes this. Thanks to consider merging.
Cheers,
Simon
> Ticket #4335: Properly detect and handle template class specialisations

- lib/checkother.cpp
The different patterns in the chain are mutually exclusive. Current code continues walking the chain if a pattern matches but other conditions are not met. It should instead abandon the chain.
> Decouple pattern matching from other checks

- lib/tokenize.cpp
I'm not sure why `members.empty()` was checked explicitly. If that was an optimization - I can rewrite the code such that the optimization is still there and the iterator is reused.
> Eliminate repeated lookup

- lib/tokenize.cpp
These are clearly mismatching function names.
Once this change is applied the ANSI chain fully matches the Unicode chain except function names and two other small changes. So I'd like to merge them so that it goes like this:
} else if (Token::simpleMatch(tok, "_tcslen (")) {
tok->str(ansi ? "strlen" : "wcslen");
tok->originalName("_tcslen");
Any objections?
> Mismatching TCHAR function names

- lib/tokenize.cpp
Once the two chains have been synchronized it's time to get rid of one of them.
> Eliminate duplication in TCHAR functions substitution

- lib/checkstl.cpp
Hi,
This is similar to https://github.com/danmar/cppcheck/pull/228, where cend() cannot be used on Mac OS X because
- If one uses clang + libc++ (default), we get a lot of test suite failures due to http://llvm.org/bugs/show_bug.cgi?id=17782
- To have the test suite succeed, one needs to use GNU's libstdc++ instead of libc++... but it does not provide cbegin() / cend(), and cppcheck does not build
It's really too bad we have to do this but at the same time I believe it's not that big a deal in that case and it's good to have cppcheck build on as many environments as possible.
Thanks to consider merging,
Simon
> Restore build on Mac OS X

- lib/token.cpp
- test/testsimplifytemplate.cpp
Hi,
The code in this ticket triggers a memory corruption because we end up considering the default value of a template parameter as an instantiation, that's deleted by useDefaultArgumentValues but still referenced as an instantiation and therefore read later.
The code that computes the list of instantiations is supposed to skip template parameter default values, but does not because Token::findClosingBracket considers "=" as a closing bracket, for no obvious nor good reason (I tracked this down to https://github.com/danmar/cppcheck/commit/c283bc414d71d4f63c35254f31fa148b9d0e7814). This patch fixes findClosingBracket, and the ticket. Thanks to consider merging.
Cheers,
Si,mon
> Ticket #6587: Do not consider template expressions in decltype as instantiations

- cli/cppcheckexecutor.cpp
`%x` is for `int`, so the original code would only print half of pointer when compiled for x64. The new code is not perfect (`%p` can only be used for valid pointers) but will do for Windows.
> Resolve CID 1288510

- lib/checkbufferoverrun.cpp
The very same check is in the loop header and there's no point in having it twice in the code
> Remove duplicate check

- lib/tokenize.cpp
- test/testsimplifytokens.cpp
`delete a, b` is equivalent to `(delete a), b`. Perhaps it's worth adding a warning for this case.
> Proper simplify delete a,b

- lib/token.cpp
Calling `std::abort()` in the middle of C++ code subverts stack unwinding and makes the hosting process terminate immediately.
> Don't call abort() in the middle of C++ code

- lib/checkother.cpp
Inconclusive checks are usually disabled. No need to fetch other settings most of the time.
> Omit uneeded checks

- lib/templatesimplifier.cpp
Hi,
While investigating the comment mathiaskrgr did in https://github.com/danmar/cppcheck/pull/586, I've noticed that the "Failed to instantiate template" debug message does not name the template that we fail on, and also gives as location where the template was defined, not where it actually is instantiated. This trivial patch fixes that. Thanks to consider merging.
Cheers,
Simon
> Show template instantiation and not definition location in template instantiation debug message

- lib/checkio.cpp
- lib/checkstl.cpp
- lib/library.h
- lib/mathlib.cpp
- test/testsuite.cpp
Hi,
This patch works around https://llvm.org/bugs/show_bug.cgi?id=17782, a bug in libc++ that forced to use GNU's STL when building on Mac OS X, and therefore prevented the use of cbegin() and cend() (hence https://github.com/danmar/cppcheck/pull/228 and https://github.com/danmar/cppcheck/pull/562, that are reverted as well here).
The idea is to detect cases where conversion to double will fail due to that bug and directly call strtod.
Cheers,
Simon
> Restore build with libc++ and revert PR#228 and PR#562.

- lib/checkleakautovar.cpp
- test/testgarbage.cpp
Hi,
This trivial patch fixes this ticket, where we crash upon garbage code as we end up dereferencing a null pointer. Thanks to consider merging.
Cheers,
Simon
> Ticket #6666: Don't crash upon garbage code in CheckLeakAutoVar::checkScope

- lib/symboldatabase.cpp
- test/testconstructors.cpp
Hi,
This ticket highlights that the pattern currently used to recognise C++ 11 delegated constructors is incomplete: it detects ": Foo {" but not ": Foo (". This patch fixes this by tweaking the regular expression. Thanks to consider merging.
Cheers,
Simon
> Ticket #6675: Fixed pattern detecting C++ 11 delegated constructors.

- lib/checkuninitvar.cpp
- test/testuninitvar.cpp
Hi,
This ticket shows that the check for uninitialised member variables does not take into account that they might be initialised by operator>>. This patch fixes this. Thanks to consider merging.
Cheers,
Simon
> Ticket #6680: Members can be initialized by operator>>.

- lib/symboldatabase.cpp
- lib/symboldatabase.h
- test/testgarbage.cpp
- test/testsimplifytokens.cpp
- test/testsymboldatabase.cpp
- test/testtokenize.cpp
Hi,
Both tickets are for garbage code that confuses the parser and eventually leads to a crash. In both cases the root cause is that a Function is built for a name that's reserved to the language. This patch fixes this by ensuring that we don't build function declarations when their name is reserved.
Cheers,
Simon
> Ticket #6620, #6685: Reserved keywords cannot be function names.

- test/testgarbage.cpp
Hi,
This ticket has been fixed via https://github.com/danmar/cppcheck/pull/596 and this patch adds a test case with the reported snippet. Thanks to consider merging.
Cheers,
Simon
> Ticket #5760: Added test case since the issue has been fixed with PR#596

- lib/symboldatabase.cpp
- test/testgarbage.cpp
Hi,
This trivial patch fixes the ticket by rewriting a pattern to avoid dereferencing some possibly null pointer. Thanks to consider merging.
Cheers,
Simon
> Ticket #6703: Rewrite pattern in SymbolDatabase to avoid crash upon garbage code

- lib/tokenize.cpp
- test/testgarbage.cpp
Hi,
This ticket highlights that the pattern used to skip base class declarations in a class definition is not tight enough, and can trigger a crash upon malformed code. This patch fixes the pattern and the ticket. Thanks to consider merging.
Cheers,
Simon
> Ticket #6704: Tighten pattern skipping base class declarations and fix crash upon garbage code

- lib/tokenize.cpp
Hi,
While investigating ticket #4884, I've noticed that we're doing some token string check that's not necessary in Tokenizer::simplifyKnownVariablesSimplify; which this PR fixes. Thanks to consider merging.
Cheers,
Simon
> Removed unnecessary string comparison in Tokenizer::simplifyKnownVariablesSimplify

- test/testsimplifytemplate.cpp
Hi,
While investigating (again) ticket 6592, I came to wonder about the behaviour of  TemplateSimplifier::templateParameters with variadic templates, and came up with the attached new cases (including some that need to be fixed, when ... is the last token before the end of the parameter list). Thanks to consider merging.
Cheers,
Simon
> Added unit tests for TemplateSimplifier::templateParameters involving variadic templates

- lib/symboldatabase.cpp
- lib/symboldatabase.h
- test/testgarbage.cpp
- test/testsimplifytokens.cpp
- test/testsymboldatabase.cpp
- test/testtokenize.cpp
Hi,
This is a follow-up to https://github.com/danmar/cppcheck/pull/596 that actually caused a regression as highlighted by @amai2012 in ticket #6708. The problem is that the initial PR checked that a function's name is not a reserved keyword while building a Function instance, while it's better to do it in isFunction.
Cheers,
Simon
> Ticket #6708: Check that a function name is not a reserved keyword in SymbolDatabase::isFunction instead of later.

- lib/valueflow.cpp
- test/testgarbage.cpp
Hi,
This ticket is a hang upon invalid code because valueFlowForward believes it has encountered a ternary operator (due to the ? character) and desperately tries to analyse, while it's _not_ a ternary operator. This patch fixes this by properly detecting such operators. Thanks to consider merging.
Cheers,
Simon
> Ticket #6713: Properly detect ternary operator in valueFlowForward.

- lib/tokenize.cpp
Hi,
Trivial style change: no need for a space here. Thanks to consider merging.
Cheers,
Simon
> Removed useless space in the declaration for Tokenizer::Simplifyfunctionpointers

- lib/tokenize.cpp
- test/testtokenize.cpp
Hi,
While tackling ticket #4884, I've noticed that we miss the opportunity to simplify known variables when they appear at the end of a statement. This patch fixes this, as well as two TODO test cases. Thanks to consider merging.
Cheers,
Simon
> Simplify known variables when they are at the end of a statement.

- lib/tokenize.cpp
- test/testbool.cpp
- test/testother.cpp
Hi,
This is a follow-up to https://github.com/danmar/cppcheck/pull/606 where I wrongly assumed the ticket was fixed, while it still existed in C mode. The issue is that simplifyConstTernaryOp wrongly handled the '<' character in C mode ("n < 4 ? foo : bar" was turned into "n < foo", a bool hence the warning). This is fixed in the attached patch. Thanks to consider merging.
Cheers,
Simon
> Ticket #6588: Properly detect whether the condition in a ternary operator is constant on C input

- lib/checkmemoryleak.cpp
- test/testmemleak.cpp
Hi,
This ticket shows that the leak checker can get confused by variables called the same as an allocation function. This patch fixes this by only considering tokens with no varId as possible allocation functions.
Cheers,
Simon
> Ticket #6536: Properly handle variables whose name is that of an allocation function.

- lib/tokenize.cpp
Hi,
I'm working on ticket#6810 and I've noticed that the code parsing C++0x typed enumerations can be simplified, which this patch does. Thanks to consider merging.
Cheers,
Simon
> Simplify the code handling C++0x typed enumerations.

- lib/tokenize.cpp
- test/testsimplifytokens.cpp
Hi,
In this ticket, we end up simplifying a faulty enum declaration until memory is exhausted because we're too permissive in typed enumeration declarations. This trivial patch fixes the issue by detecting such recursive definitions. We could definitely be more strict on such definitions, however I don't think it's worth the pain.
Cheers,
Simon
> Ticket #6810: Avoid infinite loop upon invalid typed enum declaration.

- lib/templatesimplifier.cpp
- test/testgarbage.cpp
Hi,
This ticket is a crash upon invalid code due to the fact that TemplateSimplifier::useDefaultArgumentValues does not properly handle parenthesis while scanning for default values, which this patch fixes. Thanks to consider merging.
Cheers,
Simon
> Ticket #6835: Don't get confused by parentheses while detecting template parameter default values.

- lib/tokenize.cpp
- test/testuninitvar.cpp
Hi,
This ticket highlights that we transform (&a)->b into (&a).b, a format that is not properly handled by the uninitialised member checker. This patch ensures that it is transformed into a.b, that not only fixes the ticket but is also the correct simplification. Thanks to consider merging.
Cheers,
Simon
> Ticket #5776: Simplify (&a)->b into a.b

- test/testsimplifytokens.cpp
- test/testuninitvar.cpp
Hi,
As highlighter by amai in https://github.com/danmar/cppcheck/pull/623, it makes more sense to write a Tokenizer unit test for this fix that's purely in Tokenizer. This patch does exactly this. Thanks to consider merging.
Cheers,
Simon
> Ticket #5776: Since the fix is in Tokenizer, write a Tokenizer unit test

- test/testsimplifytemplate.cpp
Hi,
While investigating Ticket #6601, I saw that we don't have any test involving function pointers and referenced for TemplateSimplifier::templateParameters. This patch adds some. Thanks to consider merging.
Cheers,
Simon
> Added unit test involving function reference for TemplateSimplifier::templateParameters

- lib/checkleakautovar.cpp
- test/testleakautovar.cpp
Hi,
This ticket shows that CheckLeakAutovar does not properly handle variables that have been freed and whose address is taken later: this should not trigger any error. This patch fixes this by checking whether it really is the variable or its address that's taken. Thanks to consider merging.
Cheers,
Simon
> Ticket #6648: Properly handle variables that have been deallocated and whose _address_ is taken after

- cli/cppcheckexecutor.cpp
Commit https://github.com/danmar/cppcheck/commit/8b97f04de4a7ecfa1b52c4b94f3321057e1e495a first, breaks the code Coverity wasn't even unhappy about (on line 583) and also effectively breaks previously corrected code without making Coverity happier.
This fixes both problems and most likely makes Coverity happy with a cast between `ULONG_PTR` and a pointer as suggested in this comment https://github.com/danmar/cppcheck/commit/8b97f04de4a7ecfa1b52c4b94f3321057e1e495a#commitcomment-12267821
> Resolve CID 1312126 and maybe also CID 1288510

- test/testtype.cpp
Hi,
This ticket is a claim (not justified by any snipped, just code read) that the check for too large right shifts is not run on template code. This patch adds some unit tests showing that it does (at least basic cases; will check more advanced ones later). Thanks to consider merging.
Cheers,
Simon
> Ticket #6793: Added basic unit test showing that basic integer shift length check is run even for templates.

- lib/checkother.cpp
- lib/checkother.h
- test/testother.cpp
This PR contains a prototype for evaluation. I'll add tests if you like it.
A common pattern for reference counted objects goes like this:
InterlockedDecrement(&referenceCount);
if (referenceCount == 0)
destroySelf();
here the problem is that the second access in not interlocked and so this allows for a race which can cause `destroySelf()` called twice.
Good code would do this instead:
int newCount = InterlockedDecrement(&referenceCount);
if (newCount == 0)
destroySelf();
> Prototype for detecting non-interlocked check after InterlockedDecrement()

- cfg/std.cfg
freopen either returns the FILE* it was given, or returns NULL.
It does not allocate a new FILE*.
> freopen does not allocate

- lib/preprocessor.cpp
- test/testpreprocessor.cpp
Parsing of C++11 raw string literals only worked in the first 16 bytes of a file.
Backslashes in raw string literals were not escaped.
Single quotes in raw string literals were escaped unnecessarily.
> Fixed #5028  Fix parsing of C++11 raw string literals

- Makefile
- tools/dmake.cpp
On different systems it may point to different locations, e.g. FreeBSD uses ${LOCALBASE}/share/xsl/docbook/manpages/docbook.xsl
> Make DB2MAN overridable

- lib/checkclass.cpp
- test/testclass.cpp
Hi,
I've noticed that one of the test cases for CheckClass::checkMemset, that involves arrays of pointers, was incorrect and was giving too many errors. This is due to an incorrect management of & and * for arrays of pointers, that this patch fixes. Thanks to consider merging.
Cheers,
Simon
> Fix CheckClass::checkMemset for arrays of pointers.

- lib/checkautovariables.cpp
- lib/checkautovariables.h
- lib/checkother.cpp
- lib/checkuninitvar.cpp
- lib/symboldatabase.cpp
- lib/symboldatabase.h
- lib/tokenize.cpp
- test/testautovariables.cpp
- test/testconstructors.cpp
- test/testother.cpp
- test/testsimplifytypedef.cpp
- test/testsymboldatabase.cpp
- test/testtokenize.cpp
- test/testuninitvar.cpp
- test/testvarid.cpp
Hi,
Two TODO test cases in TestAutoVariables highlight that cppcheck does not distinguish arrays of pointers and pointers to arrays. This patch fixes this and also replace the (incorrect) fix for #5646 (turning type (*ptr)[] into type* ptr[]) by the good one.
Pointers to arrays both have fIsPointer and fIsArray, however the getters in Variable have been modified to have the good semantic. Thanks to consider merging.
Cheers,
Simon
> Properly differentiate arrays of pointers and pointers to arrays.

- lib/checkautovariables.cpp
Benchmark shows that `Match()` calls are reduced by 8 percent and the whole function gets about 5 percent faster on some random pile of code.
> Merge identical matches

- lib/library.cpp
These `find()` calls are duplicated in the code. for no good. Also the second change location used `find(const char*)` version where `find(char)` version could have been used. Would it be a good idea to craft a check for the latter?
> Eliminate duplicate find() calls

- test/testexceptionsafety.cpp
Hi,
While looking at TODO test cases, I've noticed one for exception safety that is clearly invalid. Fixing it would require ugly (and IMHO unnecessary) changes in a part of SymbolDatabase (destructor detection) that's currently very clean... something we don't want to do. I therefore believe this test case is useless and is better removed. Thoughts?
Thanks,
Simon
> Remove unnecessary TODO exception safety test case.

- lib/checkunusedvar.cpp
- test/testunusedvar.cpp
Hi,
This ticket (thanks @amai2012!) highlights an issue in https://github.com/danmar/cppcheck/pull/651, that failed to update CheckUnusedVar to handle the new representation of pointers to arrays. This patch fixes it and the ticket. Thanks to consider merging.
Cheers,
Simon
> Ticket #6954: Properly handle pointers to arrays in CheckUnunsedVar.

- lib/valueflow.cpp
Here the second match checks for a subset of a previous match. All is needed is actually comparing the first token - that's easier to read and not slower.
> Replace match call with explicit comparison

- lib/valueflow.cpp
This makes code clearer and a tiny bit faster. Once either of the matches happens the code below has no chance to be useful, so just `continue`.
> Treat matches as mutually exclusive

- lib/checkautovariables.cpp
- test/testautovariables.cpp
Hi,
@amai2012 found another issue with my fix in https://github.com/danmar/cppcheck/pull/651, because it fails to recognise when the address of a local variable is assigned to a pointer-pointer argument. This patch fixes this. Thanks to consider merging.
Cheers,
Simon
> Ticket #6596: Address of local variables can also be assigned to pointer-pointer arguments

- lib/checkclass.cpp
- lib/symboldatabase.cpp
- lib/symboldatabase.h
- test/testconstructors.cpp
- test/testsymboldatabase.cpp
Hi,
This is another follow-up to https://github.com/danmar/cppcheck/pull/651, and @amai2012 showed (thanks!) that we need to keep track of the fact that a variable is an array of pointers, and use this information in CheckClass::constructors. Thanks to consider merging.
Cheers,
Simon
> Ticket #6957: Properly handle arrays of pointers in CheckClass::constructors

- lib/checkclass.cpp
- test/testconstructors.cpp
Hi,
This is a follow-up to https://github.com/danmar/cppcheck/pull/661, because the ticket (thanks again @amai2012!) highlights that there's another place one needs to check for pointer arrays. This patch fixes this, and the ticket. Thanks to consider merging.
Cheers,
Simon
> Ticket #6959: Properly handle arrays of pointers in CheckClass::constructors

- lib/errorlogger.cpp
- test/testerrorlogger.cpp
The current code is broken.
Start with `source = "{file}{file}"` and try to replace `{file}` with `c`. First, `index` is set to zero, then `0 + 1 - 6 + 1` is computed which yields `-4` which is then flipped into unsigned variable and turns into `npos - 3` and the loop terminates instead of proceeding to the next match.
> Fix search-replace

- lib/checkother.cpp
This makes the function about four times faster on a random pile of code
> Avoid unneeded match checks

- lib/checkcondition.cpp
- test/testcondition.cpp
Hi,
This patch fixes a TODO test case by properly detecting "x | non_null_integer" patterns returned in boolean functions. Thanks to consider merging.
Cheers,
Simon
> Fixed TODO-test for CheckCondition::checkBadBitmaskCheck by handling functions return bool.

- cli/filelister.cpp
This edge case is handled earlier, `hFind` cannot be "invalid" here
> Remove useless check

- lib/valueflow.cpp
Set was used to store no more than two objects. Actually once the second object was added the function would return immediately, so it was used to store no more than one object. The object stored is varid which can be zero to mean "no varid", so just use a single integer for that.
> Get rid of set object

- lib/checkunusedvar.cpp
These changes make code more readable and also the function runs 23 percent faster on some random pile of code
> Continue early, reuse pattern, better names

- lib/checkclass.cpp
- test/testclass.cpp
Hi,
This trivial patch ensures we properly detect that operator= for template classes returns a reference to self. Thanks to consider merging.
Cheers,
Simon
> Ticket #7017: Properly interpret operator= return type for template classes in CheckClass::operatorEq.

- lib/tokenize.cpp
The current code not only does the same map lookup twice, it also accesses `tokAt(2)`, then deletes some tokens and accesses the very same token as previously but now it's not `tokAt(2)` anymore - this isn't trivial. This change makes it clearer by removing the second lookup.
> Remove repeated search, clearer code

- lib/tokenize.cpp
The current code first sets `sz`, then falls through, then checks `sz` and proceeds to the next iteration. It's more explicit to just use `continue`.
> Explicit continue instead of fall through with a check

- lib/tokenize.cpp
- test/testsimplifytypedef.cpp
Hi,
This ticket highlights that the typedef simplifier does not properly handle "typedef unsigned T;" constructs. This patch fixes this. Thanks to consider merging.
Cheers,
Simon
> Ticket #6998: Properly handle "typedef unsigned T;" constructs.

- lib/cppcheck.cpp
- test/testsuppressions.cpp
syntaxErrors were not suppressable, because they were treated as
InternalErrors which were thrown and catched during the checking,
and normal suppression rules were not applied for those.
We fix this by calling normal reportErr() function when we have
syntaxErrors. Internal errors are still kept unsuppressable.
> Make syntaxError suppressable (fixes #5917 and #7076)

- cfg/gnu.cfg
* first argument of backtrace() can be uninitialized
* treat second argument as size
> gnu.cfg: Few improvements in backtrace* functions support

- cfg/gtk.cfg
"This call makes a shallow copy; the return result should be released
with g_free(), but the individual strings must not be modified."
https://developer.gnome.org/glib/stable/glib-GVariant.html
> gtk.cfg: Fix some g_variant deallocators

- lib/path.cpp
Previously they were erroneously detected as C files.
Also add *.hh and *.hxx files to be checked with the Git
pre-commit hook script.
> Treat *.hh and *.hxx files as C++ files

- lib/checkother.cpp
Hi,
Trivial patch to fix a warning introduced by https://github.com/danmar/cppcheck/commit/f15f8514f67cc678a04f42a70bac5c762108c406. Thanks to consider merging.
Cheers,
Simon
> Silence clang warning.

- Makefile
- tools/dmake.cpp
Hi,
Build on OSX is broken since https://github.com/danmar/cppcheck/commit/11915f84e26204c34b5821335f82ddccff5b8aaf because make on this platform defines CXX as c++, and -std=c++0x is not appended to CXXFLAGS. This patch fixes this by handling the "CXX=c++ and OS=OSX" case appropriately. Thanks to consider merging.
Cheers,
Simon
PS: One can find the default value make gives to CXX by issuing "make -p | grep 'CXX ='"
> Restore build on OSX, where make defines CXX as "c++" by default.

- lib/checkfunctions.cpp
Since `std::fabs` is defined in `cmath` we should include it.
Otherwise this fails to compile for me with a trunk version of libc++ under OS X.
> Include cmath for std::fabs

- lib/checkother.cpp
- test/testother.cpp
This covers a yet another way to introduce a race. Bad code goes something like this:
if( InterlockedDecrement(&var)==0) {
delete this;
return 0;
}
return var;
Assume `var` equals two. Thread A enters the function, `InterlockedDecrement()` returns 1 and then thread A is suspended. Thread B enters the functions, `InterlockedDecrement()` returns 0, object is `delete`d. Thread A resumes and accesses a no longer live object.
> Detect more non-interlocked accesses

- lib/errorlogger.cpp
- lib/errorlogger.h
- lib/symboldatabase.cpp
- lib/tokenize.cpp
lib/symboldatabase.cpp and lib/tokenize.cpp both
define a static toxml() function. Make it a single
static ErrorLogger::toxml() member function.
> Factorize toxml() into a single member function

- lib/tokenize.cpp
This makes code a bit clearer by putting reused values in temporaries with more or less descriptive names
> Cache and reuse value

- lib/cppcheck.cpp
- lib/cppcheck.h
- lib/tokenize.cpp
- lib/tokenize.h
Move dump generation from `CppCheck::checkFile()` to `CppCheck::processFile()` including Tokenizer, then optimize tokeninzing by removing duplicate token creations.
> Separate dump from checks and optimize tokenizing

- cli/filelister.cpp
- cli/filelister.h
- test/testfilelister.cpp
At my office I work on huge codebase, really huge. at it takes hours for cppcheck to analyze it.
So i decided to join cppcheck and try to optimize it.
So, here is my first commit. On my Mac It took 47 seconds for FileLister just to traverse entire codebase and collect all files. I profiled it and rewrote it a bit. 
Now it takes 3 seconds.
Unfortunately the previous traverse code before was a bit obfuscated so I'm not sure for 100% that all path variations still work (All combinations i tried did work). 
I aslo had no tools to test it on non mac (xcode) systems. :(
I'll really appreciate if you'll review and test my code thoughtfully and then merge it into the next version of cppcheck.
Thanx for the great product :)
> Faster collection of files on huge codebases (posix system)

- lib/symboldatabase.cpp
warning: comparison between signed and unsigned integer expressions 
for ( int p = 0; p < pointer; p++) {
^
> Fix Compiler warnings.

- addons/cert.py
- addons/cppcheckdata.py
- addons/findcasts.py
- addons/naming.py
- addons/threadsafety.py
- lib/cppcheck.cpp
This PR moves dump generation from CppCheck::checkFile() to CppCheck::processFile() then fixes multiple-configuration XML dumps so that all configurations are dumped, not only the last one. The new behavior is obtained with the new option **`--dump=all`**(original option `--dump` retains original behavior).
> Fix multiple config dumps

- lib/tokenize.cpp
The original code is basically checks `A&&B || B` which is equivalent to just `B`
> Remove redundant check

- lib/symboldatabase.cpp
Loop only traversed the scopes tree leaf-to-root but each iteration used the leaf scope anyway. That was obscured but not very clear variable names.
> Loop variable wasn't really used

- lib/checkbufferoverrun.cpp
These braces look as if they somehow have an effect on code execution. They don't, they are just useless.
> Drop useless braces

- lib/checkunusedfunctions.cpp
`markupFile()` causes rather expensive conversion to lowercase on case-insensitive systems and a lot of other manipulations on case-sensitive systems. There's no point in calling it so often in this code. This change makes `parseTokens()` about 20 percent faster on Windows.
> Cache and reuse result of expensive operation

- lib/checkfunctions.cpp
The pre-check ensures that the pattern at least looks like a function call. This reduces number of `Match()` calls three times compared to what would mostly be a check-fail-check-fail-check sequence. Performance is improved for pattern version of `Match()` and should be even better for pre-compiled version.
> Pre-check to reduce number of match checks

- lib/preprocessor.cpp
Currently, if its argument is all spaces and tabs,
trim() returns it without actually trimming it.
Fix this by returning an empty string in this case.
> Fix trim() in lib/Preprocessor.cpp

- tools/daca2-addons.py
- tools/daca2-download.py
- tools/daca2.py
- tools/matchcompiler.py
- tools/rundaca2.py
Run all Python code through autopep8 as follows:
autopep8 -ri --ignore=E261,E262 .
E261 or E262 would cause spaces after a comment's hash sign
to be squashed. Since some of the comments in cppcheck's
Python code have space-indented code examples, not ignoring
E261 or E262 would wreck the formatting of those examples.
> Run all Python code through autopep8

- cfg/posix.cfg
Idea: Library editor should do some type-checking on the arguments.
> posix.cfg: Only pointers can be null

- lib/preprocessor.cpp
The original code fully copies the string, then erases all or part of it. That doesn't make much sense.
> Use substr() instead of assignment plus erase()

- Makefile
- addons/cppcheckdata.py
- addons/y2038/README
- addons/y2038/test/y2038-inc.h
- addons/y2038/test/y2038-test-1-bad-time-bits.c
- addons/y2038/test/y2038-test-2-no-time-bits.c
- addons/y2038/test/y2038-test-3-no-use-time-bits.c
- addons/y2038/test/y2038-test-4-good.c
- addons/y2038/y2038.py
- lib/cppcheck.cpp
- lib/preprocessor.cpp
- lib/preprocessor.h
- test/testpreprocessor.cpp
- tools/dmake.cpp
This patch augments the XML dumps with a 'directivelist'
subtree which lists all raw preprocessor directives met
while reading the source code in each configuration.
Also, the addons/cppcheckdata.py file has been extended
to give easy access to the list of directives.
Finally, an new addon, addons/y2038/y2038.py, is created
to detect occurrences of glibc symbols when they may not be
Y2038-proof. This is determined for each symbol by checking
whether _TIME_BITS is currently defined equal to 64 when
the symbol is met.
Both the preprocessor dump and the y2038 checker handle
multiple configuration.
> Add preprocessor directives dump and Y2038 addon

- lib/checkbufferoverrun.cpp
Here's how code ended this way. Originally it was `unsigned int` but that caused warnings somewhere, so it was changed to `unsigned char`. `unsigned char` looks very unusual for a variable counter - limits the number of variables and nowhere else in the code did I find similar usage.
> This variable type looks very suspicious

- cli/filelister.cpp
I have tried to update from cppcheck 1.69 to 1.72 but failed because cppcheck failed to load files to verify recursively. Turns out that the reason is that I am using the XFS file system and the readdir_r dirent->d_type is set to DT_UNKNOWN instead of DT_DIR.
I have created a small patch to let cppcheck handle the DT_UNKNOWN situation by using the FileLister::isDirectory for this special case.
> Determine if path is directory for XFS filesystem

- lib/errorlogger.cpp
Original code would compute `npos+1` which isn't a good idea. Code would likely yield two identical strings and later fail to parse one of them as a number. Explicit error handling won't hurt.
> Check string has expected format before processing it

- lib/checkbufferoverrun.cpp
- lib/checkclass.cpp
- lib/checkfunctions.cpp
- lib/checkio.cpp
- lib/checkleakautovar.cpp
- lib/checkmemoryleak.cpp
- lib/checknullpointer.cpp
- lib/checkother.cpp
- lib/checkstl.cpp
Added propers CWEs to insecureCmdLineArgs, negativeMemoryAllocationSize, memsetClass, memsetClassReference, IOWithoutPositioning, readWriteOnlyFile, writeReadOnlyFile, useClosedFile, wrongPrintfScanfArgNum, invalidScanfFormatWidth, deallocret, leakNoVarFunctionCall, leakReturnValNotUsed, nullPointer, invalidFunctionArg, invalidFunctionArgBool, zerodiv, unusedScopedObject, doubleFree, shiftNegative, wrongPipeParameterSize, invalidIterator1, iterators, mismatchingContainers, eraseDereference, stlOutOfBounds, mallocOnClassError, virtualDestructor, 
selfInitialization.
> Mapped 29 errors to their CWEs ID.

- man/manual-ja.docbook
translate manual.docbook in en-US to manual-ja.docbook in ja-JP . this is first release of this file in Japanese.
> translate manual.docbook in Japanese v 0.01

- lib/astutils.cpp
- lib/astutils.h
- lib/checkother.cpp
- lib/checkother.h
- test/testcharvar.cpp
> Portability warning when 'char' type is used as array index

- lib/check.h
- lib/check64bit.cpp
- lib/checkassert.cpp
- lib/checkautovariables.cpp
- lib/checkbool.cpp
- lib/checkbufferoverrun.cpp
- lib/checkbufferoverrun.h
- lib/checkclass.cpp
- lib/checkcondition.cpp
- lib/cppcheck.cpp
- lib/errorlogger.cpp
- lib/errorlogger.h
Hi, 
I expanded errorLogger interface to include CWE as parameters. 
I had to move the CWE struct definition otherwise I was not able to used it inside errorlogger.h 
I mapped below list ID to their CWEs ID. 
I have only one minor doubt about the assignment of CWE  to arrayIndexOutOfBounds**Cond** error.
When is it triggered ? I've not been able to find the test case to dig more and therefore at the moment it has the same CWE as arrayIndexOutOfBounds.
toomanyconfigs
AssignmentAddressToInteger
AssignmentIntegerToAddress
CastIntegerToAddressAtReturn
CastAddressToIntegerAtReturn
assertWithSideEffect
assignmentInAssert
uselessAssignmentArg
uselessAssignmentPtrArg
comparisonOfFuncReturningBoolError
comparisonOfTwoFuncsReturningBoolError
comparisonOfBoolWithBoolError
incrementboolean …
> Mapped various errors, warnings, styles, etc to their CWEs ID

- htmlreport/cppcheck-htmlreport
I fixed a few stylistic issues in htmlreport and added checkboxes to toggle errors visibility by id. It looks like this:
> htmlreport tweaks and enhancements

- lib/checkcondition.cpp
- test/testcondition.cpp
This is a fix proposal for TRAC #7428
http://trac.cppcheck.net/ticket/7428
Tested with file:
```
void main(int a)
{
if( (a & 0x07) == 8U ) // statement always false, because 7 == 8 is false
if( (a & 0x07) > 7U ) // statement always false, because 7 > 7 is false
if( (a | 0x07) < 7U ) // statement always false, because 7 < 7 is false
if( (a & 0x07) > 8U ) // statement always false, because 7 > 8 is false
if( (a | 0x07) < 6U ) // statement always false, because 7 < 6 is false
if( (a & 0x07) >= 7U ) // statement correct
if( (a | 0x07) <= 7U ) // statement correct
if( (a & 0x07) >= 8U ) // statement always false, because 7 >= 8 is false
if( (a | 0x07) <= 6U ) // statement always false, because 7 <= 6 is false
if( (a & 0x07) > 3U ) // statement correct
if( (a | 0x07) < 9U ) // statement correct …
```
> #7428 assigned enhancement

- cli/cppcheckexecutor.cpp
fix build on OpenBSD:
cli/cppcheckexecutor.cpp:45:25: fatal error: ucontext.h: No such file or directory
OpenBSD doesn't have ucontext.h, ucontext_t is a typedef to struct sigcontext in signal.h
> fix build on OpenBSD

- lib/mathlib.cpp
- lib/mathlib.h
- test/testmathlib.cpp
This ticket highlights that we don't properly parse character literals when they contain escape sequences and are not made of a single one of those. This patch fixes this.
Thanks to consider merging,
Simon
> Ticket #7452: Properly interpret escape sequences in character literals.

- lib/mathlib.cpp
This addresses the remark @amai2012  made in https://github.com/danmar/cppcheck/commit/3af30e728cb404a2030425ea8cb6d1845469d9b1 and implements an alternative fix (IMHO better) for ticket #7500.
Simon
> Address comments in PR#794 and alternative fix for ticket #7500.

- lib/mathlib.cpp
Hi,
Another follow-up to https://github.com/danmar/cppcheck/pull/794: I don't know why and how I ended up writing "1 == std::min<unsigned>(3, iLiteralLen - idx)", but it can definitely be simplified as proposed here.
Simon
> No need to use std::min() in normalizeCharacterLiteral.

- lib/checkio.cpp
- test/testio.cpp
This ticket highlights an issue in https://github.com/danmar/cppcheck/commit/b77203a277c37ff008b9205636e0c47927316acb, that effectively considers as int any argument with an integral type smaller than int . This patch fixes this and the ticket.
> Ticket #7445: Properly represent integer types smaller than int in CheckIO::ArgumentInfo.

- lib/mathlib.cpp
- lib/mathlib.h
- lib/preprocessor.cpp
- test/testmathlib.cpp
- test/testpreprocessor.cpp
Hi,
This ticket highlights that the fix for ticket 7042 is too eager at detecting C++14 digit separators. This patch fixes this.
Simon
> Ticket #7137: Properly detect C++14 digit separators.

- lib/checksizeof.cpp
- lib/checkstl.cpp
CWE mapping of stlIfStrFind, stlcstrReturn, stlcstrParam, stlSize, StlMissingComparison, redundantIfRemove
> CWE mapping of stlIfStrFind, stlcstrReturn, stlcstrParam, stlSize, StlMissingComparison, redundantIfRemove.

- lib/checkcondition.cpp
- test/testcondition.cpp
((X&7)>7U) is always false and ((X|7)>=6) is correct (X can be negative).
> - #7522 and #7428 revisited. 

- addons/y2038/README
- addons/y2038/test/y2038-inc.h
- addons/y2038/test/y2038-test-1-bad-time-bits.c
- addons/y2038/test/y2038-test-2-no-time-bits.c
- addons/y2038/test/y2038-test-3-no-use-time-bits.c
- addons/y2038/test/y2038-test-4-good.c
- addons/y2038/y2038.py
- standardize on kernel's 'Y2038-[un]safe'
- expand Y2038-unsafe symbols list
- make y2038 addon C test more complete
> Update Y2038 addon

- lib/mathlib.cpp
- test/testmathlib.cpp
Hi,
This patch improves C++14 integer separator detection when the integer contains several of them, and fixes the ticket. Thanks to consider merging.
Simon
> Ticket #7565: Handle numbers with several C++14 integer literals.

- lib/checkbufferoverrun.cpp
Hi,
symboldDatabase, as a parameter to CheckBufferOverrun::ArrayInfo::ArrayInfo, shadows CheckBufferOverrun::symboldDatabase, and clang rightfully warns about it. This patch fixes it. Thanks to consider merging.
Simon
> Silent clang -Wshadow warning.

- tools/listErrorsWithoutCWE.py
This script once I've finished to maps all current missing errors (67) I would like that will be integrated into the continuous integration to send me an email when new errors will not have a CWE assigned and so promptly follow up with the mapping during normal development.
> added python script to list in CSV format all errors without a CWE

- lib/checkio.cpp
- lib/checkmemoryleak.cpp
- lib/checknullpointer.cpp
- lib/checkother.cpp
CWE mapping of invalidLengthModifierError, leakUnsafeArgAlloc, nullPointerDefaultArg, nullPointerRedundantCheck, raceAfterInterlockedDecrement.
> CWE mapping of invalidLengthModifierError, leakUnsafeArgAlloc, nullPointerDefaultArg, nullPointerRedundantCheck, raceAfterInterlockedDecrement.

- htmlreport/requirements.txt
- htmlreport/setup.py
I noticed for umpteenth time that I had forgotten to install Pygments before install cppcheck-htmlreport. I figured it was about time to fix the dependency in the setup.py. Please consider this pull request that adds the file requirements.text and changes the setup.py to have Pygments be an install requirement.
> Pygments is a required package

- lib/checkmemoryleak.cpp
- lib/tokenlist.cpp
- test/testmemleak.cpp
Using ::delete instead of delete confuses the memory leak checker, and this patch fixes this. Thanks to consider merging.
> Ticket #7680: Properly handle ::delete during memory leak checks.

- lib/checkother.cpp
- lib/token.cpp
- test/testother.cpp
Before:
[/tmp/test.c:8]: (style) Checking if unsigned variable '.' is less than zero.
[/tmp/test.c:12]: (style) Checking if unsigned variable '.' is less than zero.
After:
[/tmp/test.c:8]: (style) Checking if unsigned variable 'd.n' is less than zero.
[/tmp/test.c:12]: (style) Checking if unsigned variable 'd.n' is less than zero.
> Show struct member in unsignedLessThanZeroError warning

- lib/checkclass.cpp
- test/testconstructors.cpp
This ticket highlights that a missing kind of member initialization in CheckClass::initializeVarList. This patch fix this.
> Ticket #7068: Treat "memset(&this->member, ..." as member initialization

- lib/tokenize.cpp
- test/testsimplifytypedef.cpp
When a namespace is defined in multiple "pieces", we don't properly track definition end markers when simplifying typedefs, hence the ticket. This patch fixes this.
> Ticket #7541: Properly keep track of namespace definition end markers

- lib/preprocessor.cpp
- test/testpreprocessor.cpp
Cppcheck 1.76 introduced a regression in preprocessor which causes
the following code to hang:
$ cat > test.c << EOF
#ifndef Y
#else
#endif
EOF
$ cppcheck -D BAR --force test.c
Checking test.c ...
^C
This used to work with version 1.75. Git bisect reveals that this
regression was caused by commit:
ff036c8742e8f3a0a54d36dbbbb9845af7d22c53
This commit fixes the regression by avoiding infinite loop in
hasDefine(). If cfg is empty string "", we can skip the whole loop
and exit early.
> Fixes preprocessor regression causing hang

- Makefile
- lib/astutils.cpp
- lib/astutils.h
- lib/checkcondition.cpp
- lib/valueflow.cpp
- lib/valueflow.h
- test/testcondition.cpp
- test/testnullpointer.cpp
- test/testvalueflow.cpp
In astutils::isVariableChanged there is a comment "TODO: check if function parameter is const".
I want to put the following changes under discussion by this pull request.
This pull request removes the TODO by having a common function astutils::isVariableChangedByFunctionCall.
The algorithm used is the one from valueflow::bailoutFunctionPar (which handles const parameters correctly).
With this pull request astutils::isVariableChangedByFunctionCall is used in valueflow, too.
(As a minor change it contains a commit which removes the unused ValueKind::Min and ValueKind::Max.)
The question is know if the naming of the function isVariableChangedByFunctionCall is OK and if the location for this function in astutils is OK.
> Function parameter

- cli/cppcheckexecutor.cpp
On systems where glibc is not available, execinfo.h should not be
included.
> execinfo.h is part of glibc

- lib/tokenize.cpp
- test/testtokenize.cpp
Known variable simplification must be aware of enumerators and leave them untouched even if they are called the same as a constant variable.
> Ticket #7805: Ignore enumerators when simplifying known variables.

- lib/checknullpointer.cpp
- lib/checkother.cpp
CWE mapping of accessMoved, accessForwarded, nullPointerArithmeticRedundantCheck, nullPointerArithmetic.
> CWE mapping of accessMoved, accessForwarded, nullPointerArithmeticRedundantCheck, nullPointerArithmetic

- lib/checkleakautovar.cpp
- test/testleakautovar.cpp
Encountering such a pattern, free(some_func(p)) would lead cppcheck to believe that p was deallocated, which might be wrong. This patch fixes this.
> Ticket #7685: Properly handle function calls as argument to a dealloc function

- man/manual.docbook
Add documentation for showing how to ignore multiple directories.
Also highlight the fact that the -i option does not currently work in conjunction with the --project option.
> Example of ignoring multiple directories

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
This patch fixes how we detect the end of a template parameter default value when instantiating: the logic was flawed and would stop at the first comma. This is wrong if the default value is a template with multiple parameters.
I've added a TODO because we don't properly expand the default value if it depends on other template parameters of the template being instantiated. That's for another patch.
> Ticket #7548: Properly detect the end of template parameter default values during instantiation

- lib/checkmemoryleak.cpp
- test/testmemleak.cpp
This patch fixes the ticket by removing blocks that are of no use for the analysis: they're conditioned by the variable being not set, and allocate + deallocate.
> Ticket #7745: Simplify "alloc ; dealloc ;" blocks that we don't have any value for CheckMemoryLeak's analysis.

- lib/checkmemoryleak.cpp
- test/testmemleak.cpp
I've noticed that the snippets that I added in that patch were not giving any leak error while they should. This patch fixes this.
> Teach CheckMemoryLeak about "alloc ; loop alloc ;" kinds of patterns.

- lib/checkmemoryleak.cpp
- test/testmemleak.cpp
This ticket shows that the leak detector can be confused by "return", and this patch fixes this.
I've removed line 1972 because I could not understand why it's needed (it will still leak when we're towards the EOF...), and the test suite keeps passing without it.
> Ticket #7820: Properly report leaks with conditional deallocations followed by a return.

- lib/checkunusedvar.cpp
- test/testunusedvar.cpp
- Added support for C++11 style initialization:
`int var{123}; // instead of int var = {123};`
- Fixed http://trac.cppcheck.net/ticket/7895
- Added test.
I'm not sure how to handle `--std=c11` option here.
> (Fixed #7895) C++11 brace initialization

- lib/templatesimplifier.cpp
- test/testother.cpp
Removed skipping braces in `checkComplicatedSyntaxErrorsInTemplates` (not sure if it was intended).
> (Fixed #7846) Syntax error when using C++11 braced-initializer in function last argument

- lib/tokenize.cpp
- test/testmemleak.cpp
- test/testtokenize.cpp
This ticket shows that pointer alias analysis is aborted in cases it should not. This patch fixes it.
> Ticket #7440: Function calls should not abort pointer alias analysis for local variables.

- lib/templatesimplifier.cpp
- test/testclass.cpp
- test/testsimplifytemplate.cpp
- test/testsimplifytokens.cpp
- test/testtokenize.cpp
The ticket is a consequence of removing all spaces in the template instantiations parameters. This patch fixes this. I believe that the changes needed in testTemplateSimplifier highlight that we're also more consistent now.
> Ticket #7891: Do not remove spaces in the internal representation for template instantiations.

- lib/templatesimplifier.cpp
- test/testgarbage.cpp
- test/testsimplifytemplate.cpp
- test/testsimplifytokens.cpp
This ticket highlights that we would not recognise patterns like "<i == 0>" as template parameters, which is wrong.
Fixing that caused regressions all due to considering template instantiations within template definitions as instantiations. This is incorrect: they will really be instantiations (and handled correctly) only be if their enclosing template is instantiated. This patch also fixes that.
> Ticket #7914: Properly recognize template parameters that contains operators

- lib/tokenize.cpp
- test/testsimplifytokens.cpp
This ticket highlights that we're wrongly simplifying return statements involving trivial template functions. This is because template instantiations might be on a single or multiple tokens depending on the cases (eg "foo < bar >" vs "foo" + "<" + "bar" + ">"). This is the real bug, that I will track via http://trac.cppcheck.net/ticket/7921.
Until then, this patch fixes the priority high ticket in what I believe is an acceptable manner.
> Ticket #7916: Don't incorrectly simplify return statements involving template instantiations.

- lib/preprocessor.cpp
- test/testpreprocessor.cpp
This ticket shows that we don't preprocess files that have "decreasing line numbers" (due to using #line): we don't properly space separate tokens in Preprocessor::getcode(), and end up doing "use after free"... This patch fixes this.
> Ticket #7912: Properly preprocess files with decreasing line numbers, due to #line directives

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
While investigating http://trac.cppcheck.net/ticket/7942 I noticed that getTemplateNamePosition does not properly support out-of-line definitions of template methods. This patch fixes this.
> Update TemplateSimplifier::getTemplateNamePosition to handle out-of-line template methods.

- lib/checkother.cpp
CWE mapping of funcArgOrderDifferent, funcArgNamesDifferent
> CWE mapping of funcArgOrderDifferent, funcArgNamesDifferent

- cli/cmdlineparser.cpp
Just a simple typo fix for the --library option description.
> Remove redundant word in --library description

- lib/templatesimplifier.cpp
- test/testconstructors.cpp
- test/testsimplifytemplate.cpp
This ticket highlights that we don't properly instantiate out of line template class constructors, which confuses the class analyser. The patch fixes this, and the ticket.
> Don't generate invalid syntax for out of line template class constructors during instantiation

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
I've noticed that the fix for http://trac.cppcheck.net/ticket/4544 is not complete, in that it handles class but not struct. This patch fixes it.
> Ticket #4544: Also handle Foo<struct Bar> constructs.

- lib/checkbufferoverrun.cpp
- test/testbufferoverrun.cpp
Trivial fix for a crash on valid.
> Ticket #7964: Don't crash on valid code using function pointers named strcpy or strcat in main()

- lib/templatesimplifier.cpp
- lib/tokenize.cpp
- test/testsimplifytemplate.cpp
- test/testtokenize.cpp
The ticket highlights two issues with out of line template constructor: a bail out and missing varid setting. This patch fixes both.
> Ticket #8031: Remove bailout and fix varid for template class member initialized in out-of-line constructor.

- tools/dmake.cpp
running dmake under mingw64 causes an error
the makefile will have to be recreated
under linux
error:
tools/dmake.o: In function `getCppFiles':
F:\MSYS\home\cppcheck/tools/dmake.cpp:98: undefined reference to `FileLister::addFiles(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, …
> dmake: Add support for mingw64

- tools/matchcompiler.py
During parallel build, multiple processes will try to create build_dir in parallel, so the build will fail. Fix that by calling makedirs unconditionally and ignoring errors from it. If there's actual problem with directory creation, it'll be caught later by isdir() check.
Actual build error:
```
Traceback (most recent call last):                                                                                                                                                                                                                              
File "/wrkdirs/usr/ports/devel/cppcheck/work/cppcheck-1.79/tools/matchcompiler.py", line 692, in <module> …
```
> Fix matchcompiler failure in case of parallel build

- htmlreport/cppcheck-htmlreport
When source code contains non-ASCII characters, `cppcheck-htmlreport` currently dies with an error like:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 80673: ordinal not in range(128)
```
This is because even though the source code is read as UTF-8, and `HTML_HEAD` specifies that the file should be read as UTF-8, the output file is opened with the default encoding (ascii).
This should fix all of the cases that #869 fixes, in a better way (by actually writing non-ASCII characters properly as UTF-8 rather than skipping them).
> Write HTML report as UTF-8

- Makefile
- tools/dmake.cpp
When using a specific version of clang++ or g++ via environment variables detection of compiler in the makefile fails. For example: 
> CXX=clang++3.8 make
The command above fails because addition of "CXXFLAGS += -std=c++0x" is conditional based on compiler exact name. That is makefile only expect strict comparison "ifeq ($(CXX), clang++)" and string "clang++3.8" is not equal to "clang++".
This simple PR fixes this issue making it easier to build cppcheck with different version of compiler installed. This is especially handy with Travis CI.
> Make detection of clang++ compiler more robust

- lib/importproject.cpp
While parsing Visual Studio solutions, include paths are collected from all projects and their property sheets so it is quite likely that the same include path occurs multiple times.
This PR removes duplicate entries before setting the includes.
It would have been better to change the behavior higher up in the callstack but since the includepaths are handled as a string there, its a bigger change for some other time.
This PR will help when implementing [enhancement # 8110](http://trac.cppcheck.net/ticket/8110) because less variables will have to be evaluated.
> Unique includes

- lib/checkother.cpp
- test/testother.cpp
A unique pointer should only be passed by value or by const reference.
Passing by value means transferring ownership it makes no sense to have a pass by value Warning for unique_ptr.
Signed-off-by: Andreas Pokorny <andreas.pokorny@siemens.com>
> Do not warn when unique pointers are passed by value

- cli/filelister.cpp
which should fix the build again
this is missing from [this commit](https://github.com/danmar/cppcheck/commit/c4bd70210c40bcab84d10a1261fe170a8af5792e) by @danmar
> add missing change from "GUI: Rename methods in FileList and PathMatch"

- lib/tokenize.cpp
- test/testtokenize.cpp
simplifyNamespaceStd might insert std:: within enum definitions, and it should not. This patch fixes this by simply skipping enum definitions.
> Ticket #8091: Don't replace std types within enum definitions.

- CMakeLists.txt
- cmake/findDependencies.cmake
- gui/CMakeLists.txt
The latest commit with comment "GUI: modernize connect ..." for example 5e189de95611fa3fb9eb1cef30a1340deab04bfb require Qt5.
However, the CMake build still used Qt4.
This pull request upgrades the CMake build to use Qt5 such that it can build the current sources.
> CMake: Upgrade Qt4 to Qt5

- cli/cmdlineparser.cpp
@danmar I'm not fully sure so could you please review this?
It looks like this `tryLoadLibrary()` call tries to load windows.cfg which should never fail in normal scenarios. However the current code ignores the result and silently continues execution. This doesn't look good at all.
> Resolve CID 1365360

- lib/astutils.cpp
This is PR to see how tests pass. Will push the change myself if it's good.
> Fix typo causing two expressions being identical

- addons/misra.py
Hello!
I'm not quite sure if your intention was to make MISRA C 2012 addon (`addons/misra.py`) work with C++ codes or not, current `misra.py` addon work well with C++ codes.
I found it is highly useful to detect some rules of MISRA C++ 2008, specifically intersection of MISRA C and C++ .
To make current `misra.py` work with C++ smoothly, I made a subtle change.
Followings are the reason of my change.
If you try to analyze below code with current `misra.py`,
```
#include <iostream>
int main(void)
{
std::cout<<"Hello"<<"World!"<<std::endl;
return 0;
}
```
You will encounter following error.
```
Checking test.cpp.dump...
File "addons/misra.py", line 1107, in <module>
misra_12_2(cfg)
File "addons/misra.py", line 590, in misra_12_2
if val.intvalue > maxval: …
```
> Make MISRA C 2012 12.2 work on C++

- lib/symboldatabase.cpp
- test/testconstructors.cpp
Corrects a false positive related to the handling of noexcept constructors. Without the patch, the delegating ctor call is not recognized as a function. The function pointer seems to be set, but is not marked with the the releted eType accordingly.
> Corrected noexcept constructor delegating handling

- gui/readme.txt
- gui/test/common.pri
- gui/test/test.pro
Update readme instruction to install and build with qt5 only. Remove version check for newer version as qt4.
> Remove theoretical qt4 support for gui projects

- lib/symboldatabase.cpp
- lib/tokenize.cpp
- lib/tokenize.h
- lib/tokenlist.cpp
- lib/tokenlist.h
- test/testio.cpp
I have observed a false positive while analyzing my project. An example of code caused cppcheck warnings:
`void f() {
const char *s = "0";
printf("%ld%lld", atol(s), atoll(s));
}`
And warnings themselves:
`[test.cpp:3]: (warning) %ld in format string (no. 1) requires 'long' but the argument type is 'signed int'.`
`[test.cpp:3]: (warning) %lld in format string (no. 2) requires 'long long' but the argument type is 'signed int'.`
Configuration for functions in std.cfg were ok: return value type for atol - long int, for atoll - long long int. Further reading of source code led to the conclusion that cppcheck uses only last keyword in the configured string - int, because return value type was not rolled up as it is done in the tokenizer for the analized file.
In my patch I suggest to move …
> Wrong type parsing for library functions (from /cfg)

- Makefile
- lib/path.cpp
- lib/path.h
- lib/valueflow.cpp
- readme.md
- test/testsimplifytypedef.cpp
- test/testsuite.cpp
- test/testsuite.h
- test/testtokenize.cpp
- test/testvalueflow.cpp
I refactored the macros and function bailoutInternal (shifted preprocess-time logic to run-time logic as suggested).
> pull request for ticket 8180 (better diagnostic output for bailouts)

- cli/CMakeLists.txt
Fixes linking problems of the cmake project (at least for Visual Studio 2017). This is also vital for conan.io support, hence a new release after the pull would be nice.
> Link to Shlwapi.lib on MSVC to get rid of missing symbol issues.

- lib/symboldatabase.cpp
- lib/symboldatabase.h
Checking whether a token is an enumerator in all the available scopes
is expensive.  Once we determined that a token is not an enumerator,
skip all the expensive checks.
> Use a 'negative cache' for tokens / enumerator checks

- cfg/windows.cfg
__pragma is Microsoft specific keyword equivalent to C99 _Pragma operator
https://msdn.microsoft.com/en-us/library/d9x1s805.aspx
https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html
http://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas
It seems cppcheck does not support _Pragma at the moment.
This change will fix syntax error on code that looks like this:
#define MY_DEPRECATED_ENUM(X) X __pragma(deprecated(X))
enum myEnum
{
myEnum_1 = 1,
MY_DEPRECATED_ENUM(myEnum_2) = 2,
myEnum_3,
myEnum_4,
};
int main()
{
myEnum a = myEnum_3;
printf("%d", a);
return 0;
}
This change was fiscussed here: https://sourceforge.net/p/cppcheck/discussion/general/thread/1808a46b/
> Workaround for syntax error on Microsoft specific __pragma keyword

- addons/misra-test.c
- addons/misra.py
Hello! I found one misbehavior of current MISRA addon, and made small change :)
MISRA 15.7 is limited to if-else statements. Rule 15.7 says `if-else` constructs shall end with `else` block.
In current `addons/misra.py`, every if statements is checked whether they has else statements including simple if statements, which is explicitly mentioned in MISRA C Guide Document as an exception.
My change works as follow (also added following change to `addons/misra-test.c`)
```
if (x!=0){} // compliant, (is reported in current misra.py)
if (x!=0){} else if(x==1){} // non-compliant, 15.7
if (x!=0){} else if(x==1){}else{;} // compliant
```
> MISRA 15.7 only checks if...else if constructs

- lib/astutils.cpp
- lib/checkbufferoverrun.cpp
- lib/checkcondition.cpp
- lib/checkio.cpp
- lib/checknullpointer.cpp
- lib/checkstl.cpp
- lib/symboldatabase.cpp
- lib/tokenize.cpp
I'm a member of the [Pinguem.ru](https://pinguem.ru) competition on finding errors in open source projects. All issues were found with [PVS-Studio](https://www.viva64.com/en/pvs-studio/):
- V560 A part of conditional expression is always true: tok. astutils.cpp 407
- V560 A part of conditional expression is always true: size > 0. checkbufferoverrun.cpp 709
- V547 Expression 'secondTrue' is always true. checkcondition.cpp 1013
- V547 Expression 'firstTrue' is always true. checkcondition.cpp 1020
- V560 A part of conditional expression is always true: !scan. checkio.cpp 1036
- V560 A part of conditional expression is always true: scope->function. checknullpointer.cpp 395
- V560 A part of conditional expression is always true: tok2. checkstl.cpp 268
- V560 A part of conditional expression is …
> Remove redundant parts of conditional expressions

- lib/tokenize.cpp
- lib/tokenize.h
- test/testtokenize.cpp
Cppcheck is able to isolate embedded SQL blocks written for Oracle Pro\*C precompiler with use of wrappers in the form of assembler inline sections. So any following constructions are skipped well:
`EXEC SQL ... ;`
However Pro\*C precompiler also allows to embed more complicated blocks containing unnamed procedures written in Oracle procedure language (PL/SQL) or even definitions of named Oracle objects, like procedures, functions and sequences. In both the cases embedded block syntax as follows [(docs.oracle.com)](https://docs.oracle.com/cd/B28359_01/appdev.111/b28427/pc_07pls.htm#i2332) :
```
EXEC SQL EXECUTE
DECLARE
... 
BEGIN 
... 
END; 
END-EXEC; 
```
Both DECLARE section (optional) and procedure body section can contain mutiple lines terminated with ';'.
Suggested patch allows to …
> Fix for embedded PL/SQL blocks (Oracle Pro*C)

- test/testio.cpp
Will push it myself if tests pass.
> Improve test coverage for ptrdiff_t used as scanf read target with %Id

- lib/importproject.cpp
- lib/importproject.h
- test/testrunner.vcxproj
- test/testrunner.vcxproj.filters
transform relative paths (to property sheets) with the help of the project dir to absolutepaths so the actual checker can resolve include paths defined in property sheets.
This helps with Visual Studio adding paths rather as relative than absolute, so it is the quasi default.
Before, relative property sheets were not loaded and so the defined include paths from the property sheets were unknown resulting in false errors. This completes PR #917.
> Support relative paths in Visual Studio projects properties

- cfg/windows.cfg
The first three arguments can be NULL.
Reference: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724353.aspx
> windows.cfg: fix GetPrivateProfileString nullPointer FP

- cfg/windows.cfg
Add configuration for Sleep and SleepEx on Windows.
Not sure how to implement that the functions do not return when the first parameter is INFINITE.
> windows.cfg: Add Sleep and SleepEx

- cfg/microsoft_sal.cfg
Add annotations which are not so well documented, but could be/are used
in custom code.
> MS SAL config: add more defines for annotations

- lib/preprocessor.cpp
since its not used subsequently and all subfunction check for nullptr.
Since `Preprocessor::loadFiles()` is often called, this might have a performance impact.
Testrunner finishes without error and the output/results of `cppcheck` seem to be the same.
There might be a very good reason for the existance of `outputList` but then id expect at least a comment.
> remove outputList 

- cli/cli.vcxproj
- lib/cppcheck.vcxproj
- test/testrunner.vcxproj
This makes debugging and profiling easier and has no drawback as long as the PDB
files are not distributed (which would blow up installer sizes)
> Also generate debug information when building for release

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
The ticket is due to instantiateMatch not working properly when template parameters involve sizeof or qualified namespaces. This patch fixes this.
> Ticket #8175: Fix bug in TemplateSimplifier::instantiateMatch with template parameters involving sizeof or namespace.

- gui/main.cpp
Currently cpp check doesn't use its full user interface potential because of the lack of high dpi scaling. Without proper high dpi scaling, the user interface symbols become very tiny.
This patch enables high dpi scaling per default in case the target qt version is >= 5.6.0
> enable high dpi scaling when qt version >= 5.6.0

- man/manual.docbook
Because the configuration for strncpy contained sizeof by error, the example was no longer correct.
Replaced with a reference to memccpy which uses sizeof.
> Manual: Fix sizeof reference to strncpy config

- lib/cppcheck.cpp
- lib/importproject.cpp
- lib/importproject.h
- test/testimportproject.cpp
Define values are now parsed when using compile_commands.json.
> Fix define parsing from compile_command.json

- gui/libraryeditargdialog.cpp
- gui/libraryeditargdialog.ui
The list of items for the minsize attributes in the LibraryEditor
contains the illegal value "constant" which is removed by this PR.
> Fix 7439: GUI: Remove value "constant" from minsize attribute items list

- cfg/windows.cfg
While it was good to remove use-retval from the LoadLibrary* functions,
it is still needed for GetProcAddress. A call of GetProcAddress without
using the return value does not make sense.
> Fix windows.cfg: GetProcAddress needs use-retval

- lib/symboldatabase.cpp
- lib/symboldatabase.h
- test/testsymboldatabase.cpp
This is an attempt to fix issue #7331.
Copy and move constructors can have additional trailing parameters provided that they all have default values. See [copy ctors](http://en.cppreference.com/w/cpp/language/copy_constructor) and [move ctors](http://en.cppreference.com/w/cpp/language/move_constructor).
My approach has been to move the copy/move constructor detection to a later stage in the symbol database construction. They're initially parsed as regular constructors and checked if copy/move after default values have been parsed. Suggestions welcome, of course :innocent:
> Fixed #7331: Detect copy and move constructors with default parameters

- cfg/windows.cfg
Tested with this code:
```
// Valid code
void test_ok1()
{
HANDLE event;
event = CreateEvent(NULL, FALSE, FALSE, NULL);
if(NULL != event)
{
SetEvent(event);
CloseHandle(event);
}
}
void test_ok2()
{
HANDLE event;
event = OpenEvent(EVENT_ALL_ACCESS, FALSE, L"testevent");
if(NULL != event)
{
PulseEvent(event);
SetEvent(event);
CloseHandle(event);
}
}
void test_ok3()
{
HANDLE event;
event = CreateEventEx(NULL, L"testevent3", CREATE_EVENT_INITIAL_SET, EVENT_MODIFY_STATE);
if(NULL != event)
{
ResetEvent(event);
CloseHandle(event);
}
}
// Invalid code: uninitialized handles used
void test_error1()
{
HANDLE event1;
// cppcheck-suppress uninitvar
PulseEvent(event1);
HANDLE event2;
// cppcheck-suppress uninitvar
ResetEvent(event2);
HANDLE event3;
// cppcheck-suppress uninitvar
SetEvent(event3); …
```
> windows.cfg: Add *Event functions configuration

- lib/symboldatabase.cpp
- lib/symboldatabase.h
- lib/tokenize.cpp
- test/testsymboldatabase.cpp
Only types supported by ValueType are supported. Complex types like
function pointers are not supported. Template type aliases are not
supported.
> Add support for simple c++ 11 type ailases like: using INT = int;

- cfg/windows.cfg
I have some problems configuring the CRITICAL_SECTION functions:
How should i define CRITICAL_SECTION for cppcheck?
It is a struct and only used internally by Windows and looks like this:
```
typedef struct _RTL_CRITICAL_SECTION {
PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
LONG LockCount;
LONG RecursionCount;
HANDLE OwningThread;        // from the thread's ClientId->UniqueThread
HANDLE LockSemaphore;
ULONG_PTR SpinCount;        // force size on 64-bit systems when packed
} RTL_CRITICAL_SECTION, *PRTL_CRITICAL_SECTION;
typedef RTL_CRITICAL_SECTION CRITICAL_SECTION;
```
I guess the checks will not detect as much as they could if this is not known to cppcheck.
Since a CRITICAL_SECTION is some sort of resource i wanted to add a resource description:
```
<resource>
<alloc init="true" …
```
> windows.cfg: Add CRITICAL_SECTION handling functions.

- cli/cppcheckexecutor.cpp
- lib/check.h
- lib/checkbufferoverrun.cpp
- lib/checkbufferoverrun.h
- lib/checkunusedfunctions.cpp
- lib/checkunusedfunctions.h
- lib/cppcheck.cpp
- lib/cppcheck.h
- test/testsuppressions.cpp
- test/testunusedfunctions.cpp
This commit fixes https://trac.cppcheck.net/ticket/7502 ticket by returning error flag from analyseWholeProgram. The provided test case in the ticket succeeds now.
> Fixed #7502 (Correct exit code if never used function is found)

- cfg/windows.cfg
On the MSDN there is a prominent warning to not use this function, so i
decided to add a warn entry. See
https://msdn.microsoft.com/de-de/library/windows/desktop/ms647487(v=vs.85).aspx
for details.
> windows.cfg: Add lstrcat configuration

- cfg/std.cfg
It should be std::sinf here. std::sinl is described directly in the next function description and does not make sense here because of the return type.
> std.cfg: Fix copy&paste error or typo

- cfg/posix.cfg
It seems to be a copy & paste error.
The comment, the return value, the warn entry and the rest of the
configuration suggest that this must be the getprotobynumber function
configuration and not the getservbyport configuration which would be
redundant as it is configured a bit later.
> posix.cfg: Fix getprotobynumber configuration

- cfg/windows.cfg
Detected some errors when checking for redundant function
configurations:
The functions that receive an additional argument "locale" have the
suffix "_l".
Sadly the MSDN shows wrong declarations that are missing the "_l", i
guess this caused the wrong names (I have reported it to Microsoft, but
do not expect that this is fixed soon).
The function configuration for GetModuleHandle* existed twice, i have
merged them, and it looks sane for me now.
> windows.cfg: Fix redundant function configurations

- lib/symboldatabase.cpp
- test/testgarbage.cpp
Properly bailout upon invalid function parameters in SymbolDatabase.
> Ticket #8333: Properly report a syntax error for functions with invalid parameter types.

- lib/symboldatabase.cpp
- test/testclass.cpp
A::A(A*&) is not a copy constructor for A.
> Ticket #8337: Fix false positive in copy constructor detection.

- lib/tokenize.cpp
- test/testtokenize.cpp
There was improper check has been added in the pull request [#985](https://github.com/danmar/cppcheck/pull/985).
Member access operators (& | . | ->) in fact are allowed inside the arguments passed for embedded SQL query, for example:
`EXEC SQL SELECT 1
INTO :dummy
FROM SOME_TABLE
WHERE SOME_COLUMN = :&some_ptr->some_struct.some_fld;`
I am not sure whether access to static members of a class in C++ (::) is permissible inside the incoming argument of queries, but I think it would be better to exclude it as well.
> Member access operators inside the embedded SQL block

- cfg/posix.cfg
- test/cfg/posix.c
I intentionally removed the second access() configuration because it was
missing the use-retval attribute. But calling access() without using the
return value is absolutely senseless.
I added tests to posix.c to verify the correct configuration of
access().
> posix.cfg: access(): Removed redundant configuration, added tests

- cfg/std.cfg
This fixes some more redundant function configurations. Seems like they
are the result of copy & paste errors.
> std.cfg: Fix redundant function names

- cfg/posix.cfg
I carefully removed the duplicate/redundant entries with less/missing
configuration, so no information is lost.
> posix.cfg: Remove redundant entries

- cfg/windows.cfg
By telling cppcheck about the Microsoft Windows _countof() macro it is
now able to detect out of bounds array accesses like this:
```cpp
wchar_t buf[10];
for(size_t i = 0; i <= _countof(buf); ++i) {
buf[i] = L'\0'; /* (error) Array 'buf[10]' accessed at index 10, which is out of bounds.*/
}
```
> windows.cfg: Add _countof macro configuration

- cfg/windows.cfg
Code used for testing:
```cpp
// Valid code
void test_mutex1ok()
{
HANDLE hMutex;
hMutex = CreateMutex(NULL, TRUE, NULL);
if(hMutex)
{
ReleaseMutex(hMutex);
}
CloseHandle(hMutex);
}
void test_mutex2ok()
{
HANDLE hMutex;
hMutex = CreateMutexEx(NULL, NULL, 0, MUTEX_ALL_ACCESS);
CloseHandle(hMutex);
}
void test_mutex3ok()
{
HANDLE hMutex;
hMutex = OpenMutex(MUTEX_ALL_ACCESS, FALSE, "sem");
CloseHandle(hMutex);
}
// Invalid code: Wrong arguments
void test_mutex1error()
{
HANDLE hMutex;
// cppcheck-suppress uninitvar
ReleaseMutex(hMutex);
// cppcheck-suppress uninitvar
CloseHandle(hMutex);
// cppcheck-suppress invalidFunctionArgBool
hMutex = CreateMutex(NULL, TRUE, false);
CloseHandle(hMutex);
// cppcheck-suppress invalidFunctionArgBool
hMutex = CreateMutex(NULL, FALSE, true); …
```
> windows.cfg: Add Mutex function configurations

- cfg/std.cfg
[std::]strtoimax and [std::]strtoumax:
They were nearly completely duplicates, i removed the ones with
less/missing configuration.
std::basic_string::empty:
It was found to be redundant because very likely someone forgot to
change "empty" to "clear" when copy&pasting the function names. The
empty function in all these clear functions makes no sense, and the
clear function also was missing.
std::queue::empty and std::array:empty:
They were both twice in the same function name list.
std::string::size, std::wstring::size:
They were already configured with many other size functions above.
std::basic_string::size:
This entry was twice in the same function name list directly one after
another. Very likely one of them should be the length function, which
does simply the same but was missing in …
> std.cfg: Fix remaining functions found to be redundant

- test/cfg/runtests.sh
- test/cfg/windows.cpp
Implemented tests for the following windows configurations (more will
follow):
-Semaphore usage
-lstrcat function configuration
-_countof macro configuration
-Mutex usage
-Library usage (LoadLibrary, GetProcAddress, ...)
> Add windows configuration tests

- cmake/findDependencies.cmake
Otherwise the build may fail if Qt libraries are installed but qmake is not
Log from such failure:
```
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/local/libexec/ccache/cc
-- Check for working C compiler: /usr/local/libexec/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at …
```
> Don't try to detect Qt if GUI is disabled

- lib/tokenize.cpp
- test/testtokenize.cpp
Support global namespace types as return type for template functions.
> Ticket #8361: Fix false positive in Tokenizer::findGarbageCode.

- lib/tokenize.cpp
- test/testgarbage.cpp
- test/testtokenize.cpp
This fixes an issue with the check for case keywords outside of switch
detection that would treat a case statement inside a switch that is not
a compound statement as garbage, but this is perfectly valid C++. This
construct is used in several libraries, i.e. Google Test.
> Fixes issue with case inside switch that is not a compound statement

- lib/token.cpp
A `nullPointerRedundantCheck`-warning should be shown by cppcheck.
This PR fixes this issue in our codebase.
This is a reduced testcase:
```
void f(bool a, int *s)
{
for(int i = 0; i < 42; ++i)
if(*s) {}
if(s && a) {}
}
```
> token: Fixed potential null pointer dereference.

- cfg/std.cfg
- test/cfg/std.c
Remove misspelled function configuration "strbprk" (also from the
tests). The correct function "strpbrk" is already configured and tested.
> std config: Remove misspelled function "strbprk"

- runastyle.bat
Add astyle version check.
Changed "test/cfg/*.cpp" sources to "test/cfg/*.c*" to match C files
also.
Use a variable for the program name.
> runastyle.bat: Adapt functionality from bash script

- cfg/posix.cfg
- test/cfg/posix.c
In the posix library there is the same configuration for strtok but a
warning is added. This commit adds tests for the posix strtok.
> posix library: Add strtok tests

- lib/symboldatabase.cpp
There is a  potential `nullPointer` dereference in symboldatabase. This PR attempts to fix this. Additionally, this could be detected by Cppcheck as well. 
Here is a reduced and compilable testcase, where Cppcheck fails to detect a potential `nullPointer` dereference:
```
class Scope
{
public:
bool bar();
int *definedType;
};
int f(Scope *new_scope)
{
int ret = 1;
if (new_scope)
{
if (new_scope->bar())
{
if (!new_scope->definedType) {} // check for null
ret = *new_scope->definedType; // dereference
}
}
return ret;
}
```
The corresponding ticket on track, addressing the false negative: https://trac.cppcheck.net/ticket/8375
> symboldatabase: Fix potential null pointer dereference

- runastyle.bat
Add formatting of the configuration files (cfg/*.cfg) if the xmllint
binary is found.
Changed windows commands and arguments to uppercase to be consinstent.
Silenced the output of commands that is not interesting.
Tested with the xmllint binaries and libraries found here:
ftp://ftp.zlatkovic.com/libxml/
> runastyle.bat: Add optional cfg file formatting, cleanup.

- cfg/windows.cfg
- test/cfg/windows.cpp
Add configuration for the deprecated strlwr/strupr functions with
according warning.
test/cfg/windows.cpp: Added tests for strlwr and strupr. Moved function
call that does not return (FreeLibraryAndExitThread) to the end of the
function to fix analysis that was silently aborted at that point
(reported as issue #8378).
> windows library: Add strlwr/strupr configuration, fixing tests

- cfg/windows.cfg
- test/cfg/runtests.sh
- test/cfg/windows.cpp
Add function configurations with tests for:
GetLocalTime, GetSystemTime, GetLastError, SetLastError,
AllocateAndInitializeSid, FreeSid, HeapAlloc, HeapReAlloc, HeapFree,
HeapSize, HeapValidate and GetProcessHeap.
test/cfg/runtests.sh: Enable --inconclusive for the windows tests to
avoid some issues in the future.
> windows library: Add function configurations with tests

- cfg/windows.cfg
- test/cfg/windows.cpp
- test/testio.cpp
This fixes false positives because of wrong configuration in
windows.cfg.
Add tests in testio.cpp and test/cfg/windows.cpp to avoid regression.
> Fix 8381: false positives for swprintf_s and stprintf_s

- lib/tokenize.cpp
- test/testtokenize.cpp
The following snippet triggerd the error:
```
template<typename DerivedT>
template<typename T>
auto ComposableParserImpl<DerivedT>::operator|( T const &other ) const -> Parser {
return Parser() | static_cast<DerivedT const &>( *this ) | other;
}
```
Whenever simplifyFunctionParameters was called on a templated class'
templated member function (and probably any nested template), the
tokenizer would recognise it as a syntax error, assuming that return
type *must* come after a template<> token.
> Accept nested templates in tokenizer-simplify

- lib/checkbufferoverrun.cpp
- lib/checkuninitvar.cpp
- lib/checkunusedfunctions.cpp
- lib/cppcheck.h
- lib/errorlogger.h
- test/testunusedfunctions.cpp
This is a fix of commit 97ffec8 (of pull request #1026)
Tobias Burnus <tobias.burnus@physik.fu-berlin.de> reported me this issue:
To my problem: We use cppcheck with
--error-exitcode=1
--suppress=unusedFunction:xptiles.cc:805
Since the following patch that fails because cppcheck returns
the exit code 1 (as an unused function is found) but the patch
does not honor that it can be suppressed.
Namely, the test in lib/checkunusedfunctions.cpp's CheckUnusedFunctions::check
finds an unused function - and, hence, uses:
unusedFunctionError(errorLogger, filename, func.lineNumber, it->first);
errors = true;
This commit fixes the issue.
> Suppressed unused functions should not lead to non-zero exit code

- cfg/cppcheck-cfg.rng
I need a solution to configure functions that return a value by
reference.
This PR might not be the best solution, since it also allows reference
to reference to...
I'm not sure if this is valid C++, but generally a reference to a
reference is possible.
I'm also no regex expert, so any help here is greatly apreciated.
> cppcheck-cfg.rng: Allow return value by reference

- cfg/wxwidgets.cfg
- test/cfg/runtests.sh
- test/cfg/wxwidgets.cpp
Add test file for wxwidgets configuration, fix found issues and enhance
the cfg a bit:
Fix declarations in comments for wxLog* functions.
Merge the two wxTextFile::Create overloaded function configurations into
one that works for both now.
Removed use-retval attribute from wxBoxSizer::AddSpacer configuration
since the function has side effects and there is no need to use the
return value.
Add some function configurations, the macro _(str) and POD wxLogLevel.
> wxwidgets library: Fix/Enhance cfg, add test file

- test/cfg/runtests.sh
- test/cfg/wxwidgets.cpp
For the syntax check g++ needs to know the wxWidgets include paths which
are retrieved via wx-config. If includes are missing or not working the
syntax check is skipped.
wxwidgets.cpp: Fixed syntax, includes and added code so the syntax check
does not fail if some special features are not present.
> wxwidgets library tests: Add syntax checking, fix test file.

- cfg/std.cfg
- test/cfg/std.c
Add equivalent tests for the wide character string functions like they
are already done for the normal string functions.
Fixed some issues with the configuration of the wide character string
functions that arised through the tests and were already fixed for the
normal string functions.
> std library: Add tests for wide character string functions, fix config

- cfg/std.cfg
- test/cfg/std.c
First resolved TODO in std.c is obsolete since the "res" variable is used later
and there is therefore no warning issued.
Second resolved TODO in std.c: A warning for uninit variables is issued by
cppcheck, so this check can be enabled. But to let "make checkcfg"
succeed also the noreturn in std.cfg had to be specified for assert.
Since assert normally does return (depending on the implementation it
always returns and only prints something) it only makes sense to
configure it as noreturn=false.
> std library: Resolve two TODOs

- lib/tokenize.cpp
- lib/tokenize.h
- test/testsymboldatabase.cpp
- test/testtokenize.cpp
This commit only addresses #8382. There are issues concerning which
versions of C++ should be supported and also generic C++ 14 attribute
support which can be revisited later.
> Fix #8382 (Syntax error when scanning code with template and attribute)

- cfg/wxwidgets.cfg
- test/cfg/wxwidgets.cpp
wxDebugContext is only defined if wxUSE_DEBUG_CONTEXT is 1, so otherwise
just skip it for syntax checking because it will fail.
Change wxT to wxT_2 and add wxT_2 to the config to remove a warning
during syntax check and be more compatible with newer/older wxwidgets
versions.
> wxwidgets: Fix syntax checking errors and warning

- cfg/std.cfg
Currently Cppcheck seems to be not really aware of the offsetof function like macro.
This PR adds a configuration so Cppcheck knows a bit more about it.
> std.cfg: Add offsetof configuration

- addons/misra.py
Added additional elif confition to cause error checks to ignore .dump files.
Previous change meant that .dump always falls into else statement and script exits.
> Modified misra.py to fix issue parsing arguements

- gui/projectfiledialog.cpp
The checked state of the addon checkboxes is already set in the
updateAddonCheckBox function directly above the removed code. I do not
see any reason to set it again and only for three of the four
checkboxes.
> GUI: Remove redundant code

- gui/mainwindow.cpp
When using an absolute path for import project, prepending the current
directory results in an invalid path and the analysis (silently, no
error shown in the GUI) fails.
> GUI: Avoid path concatenation when path is absolute

- lib/checkunusedfunctions.cpp
- test/testunusedfunctions.cpp
This is a reworked version of the original pull request: https://github.com/danmar/cppcheck/pull/958
Somehow I am not allowed, to reopen the original pull request.
Sorry for the huge delay, but was a bit out of time.
I hope that this time it fits to the needs
> Taking care of operation overloading functions

- cfg/qt.cfg
The type qintptr was missing.
qlonglong, qulonglong and uchar have known sizes, so the sizes can be
specified.
> Qt library: Add missing podtype information

- cfg/windows.cfg
- test/cfg/windows.cpp
Enhance *Equal/*Compare/*Copy/*Move/*Zero/*Fill memory functions to
catch buffer access out of bounds errors and ignored return values.
Replaced some function configuration by according defines as it is done
in windows to avoid redundant (and error prone) configurations.
> Windows library: Enhance functions, add tests

- lib/checksizeof.cpp
- lib/checksizeof.h
- test/testsizeof.cpp
A common mistake that I have found in our codebase is calling a function to get an integer or enum that represents the type such as:
```cpp
int numBytes = numElements * sizeof(x.GetType());
```
This extends cppcheck for sizeof calculation to check for function calls as well.
> Check for functions calls in sizeof calculations

- gui/projectfiledialog.ui
Qt warns about two QVBoxLayout objects with the same name and
automatically renames one.
This fixes the warning.
> GUI: Minor fix: Rename one of the two layout items with the same name

- gui/projectfiledialog.cpp
Platform::loadPlatformFile needs the path to the binary not only the
path to the directory where the binary is in. Otherwise the last
directory could get stripped away and the platform files maybe will not
be found.
> GUI: Fix loading of platform files in project file dialog

- platforms/arm32-wchar_t2.xml
- platforms/arm32-wchar_t4.xml
- platforms/arm64-wchar_t2.xml
- platforms/arm64-wchar_t4.xml
The default is "unsigned" so i have choosen it for the platformfiles.
This can be changed via a compiler option, but i am not sure if it makes
sense to add all the platform files with "signed" also.
Since the size of wchar_t depends on the compiler i added both possible
variants respectively.
Sizes of data types can be checked here for example:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch08s02.html
> Platforms: Add arm32 and arm64 platform files

- cfg/std.cfg
Add missing returnValue types where appropriate and fixed a few wrong
ones.
Add some missing function names (mostly where the "std::" version of the
function is missing).
Add documentation for some functions where it is missing.
Remove functions that do not exist in the standard: std::array::clear,
std::vector::push_front.
> std.cfg: Smaller enhancements and fixes

- cfg/qt.cfg
There is no problem with a null pointer as third argument. 0 is used as
wildcard and stands for all receivers for example.
> qt.cfg: Fix false positives for function disconnect

- lib/foreach.h
- test/testforeach.cpp
This provides a fallback for older compilers that don't support the for-range loop. I wasn't able to test this with gcc 4.4 as it doesn't build with cppcheck, but it should work as it does support both `auto` and rvalue references.
> Add foreach emulation for older compilers

- lib/astutils.cpp
- test/testcondition.cpp
This fixes the false positive for things like:
```cpp
void f1(const std::string &x, const std::string &y) { if(y.empty()) if(x.size() > 42) {}}
```
> Fix false positive for opposite conditions when using different containers

- lib/checkmemoryleak.cpp
- test/testmemleak.cpp
This will get rid of the false positives when doing `Handle{fopen(...)}`.
> Fix false positive of allocation function not being stored when constructing with curly brace

- addons/misra.py
I have no copy of the misra pdf but according to
https://sourceforge.net/p/cppcheck/discussion/general/thread/ccbe9e89/#a6ab
and the number of lines/rules printed by misra.py -generate-table i
guess 143 is really the correct number of rules.
> misra.py: Typo in number of rules (comment)

- cfg/windows.cfg
- lib/tokenize.cpp
- test/testtokenize.cpp
Remove TEXT() macro from windows.cfg and handle it internally where it
can be correctly simplified (Ansi vs. Unicode).
Also add handling of _TEXT() macro which is just a synonym for _T().
Add tests to verify correct function and macro simplification.
> windows string macros: Handle _T, _TEXT and TEXT internally, add tests

- gui/mainwindow.cpp
- gui/mainwindow.h
- gui/mainwindow.ui
They both are only enabled when a project is loaded and when started
they reanalyze the project one time with the according settings.
> GUI: Add "Check library" and "Check configuration" menu entries

- lib/suppressions.h
Get rid of those
```
In file included from lib/analyzerinfo.cpp:19:
In file included from lib/analyzerinfo.h:25:
In file included from lib/errorlogger.h:25:
lib/suppressions.h:75:9: warning: control may reach end of non-void function [-Wreturn-type]
};
^
1 warning generated.
```
> Fix warning emitted by clang.

- lib/checkleakautovar.cpp
- lib/checkleakautovar.h
- lib/library.cpp
- lib/token.h
- test/testleakautovar.cpp
This catches double frees with smart pointers:
```cpp
#include <iostream>
#include <memory>
int main()
{
int *i = new int;
// smart pointer gets ownership
std::unique_ptr<int> x(i);
// this delete leads to a double free!!
delete i;
}
```
> Check for double frees when using smart pointers

- gui/codeeditor.cpp
When starting the application Qt prints this message:
QObject::connect: No such slot CodeEditor::highlightCurrentLine() in
..\gui\codeeditor.cpp:141
And this function really does not exist, i guess it is some relict. If
it is planned to implement it this PR can just be closed.
> GUI: Remove connect call with nonexistent slot function

- gui/mainwindow.cpp
Since the slots (functions) are not existent in the class MainWindow and
Qt complains that it can not connect the slots i guess it has been
forgotten to change the receiver.
The ResultsView class (from which mUI.mResults is an instance) contains
these slots, so i guess they should be connected here.
> GUI: Fix wrong receivers in connect calls

- lib/tokenize.cpp
In 9cea2d6df, simplifications were removed for a number of functions
which should instead be handled with configurations. The commit did
however not update the description of the function, do this now.
Also sin() and sinh() and their float and long double versions were
missing from the comment so add these as well.
> Fix comment in Tokenizer::simplifyMathFunctions

- rules/suggest_nullptr.xml
Correct a wording in the summary for this rule.
> Adjust summary for the rule “modernizeUseNullPtr”

- lib/checkother.cpp
- lib/checkother.h
- test/testother.cpp
This will report when opposite expressions are used in operators, such as:
```cpp
void f(bool a) { if(a != !a) {} }
```
> Report opposite expressions

- lib/tokenlist.cpp
- test/testtokenize.cpp
This patch fixes AST construction for expressions involving the ternary operator and C++11 initializations.
> Ticket #8436: Handle C++11 initializations within ternary operator.

- cfg/std.cfg
- test/cfg/std.c
minsize with argvalue for arg 2 which is a char pointer makes no sense.
Changing it to minsize with strlen for arg 2 results in false positives
(and i think false negatives too).
In std.c a test with a valid vsprintf usage is added that would result
in a FP when minsize with strlen for arg 2 would be used.
> std.cfg: Fix minsize configuration for vsprintf

- cfg/std.cfg
Move std::... functions with bool instead of int return type to their
own function configurations.
Add not-bool for the arguments that must not be bool.
> std.cfg: Add some missing C++11 declarations and not-bool attributes

- lib/preprocessor.cpp
This caused a problem where a dump from a file whose path contained an ampersand was not valid xml.
> Escaped filename, which can contain invalid xml

- lib/tokenize.cpp
- test/testtokenize.cpp
This patch fixes a false positive in Tokenizer::findGarbageCode, that did not properly detect the end of switch statements (see examples in http://en.cppreference.com/w/cpp/language/switch for legitimate cases, including the one in the test case)
> Ticket #8281 and #8417: Properly detect the end of "switch" statements to accept all legitimate uses of "case".

- lib/checkcondition.cpp
- test/testcondition.cpp
This checks if the pointer gets modified with `++` or `--`. Ideally, it might be better to reuse `isVariableModified` for this instead.
> Fix false positive with inner conditions when using pointers

- test/cfg/std.c
Make the names of uninitvar_* functions consistent and fix typos.
Remove completely redundant functions/tests. Combine according tests if
they are not completely redundant.
> test/cfg/std.c: Cleaning up function names and redundant tests

- lib/checkunusedfunctions.cpp
On Windows searching for the last colon finds the colon which is part of
the path of the source file (e.g. "C:/projects/a.cpp"). Thus the path is
saved incompletely. This fix searches for the second instead of the last
colon and uses the data after the second colon as the path of the source
file.
> checkunusedfunctions.cpp: Fix files.txt parsing

- lib/astutils.cpp
- lib/astutils.h
- lib/checkother.cpp
- test/testother.cpp
This will not check for operators that are not associative such as `-` or `/`. It also will check for expressions like `if (a < -a)`.
> Improve checking of opposite expressions

- lib/astutils.cpp
- test/testother.cpp
This fixes issue 8537:
```cpp
bool f(int i){ return !((i - 1) & i); }
```
> Fix FP when using `-` as a binary operator

- lib/checkleakautovar.cpp
- test/testleakautovar.cpp
This fixes issue 8504:
```cpp
#include <memory>
class Bar {};
Bar* foo() {
Bar* result = new Bar;
std::auto_ptr<Bar> resultPtr(result);
resultPtr.release();
return result;
}
int main() {
Bar* ptr=foo();
delete ptr;
return 0;
}
```
> Check for smart pointer release

- lib/valueflow.cpp
- test/testbufferoverrun.cpp
- test/testvalueflow.cpp
This fixes the false positive for cases like this:
```cpp
int f(int i) {
int p[2] = {0, 0};
if(i >= 2)
return 0;
else if(i == 0)
return 0;
return p[i - 1];
}
void g(int i) {
if( i == 0 )
return f(i);
}
```
> Fix false positive with negative array index in issue 8536

- lib/tokenize.cpp
- lib/tokenize.h
- test/testsimplifytokens.cpp
These are implemented as tokenizer simplifications so changes are not
needed to the tokenizer and symbol database.
> Add support for namespace aliases and C++17 nested namespaces.

- lib/astutils.cpp
- test/testother.cpp
This fixes issue 8549:
```cpp
bool test_one_bit_set(unsigned x)
{
return (x > 0) && (x & (x-1)) == 0;
}
```
> Fix false positive with oppositeExpression when using binary op

- lib/checknullpointer.cpp
- test/testnullpointer.cpp
This should fix issue 8559:
```cpp
class foo
{
};
const char* get() const { return 0; }
void CreateOverlay()
{
foo xFoo;
if (get())
{
xFoo += get();
}
}
```
> Fix false positive when using null arithmetic with class type

- lib/checkother.cpp
- lib/symboldatabase.cpp
- lib/symboldatabase.h
- lib/tokenize.cpp
- test/testpostfixoperator.cpp
- test/testsimplifytypedef.cpp
- test/testsymboldatabase.cpp
- test/testtokenize.cpp
I fixed all the checks that had tests that use volatile.  There will
probably be more changes needed due to lack of test coverage for
volatile in some checks.
> Don't remove the volatile keyword so we can properly overload functions.

- lib/tokenize.cpp
- test/testsimplifytokens.cpp
DACA2 results showed new SymbolDatabase syntax errors when duplicate
namespace aliases were simplified improperly. The solution is to remove
them in the tokenizer when found.
> Remove duplicate namespace aliases so they don't produce syntax errors.

- addons/misra.py
- addons/test/misra-test.c
According to rule 8.12, the value of an implicitly-specified enumeration constant shall be unique.
If an enumeration constant is explicitly specified, it need not be unique.
> Modified rule 8.12

- cfg/windows.cfg
Fix declaration comments for _localtime32_s() and _localtime64_s().
Add functions _time32 and _time64, and types __time32_t and __time64_t.
References: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/time-time32-time64
> windows.cfg: Add 32/64 bit time related functions and types.

- addons/misra.py
MISRA rule 20.14 is not limited to #if pragmas and also extends to
positives whenever #ifdef/#ifndef is used.
> Fix false positive in misra.py rule 20.14

- addons/misra.py
Use python's __file__ variable to figure out where the checker script is
located.
This allows a customized per project scripts to be used instead of the
one provided in the cppcheck release.
> Allow per project misra.py addon

- addons/misra.py
- Show a summary of the of the number of violations.  This can be
disabled with the --no-summary option.
- Return an error code if -verify flag not used and violation exists.
> Show summary of violations

- addons/misra.py
Output will still be given for style violations.
This allows the build process output to be smaller and cleaner,
making it easier to spot and address problems.
> Add --quiet flag to misra.py for cleaner output

- cfg/windows.cfg
- test/cfg/windows.cpp
Somehow the opposite inner condition is not detected when macros are used. I created this ticket: https://trac.cppcheck.net/ticket/8596
> windows.cfg: Add macros SUCCEEDED() and FAILED().

- lib/checkio.cpp
- lib/checkmemoryleak.cpp
- lib/token.cpp
- lib/token.h
- lib/tokenize.cpp
- lib/tokenlist.cpp
- lib/tokenlist.h
- test/testbufferoverrun.cpp
- test/testsimplifytokens.cpp
- test/testtoken.cpp
The crash occurred when a constant variable usage immediately followed a constant variable assignment.  When this happened the assignment statement was was deleted using deleteThis(), which invalidated the pointer to the usage.  This fix avoids using deleteThis() where possible, thus avoiding invalidating any pointers.
> Fix crash bug #8579

- tools/git-pre-commit-cppcheck
do not need -d'^i'(TAB) argument for cut command, it's easy to input wrong invisible char when user copping the script.
cut' default delimiter  is TAB, so this argument is needless
> small change

- CMakeLists.txt
- cmake/findDependencies.cmake
- gui/CMakeLists.txt
The qt5_use_modules syntax has been obsoleted and no longer works in up-to-date CMake (Fedora rawhide). This PR makes the program build again using standard CMake syntax.
> Use modern CMake syntax.

- gui/CMakeLists.txt
#1273 erroneously tried to link to Qt5LinguistTools, which isn't a library. This is fixed in the current PR; sorry for not realizing this before #1273 was merged. I guess Travis isn't checking CMake builds, since the earlier job went through? :stuck_out_tongue:
> One more Qt5 CMake fix

- addons/misra.py
- addons/test/misra-test.c
I have tried implementing rule 14.1 for while loop also.
> Modified rule 14.1

- cfg/qt.cfg
For qInstallMsgHandler there is an alternative function qInstallMessageHandler. Both are added.
For qsrand and qrand there is only a hint that the class QRandomGenerator should be used instead.
Reference: https://doc.qt.io/qt-5/qtglobal-obsolete.html
> qt.cfg: Add obsolete functions with warning and one alternative one.

- addons/misra.py
WARNING: breaking change - now default misra.py report style will be the
same as cppcheck itself, but previosly misra.py default template was a
little different
> misra.py: template used for error reporting will now be configurable

- lib/astutils.cpp
- lib/checkother.cpp
- test/testother.cpp
This should fix issue 8613:
```cpp
class PortWindow
{
public:
~PortWindow();
uint16_t newPort();
};
class CommandHandler
{
public:
void f();
PortWindow& port_window_;
};
void CommandHandler::f()
{
uint16_t port1 = port_window_.newPort();
uint16_t port2 = port_window_.newPort();
if(!port1 || !port2) {
}
}
```
> Fix Fix FP when using non-const members and also check return type of function for uniqueness

- lib/checkother.cpp
- test/testother.cpp
This fixes the FP by not warning for duplicate assignment if both variables are assigned to each other later on:
```cpp
struct P
{
void func();
bool operator==(const P&) const;
};
struct X
{
P first;
P second;
};
bool bar();
void baz(const P&);
void foo(const X& x)
{
P current = x.first;
P previous = x.first;
while (true)
{
baz(current);
if (bar() && previous == current)
{
current.func();
}
previous = current;
}
}
```
> Fix false positive from issue 8612

- .travis.yml
- test/cfg/runtests.sh
.travis.yml is enhanced so xmlstarlet is installed which is used to extract the defines in the configuration files.
> cfg/runtests.sh: Check syntax of defines in configuration files.

- lib/checkcondition.cpp
- test/testcondition.cpp
This fixes false positives when the user is doing `if(true) {}` or `if(!true) {}`.
> Skip literals for always true/false

- lib/astutils.cpp
- test/testcondition.cpp
- test/testother.cpp
This fixes false negative in:
```cpp
void f(bool a, bool b)
{
if(a && b){}
else if( !!b && !!a){}
}
```
> Fix issue 7904: Handle double nots in isSameExpression

- cfg/cppcheck-cfg.rng
- cfg/std.cfg
- lib/checkfunctions.cpp
- lib/library.cpp
- lib/library.h
- lib/token.cpp
- man/manual.docbook
- test/testfunctions.cpp
- test/testlibrary.cpp
This PR fixes issue 8651 (it does not add any checks to the cfg though, but I tested the example given in the issue with acos and it seemed to work fine).
The first two commits is just some refactoring of tests and addition of more tests. The third commit adds handling of <valid></valid> (i.e., no value added). Previously cppcheck would crash, instead bail out with an error message.
The fourth commit actually fixes the issue. The argument value is passed as a double instead of an int. This solves the mentioned issue. Also increase the precision when printing the error message (I chose some arbitrary number). I'm not sure this is needed, but when I tested the example in issue 8651, it didn't print the decimals so I increased precision). Unfortunately, this commit introduces a compiler …
> Support floats in valid config

- .travis.yml
naming.py is called parallel (4 times at a time) for all *.cpp.dump files directly in gui/ and lib/.
@matthiaskrgr had the idea for it: https://github.com/danmar/cppcheck/commit/e46c499f5a6c552672ce246e0be8f14c9febcc51#commitcomment-29717495
>  Travis: Parallelize naming.py calls.

- addons/misra.py
Misra.py addon to support multiple positional arguments for dump files from cppcheck. This capability existed prior to using argparse and is reintroduced in this commit.
> MISRA addon: Support multiple files with argparse

- lib/checkstl.cpp
- lib/checkstl.h
- test/teststl.cpp
This will diagnosis the cases:
```cpp
void foo(const std::vector<std::string>& vec, std::vector<std::string>::iterator it) {
std::for_each(it, it, &bar); // useless - nothing will be done
std::for_each(failed.begin(), failed.begin(), &bar); // useless - nothing will be done
std::for_each(failed.end(), failed.end(), &bar); // useless - nothing will be done
}
```
Passing the same iterator to an algorithm is really a no-op.
> Fix issue 4693: Diagnostic when using the same iterators to an algorithm

- lib/checkother.cpp
- test/testother.cpp
This fixes FPs from variable substitution:
```cpp
int f(int) __attribute__((pure));
int g(int) __attribute__((pure));
void test() {
const int x = 0;
int i = f(0);
int j = f(x);
}
```
> Fix FP with duplicate assign

- addons/misra.py
The misra.py extension would exit after first file processed. This fix causes all files to be processed then exits with a non-zero error code if any of the files produced an error.
> Misra.py fix multiple file processing

- lib/valueflow.cpp
- test/testcondition.cpp
- test/testvalueflow.cpp
This fixes issue with:
```cpp
void f(int i)
{
bool warn = false;
if (i == 0)
{
warn = true;
}
else if (!warn && i == 1) // << the value of'warn' is always true
{
// warn = true;
}
if (warn)
{}
}
```
> Fix issue 8369: False negative: Condition 'condition' is always true

- lib/astutils.cpp
- test/testother.cpp
Fix false positive with issue [8687](https://trac.cppcheck.net/ticket/8687):
```cpp
int main()
{
for(int i = 0; i < 10;)
{
if( i != 0 )
i++;
i++;
}
return 0;
}
```
> Fix issue 8687: false positive with same expression

- lib/tokenize.cpp
- test/testsimplifytypedef.cpp
Some old systems/libraries are still use syntax "typedef 'typename' unsigned 'typename' (functon_name)()", and it can't change as our self. And it wrong when use cppcheck.
ex: typedef long unsigned int (callback_fn)(void*)
In fact, the compile as gcc is good in compile and runtime with this syntax, and passing all testcase are avaiable, so i think it can should share. Plz help review it
> Allow syntax "typedef 'typename' unsigned 'typename' (functon_name)()"

- lib/cppcheck.cpp
- test/testsuppressions.cpp
if simplecpp fails to read a file and returns a syntaxError every suppression is skipped, although you have a test case for this. I don't know if it's your desired behaviour but this PR would change it.
> cppcheck.cpp: fix suppression of syntaxError

- lib/astutils.cpp
For:
```cpp
void f() {
int x = 0;
int y = 0;
if(x == 0) {
if (y == 0) {}
}
}
```
It now shows:
```
issue-8670.cpp:5:15: warning: Identical inner 'if' condition is always true. [identicalInnerCondition]
if (y == 0) {}
^
issue-8670.cpp:2:13: note: 'x' is assigned value '0' here.
int x = 0;
^
issue-8670.cpp:3:13: note: 'y' is assigned value '0' here.
int y = 0;
^
issue-8670.cpp:4:10: note: outer condition: x==0
if(x == 0) {
^
issue-8670.cpp:5:15: note: identical inner condition: y==0
if (y == 0) {}
^
```
> Avoid duplicates in the error path

- lib/checkstl.cpp
- test/teststl.cpp
This will check for mismatching iterators in expression like:
```cpp
void foo() {
if(f().begin() == g().end()) {}
}
```
And also when used for distance like:
```cpp
void foo() {
auto size = f().begin() - g().end();
}
```
> Diagnose mismatching iterators used together in operators

- cli/cmdlineparser.cpp
- lib/errorlogger.cpp
The CWE info is currently only available in the XML output.  This one-line patch makes it available via the `--template` interface, too.
> ErrorLogger: add {cwe}

- lib/tokenize.cpp
- test/testbufferoverrun.cpp
- test/testtokenize.cpp
This patch fixes a crash upon valid, when the __thread extension is used (https://en.wikipedia.org/wiki/Thread-local_storage#C_and_C++), or C++11's thread_local.
I don't handle both the same, because one is a compiler extension, while the other is linked to the C++ version being used.
> Ticket #8679: Add support for C++11 thread_local and GCC's (among others) __thread extension.

- lib/astutils.cpp
- test/testcondition.cpp
- test/testvalueflow.cpp
This should help fix issue 8696, but it requires a definition of the class:
```cpp
struct Date {
void advance();
};
void foo(Date date) {
Date today = date;
Date upcoming = date;
upcoming.advance();
if (date > today && date < upcoming)
return;
}
```
It doesn't assume that unknown member functions modify the variable as this seems to break several tests in valueflow.
> Check if member function modifies the variable

- lib/astutils.cpp
- test/testother.cpp
This fixes the crashes for issue 8712 and 8713. It also fixes the FP in 8717 as well.
> Fix crashes in followVarExpression

- lib/checkcondition.cpp
This will now produce a single error message:
```cpp
void f()
{
int x = 3;
if (x == 3) {}
}
```
With this output:
```
$ ./bin/cppcheck --enable=all 8698.cpp
Checking 8698.cpp ...
[8698.cpp:3] -> [8698.cpp:4]: (style) The expression 'x == 3' is always true because 'x' and '3' represent the same value.
```
> Fix issue 8698: Check for same expression in condition check to avoid duplicate messages

- lib/astutils.cpp
- test/testother.cpp
Fix issue for:
```cpp
volatile const int var = 42;
void f(void){ if(var == 42){} }
```
> Fix 8682: Dont follow volatile variables

- lib/astutils.cpp
- test/testother.cpp
This will fix the crash with:
```
a b;
void c() {
switch (d) { case b:; }
double e(b);
if(e <= 0) {}
}
```
> Fix issue 8709: crash with switch statement with followVar

- lib/tokenize.cpp
- test/testtokenize.cpp
This patch fixes Tokenizer::createLinks2, that would not support variadic template bases.
> Ticket #8654: Properly setup links for variadic template bases.

- lib/astutils.cpp
- test/testother.cpp
Fix FP:
```cpp
void A::f(bool a, bool c)
{
const bool b = a;
if(c) { a = false; } 
if(b && !a) { }
}
```
> Fix issue 8730: False positive: Opposite expression on both sides of &&

- lib/checkcondition.cpp
- test/testcondition.cpp
- test/testother.cpp
This:
```cpp
void f() {
int val = 0;
if (val < 0) continue;
if (val > 0) {}
}
```
will only report one message:
```
$ ./bin/cppcheck --enable=all 8722.cpp
Checking 8722.cpp ...
[8722.cpp:2] -> [8722.cpp:3]: (style) The expression 'val < 0' is always false.
[8722.cpp:2] -> [8722.cpp:4]: (style) The expression 'val > 0' is always false.
```
> Fix issue 8722: Avoid duplicate messages due for followVar

- lib/checkstl.cpp
- test/teststl.cpp
This fixes FP with:
```cpp
void f()
{
if ( mellA.begin()->id3l()==mellB.begin()->id3l()) {}
}
```
> Fix issue 8736: Iterators to containers from different expressions (a.begin().x == b.begin().x)

- tools/donate-cpu.py
When os.remove() tries to remove a file that does not exist a FileNotFoundError is issued and the script just crashes.
> donate-cpu.py: Fix crash when wget destination file does not exist.

- lib/astutils.cpp
- test/testcondition.cpp
This fixes the FP with:
```cpp
void f()
{
uint32_t value;
get_value(&value);
int opt_function_capable = (value >> 28) & 1;
if (opt_function_capable) {
value = 0;
get_value (&value);
if ((value >> 28) & 1) {}
}
}
```
> Fix issue 8737: FP with identical inner condition due to followVar

- lib/astutils.cpp
- test/testother.cpp
This fixes the FP in:
```cpp
void f()
{
const bool was_seed = isSeed ();
// ...
if (!was_seed && isSeed()) {}
}
```
> Fix issue 8741: Require pure when following variables in isSameExpression

- lib/checkstl.cpp
- test/teststl.cpp
This fixes the issue here:
```cpp
void f()
{
std::list<int*> a;
std::list<int*> b;
if (*a.begin() == *b.begin()) {}
}
```
> Fix issue 8743: FP when derefencing iterators

- lib/astutils.cpp
- test/testgarbage.cpp
This should fixes all crashes with `isVariableChanged` inside of `followVar`.
> More robust checking for crashes in followVar

- tools/donate-cpu.py
Use python tarfile instead of tar to extract the packages.
Only extract source files of interest.
Skip dangerous files that could overwrite files outside the temp folder.
Fixes https://trac.cppcheck.net/ticket/8716
Tested with Python 2 and 3 under Cygwin/Windows 7 and Ubuntu/Linux.
> Donate CPU: Only extract relevant source files from archives #8716

- lib/cppcheck.h
- lib/errorlogger.cpp
- lib/suppressions.cpp
- lib/suppressions.h
- test/testerrorlogger.cpp
- test/testsuppressions.cpp
added the ability to use suppress on line 0, since cppcheck can yield syntax error on line 0.
> --suppress on line 0

- .travis_suppressions
- lib/checkother.cpp
- lib/checkstl.cpp
- lib/checkstl.h
- test/teststl.cpp
So this suggest std algorithms for loops where it is possible. In Sean Parent's [Better Code](http://sean-parent.stlab.cc/presentations/2013-09-11-cpp-seasoning/cpp-seasoning.pdf) talk he mentions the problems with raw loops:
* Difficult to reason about and difficult to prove post conditions
* Error prone and likely to fail under non-obvious conditions
* Introduce non-obvious performance problems
* Complicates reasoning about the surrounding code
There are a lot messages in cppcheck itself recommending an algorithm. However, this can require using a lambda. We dont really use lambdas in cppcheck currently. We could consider adding these to the suppression list. Or maybe we could have a configuration from the user that they want to use lambdas, and then only recommend algorithms when the …
> Initial check for recommending algorithms

- lib/checkstl.cpp
- test/teststl.cpp
This fixes a bug where the source location wasn't shown when suggesting std::transform or std::copy with container inserts.
> Show line number when suggesting std::transform or std::copy

- lib/checkuninitvar.cpp
- test/testuninitvar.cpp
We should not report this warning for static members.
> Ticket #8734: Skip static member variables in CheckUninitVar.

- lib/tokenize.cpp
- test/testsimplifytemplate.cpp
- test/testtokenize.cpp
We generate incorrect AST for expressions like  ```a ? b < c : d > e```
because compileTerm ends up called on b, and it wrongly thinks ```b < c : d >``` is a template. Since the middle expression is parsed as if parenthesized according to the standard, the easiest is to patch prepareTernaryOpForAST, rather than going finding why < ends up linked to >. This is what this patch does.
> Ticket #8632: Parenthesize ternary operator operands containing < to avoid wrongly thinking a template instantiation is met.

- lib/astutils.cpp
- test/testother.cpp
This fixes the FP with:
```cpp
void f()
{
int avrule_cnt = 0;
struct cil_args_verify extra_args;
extra_args.avrule_cnt = &avrule_cnt;
rc = cil_tree_walk(db->ast->root, &extra_args);
if (avrule_cnt == 0) {}
}
```
> Fix issue 8775: Dont follow aliased variables

- test/testsuppressions.cpp
testsuppressions.cpp(450): warning C4458: declaration of 'errmsg' hides class member.
> Fixed compiler warning from VS2017

- tools/times.c
newer versions of git use a variable lenght proportional to the
repository size (9 for cppcheck)
remove old chomp helper function and make copying the revision
smarter to hopefully cover for edge case that needed it
> tools: allow short SHA1 longer than 7

- lib/astutils.cpp
- lib/checkcondition.cpp
- lib/checkcondition.h
- test/testcondition.cpp
It also adds an error path to the message to see what substitutions were done.
> Reenable followVar for logical conjunction

- cfg/qt.cfg
By default "qreal" is a typedef for "double".
Reference: https://doc.qt.io/qt-5/qtglobal.html#qreal-typedef
> qt.cfg: Define "qreal" as "double"

- lib/tokenize.cpp
- lib/tokenlist.cpp
- test/testgarbage.cpp
It seems checking for both operands in assignment exposes some bugs in our AST. I am not familiar with the AST code, so instead I just added some exceptions to avoid producing errors for the issues in [8749](https://trac.cppcheck.net/ticket/8749) and [8786](https://trac.cppcheck.net/ticket/8786). This should at least reduce the regressions for the soon-to-happen release.
> Skip some ast errors to avoid regressions

- lib/checkfunctions.cpp
- lib/checkfunctions.h
- man/manual.docbook
- test/cfg/std.c
- test/testfunctions.cpp
Add a check that address of a single character is not passed as argument
to argument marked as strings (using strz). The check does not warn if
the address of a character with known value '\0'.
Currently, the check warns for the following:
```
size_t f(char x) {
return strlen(&x);
}
```
which IMO is reasonable since the only valid value to pass to f is '\0'.
It does not warn for global variables, since I wasn't able to avoid FP for the following case:
```
const char x = '\0';
size_t f() {
return strlen(&x);
}
```
(I suppose it has to do with issue 7597).
It also doesn't warn for the following case:
```
struct S {
char x;
}
size_t f() {
S s;
s.x = 'x';
return strlen(&s.x);
}
```
since I wasn't able to figure out how to get the value of s.x.
> #4241: Check for address of single character passed as string

- lib/checkfunctions.cpp
- test/testfunctions.cpp
If the address is taken inside an array, the address is not of a single
character, so do not warn about this.
Originally found in real world code.
> Fix FN: Invalid string argument with pointer to pointer

- tools/donate-cpu.py
Avoids git printing a warning about redirecting to https every time
the clone command is issued. The warning was:
warning: redirecting to https://github.com/danmar/cppcheck.git/
> donate_cpu: use https url

- gui/resultsview.cpp
Dynamic memory allocation was used for a XmlReportV2 object in the function “ResultsView::readErrorsXml”.
Put this object on the stack instead so that this software can become a bit safer and more efficient.
> Put XmlReportV2 object on the stack in ResultsView::readErrorsXml()

- addons/misra.py
Functions with variadic arguments trip an exception in the MISRA checker
because some of the token is None and does not have some of the members
the code is expecting.
Prevent this by checking to see if the token is None and skipping the
code that tries to use that value.
> MISRA: Prevent exception on variadic functions

- lib/astutils.cpp
- lib/astutils.h
- lib/checkcondition.cpp
- test/testcondition.cpp
Right now, we just check in `if` and `while` statements, but this will check in `return` as well. It can catch issues such as:
```cpp
bool f(bool a) {
if(a) return a;
return false;
}
```
> Check conditions in return statements

- lib/checkbufferoverrun.cpp
- test/testbufferoverrun.cpp
Test case
```C++
#include <iostream>
#include <cstring>
int main(int argc, char *argv[])
{
if(argc>1)
{
char buf[3];
char *p = strdup(argv[1]);
strcpy(buf,p);
free(p);
}
return 0;
}
```
Executing the example with `argv[1] `longer than `buf` leads to a crash
```bash
$ g++ insecureCmdLineArgs.cpp && ./a.out abce
Checking insecureCmdLineArgs.cpp ...
(information) Cppcheck cannot find all the include files (use --check-config for details)
*** stack smashing detected ***: <unknown> terminated
Aborted
```
Having this PR applied and check with Cppcheck gives 
```bash
[insecureCmdLineArgs.cpp:9]: (error) Buffer overrun possible for long command line arguments.
```
> insecureCmdLineArgs: Fixed FN in case strdup() copies argv[].

- man/manual.docbook
This pull request fixes typo in manual.docbook 
- change Newline term from <term>\t</term> to <term>\n</term>
> fix typp on manual.docbook Newline is \n instead of \t

- man/manual-ja.docbook
fix newline in translation of manual docbook also
see https://github.com/danmar/cppcheck/pull/1442
> fix newline from backslash t to backslash n in manual-ja.docbook

- lib/checkcondition.cpp
- test/testcondition.cpp
Fixes FP in:
```cpp
int f(void)
{
const int a = 50;
const int b = 52;   
return a+b;
}
```
> Fix FP issue 8801: Condition 'a+b' is always true

- gui/main.cpp
enables AA_UseHighDpiPixmaps for less pixeled icons on 4K displays.
> enable AA_UseHighDpiPixmaps

- lib/astutils.cpp
- lib/astutils.h
- lib/tokenlist.cpp
- test/testastutils.cpp
- test/testtokenize.cpp
As mentioned in #1451. It fixes the two TODO-test cases in #1451 (perhaps I should have added it to that PR directly?).
> findLambdaEndToken handle explicit type

- lib/checkbool.cpp
- lib/checkbool.h
- test/testbool.cpp
This was triggered by https://github.com/lxqt/lxqt-config/commit/d4861aab1de402db06a57af4aac09061eb0745df. I tried figuring out if there was anymore similar bugs in the project, but I was unable to make gcc, clang or cppcheck warn about returning a value other than 0 or 1 from a boolean function so I decided to try to write a check for it in cppcheck. If you think it's out of scope or not useful, I have no problems if you reject the PR but since I had written the code anyway, I figure I could submit it and see what you think.
Some other checks in `checkboolean.cpp` are only enabled for c++, I'm unsure if this should be c++-only too?
> Add check for return value of boolean function

- test/CMakeLists.txt
This adds a check target that will build and run the tests through the testrunner.
> Add a check target to cmake

- lib/valueflow.cpp
- test/testcondition.cpp
Fixes:
```cpp
void foo(double param) {
while(bar())
{
if (param<0.)
return;
}
if (param<0.)
return;
}
```
> Fix issue 8839: FP knownConditionTrueFalse - condition inside a while-clause

- lib/astutils.cpp
- lib/astutils.h
- lib/checkautovariables.cpp
- lib/checkautovariables.h
- lib/valueflow.cpp
- test/testautovariables.cpp
This extends the lifetime check to check for variables used after they have been destroyed. So it will diagnose the lambda:
```cpp
void foo(int a) {
std::function<void()> f;
if (a > 0) {
int b = a + 1;
f = [&]{ return b; };
}
f();
}
```
It will warn about the call to `f` as it references variable `b` which is not in scope.
> Diagnose invalid lifetimes

- lib/astutils.cpp
- lib/astutils.h
- lib/checkautovariables.cpp
- lib/checkautovariables.h
- lib/valueflow.cpp
- test/testautovariables.cpp
This removes the previous diagnostics in order to avoid double messages. This will also diagnose more issues such as for issue [1143](https://trac.cppcheck.net/ticket/1143):
```cpp
#include <stdlib.h>
#include <iostream>
int main() 
{
int* x;
if( 1 ) 
{
int y[6] = {0,1,2,3,4,5};
x = y;
}
// the memory of y is not valid here
std::cout << x[3] << std::endl; 
}
```
> Extend lifetime analysis to pointer usage

- test/testsuite.cpp
some STL implementations of set (like the ones in mojave) will complain otherwise (through a used defined warning) with : 
the specified comparator type does not provide a const call operator
> test: avoid a mutable comparator for test

- lib/valueflow.cpp
- test/testautovariables.cpp
This tracks the variable lifetime through some standard c++ function calls(such as `make_tuple`, `tie`, etc). 
Right now, it uses some hard coded names for the functions. In the future, we can look at extending the library configuration so more functions can be added by the user.
Hopefully, in the future, we can do cross function analysis as well, so we can track lifetimes across functions cppcheck can see the source code for.
> Track variable lifetime through function calls

- htmlreport/cppcheck-htmlreport
Treat the first location as the main location.
Highlight other locations in the same file in the annotated source.
> cppcheck-htmlreport: Handle errors with multiple locations

- lib/valueflow.cpp
- test/testautovariables.cpp
This fixes the FP in:
```cpp
struct A {
std::vector<int*> m;
void f() {
int x;
std::vector<int*> v;
v.push_back(&x);
m.insert(m.end(), v.begin(), v.end());
}
};
```
This also fixes the crash in issue 8874:
```cpp
class MapGridCtrl
{
int Filter( Predicate pred )
{
std::vector< wxString > maps;
m_maps_unused.insert( m_maps.begin(), m_maps.end() );
}
struct MapData {};
std::map< wxString, MapData > m_maps;
std::map< wxString, MapData > m_maps_unused;
};
```
> Fix FPs and crashes with byDerefCopy

- lib/valueflow.cpp
- test/testvalueflow.cpp
I have got the following SEGFAULT:
```
0   cppcheck                      	0x0000000103013ddc Token::varId() const + 12 (token.h:576)
1   cppcheck                      	0x0000000103674b58 valueFlowAfterMove(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) + 7752 (valueflow.cpp:2963)
2   cppcheck                      	0x0000000103668856 ValueFlow::setValues(TokenList*, SymbolDatabase*, ErrorLogger*, Settings const*) + 358 (valueflow.cpp:4634)
3   cppcheck                      	0x00000001035be2ba Tokenizer::simplifyTokenList2() + 1226 (tokenize.cpp:4062)
4   cppcheck                      	0x00000001032e0bc4 CppCheck::checkFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, …
```
> Add null pointer check to fix SEGFAULT

- tools/donate-cpu.py
This is a very simple/stupid fix that just inserts 5 spaces for every line except the first.
> donate-cpu.py: Align multi line output in diff (trac #8868)

- tools/donate-cpu.py
With Python3 f.read() directly returns a string object that has no
decode() function. As a workaround AttributeError exceptions during
calling the decode() function are ignored and the data read from the file
is left unchanged.
With Python2 calling the decode() function is necessary and still done.
> donate-cpu.py: Fix Python3 compatibility problem with f.read().decode()

- lib/checkother.cpp
- test/testother.cpp
This fixes the regression with:
```cpp
template <class F, class... Ts>
auto foo(F f, Ts... xs)
{
auto x = f(xs...);
return x;
}
```
> Fix issue 8884: Regression: False positive: Variable 'f' is reassigned a value before the old one has been used

- gui/cppcheck_ja.ts
- man/manual-ja.docbook
in cppcheck_ja.ts
- fix some typo/wrong japanese translation
- standardization of terminology
in manual.docbook
- update version number to 1.87 dev
> fix japanese translation typo and manual version

- tools/donate-cpu-server.py
This should fix the issue that the number after the "+" in the "Diff" column is always one too large.
> donate-cpu-server.py: Fix wrong number of "+" diffs in latest results.

- lib/astutils.cpp
- lib/checkmemoryleak.cpp
- lib/checknullpointer.h
- lib/checkuninitvar.h
- lib/token.h
- lib/valueflow.cpp
Fixes some warnings with Clang and GCC. The most important one is the change in valueflow.cpp where an argument was missing.
> Fix warnings

- lib/templatesimplifier.cpp
- lib/templatesimplifier.h
* use already cached name token rather than recalculating it
multiple times
* cache end of template parameters token and use it rather than
recalculating it multiple times
* remove unnecessary end of template token and name token checks
* remove function parameter that is already contained in another
parameter
> template simplifier: refactor to use cached information

- lib/valueflow.cpp
- test/testvalueflow.cpp
When comparing if the shift is large enough to make the result zero, use
an unsigned long long to make sure the result fits. Also, a check that
avoids setting the value if the shift is equal to or larger than the
number of bits in the operand (this is undefined behaviour). Finally,
add a check to make sure the calculated value is not too large to store.
Add test cases to cover this.
This was detected by an MSVC warning.
valueflow.cpp(1350): warning C4334: '<<' : result of 32-bit shift implicitly
converted to 64 bits (was 64-bit shift intended?)
> Valueflow: Fix right shift with more than 31 bits

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
Fix scope info bug on derived template class which caused a use after
free crash when deleting a template forward declaration in a different
scope.
> template simplifier: fix crash on daca c++-annotations project

- tools/donate-cpu.py
Similar to the '--test' option for the donate-cpu-server.py script that lets the server listen locally on port 8001 the client now can also work against such a server by using the same option '--test'.
> donate-cpu.py: Add '--test' parameter for testing against local server.

- tools/donate-cpu-server.py
Instead of searching for a specific year (which could change) the script searches now for the current and last year to find the date and time information in the results.
> donate-cpu-server.py: Fix date/time in report is not found.

- test/cfg/qt.cpp
- test/cfg/runtests.sh
To be able to use real Qt-Code in "test/cfg/qt.cpp" and still do a
syntax check the Qt settings are read out via pkg-config now if it is
available. This way the test now can contain Qt macros and functions and
the syntax check can still be used.
Additionally the same options as for the other tests are used now for
the Qt config tests.
Installing the package "qtbase5-dev" should be enough to enable the
syntax checks (already installed for travis tests).
> qt config test: Use pkg-config to retrieve Qt settings.

- tools/donate-cpu-server.py
The package names contained the whole path, so the leading "resultPath" is now removed to only show the package names.
Tested on local server.
> donate-cpu-server.py: Fix package names in time output.

- lib/checkstl.h
due to equal arguments...
* iterators1 (`CheckStl::iteratorsError(const Token*, const std::string&, const std::string&)`) and
* iterators2 (`CheckStl::iteratorsError(const Token*, const Token*, const std::string&, const std::string&)`)
... produced equal messages. Equal messages were filtered-out `CppCheck::reportErr(const ErrorLogger::ErrorMessage&)`.
So the error iterators2 disapeared from the error list.
> CheckStl: add missing error ID iterators2

- tools/donate-cpu.py
Nearly all wxWidgets tools use `#include <wx/...` or `#include "wx/...`
This pull request aims to detect more wxWidgets code in `donate-cpu.py::scanPackage()` and reduce the number of `unknownMacros` warnings from daca2 on wxWidgets code.
> donate-cpu.py: Improved detection of wxWidgets code in scanPackage.

- tools/donate-cpu-server.py
Format the time output so the columns have the same width (as long as a text is not too long).
Add showing the factor of the time difference so very suspicious differences can be seen instantly.
Made the function body more PEP 8 conform by using lowercase variable names with underscores as delimiters.
> donate-cpu-server.py: Time report: Format output, add showing factor

- lib/valueflow.cpp
- test/testcondition.cpp
This fixes issue with:
```cpp
struct S
{
bool operator<(const S&);
};
int main() {
S s;
bool c = s<s;
if (c)
return 0;
else
return 42;
}
```
> Fix issue 8932: False positive knownConditionTrueFalse - valueflow ignores operator <

- lib/checkautovariables.cpp
- test/testautovariables.cpp
This fixes the FP in:
```cpp
void f() {
struct a {
std::vector<int> v;
auto g() { return v.end(); }
};
}
```
> Fix issue 8883: False positive: returnDanglingLifetime with local struct or class

- test/testcondition.cpp
Ticket 8168 was fixed in 713f6071680d20666a0699bcba234edc17cb69a5.
Add a regression test to make sure the bug doesn't reappear.
> Add regression test for 8168

- man/manual.docbook
The XML tag is `<suppress>` and not `<suppression>`, see code https://github.com/danmar/cppcheck/blob/master/lib/suppressions.cpp#L100
The `suppress-xml` command line parameter is use in the code here: https://github.com/danmar/cppcheck/blob/master/cli/cmdlineparser.cpp#L235
> Correct documentation and give an example

- .travis.yml
- tools/triage/mainwindow.cpp
- tools/triage/mainwindow.h
- tools/triage/readme.txt
Changes:
- Fixed compiler warnings
- Add `*.*` to file open menu so files without suffix can be opened
- Make it work under Windows
- Make wget() and unpackArchive() methods so they can access the UI
- wget() and unpackArchive() use the new method runProcess() now that also does some error handling
- Errors are shown in the status bar for easier debugging / usage
- Create the work folder "~/triage" if it does not exist
- Add readme.txt
- Let travis build the triage tool
>  triage: Fix warnings and Windows issues; some enhancements

- test/cfg/runtests.sh
On linux systems (like travis) Qt often seems to be built with the option "reduce_relocations" which requires an application using it to specify the option "-fPIC".
> test/cfg/runtests.sh: Qt test: Fix syntax check when "-fPIC" is required

- lib/templatesimplifier.cpp
- lib/templatesimplifier.h
* out of line member functions are a namespace
* template<...> and *_cast<> can't be instantiations
* refactor code to use less function parameters
* fix instantiation scopes
* use full name with namespace when available
* fallback to just matching names when full name doesn't match
> template simplifier: improve namespace matching

- lib/library.cpp
In case the XML code of a library configuration is invalid Cppcheck now additionally prints out some helpful error description like this:
"Error=XML_ERROR_MISMATCHED_ELEMENT ErrorID=16 (0x10) Line number=304: XMLElement name=noreturn"
> library.cpp: Let tinyxml2 print a helpful error message when XML is bad

- cfg/gnu.cfg
Reference (beside some other web sites):
https://www.gnu.org/software/libc/manual/html_node/Translation-with-gettext.html
> gnu.cfg: Add support for gettext() and some related functions

- test/testcondition.cpp
Ticket #8780 was fixed in b839ad60dd4d9658444982d2d21c282d187c5ab6.
Note that after 4e147a4c596f6c84b2a5733532b40b344a51ebd0, there are also
warnings about "The if condition is the same as the previous one".
Add a test to avoid regressions.
> Add regression test for #8780

- cfg/gtk.cfg
- test/cfg/gtk.c
Reference: https://developer.gnome.org/glib/stable/glib-I18N.html
Found via Donate CPU / daca@home.
Update header comment in gtk.cfg since it is now only edited manually.
> gtk.cfg: Add internationalization macros / functions

- test/cfg/gnu.c
- test/cfg/qt.cpp
- test/cfg/runtests.sh
- test/cfg/windows.cpp
Use `--check-library` for all tests as it was done before.
Re-enable all tests in runtests.sh again.
The regressions where runtests.sh would fail are disabled via "FIXME"
comment in the inline suppression comment.
> Library cfg tests: Enable all tests again, exclude regressions for now

- tools/donate-cpu.py
Optimize checking of different includes for the same library by using a `list`
instead of calling `hasInclude()` several times.
Add includes for gtk and qt library detection that were found missing when
looking at several daca@home packages.
> donate-cpu.py: Enhance library configuration detection

- tools/test/run_donate_cpu_client_tests.sh
- tools/test/start_donate_cpu_client_productive.sh
- tools/test/start_donate_cpu_client_test_local.sh
- tools/test/start_donate_cpu_server_test_local.sh
Indirectly the scripts (at first the server test script) also document what needs to be done to setup daca@home.
The productive client script can be used by everyone who wants to support daca@home, not only for testing. But i still think it is good to have it under /test to not lose too much clarity / lucidity in the /tools directory.
> Donate CPU: Add scripts under /test for testing

- lib/checkautovariables.cpp
- lib/valueflow.cpp
- lib/valueflow.h
- test/testautovariables.cpp
This will warn for this case:
```cpp
auto by_ref(int& x) {
return [&] { return x; };
}
auto f() {
int i = 0;
return by_ref(i);
}
```
And also for this case:
```cpp
template<class T>
auto by_value(T x) {
return [=] { return x; };
}
auto g() {
std::vector<int> v;
return by_value(v.begin());
}
```
> Lifetime: Support analysis with functions that do not return a reference

- lib/valueflow.cpp
- lib/valueflow.h
- test/testautovariables.cpp
This should fix the issue in #1631.
> Avoid infinite recursion in getLifetimeVariable

- test/testother.cpp
* Remove newlines after check(
* Remove unneeded statements after if-statements
As an example, the previous test case
check(
"bool foo(int x) {\n"
"  if (x < 0)"
"    return true;\n"
"  return false;\n"
"}");
is changed to
check("void foo(int x) {\n"
"  if (x < 0) {}\n"
"}");
> TestOther: Shorter test cases

- tools/donate-cpu.py
Add check to only use boost library if boost.cfg exists since it is very new.
If the boost.cfg does not exist Cppcheck would exit with an error and we
would not get the desired results.
> donate-cpu.py: Use Boost library configuration if appropriate

- cfg/python.cfg
daca@home issues `unknownMacro` errors for these (deprecated) macros.
> python.cfg: Add macros DL_IMPORT and DL_EXPORT

- lib/tokenize.cpp
- test/testsimplifytemplate.cpp
Fixed template detection to handle multi-token template parameters.
> Fixed #8969 (syntax error: template)

- runastyle
At least under Windows with Cygwin i see a problem.
For lines like `formatCplusplus lib/*.cpp` the wildcard is replaced by ONE filename before the function is called.
This results in only one file being formatted in the corresponding directory.
The fix seems quite simple. Just use quotes for all function parameters like this: `formatCplusplus "lib/*.cpp"`
The wildcard is preserved and only expanded in the function body, so all matching files get formatted.
> runastyle: Fix wildcard expansion happening too soon

- cfg/qt.cfg
- test/cfg/qt.cpp
Qt defines `Q_NULLPTR` with `nullptr` if it is available, otherwise with `NULL`.
Since there seems to be no (sane) way to configure it the same way in the library configuration it is just defined with `NULL`.
> qt.cfg: Add configuration and tests for macro Q_NULLPTR

- lib/astutils.cpp
- lib/astutils.h
- lib/checkother.cpp
- test/testother.cpp
This fixes the FP with:
```cpp
void g(int);
void f() {
char i = 1;
g(static_cast<int>(i));
}
```
> Fix FP with const argument when doing a variable and cast

- lib/valueflow.cpp
This fixes the access throwing an exception for some cases. I dont have a real reduced test case for this yet. Is it possible to add some special logging when this occurs?
> Fix possible out of bounds access on arguments

- tools/donate-cpu.py
The version number is added to the result output so issues could be more easily reproduced and in the future if it is necessary to handle any specific version of the client by the server in a special way (for example because it is erroneous) this is possible now.
> donate-cpu.py: Introduce version number for client script

- lib/tokenize.cpp
- test/testsimplifytypedef.cpp
This fixes a wrong assumption when substituting typedefs: they might be used in template instantiations, and not be followed by a variable name.
> Ticket #8878: Properly simplify typedefs within template instantiations.

- lib/symboldatabase.cpp
- lib/tokenize.cpp
- lib/tokenize.h
- lib/tokenlist.cpp
- lib/tokenlist.h
- test/testio.cpp
- test/testother.cpp
Add a call to `simplifyPlatformTypes()` in
`SymbolDatabase::setValueTypeInTokenList()` to simplify return types of
library configured functions. This fixes the FN in [#8141](https://trac.cppcheck.net/ticket/8141). Regression
tests are added, both for the original issue and another FN in the comments.
In order to do that, move `simplifyPlatformTypes()` to `TokenList` from `Tokenizer`.
This is a pure refactoring and does not change any behaviour. The code was
literally copy-pasted from one file to another and in two places
`list.front()` was changed to `front()`.
When adding the call to `simplifyPlatformTypes()`, the original type of
`v.size()` where `v` is a container is changed from `size_t` to `std::size_t`.
Tests are updated accordingly. It can be noted that if `v` is declared as
`class …
> Run simplifyPlatformTypes on library return types

- cli/threadexecutor.h
The fork implementation in Cygwin seems to be not very reliable.
See also the Cygwin documentation here: https://cygwin.com/faq/faq.html#faq.using.fixing-fork-failures
More details in the ticket https://trac.cppcheck.net/ticket/8973
> threadexecutor.h: Disable THREADING_MODEL_FORK for Cygwin (trac 8973)

- lib/checkautovariables.cpp
- test/testautovariables.cpp
Even if `ptr` is a local variable, the object `ptr->item` might be not.  So taking address of `ptr->item` is definitely not unsafe in general.
This commit fixes false positives triggered by commit [1.85-249-gf42648fe2](https://github.com/danmar/cppcheck/commit/f42648fe2262170d065d1cc0e5e5b8a487c99435) on the following code of sssd:
https://github.com/SSSD/sssd/blob/d409df33/src/sbus/request/sbus_request.c#L359
> checkautovariables: eliminate false positives on assignment of &ptr->item

- tools/donate-cpu-server.py
Ignore normal results (not fast or info) where the diff was made against the wrong OLD_VERSION. This avoids unwanted results when some client still analyzes an old package but the OLD_VERSION in the server script is changed for example.
Results missing the Cppcheck version info completely are also ignored.
Tested locally with correct and wrong version numbers.
> donate-cpu-server.py: Verify compared Cppcheck version

- lib/checkother.cpp
- test/testincompletestatement.cpp
This fixes:
```cpp
void interface()
{
Plasma::DataEngine *e = engine();
}
```
It also should fix FP with template classes as well:
```cpp
void foo()
{
std::vector<char> *var = NULL;
}
```
> Fix issue 8984: FP constStatement regression with qualified name

- lib/checkcondition.cpp
- test/testcondition.cpp
This fixes:
```cpp
long X::g(bool unknown, int& result)
{
long ret = 0;
bool f = false;
f = f || unknown;
f ? result = 42 : ret = -1;
return ret;
}
```
> Fix issue 8987: False positive knownConditionTrueFalse

- tools/donate-cpu.py
This detects more includes / headers. For example includes like
"# include <gtk/gtk.h>" with a space before "include" as it is used in
the package http://cppcheck.osuosl.org:8000/gbatnav are now also
detected.
The regex search also searches all includes for one library in one go
instead of one include per loop.
Tested with several packages to make sure libraries that were detected
before are still detected.
> donate-cpu.py: Improve header detection by using regex.

- lib/valueflow.cpp
- test/testautovariables.cpp
This will now warn for cases like this:
```cpp
std::vector<int>::iterator f(std::vector<int> v) {
for(auto it = v.begin();it != v.end();it++) {
return it;
}
return {};
}
```
> Forward lifetimes in "for" loops

- cfg/libcerror.cfg
- tools/donate-cpu.py
The function libcerror_error_set() is currently the function for which
daca@home most often reports a missing configuration (more than 80000
times).
Official repository of libcerror: https://github.com/libyal/libcerror
The library configuration has been tested with the library libvhdi:
ftp://ftp.se.debian.org/debian/pool/main/libv/libvhdi/libvhdi_20181227.orig.tar.gz
> libcerror.cfg: Add libcerror configuration file.

- lib/checkclass.h
Previous attempt 70527a78f70aa35df141cea3fadf08ca6468cf1c
doesn't work because equal error messages are filtered.
> 7772 Add uninitMemberVarPrivate to errorlist (really) #1557

- tools/donate-cpu.py
Now also found:
- Includes directly at the beginning of a file
- Indented includes
- Includes where there is no white-space between
"include" and header name
> donate-cpu.py: Improve regex to find more includes.

- cfg/qt.cfg
I would like t change the definition of the qt test macros for the qt library config. Defining this qt test macros as asserts lead to false positive assertWithSideEffect.
Second I added the definition of futher test macros.
> itions of QCOMPARE, QVERIFY & QVERIFY2, this are qtest macros not asserts

- cfg/qt.cfg
Again additional qt test macro definition , this time according to danmar last fix.
Additional added Q_ASSERT, Q_ASSERT_X.
> qt.cfg: Add support for further qtest macros & add definition Q_ASSERT, Q_ASSERT_X

- .travis.yml
As suggested by rikardfalkeborn here:
https://github.com/danmar/cppcheck/pull/1679#issuecomment-465927692
By compiling python scripts the syntax can be checked.
There are two compilations, one for Python 2 and one for Python 3 for
most scripts to make sure at least the syntax is valid for both
versions.
> .travis.yml: Check python syntax (version 2 and 3)

- cfg/qt.cfg
- test/cfg/qt.cpp
Add unknownMacro Q_DECLARE_TR_FUNCTIONS found via daca@home.
Add function QCoreApplication::translate() and macro
QT_DECLARE_DEPRECATED_TR_FUNCTIONS() the unknownMacro depends on.
Reference:
https://doc.qt.io/qt-5/qcoreapplication.html#Q_DECLARE_TR_FUNCTIONS
https://doc.qt.io/qt-5/qcoreapplication.html#translate
> qt.cfg: Add Q_DECLARE_TR_FUNCTIONS() and others

- cfg/cppcheck-cfg.rng
Make sure that the elements of function->arg contain no duplicates.
Except for 'minsize' which can be specified zero to many times.
> Library configuration validation: Enhance relaxng file (arg elements)

- test/testnullpointer.cpp
... which is fixed since [1.86-72-gbc34f0239](https://github.com/danmar/cppcheck/commit/bc34f0239)
> TestNullPointer: add regression test to cover #8813

- lib/valueflow.cpp
Fixes a compiler warning about missing declaration.
> valueflow: Mark getLifetimeToken() static

- cfg/gtk.cfg
References:
https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-new
https://developer.gnome.org/gtk2/stable/GtkLabel.html#gtk-label-get
Found by daca@home.
> gtk.cfg: Add support for gtk_label_new(), enhance gtk_label_get().

- tools/donate-cpu.py
.qml files are used when the Qt library is loaded.
> donate-cpu.py: Also extract .qml files.

- tools/donate-cpu.py
- tools/test/run_donate_cpu_client_tests.sh
Python 3 directly decodes the text when it is read(). If there is any
invalid UTF-8 character in the text an exception is thrown (IIRC it is
UnicodeDecodeError). Opening the file with `error='ignore'` avoids
throwing an exception and just ignores the invalid character. Since
this is only possible since Python version 3 there must be extra code
for older versions.
The test script has been enhanced. It now also uses a package which
contains a file with at least one invalid UTF-8 character.
> donate-cpu.py: Fix crash during decoding under Python 3.

- lib/library.cpp
If no 'alternatives' argument was specified and the `<warn/>` element
did not contain any text Cppcheck crashed because of a null pointer
access.
If there is no 'reason' and no text an error message is printed now and
loadFunction() returns with an error.
And it is now allowed to only specify a 'reason' because it is hard
sometimes to suggest 'alternatives' and an additional text also does
not help much.
> library.cpp: WarnInfo: Fix crash

- tools/daca2-getpackages.py
- tools/donate-cpu-server.py
In my tests there were about 1500 additional packages
available as bz2 on the server.
For some packages a newer version is now used if it is
only available as .tar.bz2 archive.
The donate-cpu.py client is tested to work with .tar.bz2
files under Python 2.7.15 and 3.6.8.
> Donate CPU: Also use and accept .tar.bz2 package files.

- .travis.yml
- tools/donate-cpu-server.py
The function `iteritems()` of `dict`s is deprecated. The recommended
alternative is to use `items()`, this function also works with Python 2.
The next issue is that lambdas can no longer unpack tuple parameters
in Python 3. It would be possible to use some workaround and still use
a lambda, but using `operator.itemgetter(1)` instead is faster and the
recommended method in such a case.
The syntax is now compatible with Python 2 and 3 but the server script
still does not work with Python 3. For example `socket.recv()` returns
`bytes` in Python 3 and `str` in Python 2. Currently `str` is expected
so it does not work with Python 3.
> donate-cpu-server.py: Replace syntax that is deprecated in Python 3.

- man/cppcheck.1.xml
As the title - I am not sure if the cppcheck.wiki.sourceforge.net link is down just temporarily, but the wiki link on the homepage is to the one I have linked in my patch.
> Fix link to cppcheck wiki in man page

- cfg/cppcheck-cfg.rng
- cfg/std.cfg
- lib/astutils.cpp
- lib/library.cpp
- lib/library.h
This enhances the library configuration so the direction of function
arguments can be specified (in, out, inout).
isVariableChangedByFunctionCall() uses this information now to avoid
guessing.
> Library configuration: Enable configuring the direction of arguments.

- tools/donate-cpu.py
- tools/test/run_donate_cpu_client_tests.sh
The client script will exit after the specified number of packages
have been processed. 0 means infinitely.
Useful for example to regularly quit the script, check for updates to
the client and start it again. Or as an alternative to the `--stop-time`
argument.
> donate-cpu.py: Add new argument `--max-packages=N`.

- test/options.cpp
- test/options.h
- test/testoptions.cpp
- test/testrunner.cpp
- test/testsuite.cpp
- test/testsuite.h
For now, only print the ways of running testrunner and the few options
that are available.
Also, refactor to remove an unneeded const_cast and use a range for loop.
Partially fixes [#8514](https://trac.cppcheck.net/ticket/8514).
> Add help to testrunner

- cfg/std.cfg
I added all argument directions i know or where i was able to find
information without too much effort. When in doubt i looked at the
Microsoft SAL annotations and used similar configurations when this
made sense.
> std.cfg: Add missing argument directions as far as possible.

- lib/settings.cpp
lib/settings.cpp:53:7: warning: field 'removeUnusedIncludedTemplates' will be
initialized after field 'removeUnusedTemplates' [-Wreorder]
removeUnusedIncludedTemplates(false),
^
lib/settings.cpp:54:7: warning: field 'removeUnusedTemplates' will be
initialized after field 'checkConfiguration' [-Wreorder]
removeUnusedTemplates(false),
^
> lib: reorders settings to match definition (-Wreorder)

- cfg/gnu.cfg
As can be read here:
https://www.gnu.org/software/gettext//manual/html_node/Mark-Keywords.html
The _(str) macro is typically defined for a project to abbreviate the
gettext(str) call. Although this is not part of GNU it would enhance the
analysis. Cppcheck often does not know what _() is. In daca@home it is
reported thousands of times as a function without configuration.
> gnu.cfg: Add support for non-GNU _(string) macro.

- lib/checkuninitvar.cpp
CheckUninitVar::isMemberVariableAssignment uses argument direction
to check for assignment when the member variable is handed over to a
function by reference.
> checkuninitvar.cpp: Use argument direction info from library config.

- cfg/std.cfg
wprintf(): The format string must be initialized. So add `<not-uninit/>`
swprintf(): `<formatstr/>` should not be used because Microsoft uses the
same function with a different order of the arguments. Add comment to
document this in the library configuration also. See ticket
https://trac.cppcheck.net/ticket/4790
> std.cfg: Fix wprintf(), add comment to swprintf().

- lib/checkuninitvar.cpp
- test/testuninitvar.cpp
CheckUninitVar::isMemberVariableAssignment uses argument direction "out"
now also to check for assignment when the member variable is handed over
to a function by reference.
> checkuninitvar.cpp: Use argument direction "out" info from library cfg

- test/testother.cpp
Trac ticket #8994 was fixed in b222953baeaafb4ca53760a1d054ed5516c42e08.
Add a regression test to ensure it stays fixed.
> Add regression test for #8994

- tools/daca2-download.py
- tools/daca2-getpackages.py
After using semver the latest version is picked for analysis instead. E.g., in a list of
...
xyz_3.13.1.orig.tar.gz
xyz_3.6.2.orig.tar.gz
...
Verison 3.13.1 is now picked over version 3.6.2.
> Add semver import for sorting ls-lR list

- cfg/boost.cfg
- cli/cmdlineparser.cpp
- cli/cppcheckexecutor.cpp
- gui/mainwindow.cpp
- gui/projectfiledialog.cpp
- lib/settings.h
- CLI: Save the libraries that should be loaded to a list and load them
after the std.cfg has been loaded.
- GUI: Load std.cfg (and windows.cfg / posix.cfg when applicable) before
setting other options and loading the other libraries.
In the project-file-dialog the std.cfg is searched first. If some
other library fails to load is is retried with first loading std.cfg.
- boost.cfg: Enable containers that depend on std containers.
> Load std.cfg before all other libraries

- cfg/cppcheck-cfg.rng
- cfg/posix.cfg
- lib/checkbufferoverrun.cpp
- lib/library.cpp
- lib/library.h
- test/cfg/posix.c
- test/testlibrary.cpp
Some POSIX and Windows functions require buffers of at least some
specific size. This is now possible to configure via for example this
minsize configuration: `<minsize type="value" value="26"/>`.
The range for valid buffer size values is 1 to LLONG_MAX
(9223372036854775807)
> Library: Enhance minsize configuration and allow simple values.

- lib/token.cpp
- lib/token.h
- lib/tokenize.cpp
- test/testtoken.cpp
This makes it possible to call getStrLength() and similar functions
before the tokenizer is called.
Following up the discussion in #1734, I believe this is better than tweaking `getStrSize()`, `getStrLength()`, etc to handle a possible prefix.
> Handle prefixed string in Token

- cfg/posix.cfg
- cfg/std.cfg
Add buffer-size attribute for aligned_alloc() and add test in std.c.
Move valloc() to posix.cfg since it is a legacy POSIX function and not
part of the standard (not even commonly used).
> Libraries: Move valloc() from std.cfg to posix.cfg.

- .travis.yml
Travis often fails to update / install the packages via apt-get and
jobs must be restarted manually. This should fix the problem or at least
reduce the frequency at which these failures occur.
Details about the problem and the `travis_retry` command can be found
here:
https://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries
> .travis.yml: Add retries to the `apt-get` commands.

- lib/templatesimplifier.cpp
in case of template constexpr like
```
namespace a {
template <typename T, typename enable = void>
struct promote {
using type = T;
};
template <typename T>
struct promote <T, typename std::enable_if< std::is_integral<T>::value && sizeof(T) < sizeof(int) >::type>{   
};
}
```
This is not proper solution. This change just eliminates crash and logs error.
Error is better than crash.
https://trac.cppcheck.net/ticket/9046
> Fix crash in TemplateSimplifier::TokenAndName::TokenAndName 

- test/options.cpp
- test/options.h
- test/testoptions.cpp
- test/testsuite.cpp
Take some care to not run the same test case twice, even if running:
./testrunner TestClass TestClass::TestCase
> Allow multiple test case arguments to testrunner

- lib/importproject.cpp
sets __cplusplus and __STDC_VERSION__ based on -std and the defines for -municode, -fpie, -fPIE, -fpic and -fPIC
> Add defines set by compiler options when using compilation database

- lib/tokenize.cpp
- test/testautovariables.cpp
- test/testtokenize.cpp
A function returning a reference to a `thread_local` variable is not a bug, as for example in the following function.
```C++
std::vector<int> &foo()
{
thread_local std::vector<int> v;
return v;
}
```
The returned reference can be used as long as the thread is alive.
The fix from this pull request solves this by handling `thread_local` as `static`. In fact, it replaces the token `thread_local` by `static`.
> Fixed: FP return reference to thread_local variable

- cli/threadexecutor.cpp
- tools/donate-cpu.py
Currently only signal 11 (aka `SIGSEGV` aka Segmentation fault) is being handled as a crash. This adds handling for all signals and exitcodes which are not 0 as well as ThreadExecutor errors.
I have seen reproducible ThreadExecutor errors with `fork()` failing for `php5` and another package I cannot remember. I haven't look into these, but these are obviously causing incomplete results.
Other signal should also be handled like signal 11 and produce stack trace. The most obvious would be `SIGABRT`. As the actual signal will be reflected in the negative `elapsedTime` value we can add this handling step by step.
>  donate-cpu.py: improved error detection

- tools/donate-cpu-server.py
I recognized several entries in the crash report which were outdated and when trying to run them locally it turned out the archive was no longer available. There's probably even more cases which might lead to the results not being updated, but there's currently no way to find this packages so I added a stale report which will show the results which are older than 30 days.
I also added the date and time to the crash report so it is easier to see which of the results are recent.
> donate-cpu-server.py: added stale report / cleanups

- lib/library.cpp
temp.bufferSizeArg2 was not initialized when only bufferSizeArg1
was specified or the value was out of range. But in valueflow.cpp in
valueFlowDynamicBufferSize() it was used as if it is always initialized
and has a sane value (greater than 0).
> Fix #9079 (make checkcfg crashes on Linux)

- lib/templatesimplifier.cpp
Fix some crashes caused by the template simplifier generating bad code
for some instantiations.
Sorry but there are no tests because I was unable to get C-Reduce to
create examples that were not garbage code.
> template simplifier: fix some crashes

- lib/templatesimplifier.cpp
This fixes a daca crash in Vc-1.3.3/tests/casts.cpp.
> template simplifier: fix another crash

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
This does not add support for template templates.  It only skips the
template template parameter.
> Fixed #9076 (Template Simplifier : template < template <typename> T >)

- addons/misra.py
This patch keeps record of when a violation of a rule is suppressed and shows this count when the user asks to see the suppressed rules.
> Show number of hits per suppression rules entry

- addons/cppcheckdata.py
- addons/misra.py
I'm not sure if you want this, it isn't really a complete solution, but it adds 'xml' as output format, producing cppcheck compatible output.  It does **not** create a complete xml though, the header and footer is missing, and I could not come up with a good solution to add it.
I use this to process each dump file into an xml stub file, then concatenate all stubs and xml header+footer into a complete xml file, then feed this to the cppcheck plugin for Jenkins.
> Misra xml output

- lib/library.cpp
- lib/library.h
- test/testsymboldatabase.cpp
reduces Ir from 5882 to 1149 according to callgrind
I chose the random package `nn` for profiling.
> library.cpp: optimized Library::detectContainer()

- lib/checkstring.cpp
- lib/checkstring.h
- test/teststring.cpp
When writing tests for string functions as part of #1754, I stumbled over a few (I think) improvements in `checkString()`. The PR is a bit of a mishmash (sorry for that, I can split it if you want) of improved test cases for wide strings/wide chars, extensions to the checks to handle wide strings, improvements to an error message and a fix of a TODO regarding the ternary operator.
> Checkstring fixes

- lib/checkinternal.cpp
- test/testinternal.cpp
Improve the internal check for redundant null pointer check before
calling Token::Match() (and friends). Now, warn about code snippets like
if (a && tok && Token::Match(tok, "foo"))
Also, extend the check for the inverted case.
There is still no warning for
if (tok && a && Token::Match(tok, "foo"))
since that would require checking if a is independent of tok.
Inspired by a review comment on #1783.
> CheckInternal: Extend redundant null pointer check before Token::Match()

- lib/errorlogger.cpp
Add missing line feed to the generated plist output because DOS uses carriage return and line feed as a line ending.
> Add missing line feed to the generated plist output

- addons/misra.py
I don't know if you find this interesting,  it extends the misra summary like this:
```
MISRA rule violations found: information: 1	warning: 3
Misra rules violated:
misra-c2012-5.2 (Required): 2
misra-c2012-10.4 (Required): 1
misra-c2012-19.2 (Advisory): 1
```
> List the number of violations per rule

- addons/misra.py
- addons/test/misra-test.c
This patch uses a regexp for handling preprocessor directives, which allows constructs like e.g:
```
#ifdef BLABLA
#else 
#endif 
```
> Misra explicitly allows spaces between # and the preprocessing tokens

- lib/importproject.cpp
- test/testimportproject.cpp
Previous code assumes 'commands' exists and ill assert if t does not.
> Handle 'arguments' sections in compile_commands.json

- lib/checkcondition.cpp
- lib/checkcondition.h
- test/testcondition.cpp
This will warn when writing expressions like this:
```cpp
void f(int& x, int y) {
if (x == y)
x = y;
}
```
This is rather suspicious. If `x == y` then there is no need to reassign the same value. It most likely a copy-paste error.
The same applies for `x != y`. It is faster and more readable to write `x = y` instead of checking the condition first. This most likely copy-paste error.
> Add check for duplicate condition and assignment

- lib/tokenize.cpp
- lib/tokenize.h
- test/testsymboldatabase.cpp
- test/testvarid.cpp
Don't set varid for trailing return type.
> Fixed #8889 (varid on function when using trailing return type.)

- lib/templatesimplifier.cpp
- lib/tokenize.cpp
- test/testsimplifytemplate.cpp
This fixes simplifyUsing to remove 'typename' and 'template' from type
aliases of the form: using T3 = typename T1::template T3<T2>;
This lets the template simplifier instantiate the type alias which will
then remove the using type alias.
The crash will still happen if there is no instantiation because the
type alias will not be removed.  The type alias is what cppcheck is
crashing on after the template simplifier and that still needs fixing.
> partial fix for #8663 (Stack overflow with template disambiguator)

- lib/tokenlist.cpp
- test/testincompletestatement.cpp
- test/testtokenize.cpp
So this fixes the AST when using member function qualifiers. It doesn't work with ref qualifiers, but neither does the previous commit. So you may want to run another bisect to figure out which commit broke the ref qualifiers. For now I added TODO test cases for ref qualifiers.
> Fix FP with unused variable

- lib/token.cpp
- lib/token.h
- test/testtokenize.cpp
Change the `astStringVerbose()` recursion to extend a string instead of
returning one. This has the benefit that for tokens where the recursion
runs deep (typically large arrays), the time savings can be substantial
(see comments on benchmarks further down).
The reason is that previously, for each token, the astString of its
operands was constructed, and then appended to this tokens astString.
This led to a lot of unnecessary string copying (and with that
allocations). Instead, by passing the string by reference, the number
of temporary strings is greatly reduced.
Another way of seeing it is that previously, the string was constructed
from end to beginning, but now it is constructed from the beginning to
end. There was no notable speedup by preallocating the entire string
using …
> Optimize astStringVerbose() for large arrays

- lib/valueflow.cpp
- test/testautovariables.cpp
This fixes the `unsignedLessThanZero` warnings from cppcheck.
> Fix bug in lifetime constructors

- lib/checkio.cpp
- lib/checktype.cpp
- lib/symboldatabase.cpp
- lib/symboldatabase.h
- lib/valueflow.cpp
- test/testsymboldatabase.cpp
- test/testtype.cpp
- test/testvalueflow.cpp
This is necessary for valueflow to know the size, for example when
calculating sizeof(wchar_t).
> Set wchar_t type

- lib/checkbool.cpp
- test/testbool.cpp
A common pattern is to have a function like similar to this:
bool isFlagSet(uint32_t f) {
return f & 0x4;
}
Warning that the function returns a non-boolean in this case is too
noisy, it would be better suited for a Misra check, so remove the
warnings in the most obvious cases.
> Fix 8840: Don't warn when returning a bitmask as bool

- test/cfg/posix.c
Trac ticket: https://trac.cppcheck.net/ticket/9118
Commit that likely fixed it already:
1b74bca973bb0708de0083a1fe75b92d099283d6
> posix.c: Add test to avoid regression of already fixed ticket #9118

- lib/symboldatabase.cpp
- lib/templatesimplifier.cpp
- lib/token.cpp
[Hello, Daniel.  Thank you for writing such an amazingly useful program as "cppcheck".  Being able to run it without setting up a build (that is, letting it just try all #ifdef combinations even if I have to wade through a lot of false alarms) has made it so easy for me to try, that I am now in the habit of running it any just about every C or C++ source tree that I visit.  Amazingly, it usually finds something, even in longstanding well maintained open source projects.  So, thank you so much for it!   --Adam]
This tiny patch converts a few statements of the form "assert(a && b);" into "assert(a); assert(b);" in the lib subdirectory.
The following discussion about why I think this is useful is only in this pull request, not the commit message, which is more concise.
Assertion failure …
> lib: Separate "assert(a && b)" statements into "assert(a)" and "assert(b)" for more precise diagnostics

- htmlreport/cppcheck-htmlreport
Use makedirs instead of mkdir to create report_dir to allow recursive creation of the full directory path
> [cppcheck-htmlreport] Use makedirs instead of mkdir

- lib/symboldatabase.cpp
- test/testcondition.cpp
`const` should not be deduce for `auto` variables that are not references or pointers.
> Fix issue 8993: False positive duplicateCondition related to auto

- lib/tokenize.cpp
- test/testtokenize.cpp
Whenever there is a `<>`, we will always try to link them.
>  Fix issue 8890: AST broken calling member function from templated base class

- lib/checkother.cpp
- test/testother.cpp
This fixes FP in cases like this:
```cpp
struct A { int x; };
void g(int);
void f(int x) {
A y;
y.x = 1;
g(y.x);
}
```
> Fix false positive in constArgument when passing struct member

- addons/misra.py
- addons/test/misra-test.c
By this changes the check for MISRA rule 4.1 should catch constant character literals enclosed by single quotes too.
Additional test cases has been added to check non-compliant as well as compliant case defined by MISRA C 2012 document.
> Fix misra addon rule 4 1

- lib/valueflow.cpp
- test/testvalueflow.cpp
With the following code
```
int f(int x, int y) {
if (!!(x != 0)) {
return y/x;
}
```
cppcheck would wrongly warn that there might be a division by zero in
"return y/x;".
> Fix false positive with several ! (not) operators

- lib/token.cpp
- lib/valueflow.cpp
- test/testautovariables.cpp
This fixes FP when inserting an array into a container:
```cpp
void f(bool b) {
std::vector<int> v = {1};
if (b) {
int a[] = {0};
v.insert(a, a+1);
}
return v.back() == 0;
}
```
> Fix FP with lifetime containers

- lib/checkautovariables.cpp
- test/testautovariables.cpp
This fixes the FP with:
```cpp
struct A {
std::vector<int*> v;
int x;
void f() {
v.push_back(&x);
}
};
```
> Fix FP with non-local variable referencing a non-local variable

- test/testtokenize.cpp
Although we aren't fully expanding the template aliases, it would still be good to make sure we dont cause syntax errors on these cases in the future.
> Add regression tests for syntax errors

- gui/erroritem.h
- gui/resultstree.cpp
- gui/resultstree.h
- gui/resultsview.cpp
Compile of gui would result in repeated warnings from two conditions:
1) gui/erroritem.h:104:30: warning: extra ‘;’ [-Wpedantic]
Message points to Qt Macro Q_DECLARE_METATYPE usage.
Semi Colon at EOL removed.
2) gui/resultstree.h:201:10: warning [-Woverloaded-virtual]
Message is indicating that function ResultsTree::selectionChanged
is being iterpreted as overloading function of the same name
in base clase (QTreeView::selectionChanged).
Refactored - function renamed to ResultsTree::treeSelectionChanged
> Minor changes to gui code to silence repeated build warnings

- gui/codeeditor.cpp
- gui/codeeditor.h
- gui/codeeditorstyle.h
- gui/gui.pro
With profileration of Qt5 styling methods, problems with presentation
can occur when using cppcheck-gui and user choosen themes. With a dark
theme, a highlighted line in the CodeEditor appears with white text on
a light background or dark colors on a dark background.
Commit makes changes to enforce a default style on the Code Editor widget.
Mechanism is provided, if desired, where a user defined styling can
be provided to CodeEditor widget.
> CodeEditor Widget Styling

- lib/templatesimplifier.cpp
- test/testtokenize.cpp
The fixes the analysis error, however, the template expansion is not entirely correct yet because of the varidiac templates. So this:
```cpp
template <typename> struct a;
template <bool> struct b;
template <class k, class> using d = typename b<k::c>::e;
template <class> struct f;
template <template <class> class, class... g> using i = typename f<g...>::e;
template <template <class> class h, class... g> using ab = d<i<h, g...>, int>;
template <template <class> class h, class... g> struct j {
template <class... ag> using ah = typename ab<h, ag..., g...>::e;
};
template <class> struct F;
int main() { using T = void (*)(a<j<F, char[]>>); }
```
Will now expand to this:
```
1: template < typename > struct a ;
2: template < bool > struct b ;
3: template < class k , class > using d = typename b < …
```
> Fix issue 9156: Analysis failed because square brackets arent linked correctly

- lib/templatesimplifier.cpp
- test/testtokenize.cpp
This fixes the crash in:
```cpp
class a {
public:
enum b {};
};
struct c;
template <class> class d {
d(const int &, a::b, double, double);
d(const d &);
};
template <> d<int>::d(const int &, a::b, double, double);
template <> d<int>::d(const d &) {}
template <> d<c>::d(const d &) {}
```
When replacing a template `Foo < int >` with `Foo<int>` if the previous token is `>` then it will remove the cache entry for the name position.
I dont know if that fixes all cases of this. I would need to see an example where this would still be the case.
> Fix crash in issue 9007

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
- test/testtokenize.cpp
Refactored simplifyTemplateAliases to iterate over template type aliases
rather than instantiations. This fixed template type aliases that were
not templates.
Don't instantiate templates in template type aliases. They will get
instantiated once the type alias is instantiated. This required
increasing the template simplifier pass count to 3 so one of the
existing tests continued to work.
> Fixed #9155 (Syntax error on valid C++ code)

- addons/cppcheckdata.py
- addons/misra.py
- lib/cppcheck.cpp
- lib/standards.h
Misra rules defines different length criterias for identifiers depending on what version of the C language is being used.
This patch allows choosing C version on the command line, and fixes _some_ of these rules (there may be more).
> Record C/CPP/Posix Standard used for cppcheck in dump file / use this for misra checking

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
int{} -> 0
decltype(int{}) -> int
This fixes reduced test cases like #9153.  I'm not sure they will help
real world code that much.
It was necessary to increase the pass count to 4 to get #9153 completly
simplified.
> template simplifier: add 2 new template parameter simplifications

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
This fixes the template simplification in issue 9155 and the syntax error for this case:
```cpp
template <typename a, a> struct b;
template <bool, typename> struct c;
template <typename a> struct d : b<bool, std::is_empty<a>{}> {};
template <typename a> using e = typename c<std::is_final<a>{}, d<a>>::f;
```
> Fix syntax error in issue 9155

- test/testbool.cpp
Trac ticket #7798 was fixed in 3f1e2b42700a1eb1466d4200eb87265defd962f6
(More conservative fallback for function overload matching). Add a test
to avoid regressions.
> Add regression test for #7798

- lib/symboldatabase.cpp
- lib/templatesimplifier.cpp
- lib/token.h
- lib/tokenlist.cpp
- lib/valueflow.cpp
- lib/valueflow.h
- test/testtoken.cpp
This patches replace some usage of const_cast with the addition of non-const methods.
Also, it fixes some functions (valueFlowSetConstantValue for instance) which were lying about some of their arguments, claiming not to modify them while they did it.
There are obviously more similar things to clean later.
> Cleanup some const_cast of Token*

- lib/valueflow.cpp
- test/testvalueflow.cpp
strdup() allocates the string length plus one for a terminating null
character. Add one to compensate for this.
Fixes false positive buffer out of bounds on code like this:
void f() {
const char *a = "abcd";
char * b = strdup(a);
printf("%c", b[4]); // prints the terminating null character
free(b);
}
Also, add a testcase for valueFlowDynamicBufferSize() and add tests for
strdup(), malloc() and calloc().
> Bugfix buffer size for strdup like functions

- lib/astutils.cpp
- test/testvalueflow.cpp
On the following code
void f(char const *const s, bool *b) {
for (int i = 0; i < 42; ++i) {
if (strcmp(s, "1")) {
*b = true;
break;
}
}
if (*b) {
}
}
cppcheck would wrongly warn
"Condition '*b>0' is always true"
> FP on assignment through pointer

- gui/codeeditor.cpp
- gui/codeeditor.h
- gui/codeeditorstyle.cpp
- gui/codeeditorstyle.h
- gui/codeeditstylecontrols.cpp
- gui/codeeditstylecontrols.h
- gui/codeeditstyledialog.cpp
- gui/codeeditstyledialog.h
- gui/gui.pro
- gui/mainwindow.cpp
- gui/resultsview.cpp
- gui/resultsview.h
- gui/settings.ui
- gui/settingsdialog.cpp
- gui/settingsdialog.h
- tools/triage/CMakeLists.txt
- tools/triage/triage.pro
Building on #1874, commit adds user controls to choose
or edit style in cppcheck-gui ONLY. Commit does not
address CodeEditor style usage in triage app at this time.
Code Editor style can be altered from the added "Code Editor"
tab in the user preferences. The user has the option to select
default light, default dark, or to customize.
If user leaves the style set to light or dark defaults, this
will be reflected in the choices shown in the preferences
dialog.
User choice for Code Editor Style is saved in the cppcheck-gui
preferences under the heading "EditorStyle".
> Implement User Selectable Code Editor Style in cppcheck-gui

- gui/codeeditor.cpp
Functionality for `copy` and `select all` text already exists as part
of widget construction. Commit adds connection of those existing
functions to execution with keyboard shortcuts user would normally expect.
(e.g. CTRL+C for copy text)
Qt does translation of keyboard shortcuts for platform
(i.e. Mac OS uses command key rather than control).
> Add keyboard shortcuts for CodeEditor Widget

- lib/astutils.h
- lib/templatesimplifier.h
Increasing the verbosity in Clang, warnings were produced that identified
differences in code and doxygen-formatted comments.
Corrections applied to silence warnings yet still convey intent of original comments.
> Minor Corrections to Doxygen data

- gui/codeeditorstyle.h
- gui/codeeditstylecontrols.h
- gui/codeeditstyledialog.h
- gui/settingsdialog.cpp
- gui/translationhandler.cpp
- lib/errorlogger.h
- lib/token.h
- lib/valueflow.h
- tools/triage/mainwindow.cpp
Sources were built with Clang but with increased verbosity of error detection.
A number of syntax and semantic warnings were encountered. Commit adds
changes to correct these warnings.
Some changes involve removing extra, and unncessary, semi-colons at EOL
(e.g. at end of Qt Macro).
Project astyle settings are not currently setup to detect if a file is to
have an extra carriage return after the last line of data. Two files were
altered to ensure an extra carriage return.
An advisory to enhance code was encountered in triage code. Clang advisory
on a for-loop interation value suggested that:
`use reference type 'const QString &' to prevent copying`
> Suppress Code semantic and syntax warnings

- lib/templatesimplifier.cpp
- test/testsimplifytemplate.cpp
this fixes daca boost1.67 crashes
> template simplifier: consistently handle templates with no arguments

- tools/donate-cpu-server.py
Trac ticket: https://trac.cppcheck.net/ticket/9192
This commit also fixes that negative values of the elapsed time are
used for calculating total times. These crashes and errors are now
ignored in the time report since there is no useful timing information
in that case.
Tested with a local daca@home server with old and new results.
> donate-cpu-server.py: Fix #9192: Old results are shown in the reports

- cfg/gtk.cfg
From the Gnome Developer documentation
(https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html):
If any call to allocate memory using functions g_new(), g_new0(),
g_renew(), g_malloc(), g_malloc0(), g_malloc0_n(), g_realloc(), and
g_realloc_n() fails, the application is terminated. This also means
that there is no need to check if the call succeeded. On the other
hand, g_try_...() family of functions returns NULL on failure that
can be used as a check for unsuccessful memory allocation. The
application is not terminated in this case.
`g_new()`, `g_new0()` and `g_renew()` are defines using `g_malloc()`,
`g_malloc0()` and `g_realloc()` respectively, so there is no need to change
those.
> Remove <noreturn> from g_malloc and friends

- gui/librarydialog.cpp
- test/testlibrary.cpp
Further to pull request #1938. Changes were missed in previous commit.
Resolve warnings `warning: zero as null pointer constant` in code by
using C++ 11 recommended `nullptr`.
> More Zero/Null as pointer constant corrections

- lib/tokenize.cpp
- test/testgarbage.cpp
- test/testother.cpp
- test/testsymboldatabase.cpp
Find garbage code with incorrect `.` or `,` operators.
> Check for more garbage code
